### PR TITLE
LPD-44367 Add model listener

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-44367

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:91385135

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:93189790

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
