### PR TITLE
Commerce-4620

### PR DESCRIPTION
**Pull request by tinatian**
Hi @marco-leo ,
The SF will fail on this, and the fix is here https://github.com/hhuijser/liferay-portal/pull/4705, but have not merged yet.

FYI @jpince @vicnate5 @shuyangzhou
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevante

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
@tinatian sorry for the SF run, I neglected to read the description you set.

**Comment by dantewang** [comment]
Fetched

**Comment by brianchandotcom** [comment]
@tinatian can you rebase and resend

I just published Commerce

**Comment by tinatian** [comment]
Resent at https://github.com/liferay-commerce/liferay-portal/pull/70

**Pull request closed without merging**
