### PR TITLE
COMMERCE-8891 price taglib refactoring

### PR DESCRIPTION
**Pull request by garofalog**

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:reevaluate:1357401_1364

**Comment by garofalog** [comment]
ci:reevaluate:1357401_1364

**Comment by andrea-ale-sbarra** [comment]
Commit id look to be for another ticket not COMMERCE-8891

**Pull request closed without merging**
