### PR TITLE
COMMERCE-8145 accounts better handled in add to cart buttons

### PR DESCRIPTION
**Pull request by fabio-d-m**

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
I close the PR since, according with specs, "accountId === 0" means "no accounts selected" and "accountId === -1" means "guest account selected"

**Pull request closed without merging**
