### PR TITLE
COMMERCE-4629 Fix destination names

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
#94020

**Comment by riccardo-alberti** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/94020

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@riccardo-alberti Please update as well the Breking change file inside this PR

**Comment by riccardo-alberti** [comment]
ci:stop

**Comment by riccardo-alberti** [comment]
closing this PR and opening a dedicated one: https://github.com/liferay/liferay-portal/pull/3942

**Pull request closed without merging**
