### PR TITLE
LPD-32285 Fix playwright test

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-32285

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
