### PR TITLE
Commerce 10448

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
@victoroscuro

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
