### PR TITLE
Automated Test - COMMERCE-6116 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by PauloVAS** [comment]
https://issues.liferay.com/browse/COMMERCE-6116, CC: @pietro69

**Comment by kristinonias** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
