### PR TITLE
Automated Test - COMMERCE-6273 | master

### PR DESCRIPTION
**Pull request by brunadmelo**

### CODE REVIEW

**Comment by brunadmelo** [comment]
https://issues.liferay.com/browse/COMMERCE-6273; cc:@pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Combined: https://github.com/liferay-commerce/liferay-portal/pull/1255
Forwarded: https://github.com/brianchandotcom/liferay-portal/pull/102208

**Pull request closed without merging**
