### PR TITLE
Automated Test - COMMERCE-5865 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-5865 ; CC:@lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
Sent in https://github.com/liferay-commerce/liferay-portal/pull/881
Please close.

**Pull request closed without merging**
