### PR TITLE
COMMERCE-10992 - Image URLs in Catalog API Responses include port number

### PR DESCRIPTION
**Pull request by victorcdp**
Relevant Issue: [COMMERCE-10992](https://issues.liferay.com/browse/COMMERCE-10992)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this one needs your review. It's tied to a LPP.

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
No I've just reviewed this with Bernard, we need to get rid of the port only, not to change this to be a relative path

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra , the new change should satisfy your request. Please note that the URLs will also all be https and no longer http.

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
