### PR TITLE
COMMERCE-11528 Store Front handling of Products Priced as Price on Application + Functional test

### PR DESCRIPTION
**Pull request by baharturk**
https://issues.liferay.com/browse/COMMERCE-11440

Sent from #3848 

@smottal

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures in the relevant are not related to the PR. It's good to go.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
