### PR TITLE
LPD-7837 Update commerce modules to ESM (w/ annexes)

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/issues/LPD-7837

From: https://github.com/liferay-frontend/liferay-portal/pull/4104 sent for review by @bryceosterhaus

**Warning**
This is based on BChan's repo, waiting for new base to be published to `master` for the final `rebase`.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
I've checked all the tests: all of them are known from our CI daily checks so not relevant with the PR. We can forward this.

**Comment by dsanz** [comment]
LGTM ;) pls forward

**Comment by gianmarcobrunialti** [comment]
ci:forward:force

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Pull request closed without merging**
