### PR TITLE
LPD-37783 patchWishList API can add the same item more than once to the same wish list

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-37783
https://liferay.atlassian.net/browse/LPD-37778

resend this https://github.com/brianchandotcom/liferay-portal/pull/156586

https://liferay.atlassian.net/browse/LPD-43404

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:88515725

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
@alessiorendina I checked the results of the ci
 
- ci:test:relevant is ok
- ci:test:commerce-functional is ok

**Comment by alessiorendina** [comment]
ci:forward:force

**Pull request closed without merging**
