### PR TITLE
COMMERCE-13080

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/liferay-commerce/liferay-portal/pull/4560

https://liferay.atlassian.net/browse/COMMERCE-13080

@andrea-ale-sbarra , resending with the merge conflicts resolved.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
@brianikim this looks good, but before moving forward we need to add a test for this as per the new company rules that we have on the quality matter. Can you please add a couple of functional tests that verify:

1. The download URL is present when the file entry is a file
2. The download URL is not present when the file entry is an external resource.
In both cases verify that the fileEntryId is there too.

Thank you!

**Pull request closed without merging**
