### PR TITLE
COMMERCE-6920

### PR DESCRIPTION
**Pull request by brianikim**
Resending from https://github.com/liferay-commerce/liferay-portal/pull/1526

https://issues.liferay.com/browse/COMMERCE-6920

@dsitu and @riccardo-alberti , could you guys let me know if this needs to be reviewed again? or it can be forwarded as soon as it passes CI. It was already approved in #1526.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by dsitu** [comment]
@brianikim it looks good to me.

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
