### PR TITLE
COMMERCE-7123 use AccountGroupRels instead of CommerceAccountGroups

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Review by dsitu — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@drewbrokke  @pei-jung  
Here we bridged CommerceAccountGroupAccountRel service to AccountGroupRel as per 
https://issues.liferay.com/browse/LPS-135027

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by drewbrokke — COMMENTED** [review]
@riccardo-alberti @luca-pellizzon these changes seem good. Technically, we would not consider a bridge migration complete without the following items complete:

- Remove the persistence of the service by setting the `persistence="false"` attribute on the `entity` tag in `service.xml`. See [service.xml](https://github.com/liferay/liferay-portal/blob/08c6b85908e5745c20b53fd5c8e3032bbf15e165/modules/apps/commerce/commerce-service/service.xml#L7) for an example. This guarantees no-one attempts to use the table through the service layer.
- Add an upgrade process that does the following:
    - Copies the records from the old table to the new table
    - Drops the old table

I believe those are the only outstanding items for this particular service.

Are there plans to address those items in a future pull?

cc @pei-jung

**Comment by luca-pellizzon** [comment]
@drewbrokke  can you please check again this PR pls? In particular the upgrade process part.
Thank you.

**Comment by pei-jung** [comment]
@luca-pellizzon  the sql statements for `CAccountGroupCAccountRel` should be removed from the sql files (tables.sql and indexes.sql).

**Comment by luca-pellizzon** [comment]
Done. Thank you @pei-jung

**Comment by luca-pellizzon** [comment]
ci:tet:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by drewbrokke — APPROVED** [review]
Changes look good @luca-pellizzon! 👏 👏 👏

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
