### PR TITLE
Commerce-4620

### PR DESCRIPTION
**Pull request by tinatian**
Hi @marco-leo @brianchandotcom ,
The SF will fail on this, and the fix is here hhuijser#4705, but have not merged yet.

FYI @jpince @vicnate5 @shuyangzhou
Tina.

### CODE REVIEW

**Comment by tinatian** [comment]
ci:test:relevant

**Comment by tinatian** [comment]
@marco-leo Could you please check the test result? Are those unique failures real?

Tina.

**Comment by jpince** [comment]
@marco-leo you can ignore the semantic-versioning error, it is most likely an unrelated publishing issue.

Please consider manually forwarding to Brian to unblock licensing testing. Thanks!

**Comment by marco-leo** [comment]
sent to https://github.com/brianchandotcom/liferay-portal/pull/93610

**Pull request closed without merging**
