### PR TITLE
COMMERCE-11766 Feature flag release order splitting and supplier account

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-11768
https://liferay.atlassian.net/browse/COMMERCE-11766

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by smottal** [comment]
Sent directly here: https://github.com/brianchandotcom/liferay-portal/pull/137239

**Pull request closed without merging**
