### PR TITLE
Automated Test - COMMERCE-5916 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-5916 cc: @lorenzolapescara

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by leticiachiu** [comment]
fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1293. Please close @kristinonias

**Comment by nikki-pru** [comment]
Blocked by COMMERCE-6746

**Pull request closed without merging**
