### PR TITLE
COMMERCE-6577 fix order type + move isDeliveryOnlySubscription to uti…

### PR DESCRIPTION
**Pull request by luca-pellizzon**
…l class

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
