### PR TITLE
Automated Test - COMMERCE-6232 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6232 , cc: @iovaneale

**Comment by JoMaAlves** [comment]
This PR is the updated version of https://github.com/liferay-commerce/liferay-portal/pull/1045

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//div[@class='dnd-td' and contains(text(),'MIN55857')]"

**Pull request closed without merging**
