### PR TITLE
COMMERCE-12963

### PR DESCRIPTION
**Pull request by riccardo-alberti**
https://liferay.atlassian.net/browse/COMMERCE-12963

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:close

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by smottal** [comment]
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/4604

**Pull request closed without merging**
