### PR TITLE
LPS-196309 Filter Users that are not associated with Accounts or Organizations + Automation

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi @smottal,
Please help me to review this PR. Thanks.
This is the PR for story: https://liferay.atlassian.net/browse/LPS-196309, because there is AC update with the label. The term Unassociated Users is replacing Not Associated Users.
old pr: https://github.com/liferay-commerce/liferay-portal/pull/4404
cc @tototrinh

### CODE REVIEW

**Comment by ces-quanhuynh** [comment]
ci:test:sf

**Comment by ces-quanhuynh** [comment]
ci:test:relevant

**Comment by ces-quanhuynh** [comment]
ci:test:stable

**Comment by baharturk** [comment]
sent here: #4521

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
