### PR TITLE
COMMERCE-11432 hide passwords

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11432
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3879

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Hi @victoroscuro, could you please force-forward this pr? It's good to go, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
