### PR TITLE
Commerce 9760 - Fixing conflicts

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Resend of https://github.com/liferay-commerce/liferay-portal/pull/3186 for fixing rebase conflicts

---

https://issues.liferay.com/browse/COMMERCE-9760

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
