### PR TITLE
COMMERCE-10475 - Cannot paste text in the Quick Add to Cart search bar

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-10475](https://issues.liferay.com/browse/COMMERCE-10475)
@brianikim

The problem was that the default behavior on paste for the ClayMultiSelect was to press enter automatically, so the input would get filtered and wiped.
Proposed fix is to prevent the default behavior when pasting.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this one needs your review. Might also need review from @kresimir-coko .

**Review by kresimir-coko — APPROVED** [review]
Looks fine to me 👍

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automation and resent in https://github.com/liferay-commerce/liferay-portal/pull/3672

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
