### PR TITLE
LPD-19779 Fixed commerce product definition asset summary

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/LPD-19779

cc @brianikim

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by alessiorendina** [comment]
ci:report:2547062461

**Comment by alessiorendina** [comment]
ci:forward:force

**Pull request closed without merging**
