### PR TITLE
COMMERCE-7915 Create validator for SKU targeted discounts.

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-7915

@riccardo-alberti

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Review by riccardo-alberti — CHANGES_REQUESTED** [review]
@brianikim the class name is CPInstance but i see in the code you're checking the cpDefinition

**Pull request closed without merging**
