### PR TITLE
COMMERCE-7830 Replacements in product detail view

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
resent here: https://github.com/liferay-commerce/liferay-portal/pull/2152

**Pull request closed without merging**
