### PR TITLE
COMMERCE-12169 We only need to look for the portlets that exist on th…

### PR DESCRIPTION
**Pull request by brianikim**
…e layout.

@andrea-ale-sbarra ,

See https://liferay.atlassian.net/browse/COMMERCE-12169.

We have a performance leak in our SitemapURLProviders because

1. We are using `getPlidFromPortletId`. This is extremely taxing on all layouts that do not have CPContentPortlet or CPCategoryContentPortlet because it will ultimately call: https://github.com/liferay/liferay-portal/blob/056330e6b1a2d7b8f54eeea947015524600d1e2b/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L7421 and https://github.com/liferay/liferay-portal/blob/056330e6b1a2d7b8f54eeea947015524600d1e2b/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L7796 which will ultimately loop through all the layouts and the portlets of those layouts in a given group.
2. There is no need for us to use this expensive call because we do not even use the layout returned if it does not match the layoutUUid provided: https://github.com/liferay/liferay-portal/blob/056330e6b1a2d7b8f54eeea947015524600d1e2b/modules/apps/commerce/commerce-product-service/src/main/java/com/liferay/commerce/product/internal/layout/admin/util/CPDefinitionSitemapURLProvider.java#L77
3. Given the above understanding, we only need to check the portlets on the layout for our matching portlet.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to the PR. This can be force-forwarded

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
