### PR TITLE
LPD-18571 Fix UM flaky test and performance

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-18571

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
