### PR TITLE
Automated Test - Commerce-5845 | master

### PR DESCRIPTION
**Pull request by pedro-michel**

### CODE REVIEW

**Comment by pedro-michel** [comment]
https://issues.liferay.com/browse/COMMERCE-5845, cc : @alessandro.iovane

**Comment by pedro-michel** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@pedro-michel Please uncomment setup steps and resend.

**Comment by emanuelfisilva** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
> @pedro-michel Please uncomment setup steps and resend.

Done!

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@pedro-michel The pull request failed due to source formatting. Please fix and resend.

**Comment by pedro-michel** [comment]
> @pedro-michel The pull request failed due to source formatting. Please fix and resend.

Can you please test again?

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Pull request closed without merging**
