### PR TITLE
LPS-189610 As an Instance Admin I want to be able to configure the User Image size limit

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi @smottal 
Please help review this ticket and give your feedback.
cc: @ces-quanhuynh @locpham97

### Motivation
[LPS-189610 ](https://liferay.atlassian.net/browse/LPS-189610) As an Instance Admin I want to be able to configure the User Image size limit

### Solution
Set the _UserFileUploadsConfigaration_ scope to _Company_ and apply the configuration to _UserFileUploadsSettingsImpl_.
Thanks

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by tototrinh** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]
LGTM! Thx.

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:test:um

**Comment by lorenzolapescara** [comment]
Failures are not related. Forwarding

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
