### PR TITLE
LPD-42550 Wrong userId in contact filter

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-42550

cc @smottal

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:stable

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
