### PR TITLE
Lpd 3472 final test

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-3472

@luca-pellizzon ,

I tested the front-end in SKU/UOM Edit view, Inventory, and also discounts.

Please let me know if I missed anything.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@brianikim errors in commit message, but lgtm :+1:

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@luca-pellizzon , I believe I resolved the source format issue. I will run relevant as well since PR was approved.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
resending here: CI is stuck: https://github.com/liferay-commerce/liferay-portal/pull/4771

**Pull request closed without merging**
