### PR TITLE
LPD-3469 An error is thrown if a user with the Operations Manager role navigates to an order item side panel

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-3469

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF please rebase this PR

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1327401_3420

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1407401_8392

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF please update the PR

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
