### PR TITLE
Automated Test - COMMERCE-6665 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6665; cc:@lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//span[@class='order-id']"

**Comment by pedroalmd** [comment]
Please open @kristinonias

**Comment by pedroalmd** [comment]
Fixed @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
