### PR TITLE
COMMERCE-8446 When a non valid template file is uploaded, the error should have more visibility

### PR DESCRIPTION
**Pull request by christian-chiappa**

### CODE REVIEW

**Comment by christian-chiappa** [comment]
ci:test:relevant

**Comment by christian-chiappa** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:sf

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:test:sf

**Pull request closed without merging**
