### PR TITLE
LRQA-61552 Test properties fix to prevent functional tests from running on ci

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LRQA-61552

@marco-leo, this fix will prevent the quarantined tests from running on `ci:test:commerce` as noticed here.https://github.com/liferay-commerce/liferay-portal/pull/71#issuecomment-685990678

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf
ci:test:commerce:nocompile

**Comment by nikki-pru** [comment]
ci:test:commerce:nocompile

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
Already fixed at head.

**Pull request closed without merging**
