### PR TITLE
COMMERCE-12589 CSRF bypass related to  in Commerce

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12589

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
@luca-pellizzon This ended up being a bigger PR, I added the fix to other commerce modules as well. Let me know if you want me to break up the commits into different tickets/PRs. The fix proposed is to make sure that we are not relying on passing redirect or back URLs through the url parameters. This poses risk for anyone to enter anything in there and potentially run un wanted commands to portal.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:close

**Pull request closed without merging**
