### PR TITLE
Automated Test - COMMERCE-6378 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6378 ; cc: @pietrobocale

**Comment by kristinonias** [comment]
@pedroalmd 

There are conflicting files in this PR. Please fix and resend.

**Comment by pedroalmd** [comment]
@kristinonias
Conflict fixed, thanks.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Pull request closed without merging**
