### PR TITLE
LPD-33048 Expose lastLoginDate in the admin UI

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-33048

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
