### PR TITLE
COMMERCE-10759 - Checkout: can select existing address with a country for which billing/shipping is disabled

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-10759](https://issues.liferay.com/browse/COMMERCE-10759)
@brianikim 

Problem was that the Countries weren't being filtered before being shown at the select menu.
Proposed fix is to filter the Countries, and make it not possible to select an address as Billing and Shipping, if the address uses a Country that can be used for Billing, but not Shipping.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
hey @victorcdp is it not better to add billing and shipping allowed to the index so we filter directly in the search? Check this https://github.com/riccardo-alberti/liferay-portal/pull/new/COMMERCE-10759. Thanks. /cc @andrea-ale-sbarra

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM

**Comment by brianikim** [comment]
@riccardo-alberti , @andrea-ale-sbarra ,

@victorcdp will update the PR soon with Riccardo's requested changes. Will require review one more time from you @andrea-ale-sbarra  once it happens.

**Comment by brianikim** [comment]
ci:close

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
ci:close

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/3447

**Pull request closed without merging**
