### PR TITLE
COMMERCE-10763 Get Order Details API to return array of files linked to virtual product order items

### PR DESCRIPTION
**Pull request by pietrobocale**
Original PR: https://github.com/liferay-commerce/liferay-portal/pull/3412

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
