### PR TITLE
Commerce 7412 2

### PR DESCRIPTION
**Pull request by garofalog**
This is a bug related to i18n about "Rounding Mode" in **Commerce** > **Currencies**

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
This pr comes from [this rejected pr](https://github.com/brianchandotcom/liferay-portal/pull/109530)

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by brianwulbern** [comment]
@garofalog this one looks good test-wise.  Are we looking for a PM review on it, or is it ready to forward?

**Comment by garofalog** [comment]
ci:close

**Comment by garofalog** [comment]
ci:reopen

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Pull request closed without merging**
