### PR TITLE
COMMERCE-10439 Add custom attributes display for discount and pricelist

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
