### PR TITLE
Automated Tests - CommerceProductCard.testcase - combined PRs

### PR DESCRIPTION
**Pull request by pedro-michel**

### CODE REVIEW

**Comment by pedro-michel** [comment]
https://issues.liferay.com/browse/COMMERCE-5858
https://issues.liferay.com/browse/COMMERCE-5865
https://issues.liferay.com/browse/COMMERCE-5866
https://issues.liferay.com/browse/COMMERCE-5867
https://issues.liferay.com/browse/COMMERCE-5872
https://issues.liferay.com/browse/COMMERCE-5871
https://issues.liferay.com/browse/COMMERCE-5868

cc: @kristinonias . @brittneyq

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
@lorenzolapescara this should be ready for review again!

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:stop

**Comment by kristinonias** [comment]
ci:test:stop

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Reinvoking ci:test:commerce-functional
The tests have not ran and are not showing on Testray for review.

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
Testing: https://github.com/nikki-pru/liferay-portal/pull/99

**Pull request closed without merging**
