### PR TITLE
COMMERCE-6624 Minor UI fixes 

### PR DESCRIPTION
**Pull request by fabio-d-m**
- Spacings fixed in different areas
- unnecessary code removed
- static env updated (@garofalog)
- dataset highlighting fixed in channels

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:stable

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Pull request closed without merging**
