### PR TITLE
LPD-28654 - LPD-28658 Minium 4 CSS CX with custom styles

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-28654
https://liferay.atlassian.net/browse/LPD-28658

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Pull request closed without merging**
