### PR TITLE
COMMERCE-11790 Adapt cpDefinition and cpInstance indexers to the new pattern

### PR DESCRIPTION
**Pull request by pietrobocale**
https://liferay.atlassian.net/browse/COMMERCE-11790

Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4089

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
The relevant failure are not related to the PR

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
