### PR TITLE
LPD-25858 Refactor functional test

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-25858

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:playwright

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:playwright

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
