### PR TITLE
COMMERCE-4719 Make Commerce functional tests work on master

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-4719

### CODE REVIEW

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
Need #299 to be merged.

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
@marco-leo

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
