### PR TITLE
COMMERCE-5004 New functional test: CPCommercePriceLists#AssertPriceListIsAppliedToAllAssociatedAccounts

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-5004

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
