### PR TITLE
COMMERCE-7642 | Refine Commerce relevant

### PR DESCRIPTION
**Pull request by iovaneale**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
