### PR TITLE
LPD-35556 Add delivery and payment terms to headless api

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-35556
https://liferay.atlassian.net/browse/LPD-37469

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci.test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:report:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
resend here https://github.com/liferay-commerce/liferay-portal/pull/5447

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Pull request closed without merging**
