### PR TITLE
COMMERCE-5788|COMMERCE-5767

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-5788
https://issues.liferay.com/browse/COMMERCE-5767

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
@dsitu not sure why ci:forward didn't forward it.... i'll run it again

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
