### PR TITLE
LPD-3472

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-3472

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:stable

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@luca-pellizzon , requesting final analysis on the failures. I looked at them and I do not believe they are related, but I would like your confirmation. I think we can forward if you agree.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
