### PR TITLE
[DO NOT MERGE] COMMERCE-11242 Headless API: SKU "End of Life" date is filled in by default

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-11242

Add functional test coverage

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
functional tests added here https://github.com/liferay-commerce/liferay-portal/pull/3640

**Pull request closed without merging**
