### PR TITLE
COMMERCE-10831 Provide an endpoint to allow clients to configure subscription overrides via API

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10831

resent from
https://github.com/brianchandotcom/liferay-portal/pull/132686
https://github.com/liferay-commerce/liferay-portal/pull/3585

@riccardo-alberti

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
