### PR TITLE
COMMERCE-8938 - Portlets that are not category.hidden should not have…

### PR DESCRIPTION
**Pull request by ethib137**
… com.liferay.portlet.preferences-unique-per-layout=false.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
@alessiorendina can you have a look at this?

**Comment by luca-pellizzon** [comment]
@andrea-ale-sbarra there's nothing to review here. We need our QA guys to run no-regression tests on top of this.

**Comment by ethib137** [comment]
Hi @andrea-ale-sbarra, @luca-pellizzon, and @alessiorendina any update on this? Are we able to merge it?

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
QA Passed.

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
