### PR TITLE
[TS] COMMERCE-11068

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hello @liferay-commerce , do you think this change is safe to go? There are several customers waiting for the fix.

Thank you :)

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by crodriguezy** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
thank you @crodriguezy but I think this is not the right fix, I believe we already fixed this with this https://issues.liferay.com/browse/COMMERCE-10778 -> https://github.com/liferay-commerce/liferay-portal/pull/3534

**Pull request closed without merging**
