### PR TITLE
Automated Test - COMMERCE-6086 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-6086, cc:@pietro69

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//tr/td[contains(.,'Guest')]//..//button[contains(.,'Choose')]"

**Comment by p-albuquerque** [comment]
Fixed.

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "xpath=(//div | //li)[(contains(@class,'open') or contains(@class,'show')) and (contains(@class,'dropdown') or contains(.//*/@class,'dropdown'))]//*[self::a or self::span or self::button][normalize-space(text())='Master']"

**Pull request closed without merging**
