### PR TITLE
Commerce 11661

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11661
Previous PRs: https://github.com/liferay-commerce/liferay-portal/pull/4208, https://github.com/liferay-commerce/liferay-portal/pull/4238 https://github.com/liferay-commerce/liferay-portal/pull/4250

---

Applied BChan request: https://github.com/brianchandotcom/liferay-portal/pull/141090, I've completely removed the method because in the end we weren't using it.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
@victoroscuro, the pr is good to go, please help force-forward it, thanks!

cc/ @andrea-ale-sbarra

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
sent directly to Brian here https://github.com/brianchandotcom/liferay-portal/pull/141315

**Pull request closed without merging**
