### PR TITLE
COMMERCE-11251 Order Splitting Object RuleCommerce

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-11192

### CODE REVIEW

**Comment by pietrobocale** [comment]
PR Based: #3747

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
All the relevant failures are not related to the changes present in the PR

**Comment by victoroscuro** [comment]
Since the checks on the relevant did not highlight any issue related to this PR, I'll force forward this PR. Thanks @pietrobocale

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
