### PR TITLE
COMMERCE-7217 Added attachment base64 field

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:reevaluate:1327401_440

**Comment by Commando18** [comment]
ci:test.relevant

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Pull request closed without merging**
