### PR TITLE
Automated Test - COMMERCE-6330 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
https://issues.liferay.com/browse/COMMERCE-6330, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//ul[contains(@class,'list-group')]//a[contains(@href,'site-configuration-details')]"

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1374 @kristinonias

**Pull request closed without merging**
