### PR TITLE
COMMERCE-4861 deprecate unused and unsafe methods

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:stop

**Comment by riccardo-alberti** [comment]
already forwarded https://github.com/brianchandotcom/liferay-portal/pull/94493

**Pull request closed without merging**
