### PR TITLE
COMMERCE-7046 Use proper comparison for BigDecimal values.

### PR DESCRIPTION
**Pull request by brianikim**
@ivicac ,

Could we forward this? I found a regression with my original fix.
https://issues.liferay.com/browse/COMMERCE-7046

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by ivicac** [comment]
@brianikim sure, as soon as checks are done

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
