### PR TITLE
LPS-199598 Fix account role visibility

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPS-199598

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGMT.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra @smottal I merged this manually to master

**Pull request closed without merging**
