### PR TITLE
LPD-20133

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/LPD-20133

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
The SF issue is not related to this PR

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:report:2557249854

**Comment by alessiorendina** [comment]
ci:forward:force

**Pull request closed without merging**
