### PR TITLE
COMMERCE-12895 Provide New Configuration for Specification and Option Facets

### PR DESCRIPTION
**Pull request by pietrobocale**
Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4495

Ticket: https://liferay.atlassian.net/browse/COMMERCE-12895

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:stable

**Review by baharturk — APPROVED** [review]
Review done!

**Comment by pietrobocale** [comment]
The failures are not related to the PR

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
