### PR TITLE
COMMERCE-9568 - No underline for Unit tab for Measurement Units

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-9568](https://issues.liferay.com/browse/COMMERCE-9568)
@brianikim 

The problem was ocurring because the NavigationItemURL was using the wrong string.
Proposed fix is to correct the typo.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@luca-pellizzon , this one needs your review.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
