### PR TITLE
LPD-36947 Use workflow also in API

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-36947

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:report:16346443

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
