### PR TITLE
Commerce 8878

### PR DESCRIPTION
**Pull request by garofalog**
https://issues.liferay.com/browse/COMMERCE-8878

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
https://issues.liferay.com/browse/COMMERCE-8878

**Pull request closed without merging**
