### PR TITLE
COMMERCE-9417 Show discount amount on Minium Demo Pack 

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-9417

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
Results are good

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
