### PR TITLE
COMMERCE-9482 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-9482

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:relevant

**Comment by Kvale1733** [comment]
ci:stop

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
