### PR TITLE
LPD-35731 Fix tests

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-35731

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:stop

**Comment by smottal** [comment]
ci:test:um

**Review by alessiorendina — APPROVED** [review]
LGTM

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
