### PR TITLE
COMMERCE-11084 Migrate legacy selection modal to openSelectionModal

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-11084
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3886

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:forward

**Review by baharturk — APPROVED** [review]

**Review by baharturk — APPROVED** [review]

**Pull request closed without merging**
