### PR TITLE
COMMERCE-4992 New functional test: CPCommercePriceLists#AssertPriceListHaveRequiredNameAndCurrency

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-4992

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
@marco-leo All checks passed

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
