### PR TITLE
COMMERCE-12060 Fixed options field value for bundle products

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/COMMERCE-12060

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4193

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
