### PR TITLE
Automated Test - COMMERCE-6204 | master

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by fmarcio** [comment]
https://issues.liferay.com/browse/COMMERCE-6204; cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by fmarcio** [comment]
> @fmarcio , please rebase and send again

@pedro-michel done!

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1316. Please close @kristinonias

**Pull request closed without merging**
