### PR TITLE
COMMERCE-10173 - It's possible to save a product configuration with wrong values

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-10173](https://issues.liferay.com/browse/COMMERCE-10173)

Problem was that there was no validation of existence in the inputs. Proposed fix is to add a required validator so that the product can't be saved with the specified inputs empty. Also there was no validation at the backend, so this solution includes that as well.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:close

**Comment by victorcdp** [comment]
ci:reopen

**Pull request closed without merging**
