### PR TITLE
COMMERCE-9596 Extension point to define a Collection Provider that supplies SKU's as options

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4130

**Comment by jaydawu** [comment]
Resent on https://github.com/liferay-commerce/liferay-portal/pull/4139.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
