### PR TITLE
LPD-30370 Refactor test CanSeeAllOrdersOnTheGlobalSearchByEmail to playwright

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-30370

Built on top of https://github.com/liferay-commerce/liferay-portal/pull/5141

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
