### PR TITLE
COMMERCE-10053

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://issues.liferay.com/browse/COMMERCE-10053

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
