### PR TITLE
LPD-35633 Fix discount value

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-35633

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]
LGTM, thank you!

**Comment by smottal** [comment]
ci:report:81408046

**Comment by smottal** [comment]
ci:report:81408046

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:report:82576532

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
