### PR TITLE
COMMERCE-5750 Remove from quarantine CPCommerceCatalogs#CreateNewCatalog

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5750

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
