### PR TITLE
LPD-41164 Set expando bridge attributes before update the model, otherwise the model passed to the model listener will not have the actual value of expando based custom fields

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**
## Related tickets

- https://liferay.atlassian.net/browse/LPD-41164

## Situation

Expando based custom field values are not being passed with the actual values to object actions because object actions are tied to model listener triggers and the expando attribute values are being set after the model listener is called ([see](https://github.com/liferay/liferay-portal/blob/master/modules/apps/account/account-service/src/main/java/com/liferay/account/service/impl/AccountEntryLocalServiceImpl.java#L663))

## Proposed Solution

Based on other assets ([User](https://github.com/liferay/liferay-portal/blob/9ae1acbeb7677334d77e6b694fd72f81b2fb0b3c/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L1296), [Commerce Order](https://github.com/liferay/liferay-portal/blob/12d03e22707ea59d2eabee280329a06852cf85d2/modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/service/impl/CommerceOrderLocalServiceImpl.java#L379)) I've set the expando attributes before the model listener is called.

### CODE REVIEW

**Comment by MarinhoFeliphe** [comment]
ci:test:sf

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hi @smottal, sure!

I will change the tests and I will resend.

Thank you!

**Comment by MarinhoFeliphe** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by MarinhoFeliphe** [comment]
Hey @smottal,

Regarding the failures, I've executed those tests in my local environment and they passed, do you have any idea what could be causing this failures? it seems to be related to left overs from other tests, but I couldn't identify it yet. I appreciate any help you can provide!

[Test results - Class com.liferay.account.service.test.AccountEntryServiceWhenSearchingAccountEntriesTest.pdf](https://github.com/user-attachments/files/17904937/Test.results.-.Class.com.liferay.account.service.test.AccountEntryServiceWhenSearchingAccountEntriesTest.pdf)
[Test results - Class com.liferay.account.service.test.AccountEntryLocalServiceTest.pdf](https://github.com/user-attachments/files/17904939/Test.results.-.Class.com.liferay.account.service.test.AccountEntryLocalServiceTest.pdf)

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
