### PR TITLE
COMMERCE-7617 Product Price available for use with Fragments

### PR DESCRIPTION
**Pull request by pietrobocale**
Original PR:
https://github.com/liferay-commerce/liferay-portal/pull/3468

Jira Ticket:
https://issues.liferay.com/browse/COMMERCE-7617

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:stop

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/132544

**Pull request closed without merging**
