### PR TITLE
COMMERCE-11322 PriceOnApplication on Cart Delivery API

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11322

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM

**Comment by andrea-ale-sbarra** [comment]
> [exec]   com.liferay.portal.kernel.service                  UNCHANGED  22.2.0     22.1.0     22.1.0     EXCESSIVE VERSION INCREASE
> 
> [exec]   -   version    22.1.0
> 
> [exec]   +   version    22.2.0
> 
> [exec] [Baseline Report] Mode: diff (persisted)

@smottal try to rebase the PR on Brian's head, maybe this is already solved

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Pull request closed without merging**
