### PR TITLE
LPS-147887 Delete Clay Data Set tags and API objects

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-147887 Delete Clay Data Set tags and API objects](https://issues.liferay.com/browse/LPS-147887)
- Related to #2706

### What is the goal of this PR?

In this PR, we are deleting Clay Data Set display tags and API object. I am not sure if deletion or deprecation is better, this is a borderline case of being completely safe vs. being shackled to a lot of unused legacy code. /cc @dsanz

In addition, we are migrating the last Clay Data Set usage in DXP, that snuck in during other migration of all commerce modules. That is why I am opening PR on this fork. @victoroscuro

### What does it look like?

The last migration:
screen

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@markocikos  please rebase this PR
The code is ok, just few renames to use FDS instead of ClayDS
cc @riccardo-alberti

**Comment by markocikos** [comment]
Force-pushed, fixing semver conflicts. No changes. 

@luca-pellizzon ok to forward?

**Comment by luca-pellizzon** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-commerce/liferay-portal/pull/2851

**Pull request closed without merging**
