### PR TITLE
COMMERCE-9530, COMMERCE-9531, COMMERCE-9532 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-9530
https://issues.liferay.com/browse/COMMERCE-9531
https://issues.liferay.com/browse/COMMERCE-9532

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
