### PR TITLE
LPD-29864 reset ManuallyAdjusted when modifying open order

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/liferay-commerce/liferay-portal/pull/5093

@luca-pellizzon , please check test failures (I will also double check) as a sanity check before we provide this to the customer.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Review by riccardo-alberti — COMMENTED** [review]
@brianikim if the order has an order item with manually adjusted will that be maintained with this change? Meaning it will recalculate everything but those items that are marked as manually adjusted. Correct?

**Comment by brianikim** [comment]
@riccardo-alberti , the commit was introduced by @luca-pellizzon , I just implemented the test, but I am fairly certain the CommerceOrderItem `manuallyAdjusted` settings should persist since the modelListener commit only resets for the order.

**Comment by brianikim** [comment]
@riccardo-alberti , I took a look at the code.

In the UI, if you add an item to the cart, the orderItem that was manually adjusted will be deleted, and a new one will replace it with the correct, updated quantities, essentially bypassing the `manuallyAdjusted` set. (I could showcase this to you if you need more clarification).

In headless API, `patchOrderItem` will update the orderItem, for example, but will not recalculate the order.

Therefore, in the UI, `U-Joint` which was originally 24 dollars, would be now 25 dollars, but the price and quantity calculation will still be based on the original 24 dollars amount (unless you add or update the cart).

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
