### PR TITLE
COMMERCE-11815 Fix StatusRenderer for quote-processed

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11815
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3927

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by jaydawu** [comment]
Hi [@victoroscuro](https://github.com/victoroscuro), there are no relevant errors to this pull, please force-forward it, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
