### PR TITLE
LPS-189328 Use item selector instead of category selector

### PR DESCRIPTION
**Pull request by victorg1991**
Minor changes to avoid using the categories selector since we are trying to sunset it in favor of the item selector :)

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-commerce/liferay-portal/pull/4092

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
