### PR TITLE
COMMERCE-9952 fix upgrade process

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by vicnate5** [comment]
@luca-pellizzon This fixes the upgrade on Oracle, but breaks it on other databases, including MySQL

MySQL
```
     [java] 2022-09-12 16:00:14.877 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.commerce.inventory.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Every derived table must have its own alias
```
[Full log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/4952/functional-upgrade-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0)

PostgreSQL
```
     [java] 2022-09-12 15:39:47.759 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.commerce.inventory.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: subquery in FROM must have an alias
     [java]   Hint: For example, FROM (SELECT ...) [AS] foo.
     [java]   Position: 99
```
[Full log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/4952/functional-upgrade-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0)

SQL Server
```
     [java] 2022-09-12 15:48:36.387 ERROR [main][UpgradeStepRegistratorTracker:221] Failed upgrade process for module com.liferay.commerce.inventory.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near ')'.
```
[Full log](https://testray.liferay.com/reports/production/logs/2022-09/test-1-27/test-portal-acceptance-pullrequest(master)/4952/functional-upgrade-tomcat90-sqlserver2017-jdk8/0/6/jenkins-console.txt.gz?authuser=0)

CC @victoroscuro

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
@susanchen3 please check the results

**Comment by susanchen3** [comment]
There's one unique failure, but I'm not sure if it's related to the changes made in this PR @vicnate5 

[database-upgrade-client-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/1975474449)
```
     [exec] 2022-09-13 15:30:46.260 INFO  [main][UpgradeProcess:145] Failed upgrade process com.liferay.portal.upgrade.v7_0_0.UpgradeMVCCVersion in 198 ms
     [exec] 2022-09-13 15:30:46.261 INFO  [main][UpgradeProcess:145] Failed upgrade process com.liferay.portal.upgrade.v7_0_0.UpgradeSchema in 7202 ms
     [exec] 2022-09-13 15:30:46.261 INFO  [main][UpgradeProcess:145] Failed upgrade process com.liferay.portal.upgrade.UpgradeProcess_7_0_0 in 7210 ms
     [exec] 2022-09-13 15:30:46.268 ERROR [main][DBUpgrader:79] null
     [exec] com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: com.liferay.portal.kernel.upgrade.UpgradeException: java.sql.SQLSyntaxErrorException: Duplicate column name 'mvccVersion'
     [exec] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:136) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil._upgradeProcess(UpgradeProcessUtil.java:160) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.upgrade.util.UpgradeProcessUtil.upgradeProcess(UpgradeProcessUtil.java:136) ~[portal-kernel.jar:?]
```

**Comment by susanchen3** [comment]
All other failures are unrelated, and `com.liferay.commerce.inventory.service` related failures are fixed

**Comment by vicnate5** [comment]
@luca-pellizzon @victoroscuro forwarding since this fixes a blocker

**Comment by vicnate5** [comment]
ci:forward

**Pull request closed without merging**
