### PR TITLE
LPS-164565 Update cookie.js to take user consent into account

### PR DESCRIPTION
**Pull request by tinycarol**
⚠️ **This PR requires additional changes from Commerce team** ⚠️ 

### References

- [LPS-164565](https://issues.liferay.com/browse/LPS-164565)

#### Use `setCookie` utility from `frontend-js-web` to only add cookies when user has consented

This is partial work, I have just updated the usage of `document.cookie`, which will soon be disallowed across Liferay portal. 

The new cookie utility will not allow cookies to be set when the user hasn't consented to them, so you must discuss with your product team what you should do when they haven't been set.

After these changes, the `setValue` method from `CommerceCookie` will now return a boolean representing whether the cookie has been set, as follows.

```js
const cookie = new CommerceCookie(...);

if (!cookie.setValue('key', 'value')) {
   // Cookie hasn't been set, show tooltip
   ...
} else {
   // Cookie has been set, continue
   ...
}
```

You can use this to handle the logic for the new case if necessary.

### How to replicate

The cookie banner is currently behind a feature flag (`feature.flag.LPS-142518`), so to test this:
* Add `feature.flag.LPS-142518=true` to `portal-ext.properties`
* Restart portal
* Navigate to `Control Panel > System Settings > Cookies`
* Enable the cookie banner by checking the corresponding checkbox and click `Save`
* Cookie banner should now be visible

In your specific use case, as per [this Confluence document](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/1998849368/Liferay+cookies), both cookies have **Functional** consent type, so you must test the affected functionality with Functional cookies accepted and rejected, with unset preferences (banner still visible) and without the feature flag.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
Ehi @tinycarol thanks for this PR, please be aware that we recently opened the #t-commerce channel on Slack and we're usually advised there for any new incoming PR from anyone out of our team. 

Thanks!

**Comment by dsanz** [comment]
Hi @andrea-ale-sbarra , as this PR is needed for the cookie project delivery, we'd like to know team's plan and timeline to review it

Thank you

**Review by andrea-ale-sbarra — COMMENTED** [review]
After reviewing the code here https://github.com/liferay-commerce/liferay-portal/pull/3076 and testing it we found out that:

- Compare product
- Guest user order checkout
- Guest user Wishlist
- Punchout integration

functionalities are not working anymore

**Comment by tinycarol** [comment]
Hi @andrea-ale-sbarra, that's expected. Since [the type of your cookies is functional](https://liferay.atlassian.net/wiki/spaces/ENGR/pages/1998849368/Liferay+cookies), if the user rejects those cookies then this functionality as it is won't work.

As stated in the description of this PR, your team now has to decide what should happen in that situation, and make additional changes to implement it. Some ideas: 
* hiding the elements that link to that functionality
* disabling interactive elements such as buttons and showing a tooltip on hover that informs the user that their cookie preferences disabled that functionality
* displaying an alert that asks the user to enable functional cookies if they want to use that feature

**Comment by dsanz** [comment]
Please check https://github.com/liferay-frontend/liferay-portal/pull/2938 for continuation of this

**Pull request closed without merging**
