### PR TITLE
COMMERCE-8626 - Shipment list not shown when a non-admin user with Operation Manager role navigates to Shipments page

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-8626](https://issues.liferay.com/browse/COMMERCE-8626)

Problem was that the search was being done by filtering through the commerceAccountIds, even if the array was empty.
Proposed fix is to make it return null if the array is empty, so that it doesn't interfere with the search for the Shipments.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
@luca-pellizzon Updated it. Thank you.

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
