### PR TITLE
COMMERCE-12564 - Orders Portlet Order Date Range is filtering by createDate instead of orderDate

### PR DESCRIPTION
**Pull request by victorcdp**
@luca-pellizzon Can you review this one? Tied to an LPP. Thank you.

Relevant Issue: [COMMERCE-12564](https://liferay.atlassian.net/browse/COMMERCE-12564)

The Order Date filter was filtering by createDate, causing confusion when you created an order through headless with an orderDate different from the current date

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
Re-sent at https://github.com/liferay-commerce/liferay-portal/pull/4336

**Comment by Brunno0liveira** [comment]
ci:close

**Pull request closed without merging**
