### PR TITLE
Automated Test - COMMERCE-6151 | master

### PR DESCRIPTION
**Pull request by ewertonluna**

### CODE REVIEW

**Comment by ewertonluna** [comment]
https://issues.liferay.com/browse/COMMERCE-6151, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
SearchBarWidgetSearchProductBySKU passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
