### PR TITLE
Automated Test - COMMERCE-6660 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6660 ; @cc: lorenzolapescara

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by pedroalmd** [comment]
Conflicts resolved @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not visible at "//div[@id='main-content']//div[contains(@class,'portlet-options')]/a"

**Comment by pedroalmd** [comment]
Fixed, please reopen @kristinonias

**Comment by pedroalmd** [comment]
Fixed @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not visible at "//div[@id='main-content']//div[contains(@class,'portlet-options')]/a"

**Pull request closed without merging**
