### PR TITLE
LPS-195448 Fix bypass related to redirect

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Comment by 22LucaGiannotta22** [comment]
ci:test:um

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Pull request closed without merging**
