### PR TITLE
Automated Test - COMMERCE-6327 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/COMMERCE-6327, cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
GlobalSearchSearchProductsBySKUs passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
