### PR TITLE
Automated Test - COMMERCE-6304 | master

### PR DESCRIPTION
**Pull request by Jamersonze**

### CODE REVIEW

**Comment by Jamersonze** [comment]
https://issues.liferay.com/browse/COMMERCE-6304, cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//tr/td[contains(.,'Guest')]//..//button[contains(.,'Choose')]"

**Comment by julioribeiiro** [comment]
Fixed: https://github.com/liferay-commerce/liferay-portal/pull/1260

**Pull request closed without merging**
