### PR TITLE
LPD-22351 | LPD-22352 | LPD-23779 | LPD-23780

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
LPD-22351 - https://liferay.atlassian.net/browse/LPD-20293
LPD-22352 - https://liferay.atlassian.net/browse/LPD-20294
LPD-23779 - https://liferay.atlassian.net/browse/LPD-20295
LPD-23780 - https://liferay.atlassian.net/browse/LPD-23080
FF - LPD-25394 - https://liferay.atlassian.net/browse/LPD-25394

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by gianmarcobrunialti — COMMENTED** [review]
FF Beta to be added

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Comment by gianmarcobrunialti** [comment]
Resent here: https://github.com/brianchandotcom/liferay-portal/pull/150188

**Pull request closed without merging**
