### PR TITLE
COMMERCE-5948 Fix Shopping Experience locators and macros

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-5948

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
