### PR TITLE
COMMERCE-11947 trackingURL is missing in the DTO and DTOconverter

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11947
Resent from https://github.com/liferay-commerce/liferay-portal/pull/4061

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]
QA Review Passed!

Thanks!

**Comment by jaydawu** [comment]
Hi @victoroscuro, just waiting for the CI results to come out, then it can be forwarded, please help monitor, thank you!

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Hi @victoroscuro, failures are not related to the changes, it can be force-forwarded, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
