### PR TITLE
COMMERCE-9687 | Fix failing functional tests due to Chrome 100 usage

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/COMMERCE-9687

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
@iovaneale please close this PR. Another one was created and sent to complete this task. Thanks

**Comment by andrea-ale-sbarra** [comment]
forwarded here https://github.com/john-co/liferay-portal/pull/478

**Pull request closed without merging**
