### PR TITLE
COMMERCE-11782 Provide guest experience to B2B site + Functional Tests

### PR DESCRIPTION
**Pull request by baharturk**
https://liferay.atlassian.net/browse/COMMERCE-11782

sent from: #4012

@dsitu

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Review by lorenzolapescara — COMMENTED** [review]
@baharturk can you please sort the commits so that the functional test commits are the last ones?

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
