### PR TITLE
COMMERCE-12676 fix availability checks

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12676

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra merged to master, just e6de432922145b7f5c5faaa9b7ad405d935dbf25

**Comment by jaydawu** [comment]
ci:stop

**Comment by jaydawu** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra merged to master

**Pull request closed without merging**
