### PR TITLE
COMMERCE-11679 Fix bundle price

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11679

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
cc @victoroscuro

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Thx @smottal !!!

**Comment by smottal** [comment]
I close this because already merged https://github.com/brianchandotcom/liferay-portal/commit/9233b90aed083a67119afa45c38f5914e8604a35

**Pull request closed without merging**
