### PR TITLE
[CLDR] LPD-20673 Change CommerceOrders#viewOrderShipmentDetails to work with both JRE and CLDR java locale providers

### PR DESCRIPTION
**Pull request by julschong**
Hi Team,
This is related to our planned changing of java locale provider from JRE to CLDR.
Issue: https://liferay.atlassian.net/browse/LPD-20673

I used xpath to include 2 possible date formats for the test to assert because the dates are shown in:
In JRE: "July, 6, 2023"
In CLDR: "July 6, 23"

Basically just changed testcase to accept either one.

Tested with CLDR locally passed.
Below `ci:test:commerce` will give us the result with JRE.

Thank you!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:commerce

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:commerce

**Comment by julschong** [comment]
date format need to change the hour display

**Comment by julschong** [comment]
no unique failure

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
