### PR TITLE
COMMERCE-9409

### PR DESCRIPTION
**Pull request by ghost**
resend this:
https://github.com/brianchandotcom/liferay-portal/pull/141552#issuecomment-1741174101

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:stable

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
Relevant failures aren't related to the changes made in this PR.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
