### PR TITLE
Commerce 7904

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra 

https://issues.liferay.com/browse/COMMERCE-7904

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
@brianikim can you fix rebase conflicts?

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra , 

rebase conflict is addressed.

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
