### PR TITLE
LPD-28520 - fix locator in test

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-28520

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
