### PR TITLE
LPD-16000 Fix permission check for shipment address editing

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-16000

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:um

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reevaluate:1377401_15986

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:commerce-functional

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:forward:force

**Comment by dsitu** [comment]
ci:forward:force

**Pull request closed without merging**
