### PR TITLE
COMMERCE-12216 allow guest to request quotes via email address

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
There are no related failures to this pull, it can be force-forwarded, thanks!

cc/ @[victoroscuro](https://github.com/victoroscuro)

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
