### PR TITLE
Automated Test - COMMERCE-5928 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
https://issues.liferay.com/browse/COMMERCE-5928, cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1324. Please close @kristinonias

**Pull request closed without merging**
