### PR TITLE
COMMERCE-7442, COMMERCE-7216

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-7442
https://issues.liferay.com/browse/COMMERCE-7216

These tickets need to be reviewed and merged together due to the use of serviceContext.

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
@brianikim changes for COMMERCE-7442 looks fine, but I cannot forward because I still need to review COMMERCE-7216. Please don't use same branch for different JIRA issues because I cannot forward until I review everything together.

**Comment by andrea-ale-sbarra** [comment]
Hi @brianikim I've tested COMMERCE-7126 and looks like it work, I'll forward this.
Thanks!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
sent again here https://github.com/liferay-commerce/liferay-portal/pull/2503 because CI is stuck

**Pull request closed without merging**
