### PR TITLE
LPD-34669 Localization issues for Returns

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-34669

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
@dsitu errors do not depend on changes made in the pr

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Pull request closed without merging**
