### PR TITLE
Automated Test -  COMMERCE-6335 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**

### CODE REVIEW

**Comment by leilanyaragao** [comment]
https://issues.liferay.com/browse/COMMERCE-6335, cc: @lorenzolapescara

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
EditBundledProductQuantityFromMiniCart passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
