### PR TITLE
COMMERCE-10841 Preserve doAsUserId for impersonation

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10841

@andrea-ale-sbarra , I am preserving the change from here: https://github.com/liferay/liferay-portal/commit/357667ca36218e90c9b7c4e7c30c2506770a4f34 .

We should make an exception for doAsUserId to support impersonation.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Pull request closed without merging**
