### PR TITLE
LPD-35558 Order Details - Order Summary

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-35558

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Review by gianmarcobrunialti — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
ci:forward:force

**Pull request closed without merging**
