### PR TITLE
LPD-20282\LPD-20696 - part 2

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-20282
https://liferay.atlassian.net/browse/LPD-20696

@luca-pellizzon

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by dsitu** [comment]
@CrescenzoRegaLF I split this up into 2 PR's:

PR1: https://github.com/liferay-commerce/liferay-portal/pull/5082,
Changes: https://github.com/liferay-commerce/liferay-portal/pull/5082/commits/84b9f6a57f66285f4087e9160bb0e2e14d4b04c0

PR2:https://github.com/liferay-commerce/liferay-portal/pull/5083
Changes: https://github.com/liferay-commerce/liferay-portal/pull/5083/commits/31196a8bb05cb8b0492c5e4c42de688c21d8f44d https://github.com/liferay-commerce/liferay-portal/pull/5083/commits/6346758e64698dab177b21cb18d1cfe0b6611376

**Comment by dsitu** [comment]
Closing since new PR's have been opened https://github.com/liferay-commerce/liferay-portal/pull/5077#issuecomment-2190423169

**Pull request closed without merging**
