### PR TITLE
LPD-39108

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-39108

@andrea-ale-sbarra ,

Revert of https://liferay.atlassian.net/browse/LPD-26359

Search team recommended we index HTML elements before they are indexed.

Tied to LPP.

Test for this specific PR is not needed. The test from LPD-26359 [here](https://github.com/brianchandotcom/liferay-portal/commit/a707264957f590b02696d8383a924346344cf94a) already covers our use-case.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
@brianikim do we have a test for this? if not, can you please add one?

**Comment by brianikim** [comment]
@andrea-ale-sbarra ,

We do not need a test for this. Already covered by the test introduced from LPD-26359.

See my comment here: https://github.com/liferay-commerce/liferay-portal/pull/5489#issue-2579967672

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
