### PR TITLE
COMMERCE-12864

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-12864

@luca-pellizzon , tied to critical LPP. Needs to be reviewed and tested as soon as possible as per Bernard.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
@luca-pellizzon , I updated the PR again fyi to handle an edge case when `edit_commerce_order.jsp` was being triggered. The trigger went through `EditCommerceOrderMVCActionCommand` so I also added the check there.

@jaydawu , reassigned to you for QA check again. Thanks.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
QA passed, no related errors to this pull, it can be force-forwarded, thanks!

cc/ [victoroscuro](https://github.com/victoroscuro)

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
