### PR TITLE
COMMERCE-12391 Remove pricing information from details tab

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://liferay.atlassian.net/browse/COMMERCE-12298

Resent from #4258

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to the PR. It can be force forwarded

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
