### PR TITLE
LPD-3448 When clicking on the simulation area, this entire area stops working

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPD-3448](https://liferay.atlassian.net/browse/LPD-3448)
The simulation was not working properly, so I moved outside the liferay-bottom and liferay-top divs from their wrapper. It resolved the issue. Please review my change

[LPD-3448]: https://liferay.atlassian.net/browse/LPD-3448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:report:2541749894

**Comment by andrea-ale-sbarra** [comment]
ci:report:2539596099

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by brianikim** [comment]
ci:forward:force

**Comment by brianikim** [comment]
@andrea-ale-sbarra , I reran the force command because it was stuck.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
