### PR TITLE
COMMERCE-10186 Headless API to set an Account Default Shipping Option per Channel

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by dsitu** [comment]
new PR [here](https://github.com/liferay-commerce/liferay-portal/pull/3252) with [changes](https://github.com/liferay-commerce/liferay-portal/pull/3252/commits/b91904295b50ad70646b0d7d09072ba8931dfa64) checking for a valid channelId

**Comment by andrea-ale-sbarra** [comment]
Apparently in the end this one https://github.com/liferay-commerce/liferay-portal/pull/3252 was forwarded, so this I think can be closed with no harm, isn't it?

**Pull request closed without merging**
