### PR TITLE
COMMERCE-12522 Add test CanAddToCartStaticPriceBundledProductWithUOM

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://liferay.atlassian.net/browse/COMMERCE-12522

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:forward

**Pull request closed without merging**
