### PR TITLE
Automated Test - COMMERCE-6162 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**

### CODE REVIEW

**Comment by leilanyaragao** [comment]
https://issues.liferay.com/browse/COMMERCE-6162, cc: @LorenzoLaPescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
Review started.

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
Element is not present at "//p[@title='U-Joint']//../..//select[(@class='form-control quantity-selector')]"

**Pull request closed without merging**
