### PR TITLE
COMMERCE-8376 UI to show Shipment External Reference

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-8376

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
forwarded by
https://github.com/liferay-commerce/liferay-portal/pull/2768

@luca-pellizzon @baharturk

**Pull request closed without merging**
