### PR TITLE
COMMERCE-8851 change the products action menu item from "View" to "Edit"

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
https://issues.liferay.com/browse/COMMERCE-8851

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
