### PR TITLE
LPD-18966 fix testUpdate

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/LPD-18966

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:jacoco-report

**Review by smottal — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
