### PR TITLE
COMMERCE-0 Fix query performance

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:stop

**Comment by victoroscuro** [comment]
ci:stop

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
@victoroscuro do not send this one yet

**Pull request closed without merging**
