### PR TITLE
COMMERCE-9203 Deprecate CommerceAccountService

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9203

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@dsitu I see only 1 failure that could be related to this development:
CanAddNewUserToAccountAsChannelAccountManager
We probably need to update the permissions that we are assigning by default to this "ChannelAccountManager".
Please check this with the help of our QA.
Thanks

**Comment by dsitu** [comment]
> @dsitu I see only 1 failure that could be related to this development: CanAddNewUserToAccountAsChannelAccountManager We probably need to update the permissions that we are assigning by default to this "ChannelAccountManager". I think in the test they use the SalesAgent role, probably we need to update permissions in roles.json (both Minium and Speedwell). Please check this with the help of our QA. Thanks

@luca-pellizzon Added commit here [677fd0c](https://github.com/liferay-commerce/liferay-portal/pull/3305/commits/677fd0c9d0ba418b908bdd2bec4decd6c837f03f)

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by iovaneale** [comment]
@dsitu Please resolve the conflicts so as we can forward the PR to Brian. Thanks.

**Comment by iovaneale** [comment]
Sent to #3327 

@luca-pellizzon @victoroscuro @riccardo-alberti @dsitu

**Comment by iovaneale** [comment]
ci:close

**Pull request closed without merging**
