### PR TITLE
Automated Test - COMMERCE-6232  | master

### PR DESCRIPTION
**Pull request by leilanyaragao**

### CODE REVIEW

**Comment by leilanyaragao** [comment]
https://issues.liferay.com/browse/COMMERCE-6232, cc: @iovaneale

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:stop

**Comment by JoMaAlves** [comment]
New PR sent: https://github.com/liferay-commerce/liferay-portal/pull/1338
@kristinonias , please close.

**Pull request closed without merging**
