### PR TITLE
COMMERCE-12255 CPDefinitionOptionRel db table mismatch on upgraded database

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12255

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
I'll ask QA to test this upgrade process carefully, I don't know what will happen if one upgrades from 7.3 to this version


Thank you!

**Comment by baharturk** [comment]
ci:test:upgrade

**Comment by victoroscuro** [comment]
Hey @lucasperj can I ask you the favour of checking the results of the ci:test:upgrade suite? Thanks a lot!

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by lucasperj** [comment]
:green_circle:  Hey @victoroscuro @andrea-ale-sbarra , failures on ci:test:upgrade are not related :rocket:

**Comment by baharturk** [comment]
The relevant failures are irrelevant to the PR, we can forward it. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
