### PR TITLE
COMMERCE-5053 Rename BOM to Shop by Diagram

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Review by marco-leo — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
