### PR TITLE
COMMERCE-11672 | Discount Handling of UOM

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11672
Add automation and resent from https://github.com/liferay-commerce/liferay-portal/pull/4249.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @victoroscuro, there are no related failures to this pull, it can be force-forwarded, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
