### PR TITLE
LPD-4174 Functional test

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-18765

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
