### PR TITLE
COMMERCE-9767

### PR DESCRIPTION
**Pull request by brianikim**
Sent from: https://github.com/liferay-commerce/liferay-portal/pull/3393

@baharturk

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
Test is passing and no issues are revealed, the only reason relevant fails is the semantic-versioning issue. This PR can be send directly to BChan if agreed.

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
