### PR TITLE
COMMERCE-8876 Migrate js code out of add to cart tag jsp

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-8876

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@alessiorendina @andrea-ale-sbarra is this PR still needed? If not please close

**Comment by alessiorendina** [comment]
@riccardo-alberti It is, but we didn't estimate it yet. It was part of a development that @garofalog was doing outside of the sprint.

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Pull request closed without merging**
