### PR TITLE
COMMERCE-9895 Remove Terms of Use tests

### PR DESCRIPTION
**Pull request by patriciajeanperez**
https://issues.liferay.com/browse/COMMERCE-9895

cc @iovaneale

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
@patriciajeanperez It seems that CI is stuck on this PR, do you think it could be valuable to close this and open a new one?

**Comment by victoroscuro** [comment]
ci:stop

**Comment by patriciajeanperez** [comment]
@iovaneale @victoroscuro Is it ok if I just manually forward this since I just removed the tests?

**Comment by victoroscuro** [comment]
@patriciajeanperez yes please, thanks!

**Comment by patriciajeanperez** [comment]
Tests already removed in LRQA-76699 @iovaneale @victoroscuro

**Pull request closed without merging**
