### PR TITLE
LPD-36858 New toggle in the Channel Details to enable/disable quick checkout

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-36858

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Pull request closed without merging**
