### PR TITLE
LPD-32039

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-32039

@luca-pellizzon , tied to LPP.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Review by luca-pellizzon — COMMENTED** [review]
Fine with that, but shouldn't we do the same for billing address?

**Comment by brianikim** [comment]
@luca-pellizzon , updated PR with billing address update as well.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
@luca-pellizzon , let me know if this could be forwarded.

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
