### PR TITLE
 COMMERCE-9546 Append extension to the fileName always 

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9546

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by brianikim** [comment]
@andrea-ale-sbarra , please review latest commit 54d1cb5 to address the QA failure identified in COMMERCE-9546. To clarify, the failure is not caused by the commit introduced in 7f172aa.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
The semantic versioning seems like a false alarm. Rerunning ci:test to confirm because my local environment is giving me some issues on baseline.

**Comment by brianikim** [comment]
ci;test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
Thank you @brianikim

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
@pietrobocale looks good to me, let's test it.

Thank you!

**Comment by pietrobocale** [comment]
New PR: #3145

**Comment by andrea-ale-sbarra** [comment]
forwarded here https://github.com/liferay-commerce/liferay-portal/pull/3145

**Pull request closed without merging**
