### PR TITLE
COMMERCE-12504 - Missing Data in headless-commerce-admin-catalog Endpoints

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://liferay.atlassian.net/browse/COMMERCE-12504

Resent from #4284

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
rebased and resent here https://github.com/liferay-commerce/liferay-portal/pull/4362

**Pull request closed without merging**
