### PR TITLE
LPD-34177 Widget Display Template is not showing updated prices

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-34177

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — COMMENTED** [review]
Code looks good, but I'm not sure this is the right fix, what if the expected price is not the base one?

**Comment by dsitu** [comment]
> Code looks good, but I'm not sure this is the right fix, what if the expected price is not the base one?

ahh good point, I think using CommercePriceCalculation should work

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Pull request closed without merging**
