### PR TITLE
COMMERCE-12991

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Review by smottal — APPROVED** [review]
LGTM. Thx

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to the PR. This can be force forwarded

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Pull request closed without merging**
