### PR TITLE
COMMERCE-9200 Fix replacement SKU for diagram

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-9200

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you @smottal

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by smottal** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce

**Pull request closed without merging**
