### PR TITLE
LPD-20117 Move feature flag DEV from story LPD-9361 to epic LPD-10562

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-20117

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
this is probably going to conflict with https://github.com/brianchandotcom/liferay-portal/pull/148452

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF , Stefano's PR has been merged, please rebase this one and update what needs to be converted to the new FF code. Thanks

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
