### PR TITLE
LPD-18594

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-18605
https://liferay.atlassian.net/browse/LPD-18606
https://liferay.atlassian.net/browse/LPD-20673
https://liferay.atlassian.net/browse/LPD-20674
https://liferay.atlassian.net/browse/LPD-20675
https://liferay.atlassian.net/browse/LPD-20677

@luca-pellizzon . Just will be running CI to make sure it passes.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
cc/ @julschong

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
CLDR test being ran here: https://github.com/liferay-commerce/liferay-portal/pull/4811

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by julschong** [comment]
ci:report:2555430085

**Comment by julschong** [comment]
running report on `ci:test:commerce-functional`

**Comment by julschong** [comment]
@brianikim @luca-pellizzon good to go. Test change related to this PR all passed both in this PR and in the CLDR PR

**Comment by brianikim** [comment]
ci:forward

**Pull request closed without merging**
