### PR TITLE
COMMERCE-6702 & commerce-6574 Fix order list in account selector

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by ivicac** [comment]
@alecsloan can you please rebase and fix conflicts?

thx

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
Resent at https://github.com/liferay-commerce/liferay-portal/pull/1602

**Pull request closed without merging**
