### PR TITLE
Automated Test - COMMERCE-6088 | master

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by fmarcio** [comment]
https://issues.liferay.com/browse/COMMERCE-6088, cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
https://issues.liferay.com/browse/COMMERCE-6673

**Pull request closed without merging**
