### PR TITLE
Commerce 11661

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-11661

---

Applied BChan request: https://github.com/brianchandotcom/liferay-portal/pull/141090, I've completely removed the method because in the end we weren't using it.

@jaydawu FYI

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @andrea-ale-sbarra, I've fixed the conflicts on the functional tests part under https://github.com/liferay-commerce/liferay-portal/pull/4248. But at this moment, the stable job is keeping failing, and is not related to ours only, so we might need to wait for it to be recovered, then forward the pr, thanks!

**Comment by andrea-ale-sbarra** [comment]
fixe sent here https://github.com/liferay-commerce/liferay-portal/pull/4248

**Pull request closed without merging**
