### PR TITLE
LPD-3383 CPDefinition is always a draft before publishing.

### PR DESCRIPTION
**Pull request by brianikim**
We should update and validate Asset once we actually publish.

Hello @andrea-ale-sbarra ,

https://liferay.atlassian.net/browse/LPD-3383

Cleanest way to solve this issue is to make sure the cpDefinition is in draft status.

This also allows us to use existing validation in [CardinalityAssetEntryValidator](https://github.com/liferay/liferay-portal/blob/24f404205d60c134d60385011daa6299460f157e/modules/apps/asset/asset-categories-service/src/main/java/com/liferay/asset/categories/internal/validator/CardinalityAssetEntryValidator.java#L70) in headless api for `postProduct` where we can set `productStatus` to `published`. The existing validation will fail the API call and give clear error on why it failed 

```
if (assetVocabulary.isMissingRequiredCategory(
				classNameId, classTypePK, categoryIds)) {

			throw new AssetCategoryException(
				assetVocabulary, AssetCategoryException.AT_LEAST_ONE_CATEGORY);
		}
```

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
code looks good, but I'm not sure this is the right fix, I'm not 100% sure is the right thing to do to not apply the desired change described in the bug description.
@alessiorendina can you please have a look at this too?
Thank you!

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
The code looks good to me, there isn't a real solution for this one, but this can be a workaround for now. Thank you!

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
@brianikim please check the errors

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:stable

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@brianikim I believe the failures on stable are related to the changes you made, it looks like it expect the asset for the product to be there, and that's probably the reason why we decided that the right fix is the one described in the ticket.
Can you please resend this with the right fix? 
Thank you!

**Pull request closed without merging**
