### PR TITLE
[Test Fix] LPD-20674 Fix fucntional test hour format in SFCommerceOrders

### PR DESCRIPTION
**Pull request by julschong**
Hi Team, @brianikim @pedro-oliveira446 
This is a test fix related to the CLDR change we finished.
Noticed from my test scan this morning that the hour format is not right causing the test to fail at 12 am.
UI shows 12 am, test format asserts 0 am.

I changed it to use "h"(1-12) instead of "K"(0-11)
image

Reference: https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
image

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:commerce-functional

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:report:2557992936

**Comment by brianikim** [comment]
@julschong , we can forward this if the tests passed. Please let me know your analysis on the result.

**Comment by julschong** [comment]
@brianikim all SFCommerceOrders tests passed ready to go

**Comment by brianikim** [comment]
ci:forward

**Pull request closed without merging**
