### PR TITLE
COMMERCE-7063 Change logic to prep for LPS-137328

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-7063

@andrea-ale-sbarra , this should be merged once LPS-137328(https://github.com/liferay-lima/liferay-portal/pull/2223) passes review.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@andrea-ale-sbarra ,

This can proceed now with the review process and be merged. LPS-137328 has been merged.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:bundle

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
