### PR TITLE
COMMERCE-9713 Fixed new product images issue

### PR DESCRIPTION
**Pull request by alessiorendina**
Resending https://github.com/brianchandotcom/liferay-portal/pull/123635

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
@pietrobocale, if everything's ok, we can forward it

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
