### PR TITLE
LPD-27339 Notification email templates do not support CC and BCC fields

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-27339

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:report:18973984

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
