### PR TITLE
Automated Test - COMMERCE-6258 | master

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-6193; cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
@wesleyroberts COMMERCE-6193 was attached by mistake, isn't it?

**Comment by wesleyroberts** [comment]
> @wesleyroberts COMMERCE-6193 foi anexado por engano, não foi?

Yes, i 'm sorry.

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
