### PR TITLE
COMMERCE-9944 - PIM - Remove Option to Change Name for Duplicate Product

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-9944

Based on: #2995

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:stop

**Comment by lorenzolapescara** [comment]
Resent at #3097. Please close this PR.
Thanks, Lorenzo.

**Pull request closed without merging**
