### PR TITLE
COMMERCE-12048 Show details in workflow notification for product relationships

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12048

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:stop:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Since there are more than 300 integration [tests](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2406817286&testrayRunId=2406824838&statuses=0) that didn't run in CI, I'd like to suggest rerunning the test suite until ensuring all the tests are run in CI then can be forwarded it, thanks.

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
The issues are not related to the changes, PR can be forward

@luca-pellizzon

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
