### PR TITLE
COMMERCE-8907, COMMERCE-8908, COMMERCE-8909, COMMERCE-8992, COMMERCE-8993 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-8907
https://issues.liferay.com/browse/COMMERCE-8908
https://issues.liferay.com/browse/COMMERCE-8909
https://issues.liferay.com/browse/COMMERCE-8992
https://issues.liferay.com/browse/COMMERCE-8993

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Review by iovaneale — APPROVED** [review]

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
