### PR TITLE
COMMERCE-8865 Fix mapped product section NaN error

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-8865

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reevaluate:1377401_2196

**Comment by dsitu** [comment]
ci:reevaluate:1377401_2196

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
Looks like this need just a test

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
