### PR TITLE
COMMERCE-5998 Filter to Account Users before clicking on a user

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-5998

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:forward

**Review by ivicac — APPROVED** [review]

**Pull request closed without merging**
