### PR TITLE
LPD-17895 Fix Account test

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-17895

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:um

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
