### PR TITLE
COMMERCE-11324 PriceOnApplication in product details page

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11324

### CODE REVIEW

**Review by andrea-ale-sbarra — APPROVED** [review]
just that question, but overall looks good to me.

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
