### PR TITLE
COMMERCE-10557 Fix organization deletion from account through API

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10557

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:stop

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
@luca-pellizzon can you please have a look at this too?

**Review by luca-pellizzon — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
