### PR TITLE
COMMERCE-9488 New Order Details Page default configuration

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/COMMERCE-9488

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
Review passed

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
Sent #3120

**Pull request closed without merging**
