### PR TITLE
COMMERCE-4767 Custom attributes are missing from discount ui

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
Closing sent directly here https://github.com/brianchandotcom/liferay-portal/pull/94154.

**Pull request closed without merging**
