### PR TITLE
Automated Test - COMMERCE-6322 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**

### CODE REVIEW

**Comment by leilanyaragao** [comment]
https://issues.liferay.com/browse/COMMERCE-6322, cc: @lorenzolapescara

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
GlobalSearchSearchEntryInCatalog passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
