### PR TITLE
Automated Test - COMMERCE-6110 | master

### PR DESCRIPTION
**Pull request by LucasAcacio**

### CODE REVIEW

**Comment by LucasAcacio** [comment]
https://issues.liferay.com/browse/COMMERCE-6110, cc: @pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
Review started

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
