### PR TITLE
COMMERCE-6991 followup 2

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Review by dsitu — CHANGES_REQUESTED** [review]
Whoops, sorry everything looks good besides that sf error

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
