### PR TITLE
COMMERCE-10819,COMMERCE-10820

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10819
https://issues.liferay.com/browse/COMMERCE-10820

@alessiorendina 

cc/ @MahmoudAzzam

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
@brianikim LGTM, but can we test if the category manager can access only Minium-related categories?

**Comment by jaydawu** [comment]
Hi @brianikim, could you please update the code? It has some conflicts now. Thank you in advance.

**Comment by brianikim** [comment]
@jaydawu , branch updated.

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3685

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
