### PR TITLE
Automated Test - COMMERCE-6094 | master

### PR DESCRIPTION
**Pull request by ocesar9**

### CODE REVIEW

**Comment by c3saroliveira** [comment]
https://issues.liferay.com/browse/COMMERCE-6094, cc: @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
Please add the `property test.name.skip.portal.instance = "CPCommerceProductConfigurations#UseConfiguration"`

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-function

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Passing [here](https://testray.liferay.com/home/-/testray/cases/1532397059).

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
