### PR TITLE
COMMERCE-10054

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10054

@luca-pellizzon ,

New commit: 23f14f8 to address https://issues.liferay.com/browse/COMMERCE-10671

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Tested manually for functional test failure regarding guest checkout. Not reproducible.

**Comment by lorenzolapescara** [comment]
@brianikim @luca-pellizzon I re-sent this at #3356 following changes on the functional tests after the review.
Can you please close this PR? Thanks!

**Pull request closed without merging**
