### PR TITLE
COMMERCE-9455 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-9455

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
I'm actually realizing that if this bug were to happen again then every test that uses the JSON macro to create products will fail. I'll move the API call to the test level instead.

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]

**Comment by pietrobocale** [comment]
The issue is:
`java.lang.Exception: Element is not present at "//img[@class='sticker-img'][contains(@src,'account')]"`

**Comment by pietrobocale** [comment]
@Kvale1733 Please fix the test and run again ci:test:commerce-functional.

Thanks!

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:test:sf

**Review by pietrobocale — APPROVED** [review]

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
