### PR TITLE
COMMERCE-7514 Implement InfoItemRenderer for Gallery

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@andrea-ale-sbarra is this PR still needed? if not please close it

**Comment by andrea-ale-sbarra** [comment]
closing it because the referenced ticket was closed and tested, so this looks not necessary anymore.

**Pull request closed without merging**
