### PR TITLE
COMMERCE-10360 Reorder tabs to make sure the FDS can properly render

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10360

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
Closing because outdated.

**Comment by victoroscuro** [comment]
ci:stop

**Pull request closed without merging**
