### PR TITLE
COMMERCE-11150 Fix preload subscription fields

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-11150
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3681

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional:nocompile

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
cc/ @victoroscuro

**Comment by victoroscuro** [comment]
Failures on the last relevant run seem to be unrelated to the PR changes. I'll force forward this.

**Pull request closed without merging**
