### PR TITLE
Commerce 4977 headless commerce admin shipment

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@riccardo-alberti this should pass to your team, as of now it has still 6 test failing for Shipment Item operations.

**Pull request closed without merging**
