### PR TITLE
Automated Test - COMMERCE-6069 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/COMMERCE-6069, cc: @iovaneale

**Comment by kristinonias** [comment]
@91nilo Please remove @ignore = "true" from the testcase and then resend.

**Comment by 91nilo** [comment]
Hi @kristinonias, i removed it now.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
Review started

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
