### PR TITLE
COMMERCE-5420 Add quarantine property for GuestCheckoutEnabledWithoutAuthenticationPage AssertPriceListIsAppliedToAllAssociatedAccounts and AssertDiscountIsAppliedToChannel

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5420

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
