### PR TITLE
Automated Test - COMMERCE-6282 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-6282 cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by julioribeiiro** [comment]
fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
java.lang.Exception: Element is present at "//*[@data-qa-id='row']//*[normalize-space(text())='Quantity']"

**Comment by p-albuquerque** [comment]
New PR sent: #1303 
Please Close

**Pull request closed without merging**
