### PR TITLE
COMMERCE-11553

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-11553

resend of this https://github.com/liferay-commerce/liferay-portal/pull/3806

@victorcdp please check this.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
QA passed, add automated test and resent on https://github.com/liferay-commerce/liferay-portal/pull/3839

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
