### PR TITLE
Automated Test - COMMERCE-5843 Add DeactivateCurrency test | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/COMMERCE-5843

Rebased from https://github.com/nikki-pru/liferay-portal/pull/64

cc @pedro-michel, @FabioDiegoMastrorilli

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by pedro-michel** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Comment by nikki-pru** [comment]
see #857

**Pull request closed without merging**
