### PR TITLE
COMMERCE-4621 Fixed modal overridden display css attr

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
The removal of the media query doesn't affect the original reason why it was introduced (apparently the creation of the Assigner). Tested through modals in primary AdminUI contexts and as children of SidePanels.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Review by marco-leo — APPROVED** [review]

**Comment by marco-leo** [comment]
sent directly to Brian https://github.com/brianchandotcom/liferay-portal/pull/93539

**Pull request closed without merging**
