### PR TITLE
COMMERCE-11836 | Price on Application as the "highest price"

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #3939 

https://liferay.atlassian.net/browse/COMMERCE-11836

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
Review Passed, nothing to change.

Thanks!

**Pull request closed without merging**
