### PR TITLE
Automated Test - COMMERCE-6066 | master

### PR DESCRIPTION
**Pull request by Jamersonze**

### CODE REVIEW

**Comment by Jamersonze** [comment]
https://issues.liferay.com/browse/COMMERCE-6066, cc: @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @Jamersonze, please fix your setup. Setup should not be commented out. Thanks!

**Comment by Jamersonze** [comment]
Hi @kristinonias, please confirm the fix.

**Comment by Jamersonze** [comment]
Fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Review by Pietro69 — CHANGES_REQUESTED** [review]
I made a mistake in the steps, the facts are missing the control part, is it possible to check if PG2 has been added and is present before the publish?

**Comment by Jamersonze** [comment]
Ok. Could you update the [COMMERCE-6066](https://issues.liferay.com/browse/COMMERCE-6066) description to reflect the additional step? Thanks.

**Comment by Jamersonze** [comment]
Fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
