### PR TITLE
COMMERCE-4698 prevent NPE when interacting with pricing layer

### PR DESCRIPTION
**Pull request by igorbeslic**
Please review

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:forward

**Comment by marco-leo** [comment]
Hey @igorbeslic for next time. I still didn’t review the PR, and was not approved by reviewers.

Please follow the procedures we talked in our call with all team.

**Pull request closed without merging**
