### PR TITLE
COMMERCE-10778 Mini cart fragment

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10778

resend of this https://github.com/brianchandotcom/liferay-portal/pull/131794

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Pull request closed without merging**
