### PR TITLE
Lpd 3472

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-3472

@luca-pellizzon

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
@brianikim please rebase the PR, thanks

**Comment by brianikim** [comment]
@luca-pellizzon , I know the PR was approved, but I would like to discuss with you a limitation (maybe, this is what I would like to confirm with you) of our parse implementation.

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/4766

**Pull request closed without merging**
