### PR TITLE
COMMERCE-9601 - In a Channel, users without the permission to set Permissions can still see the Permissions menu item on the payment method's ellipsis

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-9601](https://issues.liferay.com/browse/COMMERCE-9601)

Problem was that there was no check to see if user had the "Permissions" permission before showing the dropdown button.
Proposed fix is to check user's permissions before showing the button.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
@luca-pellizzon Updated it. Thanks

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
Failures are not related to the changes

**Comment by Brunno0liveira** [comment]
ci:close

**Pull request closed without merging**
