### PR TITLE
COMMERCE-7640 

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
These changes let users search orders by user creator email.

https://issues.liferay.com/browse/COMMERCE-7640

---

To make the CI work we needed to ignore the integration test in API, the test will be fixed in the linked bug and removed from ignored list

https://issues.liferay.com/browse/COMMERCE-9983 will fix the test

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
