### PR TITLE
LPD-29697 Updating a product via a PATCH API call when a UOM is set is unexpectedly setting the list price to $0

### PR DESCRIPTION
**Pull request by michelevigilante**
https://liferay.atlassian.net/browse/LPD-29697

----

Resend of https://github.com/brianchandotcom/liferay-portal/pull/152704#issuecomment-2255370107

### CODE REVIEW

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGMT.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
