### PR TITLE
LPS-156004 - Liferay Objects + Liferay Import/Export - support import of Liferay Custom Objects

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
@LuismiBarcos I've forwarded to Brian. This version supports only Import. I have to add export support. It should be done tomorrow.
Please note that I updated OpenApi infrastructure to properly map Field REQUIRED attribute.

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Hi @igorbeslic 
Thanks for doing this, really appreciate 🙂 

BTW, seems like there is a rebase error with master, isn't it?

**Comment by igorbeslic** [comment]
@LuismiBarcos I'll deal with it

**Pull request closed without merging**
