### PR TITLE
Automated Test - COMMERCE-6338 | master

### PR DESCRIPTION
**Pull request by piresdm**

### CODE REVIEW

**Comment by piresdm** [comment]
https://issues.liferay.com/browse/COMMERCE-6338; cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ViewMiniCartItemWithDiscount passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
