### PR TITLE
Automated Test - COMMERCE-6162 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6162 , cc: @lorenzolapescara

**Comment by JoMaAlves** [comment]
Corrected version of https://github.com/liferay-commerce/liferay-portal/pull/977

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
