### PR TITLE
COMMERCE-9232

### PR DESCRIPTION
**Pull request by rosdb**
Main task: [COMMERCE-9232](https://liferay.atlassian.net/browse/COMMERCE-9232)
Sub-task: [COMMERCE-11998](https://liferay.atlassian.net/browse/COMMERCE-11998)

In this PR, an unused and unmaintained development tool will be removed, achieving, in any case, the main task goal of the security issue. This tool runs a mock commerce environment used before the commerce repo was merged in DXP and is no longer helpful. --> [slack thread](https://liferay.slack.com/archives/CNBG06JS3/p1690794504019229)

### CODE REVIEW

**Comment by rosdb** [comment]
ci:test:sf

**Comment by rosdb** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:stable

**Comment by baharturk** [comment]
The failures in the relevant are unrelated to the PR, it can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
