### PR TITLE
Commerce 11387 new

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
Jira : https://issues.liferay.com/browse/COMMERCE-11387
Previous PR : https://github.com/liferay-commerce/liferay-portal/pull/3777
Forwarded PR : https://github.com/brianchandotcom/liferay-portal/pull/135148
Brian requested change : https://github.com/brianchandotcom/liferay-portal/pull/135148#issuecomment-1559497330

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed.

**Comment by jaydawu** [comment]
ci:forward

**Comment by jaydawu** [comment]
ci:forward

**Pull request closed without merging**
