### PR TITLE
COMMERCE-10750

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10750

@luca-pellizzon ,

cc/ @dsitu for review on indexer and integration test

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by brianikim** [comment]
ci:stop

**Comment by Brunno0liveira** [comment]
Hi @brianikim can you please close this PR, I open a new one at https://github.com/liferay-commerce/liferay-portal/pull/3479

Thanks!

**Pull request closed without merging**
