### PR TITLE
COMMERCE-7694

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-7694

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
@CrescenzoRegaLF, it looks good to me. Our QA can manually test it.

cc @victoroscuro

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
