### PR TITLE
COMMERCE-9343 Error thrown simply by clicking Widget Templates

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/COMMERCE-9343

/cc @chileces

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
looks good to me

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
QA Passed

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
