### PR TITLE
COMMERCE-5574 Restore ProductGroups ServiceProvider interfaces

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
These are the ProductGroups ServiceProvider interfaces which were unfortunately smashed due to a couple of files moved incorrectly here: https://github.com/liferay-commerce/liferay-portal/pull/381/files#diff-ebfbb90aadfa4dd34667b5b6e109d27764f5c8d698b98996cc15dbce466d93a5L17

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Review by riccardo-alberti — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
liferay/ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
