### PR TITLE
COMMERCE-10847 Select order type before add product to a cart

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
Hey @alessiorendina, I have made the changes you requested but kept the `event` because we need to keep the event data after we close the modal, so the product can be added on the cart. 

In the last PR you send, some tests related to products variants failed. I investigated and run the tests locally but this error also happens on master.

**Comment by alessiorendina** [comment]
Hey @ilzamcmed , we checked with @victoroscuro and he said these errors are not happening on master. You could contact him and our QAs to ask for help on reproducing the issues. Thank you

**Comment by ilzamcmed** [comment]
Hey @alessiorendina, I'll check again and get back to you.
Thanks

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
Hey @alessiorendina 
Apparently the `namespace`  we send on the fire event on `DDMFormHandler.js` is different from the one we receive on the `AddToCart.js`.
Liferay.fire event:  
> '_com_liferay_commerce_product_content_web_internal_portlet_CPContentPortlet_INSTANCE_minium_'

Liferay.on event
> "wwxc_column_2d_1_2_add_to_cart"

Can you take some time to fix that?
Thanks!

**Comment by ilzamcmed** [comment]
resent to https://github.com/liferay-commerce/liferay-portal/pull/3780

**Pull request closed without merging**
