### PR TITLE
COMMERCE-11343 clean fields if not override

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-11343

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1407401_2251

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automated test and resent on https://github.com/liferay-commerce/liferay-portal/pull/3776

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
