### PR TITLE
COMMERCE-9036 Fixed shipping options issue during checkout

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Thank you @brianchandotcom 
I'll close this one then.

**Pull request closed without merging**
