### PR TITLE
Automated Test - COMMERCE-5982 | master

### PR DESCRIPTION
**Pull request by juliaduartelira**

### CODE REVIEW

**Comment by juliaduartelira** [comment]
https://issues.liferay.com/browse/COMMERCE-5982, cc: @alessandro.iovane

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Pull request closed without merging**
