### PR TITLE
COMMERCE-10610 Check channel rel permission

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10610

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Resend on https://github.com/liferay-commerce/liferay-portal/pull/3567

**Pull request closed without merging**
