### PR TITLE
COMMERCE-8997 Product automatically created as DRAFT

### PR DESCRIPTION
**Pull request by alessiorendina**
Missing functional tests. @pietrobocale is working on them.

cc @andrea-ale-sbarra

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1357401_1476

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:stop

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:forward

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:forward

**Comment by alessiorendina** [comment]
ci:reopen

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
