### PR TITLE
Automated Test - COMMERCE-6249 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6249 ; cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//div[@id='main-content']//div[contains(@class,'portlet')]//section[contains(@id,'Checkout')]"

**Comment by pedroalmd** [comment]
Please reopen @kristinonias

**Comment by pedroalmd** [comment]
Fixed @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
