### PR TITLE
COMMERCE-12374

### PR DESCRIPTION
**Pull request by Brunno0liveira**
https://liferay.atlassian.net/browse/COMMERCE-12374

### CODE REVIEW

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Review by pietrobocale — CHANGES_REQUESTED** [review]
Review Completed checks the comments!

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
