### PR TITLE
COMMERCE-5176 New functional test: CPCommerceDiscounts#AssertDiscountIsAppliedToChannel

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-5176

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Review by marco-leo — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
