### PR TITLE
COMMERCE-5039 Change property portal.upstream in CPCommercePriceLists.testcase

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5039

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:stop

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:commerce

**Comment by marco-leo** [comment]
ci:test:commerce

**Comment by marco-leo** [comment]
ci:test:commerce

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
