### PR TITLE
LPD-37602 - Errors in Poshi tests

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-37602

cc @smottal

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by brbalazs** [comment]
ci:test:commerce

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
