### PR TITLE
Automated Test - COMMERCE-6656 | Master

### PR DESCRIPTION
**Pull request by juliomoraes-dev**

### CODE REVIEW

**Comment by julioribeiiro** [comment]
https://issues.liferay.com/browse/COMMERCE-6656, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
[Passed here](https://testray.liferay.com/home/-/testray/cases/1534560554)

**Pull request closed without merging**
