### PR TITLE
COMMERCE-6903 Implement default diagram type 1 of 5

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-6903

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Review by igorbeslic — APPROVED** [review]

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
already merged here https://github.com/brianchandotcom/liferay-portal/compare/9b7c82cc90...c0e369b2ad

**Pull request closed without merging**
