### PR TITLE
COMMERCE-11745

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/liferay-commerce/liferay-portal/pull/4140

Simplified the PR as discussed with @CrescenzoRegaLF

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
@brianikim check that there are no conflicts with the COMMERCE-11741 just merged, thanks

**Comment by brianikim** [comment]
Hi @CrescenzoRegaLF ,

It looks okay to me as is. No merge conflicts or anything.

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
@brianikim There seems to be a problem with the semantic version of the commerce-frontend-taglib module

<details><summary>Details</summary>
<p>

     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-frontend-taglib] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.frontend.taglib.servlet.taglib MAJOR      18.7.0     18.7.0     19.0.0     VERSION INCREASE REQUIRED
     [exec]     	<   class      com.liferay.commerce.frontend.taglib.servlet.taglib.AddToCartTag
     [exec]     		+   method     getQuantity()
     [exec]     			+   return     java.math.BigDecimal
     [exec]     		+   method     getUnitOfMeasureKey()
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     setQuantity(java.math.BigDecimal)
     [exec]     			+   return     void
     [exec]     		+   method     setUnitOfMeasureKey(java.lang.String)
     [exec]     			+   return     void
     [exec]     	>   class      com.liferay.commerce.frontend.taglib.servlet.taglib.PriceTag
     [exec]     		>   method     getQuantity()
     [exec]     			-   return     int
     [exec]     			+   return     java.math.BigDecimal
     [exec]     		+   method     getUnitOfMeasureKey()
     [exec]     			+   return     java.lang.String
     [exec]     		-   method     setQuantity(int)
     [exec]     			-   return     void
     [exec]     		+   method     setQuantity(java.math.BigDecimal)
     [exec]     			+   return     void
     [exec]     		+   method     setUnitOfMeasureKey(java.lang.String)
     [exec]     			+   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 20.0.0

</p>
</details>

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@CrescenzoRegaLF ,

Seems resolved in latest branch of Master.

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Pull request closed without merging**
