### PR TITLE
Automated Test - COMMERCE-6022 | master

### PR DESCRIPTION
**Pull request by MoryAlvesBR**

### CODE REVIEW

**Comment by MoryAlvesBR** [comment]
cc: @pietro.bocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@MoryAlvesBR Please uncomment setup and teardown and correct typo on Line 20. Fix source formatting, and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
Reviewing

**Comment by brittneyq** [comment]
Sent in [https://github.com/liferay-commerce/liferay-portal/pull/885](885). Please close, thank you!

**Pull request closed without merging**
