### PR TITLE
Automated Test - COMMERCE-6301| master

### PR DESCRIPTION
**Pull request by LucasAcacio**

### CODE REVIEW

**Comment by LucasAcacio** [comment]
https://issues.liferay.com/browse/COMMERCE-6301, cc: @Pietro69

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1315. Please close @kristinonias

**Pull request closed without merging**
