### PR TITLE
COMMERCE-5137 Fix test name and currency name

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/COMMERCE-5137

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:stable

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:commerce

**Review by dsitu — APPROVED** [review]

**Comment by iovaneale** [comment]
@marco-leo The test fails as expected. Now it looks for "Brazilian Real", yet the label is still "Brazilian real". Long story short the test caught the bug we knew so I think it can be merged. I will open a ticket for it.

**Comment by iovaneale** [comment]
I've opened [COMMERCE-5142](https://issues.liferay.com/browse/COMMERCE-5142) for this bug, and also fixed it. See #366 .

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:forward

**Comment by iovaneale** [comment]
ci:test:commerce

**Pull request closed without merging**
