### PR TITLE
DO NOT MERGE COMMERCE-9390 InfoItemCollectionProvider for Related Products

### PR DESCRIPTION
**Pull request by pietrobocale**
Ticket: https://issues.liferay.com/browse/COMMERCE-9390

Original PR: https://github.com/liferay-commerce/liferay-portal/pull/3476

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
Forwarded here: #3550

**Pull request closed without merging**
