### PR TITLE
LPD-20130 Update FF to release

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-20130

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:2557747223

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
