### PR TITLE
LPD-18223 Multiselect selected elements should be removable one by one

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-18223

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]
Ok for me! Thx

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
ci:forward:force

**Pull request closed without merging**
