### PR TITLE
COMMERCE-4982 Rename constants

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
HEy @riccardo-alberti if it was a rename with deprecation as asked by Brian, I don't see why there is a bump in the version from 4.1.0 to version 5.0.0

**Comment by riccardo-alberti** [comment]
@marco-leo i delete constants because i had a comment on the renaming https://github.com/brianchandotcom/liferay-portal/pull/97757 asking to remove since we can do major changes in master

**Review by dsitu — APPROVED** [review]

**Review by marco-leo — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
