### PR TITLE
COMMERCE-11517

### PR DESCRIPTION
**Pull request by brianikim**
Resent from : https://github.com/liferay-commerce/liferay-portal/pull/3838

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:um

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:um

**Comment by victoroscuro** [comment]
Failures on um/commerce tests seem to be unrelated to the changes made for this PR.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
