### PR TITLE
COMMERCE-11649 Check whether the request is valid before redirect

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-11649

@andrea-ale-sbarra , tied to LPP

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
lgtm.

thank you!

**Pull request closed without merging**
