### PR TITLE
COMMERCE-6875 We should not be deleting from the index on a fetch/get…

### PR DESCRIPTION
**Pull request by brianikim**
… method.

https://issues.liferay.com/browse/COMMERCE-6875

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
Hey @brianikim this is a recurring pattern I am seeing in portal:
https://github.com/liferay-commerce/liferay-portal/blob/fb67433d2b06034d9a01d72c9b57332f5c026c02/portal-impl/src/com/liferay/portlet/asset/service/impl/AssetCategoryLocalServiceImpl.java#L318

**Comment by brianikim** [comment]
hey @marco-leo ,

Search team also identified that code in ACLSI as an example of improper implementation.

**Comment by brianikim** [comment]
@riccardo-alberti ,

Let me know how you guys would like to proceed here.

**Comment by marco-leo** [comment]
ci:forward

**Comment by marco-leo** [comment]
@brianikim @riccardo-alberti forwarding this , do we need to abckport?

**Comment by brianikim** [comment]
Hey @marco-leo , I will take care of the back-port.

**Pull request closed without merging**
