### PR TITLE
LPD-34668 Statuses label colors in the Returns Listing do not match the ones in the Details(Admin and SF)

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-34668

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:report:73405047

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Pull request closed without merging**
