### PR TITLE
LPD-34676 | LPD-39349

### PR DESCRIPTION
**Pull request by alessiorendina**
Forwarded from: https://github.com/liferay-commerce/liferay-portal/pull/5487

https://liferay.atlassian.net/browse/LPD-34676
https://liferay.atlassian.net/browse/LPD-39349

cc @gianmarcobrunialti

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thanl you!

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Error in the stable suite seems unrelated to the PR

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
