### PR TITLE
LPD-40352 Setting primary user email value to false via email ERC API sets no other emails to true fix

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-40352

cc @smottal

Resent from: https://github.com/brianchandotcom/liferay-portal/pull/157042

### CODE REVIEW

**Comment by matyaswollner** [comment]
Cc @smottal

**Comment by matyaswollner** [comment]
ci:test:relevant

**Comment by matyaswollner** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
