### PR TITLE
LPD-29890 LPD-30000

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-29890
https://liferay.atlassian.net/browse/LPD-30000

~~**DO NOT MERGE** Send after: https://github.com/liferay-commerce/liferay-portal/pull/5190~~

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:playwright

**Comment by gianmarcobrunialti** [comment]
ci:test:playwright

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:playwright

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Pull request closed without merging**
