### PR TITLE
[DO NOT MERGE] COMMERCE-12540

### PR DESCRIPTION
**Pull request by pietrobocale**
https://liferay.atlassian.net/browse/COMMERCE-12540

This is a test PR that contains some commits needed for the functional tests on the CI for testing the changes of the COMMERCE-12540

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
