### PR TITLE
Automated Test - COMMERCE-6271 | master

### PR DESCRIPTION
**Pull request by ewertonluna**

### CODE REVIEW

**Comment by ewertonluna** [comment]
https://issues.liferay.com/browse/COMMERCE-6271, cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not visible at "//button[contains(@class,'close')] | //a[contains(@id,'closePanelAdd') and contains(@class,'close')]"

**Comment by julioribeiiro** [comment]
Fixed in: https://github.com/liferay-commerce/liferay-portal/pull/1372

**Pull request closed without merging**
