### PR TITLE
COMMERCE-11879

### PR DESCRIPTION
**Pull request by Brunno0liveira**
[COMMERCE-11879](https://liferay.atlassian.net/browse/COMMERCE-11879)

### CODE REVIEW

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Review by lorenzolapescara — CHANGES_REQUESTED** [review]
@Brunno0liveira can you add an assertion in one of these tests that checks the same in the Product Details page?

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
