### PR TITLE
COMMERCE-9416 Add compare portlet to dashboard

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9416

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reevaluate:1277401_6810

**Review by luca-pellizzon — APPROVED** [review]

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
