### PR TITLE
Automated Test - COMMERCE-6021 | master

### PR DESCRIPTION
**Pull request by juliaduartelira**

### CODE REVIEW

**Comment by juliaduartelira** [comment]
https://issues.liferay.com/browse/COMMERCE-6021, cc: @pietro.bocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
hi @juliaduartelira could you please remove @ignore = true in your PR? Thank you!

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
Reviewing

**Comment by brittneyq** [comment]
Sent in [885](https://github.com/liferay-commerce/liferay-portal/pull/885). Please close, thank you!

**Pull request closed without merging**
