### PR TITLE
LPD-41250

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

https://liferay.atlassian.net/browse/LPD-41250

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
