### PR TITLE
COMMERCE-10603 fetch category by ERC first

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-10603

Fix rebase conflicts from here https://github.com/liferay-commerce/liferay-portal/pull/3742

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:forward

**Comment by jaydawu** [comment]
ci:reopen

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
