### PR TITLE
COMMERCE-7065 Added diagram commerce product content and list entry renderer

### PR DESCRIPTION
**Pull request by alessiorendina**
@ivicac FIY

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
