### PR TITLE
COMMERCE-11452

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-11451
https://issues.liferay.com/browse/COMMERCE-11452
https://issues.liferay.com/browse/COMMERCE-11480

This fixes all three tickets and need to test for all three.

Based on #3759

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
