### PR TITLE
COMMERCE-10895 The GET for all the orders is not working for a user who has permission to view some of the orders

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-10895
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3542

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Review by lorenzolapescara — APPROVED** [review]

**Pull request closed without merging**
