### PR TITLE
COMMERCE-12681 Add Tags to Product Images

### PR DESCRIPTION
**Pull request by pietrobocale**
Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4431

Ticket: https://liferay.atlassian.net/browse/COMMERCE-12681

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
resent here https://github.com/liferay-commerce/liferay-portal/pull/4461

**Pull request closed without merging**
