### PR TITLE
Commerce 9716

### PR DESCRIPTION
**Pull request by MahmoudAzzam**

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by MahmoudAzzam** [comment]
Old PR @ https://github.com/liferay-commerce/liferay-portal/pull/2956

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
code was already merged here https://github.com/liferay-commerce/liferay-portal/pull/3018

**Pull request closed without merging**
