### PR TITLE
COMMERCE-12627 Product Details is not using Adaptive Media

### PR DESCRIPTION
**Pull request by pietrobocale**
https://liferay.atlassian.net/browse/COMMERCE-12627

Base PR:
https://github.com/liferay-commerce/liferay-portal/pull/4342

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/4373

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
