### PR TITLE
COMMERCE-4648 categoryIds now is of type String

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:stable

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
