### PR TITLE
Automated Test - COMMERCE-6229 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**

### CODE REVIEW

**Comment by leilanyaragao** [comment]
https://issues.liferay.com/browse/COMMERCE-6229, cc: @iovaneale

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//div[contains(@class,'alert') and (contains(@class,'alert-error') or contains(@class,'alert-danger'))]"

**Comment by julioribeiiro** [comment]
Fixed in: https://github.com/liferay-commerce/liferay-portal/pull/1375

**Pull request closed without merging**
