### PR TITLE
COMMERCE-12013 Support CPAttachmentFileEntries deletion through API

### PR DESCRIPTION
**Pull request by jaydawu**
Story: https://liferay.atlassian.net/browse/COMMERCE-12013
Test plan: https://liferay.atlassian.net/browse/COMMERCE-12303
Resent from https://github.com/liferay-commerce/liferay-portal/pull/4205

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by jaydawu** [comment]
Hi @victoroscuro, this pr can be force-forwarded now, all tests are good, the PM review is completed with Riccardo, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
