### PR TITLE
COMMERCE-13229 - NoSuchUserException and DuplicateCommerceChannelAccountEntryRelException when upgrading from 7.2 to 7.4

### PR DESCRIPTION
**Pull request by victorcdp**
[COMMERCE-13229](https://liferay.atlassian.net/browse/COMMERCE-13229)

@luca-pellizzon Can you review this one? Tied to an LPP. Thank you.

Fixes for the problems discussed in [this thread](https://liferay.slack.com/archives/G9CMBBA9H/p1705513298541059)

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:upgrade

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
