### PR TITLE
LPD-15425 - user notification API can return a NPE due to headless API not having a themeDisplay

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @smottal,

https://liferay.atlassian.net/browse/LPD-15425, linked to LPP.

An NPE can be thrown when using headless API to retrieve export/import notifications due to how user notifications are handled in ExportImportNotificationHandler. In ExportImportNotificationHandler.getLink(), we call PortletURLFactoryUtil.create() which eventually attempts to retrieve a ThemeDisplay. Since we do not have one due to the nature of our call, an NPE is thrown. I've added a check for it as null, similar to the one that [already exists for WorkflowTasks](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-workflow/portal-workflow-task-web/src/main/java/com/liferay/portal/workflow/task/web/internal/notifications/WorkflowTaskUserNotificationHandler.java#L244-L248).

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:headless

**Review by smottal — APPROVED** [review]
LGTM. Thx

**Comment by smottal** [comment]
@wanderlast Is there any integration test on this API?

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
> @wanderlast was this test failing for the NPE or do you know why it didn't catch the problem?

@smottal I can take a closer look tomorrow but my guess would be that due to the nature of our testing infrastructure we would already have a themeDisplay instantiated and therefore never encounter the NPE.

**Comment by smottal** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
@smottal I can confirm from testing locally at least that it appears to not trigger an NPE due to having a ThemeDisplay instantiated while running the integration test.

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
