### PR TITLE
COMMERCE-11504 APIs to Link Catalogue to an Account + JSON macro fix

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-11004
https://issues.liferay.com/browse/COMMERCE-11504

### CODE REVIEW

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:force:forward

**Comment by dsitu** [comment]
closing, sending directly to bchan

**Comment by dsitu** [comment]
ci:reopen

**Comment by alessiorendina** [comment]
Forwarded here: https://github.com/liferay-commerce/liferay-portal/pull/3811

**Pull request closed without merging**
