### PR TITLE
Commerce 5582 An error is thrown after complete the checkout with a Virtual Product

### PR DESCRIPTION
**Pull request by luca-pellizzon**
[COMMERCE-5582](https://issues.liferay.com/browse/COMMERCE-5582)

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
QA passed. Will resent after the automation.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
