### PR TITLE
COMMERCE-9459 Fix failing tests

### PR DESCRIPTION
**Pull request by iovaneale**
This is a follow up PR

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
@iovaneale please close this I forwarded it here #2908

**Comment by andrea-ale-sbarra** [comment]
forwarded here https://github.com/liferay-commerce/liferay-portal/pull/2908

**Pull request closed without merging**
