### PR TITLE
COMMERCE-11353

### PR DESCRIPTION
**Pull request by lorenzolapescara**
Re-sent from #3701 with new automated functional test

@andrea-ale-sbarra 

https://issues.liferay.com/browse/COMMERCE-11353

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@victorcdp , address the conflict asap please.

**Comment by victorcdp** [comment]
@lorenzolapescara can you cherry pick the [commit](https://github.com/victorcdp/liferay-portal/commit/215b5eae57ac2d3f3f247aea96e99079e89b0bc1) again and see if it solves the conflict? Thank you.

**Comment by lorenzolapescara** [comment]
@victorcdp I tried and I still have the conflict locally. Can you please fetch this PR and resolve it? Thanks a lot!

**Comment by brianikim** [comment]
@lorenzolapescara , see this PR: https://github.com/liferay-commerce/liferay-portal/pull/3721

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
