### PR TITLE
COMMERCE-9811

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9811

@andrea-ale-sbarra ,

### CODE REVIEW

**Review by luca-pellizzon — COMMENTED** [review]
@brianikim code is fine to me, could you please sort the commits?
I see commits regarding autogenerated code mixed with the others.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@luca-pellizzon , I changed the order as requested.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
@luca-pellizzon , updated PR to fix base conflicts.

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
