### PR TITLE
LPD-26643 Address autoselect during checkout not working for account defaults and reorder

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-26643

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:stop

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Review by alessiorendina — CHANGES_REQUESTED** [review]
@monaco-fabio Please check my comments, thank you!

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by alessiorendina** [comment]
ci:forward:force

**Pull request closed without merging**
