### PR TITLE
LPD-42626 Pagination breakdown

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/LPD-42626

this bug was opened as a consequence of this failing test https://liferay.atlassian.net/browse/LPD-42185:
CommerceSearch#SearchResultsWidgetChangeResultsPage

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
Resend of https://github.com/liferay-commerce/liferay-portal/pull/5661

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:forc

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
