### PR TITLE
COMMERCE-9698 No messages appear when items with different Shipping Methods are added to the Shipment

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [COMMERCE-9698 No messages appear when items with different Shipping Methods are added to the Shipment](https://issues.liferay.com/browse/COMMERCE-9698)
- This is a followup on https://github.com/markocikos/liferay-portal/pull/200

### What is the goal of this PR?

We are enabling page reload on commerce modal close. To achieve this, we are using `redirect` param of dropwdown item `href`, navigating to it on modal close.

`redirect` param of the shipments dropdown item is set [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-shipment-web/src/main/java/com/liferay/commerce/shipment/web/internal/display/context/CommerceShipmentDisplayContext.java#L381-L382). It currently does nothing. In a typical DXP action URL, it would used to determine redirect after an action. In a render URL, like modal content, it could be used as a redirect after form submit. But, in the case of [shipments modal](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-shipment-web/src/main/resources/META-INF/resources/commerce_shipment_item/add_commerce_shipment_items.jsp), it is unused. With this PR, we are using it to navigate to it after form submit and modal close.

I was considering adding a new param for only page refresh, something like `refreshPageOnClose`, that would be added as a part of `href`, but that seems to only be a more limiting version of the solution in this PR.

I'll be the first one to to admit that this is not the cleanest API. However, the only better alternative that I see would require large restructuring, i.e. removing `modal*` targets, rewriting commerce modal usages to `openModal`, and extending `creationMenu` customization API through `propsTransformer`. But, that's outside of scope for this task. PR as it is may may serve as a quick and dirty fix, with a limited scope.

@MahmoudAzzam @luca-pellizzon 

### What does it look like?

The page refresh is poorly visible, due to framerate of gif. Feel free to test to PR out.

after

### Steps to reproduce

See steps in JIRA ticket

### CODE REVIEW

**Comment by markocikos** [comment]
Pushed to add semver update.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
See here https://github.com/liferay-commerce/liferay-portal/pull/2975

**Comment by luca-pellizzon** [comment]
PR with functional tests https://github.com/liferay-commerce/liferay-portal/pull/2989

**Pull request closed without merging**
