### PR TITLE
LPS-127481 wait for portlet repository factory

### PR DESCRIPTION
**Pull request by igorbeslic**
Hi @csierra please check this, this way we are prottecting all dispatch api consumers

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:stable

**Comment by igorbeslic** [comment]
ci:relevant

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @igorbeslic,

can we move forward with this pull?

Thanks.

**Comment by igorbeslic** [comment]
ci:forward

**Pull request closed without merging**
