### PR TITLE
COMMERCE-4986 commerce-product-content-web Avoid executing the same q…

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
…uery multiple times

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci: test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
