### PR TITLE
LPS-195988 Increase the database AccountEntry.name column character limit to 250

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #4333  

https://liferay.atlassian.net/browse/LPS-195988

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:um

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
QA Review Passed

**Pull request closed without merging**
