### PR TITLE
COMMERCE-8670 Fixed final price calculation in imported commerce order items preview

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/114404

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
