### PR TITLE
Commerce 12681

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4442

Ticket: https://liferay.atlassian.net/browse/COMMERCE-12681

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
The relevant failures are not related to this PR

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
