### PR TITLE
COMMERCE-5544 SF Remove @NotNull annotations from *ResourceImpl

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-5544

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@dsitu can i forward this one? there is another pr depending on this. thx

**Comment by dsitu** [comment]
@riccardo-alberti yep its good.

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
