### PR TITLE
Automated Test - COMMERCE-6274 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/COMMERCE-6274 cc: @pietrobocale

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1322. Please close @kristinonias

**Pull request closed without merging**
