### PR TITLE
COMMERCE-9705 Default account currency per channel

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
@alessiorendina could you close this request, I resent it here [COMMERCE-9705](https://github.com/liferay-commerce/liferay-portal/pull/2994)

**Pull request closed without merging**
