### PR TITLE
COMMERCE-4791 Make commerce-organization-chart work again

### PR DESCRIPTION
**Pull request by fabio-d-m**
The source formatter started working after renaming .jsx in .js files. 
A few module imports were missing and literal refs got deprecated.
Also some sorting in objects was required.

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@FabioDiegoMastrorilli Semntic version looks a real fail of this pull

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:stable

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
@FabioDiegoMastrorilli Please fix SF

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
