### PR TITLE
COMMERCE-11355

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra , @luca-pellizzon ,

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3693

https://issues.liferay.com/browse/COMMERCE-11355

This PR should fulfill the requests made in : https://github.com/liferay-commerce/liferay-portal/pull/3693

It handles both accountGroupFilter and channelFilter

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
Cool! I didn't know that we needed just this!

Thank you!

**Review by luca-pellizzon — APPROVED** [review]

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
