### PR TITLE
Automated Test - COMMERCE-6328 | master

### PR DESCRIPTION
**Pull request by brunadmelo**

### CODE REVIEW

**Comment by brunadmelo** [comment]
https://issues.liferay.com/browse/COMMERCE-6328; cc:@lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
GlobalSearchSearchProductsBySpecificationValues passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
