### PR TITLE
COMMERCE-12633 CPPublisherPortlet can exist separately from CPContent…

### PR DESCRIPTION
**Pull request by brianikim**
…Portlet.

https://liferay.atlassian.net/browse/COMMERCE-12633

@andrea-ale-sbarra , tied to LPP.

### CODE REVIEW

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
