### PR TITLE
LPD-32943

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-32943

@luca-pellizzon

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Local relevant results here: https://github.com/brianikim/liferay-portal/pull/183#issuecomment-2303611941

**Comment by luca-pellizzon** [comment]
@brianikim you should include the newly added fields in the tests (methods like getRandomOrder and similar) so that all fields are there, then the auto-gerated tests are enough.

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
