### PR TITLE
COMMERCE-10701 InfoItemCollectionProvider for Related Products

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10701
https://issues.liferay.com/browse/COMMERCE-9390

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:stop

**Comment by smottal** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by smottal** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
QA Passed

New PR: https://github.com/liferay-commerce/liferay-portal/pull/3538

**Pull request closed without merging**
