### PR TITLE
LPD-25329 Avoid exceptions for performance

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:2566823319

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:2566853742

**Comment by CrescenzoRegaLF** [comment]
ci:report:2566874996

**Comment by CrescenzoRegaLF** [comment]
ci:report:2566874996

**Pull request closed without merging**
