### PR TITLE
LPD-40179 Remove unnecessary assertions

### PR DESCRIPTION
**Pull request by michelevigilante**
This PR is to address changes requested here: https://github.com/brianchandotcom/liferay-portal/pull/157066

### CODE REVIEW

**Comment by michelevigilante** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
This PR is to address changes requested here: https://github.com/brianchandotcom/liferay-portal/pull/157066

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by michelevigilante** [comment]
ci:report:95846851

**Comment by michelevigilante** [comment]
ci:test:relevant

**Comment by michelevigilante** [comment]
ci:report:96429685

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
