### PR TITLE
COMMERCE-5922 Fix test CPCommerceOptions#CreateAnOption

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5922

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
ci:test:stop

**Comment by brianchandotcom** [comment]
ci:close @andrea-ale-sbarra merged

**Pull request closed without merging**
