### PR TITLE
COMMERCE-9744 Show proper subscription type label if plural

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-9744

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/4058

@andrea-ale-sbarra , this one needs a quick review.

cc/ @jaydawu 

The PR needed to be modified to fit our existing implementations i.e.: https://github.com/liferay-commerce/liferay-portal/blob/64fb76697a19d1ac5a86195dfe57077711ba983e/modules/apps/commerce/commerce-frontend-taglib/src/main/java/com/liferay/commerce/frontend/taglib/servlet/taglib/ProductSubscriptionInfoTag.java#L221

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automation on https://github.com/liferay-commerce/liferay-portal/pull/4058 based on this pr, thanks.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
