### PR TITLE
COMMERCE-5373 Add a new test CPCommerceProducts#CreateProductBundleWithPriceTypeDynamic

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5373

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:stop

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Review by dsitu — APPROVED** [review]

**Review by marco-leo — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
