### PR TITLE
COMMERCE-9973 - REST API POST /options throws an Exception when option values are populated

### PR DESCRIPTION
**Pull request by victorcdp**
Related issue: [COMMERCE-9973](https://issues.liferay.com/browse/COMMERCE-9973)
@brianikim

Problem was that there was no default value for the contextUriInfo, so it was always null.
Proposed fix is to add a default value so that a NPException doesn't happen.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this one needs your review.

**Comment by andrea-ale-sbarra** [comment]
fix sent here https://github.com/liferay-commerce/liferay-portal/pull/3453

**Pull request closed without merging**
