### PR TITLE
Automated Test - COMMERCE-6163 | master

### PR DESCRIPTION
**Pull request by rafaellajordao**

### CODE REVIEW

**Comment by rafaellajordao** [comment]
https://issues.liferay.com/browse/COMMERCE-6163; CC: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
[Passing here](https://testray.liferay.com/home/-/testray/cases/1532392626).

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
