### PR TITLE
COMMERCE-8651

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@drewbrokke @luca-pellizzon this is the PR with all our changes + another PR that is working on the same resource. Please have a look. It worked locally.

**Comment by drewbrokke** [comment]
LGTM 👍

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Pull request closed without merging**
