### PR TITLE
COMMERCE-12715

### PR DESCRIPTION
**Pull request by riccardo-alberti**
https://liferay.atlassian.net/browse/COMMERCE-12715

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
The affected tests are now passing. Failures are not related to the PR. PR will be forwarded. Thanks!

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
