### PR TITLE
LPD-18470 Provide correct fieldName for listTYpeFieldName

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-18470

@smottal , this is a follow-up ticket to fix a remaining issue stemming from https://liferay.atlassian.net/browse/LPS-167326.

I do not think this needs a test, but I will await your input on this.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by brianikim** [comment]
I will do the test. Give me one day @smottal . will update this PR.

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/4748

**Pull request closed without merging**
