### PR TITLE
COMMERCE-12650 - Inventory change log is not getting updated on Order cancel+functional test

### PR DESCRIPTION
**Pull request by saramart81**
sent from #4371 
https://liferay.atlassian.net/browse/COMMERCE-12650

### CODE REVIEW

**Comment by saramart81** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
QA Review Passed

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
No relevant issues to this pull, I'll force-forward it, thanks!
cc/ @saramart81 @victoroscuro

**Comment by jaydawu** [comment]
ci:forward:force

**Pull request closed without merging**
