### PR TITLE
LPD-30191 Refactor test GlobalSearchSearchProductsBySKUs to playwright

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-30191

Built on top of https://github.com/liferay-commerce/liferay-portal/pull/5124

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by dsitu** [comment]
@riccardo-alberti looks like bchan merged https://github.com/liferay-commerce/liferay-portal/pull/5124, this can be forward if everything looks good.

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
