### PR TITLE
COMMERCE-12433 OrgChart View/Edit Panel - User + Automation

### PR DESCRIPTION
**Pull request by smottal**
User Story: https://liferay.atlassian.net/browse/COMMERCE-12433

Testplan: https://liferay.atlassian.net/browse/COMMERCE-12872

sent from: https://github.com/liferay-commerce/liferay-portal/pull/4463 and https://github.com/liferay-commerce/liferay-portal/pull/4419

@baharturk

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
