### PR TITLE
COMMERCE-9633 Products published using the generation of all skus combination from options do not appear in the catalog store front

### PR DESCRIPTION
**Pull request by baharturk**
resending from: #3064 
@CrescenzoRegaLF

https://issues.liferay.com/browse/COMMERCE-9633

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
Sent here: #3080 

Closing this one, thanks!

**Pull request closed without merging**
