### PR TITLE
Automated Test - COMMERCE-6302 | master

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by fmarcio** [comment]
https://issues.liferay.com/browse/COMMERCE-6302, cc: @Pietro69

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1317. Please close @kristinonias

**Pull request closed without merging**
