### PR TITLE
LPS-130205 Migrate selection modals in commerce-pricing-web

### PR DESCRIPTION
**Pull request by markocikos**
Fixes https://issues.liferay.com/browse/LPS-130205

In this PR, we are removing `discount/rule/type/*/v1_0/*` files, as pricing is not supported with v1.0 calculation key. Along with these files, we are removing selection modals in the module, which was the main purpose of the ticket.

There is no test case, as these JSPs cannot be accessed in UI.

Notes:
- With the solution in this PR, we are always showing v2 version of JSPs. This is the simplest solution. It may make sense to throw an error instead, if somebody hacks to this page with v1 (sets v1 in another tab). If you even want this behavior, it should probably be done on a higher up level, beyond the scope of this ticket.
- I left in `v2_0` folders. Would it make sense to remove these? Will there be other versions? Would you rather have `rule/type/added_all.jsp`, `rule/type/added_any.jsp` and `rule/type/card_total.jsp`?

@riccardo-alberti

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@riccardo-alberti Rebased and force-pushed. Failures look unrelated, I'll retest.

I took the liberty and removed `v2_0` dirs, in https://github.com/liferay-commerce/liferay-portal/pull/928/commits/0157e1c56535361a17ecf139fb0e8fc6c5d661ac. Please let me know if it makes more sense to leave them.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Rebased and force-pushed to retest. No changes.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@riccardo-alberti Every CI test has different unique errors :slightly_smiling_face:  Usually when long CI delays happen, we ask product team QA to manually test and forward. Is there somebody we can ask for help in the commerce team?

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@markocikos thanks for this. If it passes tests i will forward it. The change looks good to me.

**Comment by markocikos** [comment]
@riccardo-alberti the unique error looks unrelated, it's some database connection error. I rebased and force-pushed to retest, no changess.

**Comment by markocikos** [comment]
ci:test:relevant

**Pull request closed without merging**
