### PR TITLE
LPD-18483 Manage contacts on account - Emails

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-18483

This is built ontop of https://github.com/liferay-commerce/liferay-portal/pull/4789

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by smottal** [comment]
closing as inside https://github.com/liferay-commerce/liferay-portal/pull/4793

**Pull request closed without merging**
