### PR TITLE
LPS-201373

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
We are adding a new capability to Display Pages, it is provide the ability to create folders in “Display Page Templates” section.

LPS-189856_-_Usability_improvements_for_objects-page_builder_integration_–_Figma

Also, as part of this story we need to update the item selector of Display Pages taking it into account.

[Link to the story](https://liferay.atlassian.net/browse/LPS-189857)

Proposed Solution
-----
Removes the custom item selector for display pages in commerce modules and reuse AssetDisplayPageSelectorCriterion, in that way we are going to have folders navigation and removes duplicated code.

Also, since I found this duplicated item selector, I decided to review all item selectors in portal and I added two commits more removing unused item selectors and unused logic.

Please let me know if you have any question.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]
@ealonso LGTM, thank you!

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:commerce

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:commerce

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
