### PR TITLE
Automated Test - COMMERCE-5843 | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/COMMERCE-5843

cc: @pedro-michel, @FabioDiegoMastrorilli

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@nikki-pru you can use the suite ci:test:commerce-functional to test just commerce fucntional tests

**Comment by nikki-pru** [comment]
ci:test:stop

**Comment by nikki-pru** [comment]
ci:stop

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:stop

**Pull request closed without merging**
