### PR TITLE
Automated Test - COMMERCE-5861 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-5861; CC: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @leticiachiu, please remove the **@ignore = true** in your test. Thank you!

**Comment by leticiachiu** [comment]
@brittneyq Fixed

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
Review started.

**Review by lorenzolapescara — CHANGES_REQUESTED** [review]

**Comment by leticiachiu** [comment]
@lorenzolapescara Fixed

**Comment by lorenzolapescara** [comment]
@leticiachiu please remove `@ignore = "true"` from the test. Thanks.

**Comment by leticiachiu** [comment]
@lorenzolapescara Fixed

**Comment by leticiachiu** [comment]
@lorenzolapescara Fixed

**Review by lorenzolapescara — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
