### PR TITLE
[TS] LPS-152391 headless-commerce-admin-account: defaultBilling & defaultshipping cannot save with true value

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Hi team,
This PR is for ticket: https://issues.liferay.com/browse/LPS-152391 that passed our internal review. Please help us review it and give your feedback.
Thank

### CODE REVIEW

**Review by andrea-ale-sbarra — COMMENTED** [review]
Looks good to me, but the same change should be made for the PATCH as well

**Review by luca-pellizzon — APPROVED** [review]

**Comment by TaiPhamLR** [comment]
Hi @luca-pellizzon @andrea-ale-sbarra , I'm sorry for my late response.
I've rebased the master code and also fixed for the PATH as well. I'm looking forward to your review.
If you want me to create a new PR, please let me know.
Thanks,
Tai.

**Comment by andrea-ale-sbarra** [comment]
@TaiPhamLR LGTM, thank you!

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by pierpinna** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Updated the affected testcases and resent on https://github.com/liferay-commerce/liferay-portal/pull/3790. Thanks

**Pull request closed without merging**
