### PR TITLE
COMMERCE-11497 We need to pass in userId instead

### PR DESCRIPTION
**Pull request by brianikim**
@luca-pellizzon ,

https://issues.liferay.com/browse/COMMERCE-11497

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/3846. @Brunno0liveira

**Pull request closed without merging**
