### PR TITLE
LPD-34676 Order pages data sets and addenda

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-33676
https://liferay.atlassian.net/browse/LPD-33493
https://liferay.atlassian.net/browse/LPD-32234
https://liferay.atlassian.net/browse/LPD-32223
https://liferay.atlassian.net/browse/LPD-33831
https://liferay.atlassian.net/browse/LPD-32237
https://liferay.atlassian.net/browse/LPD-33783

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
From review here: https://github.com/liferay-commerce/liferay-portal/pull/5474

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
