### PR TITLE
COMMERCE-5377 Expired Discounts can be applied

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@riccardo-alberti Why there are commits not related to the change, like  Remove checks and configuration from web modules?

**Comment by riccardo-alberti** [comment]
@marco-leo it's because those web-modules are to be removed to use only pricing-web as a web module for price related entities. i have a task to remove those modules completely https://issues.liferay.com/browse/COMMERCE-4984

**Pull request closed without merging**
