### PR TITLE
LPD-15909 Provide OOTB Refund Reason

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-15909

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF tests related refund reasons are failing, please check

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
