### PR TITLE
COMMERCE-4818 Same Category is not adding for two channel using Category Display Pages

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
hey @riccardo-alberti can you please fix baseline in the PR?
thx

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
Resent under https://github.com/liferay-commerce/liferay-portal/pull/715

**Pull request closed without merging**
