### PR TITLE
Automated Test - COMMERCE-6166 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6166 , cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
[Passed here](https://testray.liferay.com/home/-/testray/cases/1534543093)

**Pull request closed without merging**
