### PR TITLE
COMMERCE-9488 New Order Details Page default configuration

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9488
https://issues.liferay.com/browse/COMMERCE-10179

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
@luca-pellizzon @iovaneale with these changes Open Carts/Placed Carts System and Instance settings will now be hidden, they will only be configurable through the portlet configuration.

**Comment by iovaneale** [comment]
Sent #3112 

@dsitu please close it. Thanks.

**Pull request closed without merging**
