### PR TITLE
COMMERCE-11352 Currency Code Should not be modified

### PR DESCRIPTION
**Pull request by baharturk**
sent from #3760 with a functional test

https://issues.liferay.com/browse/COMMERCE-11352

@brianikim

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures are not related to the PR, it's good to go.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
