### PR TITLE
COMMERCE-10161 Implement Workflow for Product Relationship

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-10161
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3802

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]
Functional tests Review Passed!

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
Based on: https://github.com/liferay-commerce/liferay-portal/pull/3802

**Comment by pietrobocale** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
fixed conflicts here https://github.com/liferay-commerce/liferay-portal/pull/3817

**Pull request closed without merging**
