### PR TITLE
COMMERCE-9798 - Add a structure to check if subscriptionType is empty

### PR DESCRIPTION
**Pull request by brianikim**
From @elocamp ,

> This bug is occurring because the subscriptionType is being passed empty in [getCPSubscriptionType](https://github.com/liferay/liferay-portal/blob/ffaf63c35bea589c743101c834914c4829f43ef5/modules/apps/commerce/commerce-subscription-web/src/main/java/com/liferay/commerce/subscription/web/internal/display/context/BaseCPDefinitionSubscriptionInfoDisplayContext.java#L47)() The proposed fix is to add a structure to check if the subscriptionType is empty, and if so, return the first item in [cpSubscriptionTypes](https://github.com/liferay/liferay-portal/blob/ffaf63c35bea589c743101c834914c4829f43ef5/modules/apps/commerce/commerce-subscription-web/src/main/java/com/liferay/commerce/subscription/web/internal/display/context/BaseCPDefinitionSubscriptionInfoDisplayContext.java#L59)()
> 
> Related ticket: [COMMERCE-9798](https://issues.liferay.com/browse/COMMERCE-9798)

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
sent here https://github.com/liferay-commerce/liferay-portal/pull/4063

**Pull request closed without merging**
