### PR TITLE
LPS-121010 - Internal categories are being shown by commerce category navigation widgets

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
HEy @ruben-pulido can you fix teh SF failure please?

Thanks

**Comment by ruben-pulido** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/221

**Pull request closed without merging**
