### PR TITLE
LPD-3469 An error is thrown if a user with the Operations Manager role navigates to an order item side panel

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-3469

resend this
https://github.com/liferay-commerce/liferay-portal/pull/4602

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF please check tests results, if ok we can forward it

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
ci:forward:forse

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Pull request closed without merging**
