### PR TITLE
[TS] COMMERCE-9441

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/COMMERCE-9441
https://issues.liferay.com/browse/LPS-152750

Follow-up PR from https://github.com/liferay-commerce/liferay-portal/pull/3021

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
looks like we need only ci:test:commerce on this

**Comment by andrea-ale-sbarra** [comment]
Ehi @ChrisKian there are conflicts to be resolved first, thank you!

**Comment by andrea-ale-sbarra** [comment]
Ehi @ChrisKian thanks for this PR, please be aware that we recently opened the #t-commerce channel on Slack and we're usually advised there for any new incoming PR from anyone out of our team. 

Thanks!

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this should be closed. I sent the updated PR here: https://github.com/liferay-commerce/liferay-portal/pull/3103 due to @ChrisKian being on PTO.

**Pull request closed without merging**
