### PR TITLE
COMMERCE-10895 The GET for all the orders is not working for a user who has permission to view some of the orders

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10895
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3599

@jaydawu

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
@CrescenzoRegaLF @jaydawu can you please move autogenerated commits after any other commit? Thanks!

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
