### PR TITLE
COMMERCE-6788

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-6788

@riccardo-alberti

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@riccardo-alberti ,

Let me know if you believe the fix is good to go for a hot-fix.

**Review by dsitu — APPROVED** [review]

**Review by luca-pellizzon — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
Thanks @luca-pellizzon. @brianikim yes please go ahead and provide the hotfix. thank you

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
