### PR TITLE
COMMERCE-10078 Add keyword support for SKU and Names in Order Search

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10078

@luca-pellizzon ,

SKU implementation is straightforward.

Localized name will be included if it exists, otherwise default name will be used.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
baseline error not related. I will run test one more time

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
Hi @brianikim I fetched the PR this morning and tested it but we have some issues related to pages (i.e: Products, Orders, Warehouses, Inventory, Placed and Pending Orders pages), they're not loading and in the relevant all tests are failing related to these areas. I controlled also master and it does not happen there. Could you check it, please? Thanks!

Screenshot 2023-01-25 at 12 35 45

**Comment by brianikim** [comment]
@baharturk , did you still need me to test the PR again? That semantic versioning change is not related to my commit.

**Comment by baharturk** [comment]
> 

@brianikim yes, I'm currently doing manual tests, and add also automation tomorrow. I saw in a thread that this semantic issue is waiting to be solved.

**Comment by baharturk** [comment]
Yes, when I first fetched the new PR, and did an Ant All, some pages were not loading as in the previous relevant failing tests, I wrote the comment, then did a new fetch and rebased it with upstream, after that, pages loaded without issue, so I deleted the message :)

**Comment by luca-pellizzon** [comment]
See https://github.com/liferay-commerce/liferay-portal/pull/3344

**Pull request closed without merging**
