### PR TITLE
LPS-196309 Filter Users that are not associated with Accounts or Organizations + Automation

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi @smottal,
Please help me to review this PR. Thanks.
This is the PR for story: https://liferay.atlassian.net/browse/LPS-196309
Due to Brian Chan's recent review, I sorted  SQL logic in in portal.xml, 
and also sort
from _joinByNoOrganizationsOrAccountEntries_
to
_joinByNoAccountEntriesAndNoOrganizations_
old pr: https://github.com/brianchandotcom/liferay-portal/pull/144876
cc @tototrinh @baharturk

### CODE REVIEW

**Comment by ces-quanhuynh** [comment]
ci:test:sf

**Comment by ces-quanhuynh** [comment]
ci:test:relevant

**Comment by ces-quanhuynh** [comment]
ci:test:um

**Review by smottal — APPROVED** [review]
LGTM! Thx

**Comment by smottal** [comment]
ci:test:stable

**Comment by baharturk** [comment]
The failures are not related to the PR. It can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
