### PR TITLE
COMMERCE-7399 fixed payment method description not displayed

### PR DESCRIPTION
**Pull request by garofalog**
fixed payment method description not displayed before

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
@luca-pellizzon can you please have a look here? :) Thanks

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
