### PR TITLE
Automated Test - COMMERCE-6101 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-6101, CC: @pietrobocale

**Comment by pedro-michel** [comment]
ci:test:sf

**Review by Pietro69 — CHANGES_REQUESTED** [review]
Remove the @ignore = "true"

**Comment by leticiachiu** [comment]
@Pietro69 fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
