### PR TITLE
LPS-199178, LPS-198657, LPS-203740, LPS-203744 Set PermissionChecker in tests

### PR DESCRIPTION
**Pull request by ghost**
Hi Team,

as discussed on [LPS-199178](https://liferay.atlassian.net/browse/LPS-199178), I am opening this PR with the updated tests for the following issues so the Commerce QA can test it:

- [LPS-199178](https://liferay.atlassian.net/browse/LPS-199178)
- [LPS-198657](https://liferay.atlassian.net/browse/LPS-198657)
- [LPS-203740](https://liferay.atlassian.net/browse/LPS-203740)
- [LPS-203744](https://liferay.atlassian.net/browse/LPS-203744)

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by smottal** [comment]
Closing this PR because not needed anymore: already fixed by COMMERCE-13166

**Pull request closed without merging**
