### PR TITLE
COMMERCE-9622 Update ClayDataSet to FDS for Commerce Account Web

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9622

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
@dsitu could you please check this one https://github.com/liferay-commerce/liferay-portal/pull/2851
I think it is pretty much the same thing.

**Pull request closed without merging**
