### PR TITLE
LPD-3391 If the device is touch, Minium sidebar user navigation items are not clickable

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-3391

### CODE REVIEW

**Review by alessiorendina — APPROVED** [review]

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:relevant

**Comment by monaco-fabio** [comment]
ci:test:playwright

**Comment by monaco-fabio** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
