### PR TITLE
COMMERCE-6974 Implement the admin UI interface for order type management

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-6974

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
@riccardo-alberti @Commando18 view changes  ee9555f, 04e1e92, 70f476a, 2cc9ccf, and f63b440.

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
