### PR TITLE
COMMERCE-9060 error.detail needs to be checked. Keep error.message fo…

### PR DESCRIPTION
**Pull request by brianikim**
…r compatibility.

https://issues.liferay.com/browse/COMMERCE-9060

@andrea-ale-sbarra , 
our change in commit: https://github.com/liferay/liferay-portal/commit/b19ae46cb2e8d64ac907f9cff5f59336439d2c8a means the default `com.liferay.portal.vulcan.jaxrs.exception.mapper.BaseExceptionMapper` is used.

The implementation in the default BaseExceptionMapper expects `error.detail`. Front-end changes as needed.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you @brianikim

**Comment by baharturk** [comment]
ci:test:commerce

**Pull request closed without merging**
