### PR TITLE
COMMERCE-12375 Allow guest users to access the order details page through pending orders widget

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-12375
test plan: https://liferay.atlassian.net/browse/COMMERCE-12790

Resent from https://github.com/liferay-commerce/liferay-portal/pull/4413

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:bundle

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @brianikim, the [bundle](https://github.com/liferay-commerce/liferay-portal/pull/4429#issuecomment-1805528744) that was built by CI is wrong. The guest user cannot see the add to cart button for product cards enabled. Please have a fix on it, thanks! Please see details under the story's [comment](https://liferay.atlassian.net/browse/COMMERCE-12375?focusedCommentId=2507889). Thank you!

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @victoroscuro, please help monitor the commerce-functional suite results when it finishes, the relevant is good, if functional is also good, please help force-forward it, thanks!

**Comment by jaydawu** [comment]
There are no related failures to this pull, it can be force-forwarded, thanks!
cc. @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
