### PR TITLE
COMMERCE-5175 New functional test CPCommercePriceLists#AssertPriceListIsAppliedToAllAssociatedAccountGroups

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5175

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by marco-leo** [comment]
ci:test

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@Pietro69  no need to run ci : test.  without suite

**Comment by marco-leo** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
Closing this because the functionality has changed in the meanwhile.

**Pull request closed without merging**
