### PR TITLE
COMMERCE-9805 Adding checks to prevent CPSubscription date option bei…

### PR DESCRIPTION
**Pull request by brianikim**
…ng less than 0/1

From @victorcdp ,

> Related Issue: [COMMERCE-9805](https://issues.liferay.com/browse/COMMERCE-9805)
> 
> The issue was that there was no backend validation for the input numbers. Proposed fix is to add validation at the addCPDefinition and updateSubscriptionInfo methods.

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@victorcdp , this is failing compile. Can you compile locally and retest please. Thanks.

**Comment by victorcdp** [comment]
@brianikim it compiled fine here. I think the problems is that there are 2 commits missing from the original PR, the new Exception declaration and the buildService commits

**Comment by brianikim** [comment]
@victorcdp , I will correct the PR. Thanks for the check

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
should be fixed by this https://github.com/liferay-commerce/liferay-portal/pull/3585

**Pull request closed without merging**
