### PR TITLE
[Fix CI Error]Commerce 9384

### PR DESCRIPTION
**Pull request by slnn**
This pull aims to fix the error in ci test results:

````
ENTRY com.liferay.commerce.product.service 4 0 2022-09-07 20:00:58.424

!MESSAGE bundle com.liferay.commerce.product.service:6.0.79 (502)[com.liferay.commerce.product.internal.option.CheckboxCommerceOptionTypeImpl(2078)] : findField: Suitable but non-accessible field _cpDefinitionOptionRelLocalService in class com.liferay.commerce.product.internal.option.BaseCommerceOptionTypeImpl, subclass of component class com.liferay.commerce.product.internal.option.CheckboxCommerceOptionTypeImpl


!ENTRY com.liferay.commerce.product.service 4 0 2022-09-07 20:00:58.428

!MESSAGE bundle com.liferay.commerce.product.service:6.0.79 (502)[com.liferay.commerce.product.internal.option.CheckboxMultipleCommerceOptionTypeImpl(2079)] : findField: Suitable but non-accessible field _cpDefinitionOptionRelLocalService in class com.liferay.commerce.product.internal.option.BaseCommerceOptionTypeImpl, subclass of component class com.liferay.commerce.product.internal.option.CheckboxMultipleCommerceOptionTypeImpl


!ENTRY com.liferay.commerce.product.service 4 0 2022-09-07 20:00:58.434`

```

### CODE REVIEW

**Comment by slnn** [comment]
ci:test:commerce

**Comment by slnn** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
