### PR TITLE
COMMERCE-4964 Integration tests permission issue when creating new company

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
