### PR TITLE
LPD-26142 Migrate poshi test to playwright

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-26142

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:playwright

**Comment by CrescenzoRegaLF** [comment]
ci:report:2570924619

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
Code looks good.
Just two little changes.
Thank you!

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:playwright

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
