### PR TITLE
COMMERCE-4052 Remove dupelicate classes and update breaking changes

### PR DESCRIPTION
**Pull request by dsitu**
resending due to merge conflict

### CODE REVIEW

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:test:releveant

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
liferay/ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
