### PR TITLE
COMMERCE-10667 | Technical Task - Currency management missing in the discounts

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10667

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF integration tests to fix

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]
I like how you reordered everything, good job.

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:help

**Comment by CrescenzoRegaLF** [comment]
ci:report:2562316943

**Comment by CrescenzoRegaLF** [comment]
ci:report:2562586714

**Comment by CrescenzoRegaLF** [comment]
ci:report:2562968723

**Comment by CrescenzoRegaLF** [comment]
ci:report:2563804898

**Comment by CrescenzoRegaLF** [comment]
ci:report:2564112111

**Comment by CrescenzoRegaLF** [comment]
ci:report:2564309437

**Comment by CrescenzoRegaLF** [comment]
ci:report:2564300105

**Comment by CrescenzoRegaLF** [comment]
ci:report:2564922942

**Comment by CrescenzoRegaLF** [comment]
ci:report:2565172883

**Comment by CrescenzoRegaLF** [comment]
ci:report:2566289695

**Comment by CrescenzoRegaLF** [comment]
ci:report:2566758365

**Comment by CrescenzoRegaLF** [comment]
ci:report:2567910366

**Comment by CrescenzoRegaLF** [comment]
ci:report:2568300738

**Comment by CrescenzoRegaLF** [comment]
ci:report:2569119714

**Comment by CrescenzoRegaLF** [comment]
ci:report:2570488164

**Comment by CrescenzoRegaLF** [comment]
ci:report:10731248

**Comment by CrescenzoRegaLF** [comment]
ci:report:9480915

**Comment by CrescenzoRegaLF** [comment]
ci:report:15428540

**Comment by CrescenzoRegaLF** [comment]
ci:report:18189485

**Comment by CrescenzoRegaLF** [comment]
ci:report:33302121

**Pull request closed without merging**
