### PR TITLE
LPD-24666 Add new commerce order item term for commerce order object notifications

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-24666

One new commit to move html into a template, https://github.com/liferay-commerce/liferay-portal/pull/5050/commits/cda0bc94dbc8ac7a890e54770798b7c1f0ca101b

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
