### PR TITLE
COMMERCE-4862 commerce-order-content-web fixed compilation failure

### PR DESCRIPTION
**Pull request by dsitu**

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Comment by marco-leo** [comment]
@dsitu I think this PR is not valid anymore, please confirm

**Comment by dsitu** [comment]
@marco-leo oh yeah looks like bchan reverted his original SF changes that were causing the error. Thanks.

**Pull request closed without merging**
