### PR TITLE
COMMERCE-9850

### PR DESCRIPTION
**Pull request by alessiorendina**
These changes will fix the following bugs:
- https://issues.liferay.com/browse/COMMERCE-9507
- https://issues.liferay.com/browse/COMMERCE-9765
- https://issues.liferay.com/browse/COMMERCE-9766
- https://issues.liferay.com/browse/COMMERCE-9850

It will be possible to delete product versions and product when versioning is enabled.

Resent of from https://github.com/liferay-commerce/liferay-portal/pull/2993

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
@victoroscuro can we forward it?

**Comment by victoroscuro** [comment]
@alessiorendina , @pietro.bocale is checking results

**Comment by pietrobocale** [comment]
Forwarded here: #3000

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
