### PR TITLE
COMMERCE-11744 Add support for UoM to pricing calculation

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-11744

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:commerce-integration

**Comment by smottal** [comment]
ci:test:commerce-integration

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
