### PR TITLE
Automated Test - COMMERCE-6020 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
https://issues.liferay.com/browse/COMMERCE-6020, cc: @pietrobocale

**Comment by kristinonias** [comment]
@AfonsoHSantos can you re-add the AddaSKU testcase, it shouldn't have been removed. Please remove the @ignore = "true" from your testcase.

**Comment by AfonsoHSantos** [comment]
@kristinonias done!

**Comment by AfonsoHSantos** [comment]
> @AfonsoHSantos can you re-add the AddaSKU testcase, it shouldn't have been removed. Please remove the @ignore = "true" from your testcase.

done!

**Comment by Pietro69** [comment]
There are issues with placeholders, in this case, AddASku must be present only CPCommerceProductSKUs and not in CPCommerceProduct, and the ticket is wrong because AddSku is COMMERCE-6021 while COMMERCE-6020 is occupied by AssertProductBundleCanBeCreatedWithPriceTypeStaticAndDynamic, sorry for the inconvenience.

**Pull request closed without merging**
