### PR TITLE
LPD-1462 Macau and Hong Kong

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-1462

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
