### PR TITLE
COMMERCE-8486 remove service reference, use sql query

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
merged.

@luca-pellizzon see 995bee59dc164bda348bca477f57e5e7002491a5 and d9e9f866eafbf6dcb0eef4e991ba42dcac069bf0

**Comment by brianchandotcom** [comment]
@luca-pellizzon see 995bee59dc164bda348bca477f57e5e7002491a5 and d9e9f866eafbf6dcb0eef4e991ba42dcac069bf0

**Pull request closed without merging**
