### PR TITLE
COMMERCE-12877 Make all resources in delivery catalog available to gu…

### PR DESCRIPTION
**Pull request by riccardo-alberti**
…est user

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
@riccardo-alberti  I had to abort the `relevant` test because the process froze.

**Comment by pyoo47** [comment]
ci:test:relevant

**Pull request closed without merging**
