### PR TITLE
COMMERCE-8531 Made product images and attachments available in Product Publisher ADT

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-8531

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
QA Passed. Forwarding

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
