### PR TITLE
Commerce 8949 new commerce's orders details UI

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
@dsitu could you check this one please? Many thanks

**Review by dsitu — CHANGES_REQUESTED** [review]
@luca-pellizzon `newView.jsp` should be `new-view.jsp`. Also is this a temporary page? If so maybe we can follow this pattern here. https://github.com/brianchandotcom/liferay-portal/pull/117444/files/8e35fd87a0917971d4e2ab6e626ef3443e61ccb7..25b134023d13b967a60e4007b3cd28793f4d8737. They created a new folder with the issue number with the same jsp file names. Although there's is trigger with a feature flag.

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test.sf

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
See https://github.com/liferay-commerce/liferay-portal/pull/2807

**Pull request closed without merging**
