### PR TITLE
Automated Test - Commerce-5862 | master

### PR DESCRIPTION
**Pull request by gabrielargomes**

### CODE REVIEW

**Comment by gabrielargomes** [comment]
https://issues.liferay.com/browse/COMMERCE-5862, cc:@lorenzo.lapescara

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Pull request closed without merging**
