### PR TITLE
LPD-15200 Added UPSERT strategy support to batch framework for headless-admin-user/v1.0/roles

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-15200

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:functional-commerce

**Review by riccardo-alberti — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Pull request closed without merging**
