### PR TITLE
COMMERCE-12504 - Missing Data in headless-commerce-admin-catalog Endpoints

### PR DESCRIPTION
**Pull request by victorcdp**
https://liferay.atlassian.net/browse/COMMERCE-12504

resent of #4362, Updating addCPDefinitionOptionValueRel calls made on some tests

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
@andrea-ale-sbarra Had to enforce the [Quantity = 0](https://github.com/liferay-commerce/liferay-portal/pull/4375/commits/ae52b15573a19ef0a84e48862c8fb09eb6c62bfa#diff-29f705ffd258b4a5c752c2cb3c483fe05fbb49358512cf8602f966a6cbce7bd7R180-R184) when the priceType is null, since otherwise integration tests would fail.
Hopefully there aren't any more broken tests.

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
Please see here https://github.com/liferay-commerce/liferay-portal/pull/4387

Thank you!

**Pull request closed without merging**
