### PR TITLE
[Do not merge] COMMERCE-9693 | Automate test for COMMERCE-9651 Order fields with Fragments

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
comment

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
