### PR TITLE
Automated Test - COMMERCE-6033 | master

### PR DESCRIPTION
**Pull request by IsaVV**

### CODE REVIEW

**Comment by IsaVV** [comment]
https://issues.liferay.com/browse/COMMERCE-6033, cc: @pietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
Please add the property `test.name.skip.portal.instance = "CPCommerceProductMedia#RemoveAnAttachment"`

**Comment by IsaVV** [comment]
fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @IsaVV, please fix your source formatting by correcting it to `property test.name.skip.portal.instance = "CPCommerceProductMedia#RemoveAnAttachment";`

**Comment by kristinonias** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:test:commerce-functional

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
