### PR TITLE
Automated Test - COMMERCE-6017 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6017 ; cc: @pietrobocale

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
Remove the @ignore = "true"

**Comment by pedroalmd** [comment]
@Pietro69 fixed.

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
