### PR TITLE
Automated Test - COMMERCE-6169 | master

### PR DESCRIPTION
**Pull request by IsaVV**

### CODE REVIEW

**Comment by IsaVV** [comment]
https://issues.liferay.com/browse/COMMERCE-6169, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
