### PR TITLE
COMMERCE-5483 DIAGRAM_1of5

### PR DESCRIPTION
**Pull request by garofalog**

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:stable

**Comment by garofalog** [comment]
ci:foreward

**Comment by garofalog** [comment]
ci:forward

**Pull request closed without merging**
