### PR TITLE
LPD-7935 Remove unused reference

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
@riccardo-alberti Rebase required, sent here: https://github.com/liferay-commerce/liferay-portal/pull/4667

**Pull request closed without merging**
