### PR TITLE
COMMERCE-7000 Escape admin breadcrumb url

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-7000,

I cannot get this issue to reproduce in Master, but we should still implement this as a pre-caution as per:
https://liferay.atlassian.net/browse/COMMERCE-7000?focusedCommentId=465283

@andrea-ale-sbarra ,

I would say only thing that needs to be QA tested is just checking whether issue is reproducible in 7.1.x-7.3.x.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/4041

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
