### PR TITLE
LPD-3472

### PR DESCRIPTION
**Pull request by brianikim**
Resending from: https://github.com/liferay-commerce/liferay-portal/pull/4766

https://liferay.atlassian.net/browse/LPD-3472

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@brianikim lots of test failures that could be related, please check the results. Many thanks

**Comment by brianikim** [comment]
@luca-pellizzon , I am checking the failures now.

**Comment by brianikim** [comment]
@luca-pellizzon , there are some additional failures due to the parsing logic I introduced. I will fix the commits as well.

**Comment by brianikim** [comment]
@luca-pellizzon , still fixing the tests. Sorry about the delay on this.

**Comment by brianikim** [comment]
Running test separately here: https://github.com/brianikim/liferay-portal/pull/150

There is an edge case scenario that I need CI results to reliably re-test. Failures will most likely happen. But I feel very positive about being able to resolve it today.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:stable

**Comment by brianikim** [comment]
Hello @luca-pellizzon , please take a look at the latest test fix commit and let me know if you see any concerns with the changes I have made to accommodate the PR.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by brianikim** [comment]
Running CI one more time, but I am fairly certain none of the failures are related.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:stable

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:stable

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:stable

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
@brianikim please check the SF failure

**Comment by brianikim** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/4832

**Pull request closed without merging**
