### PR TITLE
COMMERCE-9409

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-9409
Add automation and resent from https://github.com/liferay-commerce/liferay-portal/pull/4242.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
resent here
https://github.com/liferay-commerce/liferay-portal/pull/4242

**Pull request closed without merging**
