### PR TITLE
COMMERCE-4301 We should be indexing the lowest price not the highest

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Review by marco-leo — APPROVED** [review]

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
