### PR TITLE
COMMERCE-11807 Only return if fetch is not null

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-11807

@andrea-ale-sbarra , tied to LPP.

Caused by https://liferay.atlassian.net/browse/COMMERCE-9935

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
