### PR TITLE
LPD-21231 Remove feature flags

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-21231

### CODE REVIEW

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:report:2563053106

**Comment by dsitu** [comment]
unique test failure: AgentPortalK8sConfigMapModifierTest

**Comment by dsitu** [comment]
ci:forward

**Comment by luca-pellizzon** [comment]
from https://github.com/brianchandotcom/liferay-portal/pull/149481

**Pull request closed without merging**
