### PR TITLE
COMMERCE-9798 Fix subscription cycle length suffix

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-9798

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:stop

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
