### PR TITLE
COMMERCE-12375 Allow guest users to access the order details page thr…

### PR DESCRIPTION
**Pull request by brianikim**
…ough pending orders widget

@luca-pellizzon ,

https://liferay.atlassian.net/browse/COMMERCE-12375

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/4429

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
