### PR TITLE
COMMERCE-11649 | Check whether the request is valid before redirect

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #3847 

https://issues.liferay.com/browse/COMMERCE-11649

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
The failures on the relevant are not related to this PR. This PR can be forwarded. Thanks!

cc/ @luca-pellizzon

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
