### PR TITLE
LPD-39641 - Facet option empty after deleting a product Option

### PR DESCRIPTION
**Pull request by victorcdp**
this is a resend of https://github.com/brianchandotcom/liferay-portal/pull/156106

@andrea-ale-sbarra the reason I didn't use @DeleteAfterTestRun for _cpDefinitionOptionRels is because, apparently, DeleteAfterTestRun runs after the Teardown (at least it did in my local testing), so the teardown would throw exceptions when trying to delete the CPOptions before it's CPDefinitionOptionRels.
This was the only way I found to garantee the Rels would be deleted before it's parent Options, if you know of a better way to do the data cleanup, please let me know.

### CODE REVIEW

**Review by alessiorendina — APPROVED** [review]
@victorcdp LGTM, thank you!

**Comment by alessiorendina** [comment]
@victorcdp there are conflicts, please rebase. Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by alessiorendina** [comment]
@victorcdp can you check if the failures are related to your changes?

**Comment by victorcdp** [comment]
Hey @alessiorendina , they are unrelated

**Comment by alessiorendina** [comment]
Thank you, @victorcdp 

I'll forward it then.

**Comment by alessiorendina** [comment]
ci:forward:force

**Pull request closed without merging**
