### PR TITLE
Commerce 7339

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-7339

@riccardo-alberti

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/1954

**Pull request closed without merging**
