### PR TITLE
COMMERCE-9877 Add account name to order search

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9877

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:reevaluate:1317401_4978

**Comment by dsitu** [comment]
@luca-pellizzon Added a check to only reindex when account name is changed, https://github.com/liferay-commerce/liferay-portal/pull/3020/commits/a8182238c71b9c4aaf44645f2524d5ca5adbbbd3 and created CommerceBatchReindexer https://github.com/liferay-commerce/liferay-portal/pull/3020/commits/b360d381ad27a2784e0e36afd06f12e36e55daa4. I'm guessing it would be more efficient.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
