### PR TITLE
COMMERCE-9184 Fix custom price range filter

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9184

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
Thank you @dsitu

**Comment by pietrobocale** [comment]
QA Passed

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
