### PR TITLE
COMMERCE-5142 Fix Brazilian currency label

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/COMMERCE-5142

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:stable

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:commerce

**Review by dsitu — APPROVED** [review]

**Comment by iovaneale** [comment]
@marco-leo This failure, which affects other PRs also, occurs because the test does not catch the user Test Test within an item selector. After the analysis, it came out that the entry is not listed unless a full reindex is executed. Is it a bug, or we just need to add the reindex step to the test?

**Comment by marco-leo** [comment]
@iovaneale This seens unique to this PR

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
