### PR TITLE
COMMERCE-10761 Chekout: user can select existing address with a country that is not available for the channel

### PR DESCRIPTION
**Pull request by elocamp**
This issue was reproducing because there wasn't a check before adding the Addresses into the dropdown menu.
Proposed fix consists in adding a verification in the JSP file to check if the Country of the current Address has not the Group Filter enabled before adding them.

Related ticket: [COMMERCE-10761](https://issues.liferay.com/browse/COMMERCE-10761)

### CODE REVIEW

**Comment by elocamp** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this PR needs your review and needs to be prioritized.

**Comment by elocamp** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
@elocamp here we should check not only if the filter is enabled but also if the country is usable for a specific channel. /cc @brianikim

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
