### PR TITLE
LPD-40615 - Deprecate Commerce Addresses

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-40615

cc @smottal

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:61510093

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
