### PR TITLE
COMMERCE-11790

### PR DESCRIPTION
**Pull request by brianikim**
Resent from:

https://github.com/liferay-commerce/liferay-portal/pull/4004

https://liferay.atlassian.net/browse/COMMERCE-11790

CI should not be ran on this until LPS-191707 has been merged: https://github.com/brianchandotcom/liferay-portal/pull/138620

Sincerely,
Brian I. Kim

### CODE REVIEW

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4101

**Comment by pietrobocale** [comment]
ci:close

**Comment by jaydawu** [comment]
PR was sent here https://github.com/liferay-commerce/liferay-portal/pull/4101 and merged already..

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
