### PR TITLE
COMMERCE-11821 Subtract shipping tax based on discount percentage

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-11821

@luca-pellizzon , tied to LPP.

When shipping is discounted, the tax and total should reflect the discount.

Ex. shipping (100%) discount for 20$, shipping tax would be 0$ (4$-4$).
Ex. shipping (40%) discount for 20$, shipping tax would be 2.4$ (4$ - 1.6$).

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
The issues are not related to the changes, PR can be forwarded, thanks!

**Pull request closed without merging**
