### PR TITLE
COMMERCE-5661 Remove unused searcher

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:stop

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:stop

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@Commando18 I merged this manually.

**Comment by Commando18** [comment]
@brianchandotcom Thanks! I will close it then

**Pull request closed without merging**
