### PR TITLE
COMMERCE-12813 Make sure companyId is provided

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12813

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR.
@victoroscuro can you force-forward this PR? Thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
