### PR TITLE
LPS-123965,LPS-124914,LPS-124915

### PR DESCRIPTION
**Pull request by julien**
This PR has 3 associated LPS tickets originally reviewed by @liferay-frontend.

Here's a summary for each of them:

---

**LPS-123965**

The `editorName` attribute has been removed from the
`<liferay-ui:input-localized>` tag instance, so that it uses
`_EDITOR_WYSIWYG_DEFAULT`, which is `ckeditor`.

**Test plan**

- Deploy the `commerce-payment-method-money-order` module
- From the global menu, select the **Control Panel** tab
- Navigate to **Sites**
- Create a new site based on the **Speedwell** template
- From the global menu, select the **Commerce** tab
- Under **Store management** select **Channels**
- Select **Commerce Portal**
- Scroll down the **Payment Methods** panel
- Click the **Edit** button next to **Money Order**
- Toggle the **Active** check box
- Click on **Save**
- Select the **Configuration** tab
- Toggle the **Show Message Page** check box

**Before**

**After**

---

**LPS-124914**

The `editorName` attribute has been removed from the
`<liferay-ui:input-localized>` tag instance, so that it uses
`_EDITOR_WYSIWYG_DEFAULT`, which is `ckeditor`.

**Test plan**

- Deploy the `commerce-product-definitions-web` module
- From the global menu, select the **Control Panel** tab
- Navigate to **Sites**
- Create a new site based on the **Speedwell** template
- From the global menu, select the **Commerce** tab
- Select **Products**
- Edit an existing product
- Assert that a ckeditor instance is visible under **Full Description**

**Before**

**After**

---

**LPS-124915**

The `editorName` attribute has been removed from the
`<liferay-ui:input-localized>` tag instance, so that it uses
`_EDITOR_WYSIWYG_DEFAULT`, which is ckeditor.

**Test plan**

- Deploy the `commerce-product-type-virtual-web` module
- From the global menu, select the **Control Panel** tab
- Navigate to **Sites**
- Create a new site based on the **Speedwell** template
- From the global menu, select the **Commerce** tab
- Select **Products**
- Create a new **virtual** product
- Select the **Virtual** tab
- Toggle the **Enable Terms of Use** check box
- Assert that a ckeditor instance is visible and usable

**Before**

**After**

---

Sent with @jbalsas's [blessing](https://github.com/liferay-frontend/liferay-portal/pull/637#issuecomment-747490476) :heart:

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @luca-pellizzon, do you have any specific concerns about this that would prevent us from forwarding it?

We can walk you (or anyone in @liferay-commerce) through the changes if needed. It should be pretty straightforward and this responds to our attempt to completely remove AlloyEditor in `7.4`. We did this work for any other app in DXP in the past release cycle but commerce was not there yet, which is the reason why we skipped it.

Please, let us know how to help you here. I'd suggest we simply forward this and deal with issues later if there are any.

**Comment by marco-leo** [comment]
Hi chema . all looks good to me, just will run tests

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:sf

**Review by marco-leo — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
