### PR TITLE
COMMERCE-5179 commerce-product-test added test for checking the updat…

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
…e of the ERC field of a CPInstance

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Pull request closed without merging**
