### PR TITLE
[DO NOT MERGE] COMMERCE-9596 Extension point to define a Collection Provider that supplies SKU's as options

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-9596

Add automation based on https://github.com/liferay-commerce/liferay-portal/pull/4057 and https://github.com/liferay-commerce/liferay-portal/pull/4117.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:stop

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4130

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
