### PR TITLE
COMMERCE-12104 Fixed Image Gallery

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/COMMERCE-12104

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by brianchandotcom** [comment]
@alessiorendina merged to master and U88

**Comment by alessiorendina** [comment]
@brianchandotcom Ok, thank you! Closing this one then

**Pull request closed without merging**
