### PR TITLE
COMMERCE-10173 - It's possible to save a product configuration with wrong values

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-10173
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3547

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
@victorcdp @jaydawu semantic versioning issue, must run baseline

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/3637

**Pull request closed without merging**
