### PR TITLE
COMMERCE-12433 OrgChart View/Edit Panel - User + Automation

### PR DESCRIPTION
**Pull request by smottal**
User Story: https://liferay.atlassian.net/browse/COMMERCE-12433

Testplan: https://liferay.atlassian.net/browse/COMMERCE-12872

resent from: https://github.com/brianchandotcom/liferay-portal/pull/144073 for renaming

@baharturk

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:stable

**Comment by saramart81** [comment]
The stable is ok, @victoroscuro please help force-forward it, thanks!

**Comment by lorenzolapescara** [comment]
ci:forward:force

**Pull request closed without merging**
