### PR TITLE
Commerce 8455 fix

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@CrescenzoRegaLF

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@luca-pellizzon merged

**Pull request closed without merging**
