### PR TITLE
COMMERCE-10128 Fixed permission error thrown after publishing a page with Categories-related widgets

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-10128

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1367401_2465

**Comment by pietrobocale** [comment]
QA Passed

**Pull request closed without merging**
