### PR TITLE
COMMERCE-4970 New functional test: CPCommercePriceLists#AssertPriceListCannotBeMovedToADifferentCatalog

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-4970

### CODE REVIEW

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
