### PR TITLE
Commerce 12733 - fix price range facet

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12733

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]
@andrea-ale-sbarra overall it looks good. Just a question on the if here https://github.com/liferay-commerce/liferay-portal/blame/2ee969d71cb5c648488e3bba2fe24b564c3edb10/modules/apps/commerce/commerce-product-content-search-web/src/main/resources/META-INF/resources/price_range_facets/view.jsp#L64 (I'm not able to add a comment on the code itself because it's not something touched by the PR): is this `<c:if` still needed? Because it should be already inside the `c:choose` of when it's visible

**Comment by andrea-ale-sbarra** [comment]
@smottal I would say yes it prevents quite few code to be executed if the condition is not met

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
