### PR TITLE
LPD-18485 Manage contacts on Account by API

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-18485

Resent from https://github.com/brianchandotcom/liferay-portal/pull/147965

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
