### PR TITLE
COMMERCE-12768 - Case sensitive coupon codes are not applied

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-12768](https://liferay.atlassian.net/browse/COMMERCE-12768)

@luca-pellizzon Can you review this one? Tied to an LPP. Thank you.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed, added automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/4437

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
