### PR TITLE
COMMERCE-7550 Mapping view refactored in import/export

### PR DESCRIPTION
**Pull request by fabio-d-m**

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:stable

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:forward

**Pull request closed without merging**
