### PR TITLE
COMMERCE-11452

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

https://issues.liferay.com/browse/COMMERCE-11451
https://issues.liferay.com/browse/COMMERCE-11452
https://issues.liferay.com/browse/COMMERCE-11480

This fixes all three tickets and need to test for all three.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this one still needs your review. tied to LPP.

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]

**Comment by brianikim** [comment]
@andrea-ale-sbarra , can you check my latest commit 57e6b43 if it meets the requested change for inlining? Thank you.

**Review by andrea-ale-sbarra — APPROVED** [review]
Yes that was it!

Thank you!

**Pull request closed without merging**
