### PR TITLE
LPD-32094 - ERC Support for Postal Addresses

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-32094

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:stable

**Comment by brbalazs** [comment]
ci:stop

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:56977040

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
