### PR TITLE
LPD-37906 Permissions to manage Multi Shipping

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-37906

resend this https://github.com/brianchandotcom/liferay-portal/pull/155395

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:report:53627424

**Comment by CrescenzoRegaLF** [comment]
ci:report:53642920

**Comment by CrescenzoRegaLF** [comment]
Hi @luca-pellizzon I checked the CI failures and they do not depend on the code in the PR

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
