### PR TITLE
DO NOT MERGE - COMMERCE-7221 Refactor Commerce poshi tests teardown by using API calls(JSON)

### PR DESCRIPTION
**Pull request by victoroscuro**
https://issues.liferay.com/browse/COMMERCE-7221

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by pyoo47** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:stop

**Review by dsitu — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:stop

**Pull request closed without merging**
