### PR TITLE
COMMERCE-5065 Element is not present at LocalFile.CommerceSmoke#CreateNewSpecificationOptions

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-5065

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@lorenzolapescara relevant tests passed already , why you are retesting ?

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
