### PR TITLE
Commerce 7089_2 | Fix functional tests

### PR DESCRIPTION
**Pull request by iovaneale**

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:stop

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:stop

**Comment by riccardo-alberti** [comment]
open a new one

**Pull request closed without merging**
