### PR TITLE
LPD-32045 - Refactor of poshi test Account#AllAccountsEntriesDisplay

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-32045

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:playwright:nocompile

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:playwright

**Comment by brbalazs** [comment]
ci:test:playwright

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
