### PR TITLE
COMMERCE-10826 Uses item selector to select web content, in that way we can also have folder navigation

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-------
In order to use item selector we migrated the Asset Browser to Item Selector, in case of web content it also enables folder navigation.

Proposed Solution
-------
Use item selector to select web content for term of use.

Steps to reproduce
-------
1. Create a new virtual product
2. Go into the "Virtual" tab

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
Tested locally

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
