### PR TITLE
COMMERCE-10012 Adding external reference code to the UI and editing services to save\edit the field

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10012

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
This looks good to me.

Thank you @CrescenzoRegaLF .

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
sent here #3060

**Pull request closed without merging**
