### PR TITLE
Commerce 5767 persist erc account address

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-5767

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevantr

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by dsitu** [comment]
@andrea-ale-sbarra rebased and added your commits onto my PR https://github.com/liferay-commerce/liferay-portal/pull/678

**Comment by riccardo-alberti** [comment]
closing this PR. Refer to #678

**Pull request closed without merging**
