### PR TITLE
COMMERCE-11195 | Fix fragment diagram product card

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-11195

Re-sent from https://github.com/liferay-commerce/liferay-portal/pull/3639

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
@lorenzolapescara Please fix the functional tests, thank you!

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by pietrobocale — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward:force

**Comment by alessiorendina** [comment]
ci:forward:force

**Comment by alessiorendina** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/133457

**Pull request closed without merging**
