### PR TITLE
COMMERCE-12536 Display UOM on Shipment pages

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12536

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
