### PR TITLE
Automated Test - COMMERCE-6355 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-6355; cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//td[contains(@class,'table-cell-expand') and contains(.,'U-Joint')]"

**Pull request closed without merging**
