### PR TITLE
COMMERCE-12002 Short ciruit if product.productName is undefined

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/COMMERCE-12002

/cc @ilzamcmed @pedro-michel

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
