### PR TITLE
LPD-21367 Fix playwright tests

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-21367

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:playwright

**Review by riccardo-alberti — APPROVED** [review]

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
