### PR TITLE
Automated Test - COMMERCE-6332 | master

### PR DESCRIPTION
**Pull request by Jamersonze**

### CODE REVIEW

**Comment by Jamersonze** [comment]
https://issues.liferay.com/browse/COMMERCE-6332, cc:@lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ViewMiniCartItemDetails passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
