### PR TITLE
Automated Test - COMMERCE-6751 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6751 ; cc: @pietrobocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
Running CI on [kristinonias #9](https://github.com/kristinonias/liferay-portal/pull/9)

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//div[@id='main-content']//div[contains(@class,'portlet')]//section[contains(@id,'Checkout')]"

**Comment by pedroalmd** [comment]
@kristinonias I fixed it but it looks like it needs to be open so I can force-push it.

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1422 @kristinonias

**Pull request closed without merging**
