### PR TITLE
COMMERCE-11959 Reassign call result

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-11959

@luca-pellizzon ,

We should expedite forwarding this if we can.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures on the relevant are not related to the PR, this can be forwarded. Thanks!

@victoroscuro @luca-pellizzon

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
