### PR TITLE
COMMERCE-5496 Remove from quarantine and fix CPCommerceProducts#TranslateProductName

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5496

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
