### PR TITLE
Commerce 11289

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
Jira : https://issues.liferay.com/browse/COMMERCE-11289

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you!

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
Hi @MahmoudAzzam could you please close this PR I have sent a new one at https://github.com/liferay-commerce/liferay-portal/pull/3722

Thanks!

**Pull request closed without merging**
