### PR TITLE
Commerce 10182 - OM - Account Channel Defaults

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
These commits will introduce the new API to manage Account Channels Defaults.

- https://issues.liferay.com/browse/COMMERCE-10202 - YAML Changes
- https://issues.liferay.com/browse/COMMERCE-10182 - Headless API to set an Account Default Address (Billing and Shipping) per Channel
- https://issues.liferay.com/browse/COMMERCE-10184 - Headless API to set an Account Default Delivery Terms per Channel
- https://issues.liferay.com/browse/COMMERCE-10185 - Headless API to set an Account Default Payment Terms per Channel
- https://issues.liferay.com/browse/COMMERCE-10188 - Headless API to set an Account Default Price List per Channel
- https://issues.liferay.com/browse/COMMERCE-10189 - Headless API to set an Account Default Discount per Channel
- https://issues.liferay.com/browse/COMMERCE-10190 - Headless API to set an Account Manager per Channel
- https://issues.liferay.com/browse/COMMERCE-10191 - Headless API to set an Account Default Currency per Channel

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:reevaluate:1267401_5743

**Comment by dsitu** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test

**Comment by andrea-ale-sbarra** [comment]
ci:test:stop

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
🤞 for the relevant and conflicts

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
I'm closing this because I've already solved the conflicts in the other PRs

**Pull request closed without merging**
