### PR TITLE
LPD-17212

### PR DESCRIPTION
**Pull request by brianikim**

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this is not necessarily tied to any ticket for review. Just running CI to confirm everything is okay, then it should be forwarded to BChan.

**Comment by andrea-ale-sbarra** [comment]
failure looks unrelated

**Pull request closed without merging**
