### PR TITLE
Automated Test - COMMERCE-6353 | master

### PR DESCRIPTION
**Pull request by ewertonluna**

### CODE REVIEW

**Comment by ewertonluna** [comment]
https://issues.liferay.com/browse/COMMERCE-5957, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ViewProductDetailsWidget passed, forwarding it.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
