### PR TITLE
LPD-32519 Not show warning message after submit return

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-32519

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
LGTM.
Can you please add a functional test?
You can use this as reference: https://github.com/liferay-commerce/liferay-portal/pull/5220/commits/36927d7d8c12adc29cb30716f5c4f0b47d48ba25

**Review by CrescenzoRegaLF — APPROVED** [review]

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:test:playwright

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@monaco-fabio the functional test LPD-21633 Returns widget to show return and refunds is failing, please have a look

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright

**Comment by monaco-fabio** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
