### PR TITLE
Add to cart button refactored to handle multiple skus + SbD table improved (2)

### PR DESCRIPTION
**Pull request by fabio-d-m**
This PR make the user able to delete a number in a quantity selector. The add to cart button will be disabled in case of an empty string.

image

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
@victoroscuro @riccardo-alberti

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:stop

**Pull request closed without merging**
