### PR TITLE
COMMERCE-9915 Deleting Account Addresses does not remove association in Orders

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9915

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:stop

**Review by luca-pellizzon — COMMENTED** [review]
@dsitu for legal reasons we can't allow to remove addresses from placed orders.
When the order is placed there should be a logic that clones the address, so we are effectively linking to the order a copy of the address, not the "original" one.
Can you do some checks, that those addresses cannot be deleted manually? (maybe only if the order is deleted they can also be removed)

**Comment by dsitu** [comment]
> @dsitu for legal reasons we can't allow to remove addresses from placed orders. When the order is placed there should be a logic that clones the address, so we are effectively linking to the order a copy of the address, not the "original" one. Can you do some checks, that those addresses cannot be deleted manually? (maybe only if the order is deleted they can also be removed)

@luca-pellizzon ahhh ic, yep I can add in some validation to make sure addresses tied to orders that have already been placed can not be deleted until its associations are updated. Thanks for clarification.

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by dsitu** [comment]
ci:reevaluate:1327401_5591

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
@luca-pellizzon I had to add a commit https://github.com/liferay-commerce/liferay-portal/pull/2977/commits/dd735ab77968939da0c99bfdb06f2f74b699ec35

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
