### PR TITLE
COMMERCE-12027 Fix CommerceMiniCart#ViewMiniCartItemDetails

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-12027

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
cc/ @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
