### PR TITLE
COMMERCE-6413 Commerce Channel API unable to define "Type"

### PR DESCRIPTION
**Pull request by victoroscuro**
https://issues.liferay.com/browse/COMMERCE-6413

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
resent from https://github.com/liferay-commerce/liferay-portal/pull/3104

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
