### PR TITLE
COMMERCE-9476 Fix minium demo site knowledge base page

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9476

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
QA Passed. Forwarding

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
