### PR TITLE
Commerce 12504 1

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12504

resent of https://github.com/liferay-commerce/liferay-portal/pull/4355

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by victorcdp** [comment]
Sent again at #4375

**Comment by victorcdp** [comment]
ci:close

**Pull request closed without merging**
