### PR TITLE
Automated Test - COMMERCE-6203 | master

### PR DESCRIPTION
**Pull request by piresdm**

### CODE REVIEW

**Comment by piresdm** [comment]
https://issues.liferay.com/browse/COMMERCE-6203; cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
