### PR TITLE
COMMERCE-12164 sort

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://github.com/brianchandotcom/liferay-portal/pull/140532#issuecomment-1718029708

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
The failures are not related to the PR, check only the semantic versioning issue

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
