### PR TITLE
Automated Test - COMMERCE-6304 | master

### PR DESCRIPTION
**Pull request by juliomoraes-dev**

### CODE REVIEW

**Comment by julioribeiiro** [comment]
https://issues.liferay.com/browse/COMMERCE-6304, cc: @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//tr/td[contains(.,'Guest')]//..//button[contains(.,'Choose')]"

**Pull request closed without merging**
