### PR TITLE
COMMERCE-5274 Number of items restored in Cart opener

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Review by marco-leo — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
