### PR TITLE
COMMERCE-6312 Changed event name for DDMFormHandler as it was changed in DDMForm FE Impl

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
Out of completeness, by the time the DDMForm change was put in place and proposed, the event name was still the old one
https://github.com/liferay-forms/liferay-portal/pull/137

**Comment by gianmarcobrunialti** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/100337

**Pull request closed without merging**
