### PR TITLE
COMMERCE-9633 Products published using the generation of all skus combination from options do not appear in the catalog store front

### PR DESCRIPTION
**Pull request by alessiorendina**
resending from: https://github.com/liferay-commerce/liferay-portal/pull/3073
@CrescenzoRegaLF @baharturk

https://issues.liferay.com/browse/COMMERCE-9633

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
ci:test:relevant

**Pull request closed without merging**
