### PR TITLE
COMMERCE-7066 Pass a variable instead of a defined string in Commerce…

### PR DESCRIPTION
**Pull request by lorenzolapescara**
…Entry.viewPaginationResults()
https://issues.liferay.com/browse/COMMERCE-7066

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
