### PR TITLE
LPD-29800 Refactor poshi test

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-29800

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]
LGTM, thank you!

**Comment by monaco-fabio** [comment]
ci:stop

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
