### PR TITLE
COMMERCE-4482 | COMMERCE-4483 | COMMERCE-4484 | COMMERCE-4485 | COMMERCE-4486

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@marco-leo all these tickets need change to the same yaml that's why they are all in a single PR. If necessary i can try to split them.

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
