### PR TITLE
LPD-370737 Partial Revert "COMMERCE-10598 Sanitize addresses for safe…

### PR DESCRIPTION
**Pull request by brianikim**
… HTML viewing"

COMMERCE-11974 fixes COMMERCE-10598

Partial revert of: https://github.com/brianchandotcom/liferay-portal/commit/d417f0de65b5de07f468881ced15ccaa0b5997ff

Fixed already by : 

https://github.com/brianchandotcom/liferay-portal/commit/6c00be0274fac574159a1f4b3d382dc0a03d8199

@smottal , https://liferay.atlassian.net/browse/LPD-37037

Tied to LPP.

### CODE REVIEW

**Comment by brianikim** [comment]
@smottal ,

I don't think this needs a test, but I await your assessment.

**Comment by brianikim** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
