### PR TITLE
Automated Test - COMMERCE-6109 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-6109 , cc: @Pietro69

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
Review started

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
