### PR TITLE
COMMERCE-4837 added wildcards to PL name

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
@andrea-ale-sbarra I don't feel this is the right solution, see :  DLFileEntryKeywordQueryContributor

**Comment by andrea-ale-sbarra** [comment]
Hey @marco-leo @riccardo-alberti can we talk about this https://issues.liferay.com/browse/LPS-121446 I think it related also to this pr #256

**Comment by riccardo-alberti** [comment]
closing this and opening https://github.com/liferay-commerce/liferay-portal/pull/589

**Pull request closed without merging**
