### PR TITLE
COMMERCE 12950 Commerce Product description is displayed with HTML Tags in Paragraph Fragment + fix a locator

### PR DESCRIPTION
**Pull request by saramart81**
sent from #4488 
https://liferay.atlassian.net/browse/COMMERCE-12950

### CODE REVIEW

**Comment by saramart81** [comment]
ci:test:sf

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:sf

**Comment by saramart81** [comment]
ci:test:sf

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
CI results are ok, the failures are not related to the PR. It can be forwarder, thanks!

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
