### PR TITLE
COMMERCE-12657 Fix account context in product details page

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12657

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
Closing as already merged: https://github.com/brianchandotcom/liferay-portal/pull/142857

**Pull request closed without merging**
