### PR TITLE
COMMERCE-9743 - Delivery Subscription is visible on the SF even if it's not enabled, with multiple SKUs product

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-9742
https://liferay.atlassian.net/browse/COMMERCE-9743

Resent from https://github.com/liferay-commerce/liferay-portal/pull/3605, https://github.com/liferay-commerce/liferay-portal/pull/4444

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
cc/ @victoroscuro

**Comment by jaydawu** [comment]
The results on PR are good, so it can be force-forwarded, thanks!
cc. [victoroscuro](https://github.com/victoroscuro)

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
