### PR TITLE
Automated Test - COMMERCE-6124 | master

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-6124; cc: @Pietro69

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Combined: https://github.com/liferay-commerce/liferay-portal/pull/1255
Forwarded: https://github.com/brianchandotcom/liferay-portal/pull/102208

**Pull request closed without merging**
