### PR TITLE
COMMERCE-12371 Condition got lost during migration in COMMERCE-11354

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

Sending the PR to you as https://liferay.atlassian.net/browse/COMMERCE-12371 was caused by

https://liferay.atlassian.net/browse/COMMERCE-11354
https://github.com/liferay-commerce/liferay-portal/pull/4116/commits/e5320b1c61465d27a45d7dce5e09ca7902960cf0

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Pull request closed without merging**
