### PR TITLE
COMMERCE-9764 Fix query for discount validator

### PR DESCRIPTION
**Pull request by lorenzolapescara**
Re-sent from #2922

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
ci:forward

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
