### PR TITLE
COMMERCE-12551 validate order item before saving it

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12551

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
LGTM! Thanks @andrea-ale-sbarra

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by brianchandotcom** [comment]
@alessiorendina @andrea-ale-sbarra I merged this manually.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
