### PR TITLE
LPD-35920 add attachment to delivery order api

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-35920

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
@smottal please see here

**Comment by smottal** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:report:43851618

**Comment by smottal** [comment]
ci:test:stable

**Comment by smottal** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
sent here

**Pull request closed without merging**
