### PR TITLE
Automated Test - COMMERCE-6242 | master 

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
Element is not present at "//div[@id='main-content']//div[contains(@class,'portlet')]//section[contains(@id,'Checkout')]"

**Comment by pedroalmd** [comment]
Fixed @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
