### PR TITLE
COMMERCE-12909 Preserve switched account and return to open orders view

### PR DESCRIPTION
**Pull request by lorenzolapescara**
[COMMERCE-12909](https://liferay.atlassian.net/browse/COMMERCE-12909)

Resend of #4512

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]
Review done

Thanks!

**Comment by lorenzolapescara** [comment]
Failures are not related, PR can be force-forwarded.

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
