### PR TITLE
COMMERCE-8802 - When the user focuses on the Term Description modal, the outline is bigger than the modal

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related Issue: https://issues.liferay.com/browse/COMMERCE-8802

### CODE REVIEW

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by ericthmoritsuka** [comment]
@luca-pellizzon 
Hi Luca, I did some thinking and I guess only using modal in className will do the trick. That is why I changed the commit.

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by ericthmoritsuka** [comment]
@victoroscuro and @luca-pellizzon 
Luca Giannotta pointed out that the bug is still reproducing. I believe that the modal with the terms appear in two different moments and they are two different modals. The one that opens in the checkout process has been corrected. However, the one that opens in placed orders appears to be broken still. I will fix it and return as soon as I do it.

**Comment by ericthmoritsuka** [comment]
There you go, I hadn't noticed that both modals were created differently in different places (in commerce-checkout-web and commerce-order-content-web). I altered both of them now.

**Comment by 22LucaGiannotta22** [comment]
Hi @ericthmoritsuka, yesterday I couldn't see any of the 2 modals fixed. Even the modal in "Placed Order" has the vertical lines of the outline that go outside the white area of the modal. The outline should not go outside the white area of the modal. 
I saw that you reduced the white area of the modal inside the checkout, but the issue it's not the white area, but the outline surrounding the white area.

**Comment by ericthmoritsuka** [comment]
I believe it is as requested now. I left the center property in containerProps because, otherwise, the scrollbar was not appearing when the modal was bigger than the screen. I also used size 'lg' to maintain a large size in the modal.

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by ericthmoritsuka** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
