### PR TITLE
COMMERCE-11927 - Unable to search account group inside products

### PR DESCRIPTION
**Pull request by victorcdp**
https://liferay.atlassian.net/browse/COMMERCE-11927

@andrea-ale-sbarra Can you review this one? Tied to an LPP, thank you.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by lorenzolapescara** [comment]
Re-sent at #4009.

**Comment by lorenzolapescara** [comment]
ci:close

**Pull request closed without merging**
