### PR TITLE
Automated Test - COMMERCE-5856 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@evanilson-santana 

This pull request failed Source Formatting. Please fix and resend.

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:stop

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@evanilson-santana ,

This pull request has formatting issues. Please fix and resend.

**Comment by evanilson-santana** [comment]
Fixed.

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1386 @kristinonias

**Pull request closed without merging**
