### PR TITLE
COMMERCE-9707 New permission to limit the views of Accounts for Agents based on Account/Channel Relationship

### PR DESCRIPTION
**Pull request by ghost**
Re-sent from https://github.com/brianchandotcom/liferay-portal/pull/124023#issuecomment-1265535234

https://issues.liferay.com/browse/COMMERCE-9707

@lorenzolapescara

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Pull request closed without merging**
