### PR TITLE
LPD-7935 Remove unused reference

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
From here: https://github.com/liferay-commerce/liferay-portal/pull/4655

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:stable

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
resent here https://github.com/liferay-commerce/liferay-portal/pull/4686

**Pull request closed without merging**
