### PR TITLE
LPD-21645 Enable default names on SF

### PR DESCRIPTION
**Pull request by smottal**

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
SF changes are good to go.

**Comment by CrescenzoRegaLF** [comment]
ci:report:2560769198

**Comment by CrescenzoRegaLF** [comment]
ci:report:2561108563

**Comment by smottal** [comment]
Closing this as already inside https://github.com/liferay-commerce/liferay-portal/pull/4871

**Pull request closed without merging**
