### PR TITLE
Commerce 8940 User must have VIEW permission for com.liferay.commerce.model.CommerceOrderType

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@drewbrokke I moved CommerceGroupThreadLocal to commerce-api to be accessible because during order payments we switch servlet context (to payment servlet) and so loosing the current groupId (I think because of a blank WebKeys.VISITED_GROUP_ID_RECENT).
Just check this out please.
Thanks.

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@luca-pellizzon I merged this manually.

@drewbrokke fyi

**Pull request closed without merging**
