### PR TITLE
COMMERCE-12658 Channel Restriction on Account Addresses

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12658

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4481

**Comment by pietrobocale** [comment]
ci:stop

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
