### PR TITLE
COMMERCE-8287, COMMERCE-8489 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-8489
https://issues.liferay.com/browse/COMMERCE-8287

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-funcitonal

**Comment by Kvale1733** [comment]
ci:stop

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
This PR is going to have merge conflicts due to another PR so I'm going to wait for the for the next stable synch and rebase.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
