### PR TITLE
LPD-36713 Total price in minicart is wrong calculated with a UOM in bundle product

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-36713
https://liferay.atlassian.net/browse/LPD-36295

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
I've sent the fix for test failures [here](https://github.com/liferay-commerce/liferay-portal/pull/5405)

**Pull request closed without merging**
