### PR TITLE
LPD-22351 LPD-22352

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
LPD-22351 story: https://liferay.atlassian.net/browse/LPD-20293
LPD-22352 story: https://liferay.atlassian.net/browse/LPD-20294

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Pull request closed without merging**
