### PR TITLE
COMMERCE-6529 PART 1 - Batch Engine User Interface

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:relevant

**Pull request closed without merging**
