### PR TITLE
LPD-6058 significant test performance improvement

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-6058

### CODE REVIEW

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Comment by brbalazs** [comment]
ci:reopen

**Comment by brbalazs** [comment]
ci:reopen

**Pull request closed without merging**
