### PR TITLE
LPD-29994 Refactor poshi test

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-29994

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]
LGTM, thank you!

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
