### PR TITLE
COMMERCE-10373 Remove old integration test

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-10373

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]
@dsitu can you please explain why we are removing this test? If it is only failing on Oracle, shouldn't we be fixing it on that instead?

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Comment by dsitu** [comment]
> @dsitu can you please explain why we are removing this test? If it is only failing on Oracle, shouldn't we be fixing it on that instead?

Removed based off the comment from Victor https://liferay.atlassian.net/browse/COMMERCE-10373?focusedCommentId=2468282. Looks like the test case was fixed in a new test, and the old one was added back in by accident during a merge conflict.

**Pull request closed without merging**
