### PR TITLE
Commerce 9765

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9765

resend of https://github.com/liferay-commerce/liferay-portal/pull/2976

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
@andrea-ale-sbarra  Forwarded here: https://github.com/liferay-commerce/liferay-portal/pull/2982

You can close this one, thanks!

**Pull request closed without merging**
