### PR TITLE
LPD-39651 - Refactor LocalFile.CountriesManagement#CanActivateCountriesInBulk into Playwright

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-39651

cc @smottal

### CODE REVIEW

**Comment by matyaswollner** [comment]
ci:test:sf

**Comment by matyaswollner** [comment]
ci:test:playwright:nocompile

**Comment by matyaswollner** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
