### PR TITLE
LPD-19907 Make sure correct format is returned for different databases.

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-19907

Hello @luca-pellizzon , tied to LPP. Discussed the solution with @CrescenzoRegaLF .

Solution is needed because we cannot insert boolean into ORACLE or MSSQL.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:report:2548591647

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
@luca-pellizzon , sorry I meant to forward another PR. Here's the test result: https://github.com/liferay-commerce/liferay-portal/pull/4750#issuecomment-1992805255

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
