### PR TITLE
LPD-37913 fix LocalFile.CommerceOrderSplitting#CanCreateTheActionUsingTheHealthCheck

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-37913

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
