### PR TITLE
Automated Test-COMMERCE-5807| master

### PR DESCRIPTION
**Pull request by CalumR23**
[COMMERCE-5807](https://issues.liferay.com/browse/COMMERCE-5807) @pietro69

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
ci:test:commerce-functional

**Comment by CalumR23** [comment]
Failures above are not related to testcase

**Comment by brittneyq** [comment]
Sent in [887](https://github.com/liferay-commerce/liferay-portal/pull/887). Please close, thank you!

**Pull request closed without merging**
