### PR TITLE
COMMERCE-12555 Fix related commerce shipment item related integration test

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12555

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
Integration tests failing are now passing

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
