### PR TITLE
Automated Tests - CPCommerceProductSKUs.testcase - combined PRs

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/COMMERCE-6021
https://issues.liferay.com/browse/COMMERCE-6022

cc:@pietro69 these tests should be ready for review!

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
SF failing due to `[java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./build.properties expected:<...ut,\
     [java]     #    apps/l[earn-taglib,\
     [java]     #    apps/l]icense-manager,\
     [java]    ...> but was:<...ut,\
     [java]     #    apps/l[]icense-manager,\
     [java]    ...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:454)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)`

Seems to be occurring in multiple ci:test:sf runs

**Comment by brittneyq** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
