### PR TITLE
COMMERCE-10360 Make sure the FDS can properly render when not initially visible in the product page

### PR DESCRIPTION
**Pull request by victoroscuro**
https://issues.liferay.com/browse/COMMERCE-10360

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
