### PR TITLE
COMMERCE-5801 commerce-product-test added placeholders for new functional tests

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-5801

This PR adds new functional test placeholders for the PIM component.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
@Pietro69 can you review this please?

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
