### PR TITLE
Automated Test - COMMERCE-6063 | master

### PR DESCRIPTION
**Pull request by ocesar9**

### CODE REVIEW

**Comment by c3saroliveira** [comment]
https://issues.liferay.com/browse/COMMERCE-6063, cc: @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@c3saroliveira Please fix formatting and resend. Thank you.

**Comment by c3saroliveira** [comment]
Changed to https://github.com/liferay-commerce/liferay-portal/pull/935

**Pull request closed without merging**
