### PR TITLE
COMMERCE-4052 Fix dependencies

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by petershin** [comment]
ci:test:stable

**Comment by jpince** [comment]
@petershin for https://github.com/liferay-commerce/liferay-portal/pull/44/commits/e3a9f1cdd381e8ebb420d052c04011d68e6caed6, the commerce-elasticsearch6/build.gradle file looks empty
```
dependencies {
	compileOnly group: "com.liferay.portal", name: "release.portal.api", version: "7.1.1"
	compileOnly group: "org.osgi", name: "org.osgi.core", version: "5.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
}
```

**Comment by marco-leo** [comment]
@jpince @petershin I think @dsitu removed that module in favor of es7. @dsitu is accurate?

**Comment by dsitu** [comment]
yeah, we should actually just remove that module(commerce-elasticsearch6).

**Comment by petershin** [comment]
Added a commit to bump up the versions.  Resent: https://github.com/liferay-commerce/liferay-portal/pull/47

**Pull request closed without merging**
