### PR TITLE
COMMERCE-6424 fix action command name

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
