### PR TITLE
Automated Test - COMMERCE-6230 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-6230, cc:@iovaneale

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class,'form-group')]//input[contains(@placeholder,'Name')]"

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1456

**Pull request closed without merging**
