### PR TITLE
COMMERCE-11472 same check regardless the list size

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-11472

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
QA passed. Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3767

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:stop

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
