### PR TITLE
Automated Test - COMMERCE-6329| master

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-6327; cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
GlobalSearchSearchProductsByCategories passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
