### PR TITLE
COMMERCE-4013 fix accept language

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@jbalsas
With this PR we align language header to match the standard.

Opening in liferay-commerce because it started from a Commerce bug.

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by jbalsas** [comment]
Hey @luca-pellizzon, looks reasonable to me... could you send it to @liferay-frontend when ready so the team (other than myself) can have a quick look and keep it in mind for the future?

It would be great if you could link to "the standard" and add some rationale in there for context.

Thanks!!

**Comment by luca-pellizzon** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/802

**Pull request closed without merging**
