### PR TITLE
COMMERCE-12944 Fix supplier role usages in commerce

### PR DESCRIPTION
**Pull request by riccardo-alberti**
resent from https://github.com/liferay-commerce/liferay-portal/pull/4486

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:um

**Comment by riccardo-alberti** [comment]
ci:test:stable

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Close this directly since the pr has been forwarded manually to BChan's repo, and already merged into master.
See https://github.com/brianchandotcom/liferay-portal/pull/144321

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
