### PR TITLE
LPD-27036 - Decimal quantity is not working in cart widget

### PR DESCRIPTION
**Pull request by victorcdp**
Issue: https://liferay.atlassian.net/browse/LPD-27036

@andrea-ale-sbarra Can you review this? Tied to an LPP. Thank you!

Commerce quantity tags should use BigDecimal instead of int now, since CommerceOrderItem uses BigDecimal for it's quantity, and UOM supports decimal numbers.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@victorcdp can you please add some automated test for this bug?

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:playwright

**Comment by victorcdp** [comment]
ci:test:playwright

**Comment by victorcdp** [comment]
ci:test:playwright

**Review by andrea-ale-sbarra — COMMENTED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
