### PR TITLE
LPD-22786 Fix iOS personal menu

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-22786

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

cc. @gianmarcobrunialti

**Pull request closed without merging**
