### PR TITLE
LPD-1288 User selector

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-1288

This solution fixes the selector problem for the OAuth 2 Application management UI.

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/4660

cc: @andrea-ale-sbarra @stian-sigvartsen

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:playwright

**Comment by smottal** [comment]
ci:report:2541598259

**Comment by smottal** [comment]
ci:report:2541598259

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
