### PR TITLE
COMMERCE-12633 CPPublisherPortlet can exist separately ...+Automation

### PR DESCRIPTION
**Pull request by baharturk**
Jira Ticket:
https://liferay.atlassian.net/browse/COMMERCE-12633

sent from: #4347

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
QA Review Done!

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by jaydawu** [comment]
PR was forwarded manually here: https://github.com/brianchandotcom/liferay-portal/pull/142963

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
