### PR TITLE
COMMERCE-4688 Replace help icon

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/COMMERCE-4688

image

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
