### PR TITLE
COMMERCE-9060

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9060

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci;test:sf

**Comment by luca-pellizzon** [comment]
@alessiorendina can you check this please? Thanks

**Comment by alessiorendina** [comment]
@luca-pellizzon It seems fine to me. Thank you!

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
