### PR TITLE
Automated Test - COMMERCE-6227 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6227 ; cc: @iovaneale

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by julioribeiiro** [comment]
Fixed

**Comment by JoMaAlves** [comment]
Noticed that 2 macros were duplicated and corrected it

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
