### PR TITLE
COMMERCE-11975 - Categories Admin Image selection navigates differently

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11975](https://liferay.atlassian.net/browse/COMMERCE-11975)

@andrea-ale-sbarra Can you review this one? Tied to an LPP. Thank you.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Pull request closed without merging**
