### PR TITLE
LPD-34906 Switching Accounts:- Breaking the Wish List UI

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/LPD-34906

### CODE REVIEW

**Review by alessiorendina — APPROVED** [review]
LGTM

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
@andrea-ale-sbarra Code looks good to me, but the PR is missing tests

**Comment by andrea-ale-sbarra** [comment]
ci.test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:playwright

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
