### PR TITLE
COMMERCE-10829 We need to use portletResourcePermission for correct p…

### PR DESCRIPTION
**Pull request by brianikim**
…ermission checks

https://issues.liferay.com/browse/COMMERCE-10829

@luca-pellizzon ,

We need to use _portletResourcePermission for all checks related to MANAGE_X_NOTES.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Pull request closed without merging**
