### PR TITLE
COMMERCE-8663, COMMERCE-8673, COMMERCE-8732 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-8663
https://issues.liferay.com/browse/COMMERCE-8673
https://issues.liferay.com/browse/COMMERCE-8732

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional:nocompile

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
