### PR TITLE
COMMERCE-12950 - Commerce Product description is displayed with HTML Tags in Paragraph Fragment

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-12950](https://liferay.atlassian.net/browse/COMMERCE-12950)

@andrea-ale-sbarra Can you review this one? Tied to an LPP. Thank you.
The Info Field Type for the Product Description was textInfo, making the html tags in the content be rendered as simple text by the Fragment. If we change the Info Field Type to HTML, it'll render the tags correctly.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:close

**Pull request closed without merging**
