### PR TITLE
COMMERCE-5326 Refactor PriceTag so it can be used anywhere and respond to DDMFormHandler

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevance

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
@alecsloan Sorry if I must have missed out on something but... why did we refactor the one in `commerce-taglib` rather than the one in `commerce-frontend-taglib`? Was this a requirement?

**Comment by alecsloan** [comment]
> @alecsloan Sorry if I must have missed out on something but... why did we refactor the one in `commerce-taglib` rather than the one in `commerce-frontend-taglib`? Was this a requirement?

The one in commerce-frontend-taglib was the soy one, whereas the commerce-taglib was an existing jsp one. If needed we can just move the refactored commerce-taglib one to commerce-frontend-taglib.

**Comment by gianmarcobrunialti** [comment]
@alecsloan Yeah, if you don't mind it'd be better to move it to commerce-frontend-taglib as that is going to be the only source of truth for our tags, where all the magic of conversions/refractors/rewrites is going to happen. The idea would then be to either to dismiss/clean-cut the others as soon as we're ready.

**Comment by alecsloan** [comment]
@gianmarcobrunialti sounds like a plan! The only usage of the old tag is in the productCard.soy which we can update when you're refactor for that is merged.

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:stop

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
