### PR TITLE
Draft discount on cheapest item

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
sent here https://github.com/andrea-ale-sbarra/liferay-portal/pull/35  to clean the repo

**Pull request closed without merging**
