### PR TITLE
LPD-30190 Refactor poshi test

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-30190

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:reopen

**Comment by smottal** [comment]
ci:report:31563137

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Pull request closed without merging**
