### PR TITLE
COMMERCE-11528 Store Front handling of Products Priced as Price on Application + Functional test

### PR DESCRIPTION
**Pull request by baharturk**
https://issues.liferay.com/browse/COMMERCE-11440

sent from #3808 with a functional test and locators

@smottal

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/3848

**Pull request closed without merging**
