### PR TITLE
(Resend) Organization Chart 4 - Permissions handling and refinements 

### PR DESCRIPTION
**Pull request by fabio-d-m**
Duplicated of https://github.com/brianchandotcom/liferay-portal/pull/106434

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Pull request closed without merging**
