### PR TITLE
LPD-25773 Fix poshi path

### PR DESCRIPTION
**Pull request by dsanz**
This is a draft PR to see how many commerce tests are affected

### CODE REVIEW

**Comment by dsanz** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
i'm gonna merge this. Even if the tests are not passing on CI i see locally that it works.

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
thanks a lot @dsanz

**Pull request closed without merging**
