### PR TITLE
LPS-200028 Removes unnecessary classes and change the frontend-data-set to fluid to match with other control menu apps

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Make applications consistent around control panel.

[Link to the ticket](https://liferay.atlassian.net/browse/LPS-200028)

Proposed Solution
-----
Removes no needed css classes and change frontend-data-set to fluid to make management toolbar looks match with other applications.

Before changes:
Price_Lists_-_Liferay_DXP

After changes:
Price_Lists_-_Liferay_DXP

Please let me know if you have any question.

### CODE REVIEW

**Review by andrea-ale-sbarra — COMMENTED** [review]
LGTM.
Thank you!

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by ealonso** [comment]
Hey @victoroscuro,

Can we forward this one? Or should we execute test suites again?

**Comment by victoroscuro** [comment]
Hey @ealonso failures on both commerce-functional and relevant seem not to be related to the code of this PR. This is good to go. Thanks

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
