### PR TITLE
COMMERCE-5392 Manage cart endopoint permissions for guest user

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by dsitu — CHANGES_REQUESTED** [review]
@luca-pellizzon view changes requested by bchan from here, https://github.com/brianchandotcom/liferay-portal/pull/98167.
I removed NotNull annotations here https://github.com/liferay-commerce/liferay-portal/pull/573.

**Comment by luca-pellizzon** [comment]
@dsitu do you know the reason why BChan say the class CommerceServiceAccessPolicyHealthHttpStatus has a wrong class name and the wrong package?
It looks fine to me. It is in the same package of others system health checks

**Comment by dsitu** [comment]
@luca-pellizzon I think he wants the package path to follow the class that it is implementing `CommerceHealthHttpStatus`. So it would be something like `com.liferay.commerce.health.status.web.internal.health.status;`. We would want to update the other exiting classes also.

**Comment by riccardo-alberti** [comment]
waiting for #573 to be merged

**Comment by luca-pellizzon** [comment]
@dsitu rebased on top of master with your changes regarding NotNull annotations.
Also changed the package name for all health check classes and fixed the name of the new one.
Please check it again.
Thank you.

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
