### PR TITLE
COMMERCE-9800 - It's not possible to add a sample URL if the file is selected and then removed

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-9800](https://issues.liferay.com/browse/COMMERCE-9800)
@brianikim

The problem was that the check was using setAttribute to change the "disabled" html attribute, instead of deleting it.
Proposed fix is to use removeAttribute instead, as the "disabled" attribute is always active, even if you set it to something other than "true"

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@andrea-ale-sbarra , this one needs your review.

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by Brunno0liveira** [comment]
Resent at: https://github.com/liferay-commerce/liferay-portal/pull/4076

Thanks!

**Pull request closed without merging**
