### PR TITLE
Automated Test - COMMERCE-6280 | master

### PR DESCRIPTION
**Pull request by ocesar9**

### CODE REVIEW

**Comment by c3saroliveira** [comment]
https://issues.liferay.com/browse/COMMERCE-6280, cc: @pietro69

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
RemoveAnOption passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
