### PR TITLE
LPD-17011 - UM failing test

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-17011

[openMySitesModal](https://github.com/liferay/liferay-portal/commit/b096ec56f72e9b76920fb863ffe2115d832af76b#diff-9464b70403415c3223a77ed67ac8ce5d112aca21f8b26a55a3c41fc239e7d7d0R8) needs to match [mySitesOpener](https://github.com/liferay/liferay-portal/commit/b096ec56f72e9b76920fb863ffe2115d832af76b#diff-1a05dfe045bbc7d2b86b47376f271d7da26ab749170944c178069953093cc16bR100).

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]
It's ok for me. Thx

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by smottal** [comment]
Hi @ethib137 , could you please verify the test LocalFile.SitesExportImportWithStaging#ImportLiveSiteToStagingSite? Because seems to be unique for this PR. Thx

**Comment by ethib137** [comment]
Hey @smottal it looks like that's just a flaky test. The change isn't related to it and the previous relevant test against this PR [passed that test](https://testray.liferay.com/home/-/testray/case_results/2538077258?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2538076918%26testrayRunId%3D2538077008%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc).

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
