### PR TITLE
Automated Test - COMMERCE-6270 | master

### PR DESCRIPTION
**Pull request by IsaVV**

### CODE REVIEW

**Comment by IsaVV** [comment]
fixing https://github.com/liferay-commerce/liferay-portal/pull/1168

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@IsaVV This is failing at source formatting. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
[exec] 2021-06-30 01:12:55.243 ERROR [http-nio-8080-exec-2][PortletServlet:119] javax.portlet.PortletException: java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=20100, name=com.liferay.commerce.notification, primKey=41944, scope=4}
     [exec] javax.portlet.PortletException: java.lang.IllegalArgumentException: Someone may be trying to circumvent the permission checker: {companyId=20100, name=com.liferay.commerce.notification, primKey=41944, scope=4}

**Pull request closed without merging**
