### PR TITLE
COMMERCE-11393 Use com.ibm.icu.text.DecimalFormat instead to better s…

### PR DESCRIPTION
**Pull request by brianikim**
…upport currency patterns

@luca-pellizzon , tied to a LPP.

https://issues.liferay.com/browse/COMMERCE-11393

Straightforward PR. The solution was simpler than expected. I did some basic edge-case testing to confirm it worked.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Hi @brianikim, There is an integration test failed only on this PR. Could you please check it out? Does it relate to this PR? Thanks in advance!
[com.liferay.headless.commerce.admin.order.resource.v1_0.test.OrderResourceTest](https://testray.liferay.com/home/-/testray/case_results/2291356078?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2291347632%26testrayRunId%3D2291351520%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) | [Jenkins Console](https://testray.liferay.com/reports/production/logs/2023-05/test-1-32/test-portal-acceptance-pullrequest(master)/9354/modules-integration-mysql57-jdk8/0/12/jenkins-console.txt.gz?authuser=0)
```
     [exec] com.liferay.headless.commerce.admin.order.resource.v1_0.test.OrderResourceTest > testDeleteOrder FAILED
     [exec]     com.liferay.headless.commerce.admin.order.client.problem.Problem$ProblemException: Unquoted special character '8' in pattern "4OKDB8iO"
     [exec]     	at com.liferay.headless.commerce.admin.order.client.resource.v1_0.OrderResource$OrderResourceImpl.postOrder(OrderResource.java:494)
     [exec]     	at com.liferay.headless.commerce.admin.order.resource.v1_0.test.OrderResourceTest.testDeleteOrder_addOrder(OrderResourceTest.java:318)
     [exec]     	at com.liferay.headless.commerce.admin.order.resource.v1_0.test.BaseOrderResourceTestCase.testDeleteOrder(BaseOrderResourceTestCase.java:705)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by brianikim** [comment]
Hi @jaydawu , 

I ran the test locally. They are reproducible without my fix either.

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Thanks @brianikim
Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3736

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
