### PR TITLE
COMMERCE-12979

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-12979

1. First commit addresses issue 1 described in COMMERCE-12979.
2. Second commit addresses issue 2 described in COMMERCE-12979. Commit implementation was discussed with the IPT Member of the Search Team. From the search team perspective, if the sub facet terms do not exist, there is no reason to display the parent facet. The commit is reflective of their input.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Resent on https://github.com/liferay-commerce/liferay-portal/pull/4557

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
