### PR TITLE
COMMERCE-9794 Refactor to fit correct naming scheme for commerce_orde…

### PR DESCRIPTION
**Pull request by brianikim**
…r_item/*

https://issues.liferay.com/browse/COMMERCE-9794

@luca-pellizzon , this could probably be forwarded with minimal QA testing.

Altered PR for BChan's request from here: https://github.com/brianchandotcom/liferay-portal/pull/132715#issuecomment-1493447696

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by Brunno0liveira** [comment]
Hi @brianikim can you please close this PR

I have sent a new one at https://github.com/liferay-commerce/liferay-portal/pull/3623

**Pull request closed without merging**
