### PR TITLE
Automated Test - COMMERCE-5708 | master 

### PR DESCRIPTION
**Pull request by zmmarina**

### CODE REVIEW

**Comment by zmmarina** [comment]
https://issues.liferay.com/browse/COMMERCE-5708
cc: @riccardo-alberti

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
@zmmarina This PR has unrelated file changes including jar files. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Hi @zmmarina, it looks like the file changed from CommerceWarehouses to CPCommerceWarehouses. Please move the test and resend. Thank you!

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
@zmmarina, could you please source format and push? Thank you!

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @zmmarina, I tried testing your test locally but it fails because it seems like your test is referencing macros that are not in the CommerceEntry.path file. I noticed you pushed your Account.path file but did you mean to add your CommerceEntry.path file instead? Could you take a look at this and add the appropriate paths? Thank you!

**Comment by zmmarina** [comment]
Hi @brittneyq Fixed :)

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Made changes and sent in [944](https://github.com/liferay-commerce/liferay-portal/pull/944)

**Pull request closed without merging**
