### PR TITLE
Automated Test - COMMERCE-6354 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6354 , cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//div[@id='ggzi_column1_0_add_to_wish_list']"

**Comment by JoMaAlves** [comment]
> Element is not present at "//div[@id='ggzi_column1_0_add_to_wish_list']"

Fixed!

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
Solved conflict

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//td[contains(@class,'table-cell-expand') and contains(.,'U-Joint')]"

**Comment by JoMaAlves** [comment]
Rebased and checked if it was working

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
