### PR TITLE
LPD-18699   Remove FT | LocalFile.CPCommerceChannels#AddShippingOptionFedEx

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-18699

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
