### PR TITLE
COMMERCE-4693 Dropdown button is secondary

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/COMMERCE-4693

image

### CODE REVIEW

**Comment by carloslancha** [comment]
@jbalsas we could update this to use `clay:dropdown` tag but for that we need to add support to place the trigger icon at the right side of the label. Doing that we could get rid of adding a couple of custom event handlers via `document.querySelector` and replace it with a `propsTransformer`.

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
