### PR TITLE
LPS-197276 Escape redirect

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPS-197276

@smottal ,

Straight-forward PR to fix security issue. Assigned to you as USM/Accounts is owned by you now.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]
LGTM! Thanks

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR. @victoroscuro can you please force-forward this PR? Thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
