### PR TITLE
LPD-29981 aui:option label escaped twice

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
Hello @gianmarcobrunialti,

Can you or the team take a look at this?
Thank you for your help!

> FWD: https://github.com/liferay-commerce/liferay-portal/pull/5189
> FWD: https://github.com/liferay-frontend/liferay-portal/pull/4326
> 
> https://liferay.atlassian.net/browse/LPD-29981
> 
> The label within aui:option was being escaped twice and resulting in incorrect labels.
> 
> The double escape was introduced in https://liferay.atlassian.net/browse/LPS-185312 with this commit https://github.com/liferay-frontend/liferay-portal/pull/3578/files adding the escape to true.
> 
> I looked for aui:option with HtmlUtil.escape for the label and removed it so it would not get escaped twice.
> 
> I provided playwright test for user's custom fields and would like a review for this.
> Please let me know if there are any questions or comments about this.
> 
> Thank you for the help!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @liferay-commerce 

The failures here seem to be unrelated the changes.
Can I get an ETA on when this PR can be reviewed? Mainly the playwright tests.

Thank you for all your help!

**Comment by fortunatomaldonado** [comment]
Hello @gianmarcobrunialti 

I assumed that this would affect all aui:option labels that were being escaped and so removed them.

If you are saying that this is not the case, I will revert the changes and only make the change that I know is affect which is expando-taglib.

Thank you for taking a look at this!

**Comment by gianmarcobrunialti** [comment]
Hey @fortunatomaldonado, I did not say it's not the case, I said I dug into the code of the Tags in use and couldn't find local escapings so I wondered whether this change was a removal of an actual double escaping as you mentioned in the title. Do you have a screenshot that shows the double escaping? 

I'll run our functional tests, if you could visually/manually validate that the change is fine, that'll be good as well. 👍🏼

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by fortunatomaldonado** [comment]
Hello @gianmarcobrunialti 

I have attached a video of the double escape in Custom Fields
[Screencast from 09-20-2024 11:26:27 AM.webm](https://github.com/user-attachments/assets/395e741e-0cc0-41e1-95fc-81be31866d2b)

Let me know if I am still misunderstanding and I'll try to get the correct information.

Also the playwright test is failing due to a conflict so I will go ahead and make the changes.

**Comment by fortunatomaldonado** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
Hello @fortunatomaldonado, any follow-up's on this PR? Thanks!

**Comment by fortunatomaldonado** [comment]
Hello @gianmarcobrunialti 
In this comment, I showed the Custom Fields being double escaped: https://github.com/liferay-commerce/liferay-portal/pull/5358#issuecomment-2364190620

Let me know if this is what you are asking or if I am misunderstanding.
Thank you!

**Comment by MarioArb85** [comment]
Hi @gianmarcobrunialti ! have you had a chance to review the last comment from Fortunato?

**Comment by gianmarcobrunialti** [comment]
Hello @MarioArb85 and @fortunatomaldonado, the example is sound but outside of Commerce. For the time being I'd leave out those modules and move forward with this PR. Thanks!

**Comment by fortunatomaldonado** [comment]
@gianmarcobrunialti, truly appreciate your input on this, thank you!

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
@gianmarcobrunialti, I removed the other modules and only have the expando-taglib with user-admin-web playwright tests

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Pull request closed without merging**
