### PR TITLE
LPD-22400 Fixed poshi test

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/LPD-22400

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:report:2568414756

**Comment by andrea-ale-sbarra** [comment]
Test passed https://testray.liferay.com/home/-/testray/case_results/2568416535?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DCanBuyerEditProductOptionsOnThePendingOrder%26testrayBuildId%3D2568414756%26testrayRunId%3D2568414792%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
