### PR TITLE
COMMERCE-9459 | Shipments - Link to carrier based tracking

### PR DESCRIPTION
**Pull request by alessiorendina**
DEV: https://issues.liferay.com/browse/COMMERCE-9459

QA: https://issues.liferay.com/browse/COMMERCE-9671

Base PR: #2883

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:forward

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
