### PR TITLE
Lpd 27148

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-27148

@luca-pellizzon , implemented search team's recommendation to handle situations where ` indices.query.bool.max_clause_count ` for ElasticSearch can be overloaded by having more than 1024 accounts assigned to one user (Each account adds a separate boolean clause).

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@luca-pellizzon , restarting CI. Checked locally that tests pass.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Pull request closed without merging**
