### PR TITLE
COMMERCE-11913 - Pagination is not correct on order details page

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11913](https://liferay.atlassian.net/browse/COMMERCE-11913)

@luca-pellizzon Can you review this one? Tied to an LPP. Thank you.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by jaydawu** [comment]
QA passed, add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3995

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
