### PR TITLE
COMMERCE-11837 - Products with Specification generate a 500 Status Error

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11837](https://liferay.atlassian.net/browse/COMMERCE-11837)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
@andrea-ale-sbarra Can you review this one? It's tied to an LPP. Thank you!

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@andrea-ale-sbarra , tied to LPP.

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM, Thank you!

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
@victoroscuro waiting for new CI results

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
Issues are not related to the changes, PR can be forward

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
