### PR TITLE
Automated Test - COMMERCE-6216 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-6216, CC: @iovaneale

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Expected to find an object with property ['items'] in path $ but found 'java.lang.String'. This is not a json object according to the JsonProvider: 'com.jayway.jsonpath.spi.json.JsonSmartJsonProvider'.

**Comment by p-albuquerque** [comment]
Fixed.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
