### PR TITLE
COMMERCE-11276 Price on Application on Price Lists & Promotions

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-11276
Base PR: https://github.com/liferay-commerce/liferay-portal/pull/3841, https://github.com/liferay-commerce/liferay-portal/pull/3872 and https://github.com/liferay-commerce/liferay-portal/pull/3882

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
The SF issue should not be caused by this pull. Maybe it's related to this [one](https://github.com/liferay/liferay-portal/commit/c895015249069f40f2b12549cb73e53b334fe7de).

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by smottal** [comment]
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/3889

**Pull request closed without merging**
