### PR TITLE
COMMERCE-12026 Chain of replacement SKUs doesn’t work+functional test

### PR DESCRIPTION
**Pull request by saramart81**
Sent from #4343
https://liferay.atlassian.net/browse/COMMERCE-12026

### CODE REVIEW

**Comment by saramart81** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
QA Review Passed

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @saramart81, since a couple of functional tests didn't run on CI, we'd like to ensure they can be run all the time, so I rerun the suite, please check again the results when it comes out, thank you!

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:test:stable

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by saramart81** [comment]
forwarded manually to BChan

**Pull request closed without merging**
