### PR TITLE
COMMERCE-11975 - Categories Admin Image selection navigates differently

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #4036 

https://liferay.atlassian.net/browse/COMMERCE-11975

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:reevaluate:1297401_7747

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to this PR, this can be force forwarded

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
