### PR TITLE
COMMERCE-10036 Check whether Object is ObjectEntry type

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10036

@andrea-ale-sbarra ,

Marco missed the implementation that he already made in : https://github.com/brianchandotcom/liferay-portal/commit/0c452486b82bfde33e6e71a90a8b686c06191163

https://github.com/liferay-commerce/liferay-portal/blob/8faee93338fc2807062c1a76735cb71a7a42a0ef/modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/order/term/contributor/ObjectCommerceDefinitionTermContributor.java#L71

Solution just implements the correct check.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
