### PR TITLE
COMMERCE-10966 Use resourcePermission.check() instead of contains()

### PR DESCRIPTION
**Pull request by julschong**

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:sf

**Comment by julschong** [comment]
ci:test:relevant

**Comment by julschong** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by julschong** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/131620

**Comment by julschong** [comment]
@Kvale1733 Hi Kevin, could you please help me scan this PR? Thanks!

**Comment by julschong** [comment]
Hi Kevin @Kvale1733, could you please help me scan this test result?

**Comment by Kvale1733** [comment]
@julschong Regression in

com.liferay.commerce.order.engine.test.CommerceOrderEngineTest
```
[exec] com.liferay.commerce.order.engine.test.CommerceOrderEngineTest > testAutomaticallyTransitionOrderToCompleted FAILED
     [exec]     java.lang.AssertionError: 
     [exec]     [
     [exec]     SCENARIO Use the Order Engine to checkout an Order, transition it to processing then create a shipment with all of the order items and mark that shipment as delivered
     [exec]     GIVEN An Open Order that has an order item
     [exec]      AND A user who has checkout permissions
     [exec]     WHEN We create a shipment with the only order item and deliver it
     [exec]     THEN The order should automatically be transitioned to Completed
     [exec]     ]
     [exec]     [
     [exec]     Message: expected:<0> but was:<10>
     [exec]     ]
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.commerce.order.engine.test.CommerceOrderEngineTest.testAutomaticallyTransitionOrderToCompleted(CommerceOrderEngineTest.java:230)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Me
```
[Log](https://testray.liferay.com/reports/production/logs/2023-03/test-1-37/test-portal-acceptance-pullrequest(master)/9673/modules-integration-mysql57-jdk8/0/9/jenkins-console.txt.gz?authuser=0)

**Comment by julschong** [comment]
@luca-pellizzon 
Hi Luca, I tried to fix the integration test by adding the MANAGE_COMMERCE_SHIPMENTS permission to user but I could not make it work after many tries. Could you please help take a look at this?
Thank you

**Comment by luca-pellizzon** [comment]
The issue is coming from com.liferay.commerce.service.impl.CommerceShipmentLocalServiceImpl#sendShipmentStatusMessage
when it tries to access commerceShipmentDTOConverter.toDTO(......) in here we get to
_commerceShipmentService.getCommerceShipment((Long)dtoConverterContext.getId());
that checks permission (now with your fix in the proper way)
So as long as the permission checker that is active in that moment has the permission everything should work as expected.
Probably the permission was not set properly, this is a PortletResourcePermission.

cc @riccardo-alberti

**Pull request closed without merging**
