### PR TITLE
COMMERCE-12736 whitelisted getProduct endpoint

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12736

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by juliocezar96** [comment]
Just starting reviewing :)

**Review by alessiorendina — APPROVED** [review]

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
