### PR TITLE
COMMERCE-9390 InfoItemCollectionProvider for Related Products

### PR DESCRIPTION
**Pull request by lorenzolapescara**
Ticket: https://issues.liferay.com/browse/COMMERCE-9390

Re-sent from #3550 

cc @alessiorendina @victoroscuro

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:test:forward

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
