### PR TITLE
COMMERCE-11836 Price on Application should be considered as the "highest price"

### PR DESCRIPTION
**Pull request by riccardo-alberti**
https://liferay.atlassian.net/browse/COMMERCE-11836

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Pull request closed without merging**
