### PR TITLE
LPD-26213 Fix preload order addresses

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-26213

There is no a specific test for the fix because there is already an existing test (LocalFile.CommerceAddressesEligibility#CanUseEligibleAddressesOnCheckoutWithAccountDefault) that is failing due to this bug

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:report:2570488164

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
ci:report:2571375745

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
