### PR TITLE
Lpd 22571 expedite service

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/LPD-22571

### CODE REVIEW

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
LGTM! Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
