### PR TITLE
COMMERCE-5837 PriceTag component now handles product options change via DDMForm in FS 

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
The following introduces a slightly new update mechanism for the Price component in the FS Product detail page, upon changing the product options. The Price component now is rendered in 2 different ways (server-side via JSP and client-side via React).

The reason for this is that while in the Catalog and in the Product Detail (for SEO purposes) we always need SSR, once the user lands on the Product Detail page he can interact with it, SEO purposes can then be contextually dropped, and having the same update mechanism as we have in other React components looks like a neater and reusable solution.

The presentational logic for prices within the JSP templates and the React component are now equivalent and we'll have to maintain them in parallel. The React Price component is also used by the MiniCart component, with the same templating rules, but more compact styling.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Pull request closed without merging**
