### PR TITLE
Automated Test - COMMERCE-6276 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/COMMERCE-6276, cc: @pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1313. Please close @kristinonias

**Pull request closed without merging**
