### PR TITLE
Commerce 5019 wildfly option fix

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Showing code below the priority field while adding image/attachments for a product under media, there was a DDMForm js error that prevented the html tags to close properly

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by marco-leo — APPROVED** [review]

**Review by marco-leo — CHANGES_REQUESTED** [review]
avoid version change in pazkage and deprecate old method

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
packageinfo version change is happening because the old method is not used anymore, so I believe the baseLine tool would like to delete it..

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1092004_4268

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:test:relevant
Couldn't reproduce the error, retesting.

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
