### PR TITLE
LPS-135340 SF Rename String getCreateDate to String getCreateDateString

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/LPS-135340

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
