### PR TITLE
LPD-26142 Migrate POSHI test

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-26142

Removed poshi GuestCheckout#GuestAccountIsNotCombinedWithExistingUserAccount and GuestCheckout#AssertNewAccountIsCreatedAfterGuestCheckout

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
