### PR TITLE
COMMERCE-4957 Refactored AddToCart (Button + Wrapper with QuantitySelector)

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
The new AddToCart components suite also includes the correlated unit test suites.

Test coverage
image

To be rebased and forwarded after https://github.com/liferay-commerce/liferay-portal/pull/422

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
This is now up-to-date with the latest Commerce FE changes, yet on top of BChan's base. Will give it a final rebase against upstream once those changes are in and liferay-commerce gets updated as well.

**Comment by gianmarcobrunialti** [comment]
Sent here: https://github.com/liferay-commerce/liferay-portal/pull/461

**Pull request closed without merging**
