### PR TITLE
Commerce 9224

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9224

resend of this https://github.com/liferay-commerce/liferay-portal/pull/2819

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test.sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
@andrea-ale-sbarra this passed the QA Check. I'll resend the PR together with the fixes for the functional tests. Can you close this one? Thanks!

**Comment by lorenzolapescara** [comment]
Resent here: #2924

**Pull request closed without merging**
