### PR TITLE
COMMERCE-5541 upgrade dependency for vulnerability

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Review by riccardo-alberti — APPROVED** [review]

**Review by riccardo-ferrari — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:foward

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
