### PR TITLE
COMMERCE-12433 OrgChart View/Edit Panel - User + Automation

### PR DESCRIPTION
**Pull request by baharturk**
User Story: https://liferay.atlassian.net/browse/COMMERCE-12433

Testplan: https://liferay.atlassian.net/browse/COMMERCE-12872

sent from: #4419 

@smottal

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
Review done!

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:stable

**Comment by baharturk** [comment]
ci:test:stable

**Comment by smottal** [comment]
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/4474

**Pull request closed without merging**
