### PR TITLE
COMMERCE-5533 Add workaround tests for bypassing upstream browser's resolution issue

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-5533

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:stop

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by brianchandotcom** [comment]
ci:close @ivicac merged

**Pull request closed without merging**
