### PR TITLE
COMMERCE-9409

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/COMMERCE-9409

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by luca-pellizzon — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by alessiorendina — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:bundle

**Comment by jaydawu** [comment]
QA passed, resent on https://github.com/liferay-commerce/liferay-portal/pull/4266.

**Comment by jaydawu** [comment]
ci:close

**Comment by jaydawu** [comment]
ci:reopen

**Comment by jaydawu** [comment]
Sorry @CrescenzoRegaLF, due to the functional tests catching a problem, it needs you to take a fix, thanks! Please refer to the [comment](https://liferay.atlassian.net/browse/COMMERCE-9409?focusedCommentId=2470748) here, thanks!

**Comment by CrescenzoRegaLF** [comment]
Hi @jaydawu I updated the pr with the fix

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
The issues are not related to the changes, PR can be forward

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by CrescenzoRegaLF** [comment]
resend this
https://github.com/brianchandotcom/liferay-portal/pull/141552

**Pull request closed without merging**
