### PR TITLE
Automated Test - COMMERCE-5802 | master

### PR DESCRIPTION
**Pull request by MoryAlvesBR**

### CODE REVIEW

**Comment by MoryAlvesBR** [comment]
https://issues.liferay.com/browse/COMMERCE-5802, cc: @pietro.bocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Pull request closed without merging**
