### PR TITLE
LPD-33423 Fix JS path

### PR DESCRIPTION
**Pull request by brianikim**
@smottal ,

https://liferay.atlassian.net/browse/LPD-33423, tied to LPP

Test should not be needed since we are just updating file path that was not done as part of https://liferay.atlassian.net/browse/LPD-17434 : https://github.com/brianchandotcom/liferay-portal/pull/147323/commits/dca4ea5f0eef6ff85825ed2b21775ad06dd31a51

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
