### PR TITLE
COMMERCE-11365 Automated functional tests for COMMERCE-10840 1/2

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-11365

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
Review Passed

**Review by pietrobocale — APPROVED** [review]

**Pull request closed without merging**
