### PR TITLE
COMMERCE-4719 Make Commerce functional tests work on master

### PR DESCRIPTION
**Pull request by lorenzolapescara**

### CODE REVIEW

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Review by dsitu — APPROVED** [review]

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
Forwarded to #234

**Pull request closed without merging**
