### PR TITLE
COMMERCE-11492 Drop DDM 5/5 - Clean up

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/COMMERCE-11492

from #4109

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
Re-sent at #4141

**Comment by lorenzolapescara** [comment]
ci:close

**Pull request closed without merging**
