### PR TITLE
COMMERCE-6456 edit fields don't use localized values

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
