### PR TITLE
COMMERCE-11745

### PR DESCRIPTION
**Pull request by brianikim**
@luca-pellizzon ,

https://liferay.atlassian.net/browse/COMMERCE-11745

Added JS Support for both PriceTag and AddToCartTag so that they can be utilized by: https://liferay.atlassian.net/browse/COMMERCE-11662

Quantity support for both PriceTag and AddToCartTag is not complete. 

Both are dependent on https://liferay.atlassian.net/browse/COMMERCE-11656, specifically we need `Base Unit of Quantity`to fulfill criteria:
```
Increasing or decreasing the quantity using the arrows increases/decreases by the Base Unit of Quantity
```

Let me know if I missed anything in my implementation.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
@brianikim please rebase this

**Comment by brianikim** [comment]
hi @CrescenzoRegaLF , updated as requested.

**Comment by CrescenzoRegaLF** [comment]
@brianikim could you rebase, thanks

**Pull request closed without merging**
