### PR TITLE
LPD-34378 - Email Address api

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-34378

Resent from https://github.com/brianchandotcom/liferay-portal/pull/154287 to improve the BaseExternalReferenceCodeUpgradeProcessTestCase

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:18756921

**Comment by smottal** [comment]
ci:report:18775492

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:upgrade

**Comment by smottal** [comment]
ci:report:18798144

**Comment by smottal** [comment]
ci:report:18790541

**Comment by matyaswollner** [comment]
ci:report:18798144

**Comment by matyaswollner** [comment]
ci:report:18790541

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
