### PR TITLE
COMMERCE-9700 | COMMERCE-9703 Default account address and terms per channel

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-9700

https://issues.liferay.com/browse/COMMERCE-9703

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Based on #2950

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Forwarded here #2964

**Pull request closed without merging**
