### PR TITLE
COMMERCE-6784 Fixed product publisher URL to include pagination information.

### PR DESCRIPTION
**Pull request by brianikim**
cc/ @ivicac .

1. The "work-around" provided in COMMERCE-6785 needs to be merged into Master even if we are going to pursue a different solution. The reason for this is because we have consistently provided COMMERCE-6785 to 7.3.x customers who are actively utilizing the fix in their PROD environments. I have already confirmed COMMERCE-6785 works as expected in Master. If given the okay, we should go ahead with merging COMMERCE-6785 in Master and allow CIFA to use it while we pursue a more definitive solution. Note that from Minhchau's (and basically Support) perspective, the merge must be done because this ensures clean back-port + hot-fixes for future customers who receive the "new" hot-fix with the potential updated solution.
2. We cannot pursue the solution that Minhchau suggested in LPP-41100. We only care that it has a product details and/or product publisher portlet to construct our URLs. We cannot pursue the solution from LPP-41100 as that is layout dependent.
3. Minhchau has suggested to me a different solution that I am currently in the process of trying to implement. This is currently a WIP which requires communication with the Core Infrastructure team. For now, COMMERCE-6784 needs to be merged.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
