### PR TITLE
COMMERCE-9047 Remove ServiceContextThreadLocal

### PR DESCRIPTION
**Pull request by smottal**
Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3594 for conflicts

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
