### PR TITLE
COMMERCE-6678

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-6678

@riccardo-alberti , you need to review this one specifically because you introduced the fix for SAPPHIRE. They are requesting this one to be introduced in Master, but I see that you did not commit it.

Let me know if this is something we want to commit.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
