### PR TITLE
LPD-33967 Delivery endpoint to get the Carts page

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-33967

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/5324

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]
LGTM, thank you!

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:stable

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
