### PR TITLE
LPD-43700 fix tests

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-43700

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:report:85814596

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
