### PR TITLE
COMMERCE-11152 SKU Virtual Settings

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11152

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3645

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:forward

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:forward

**Comment by pietrobocale** [comment]
ci:stop

**Comment by pietrobocale** [comment]
ci:forward

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
