### PR TITLE
COMMERCE-10454

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-10454

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:close

**Comment by andrea-ale-sbarra** [comment]
sent here https://github.com/liferay-commerce/liferay-portal/pull/3441

**Pull request closed without merging**
