### PR TITLE
COMMERCE-4835 Can't add a SKU to a price list or sale price list or option value by searching by SKU

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
close this one and open https://github.com/liferay-commerce/liferay-portal/pull/421

**Pull request closed without merging**
