### PR TITLE
COMMERCE-8979 Require options even when there are no values

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-8979

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — COMMENTED** [review]
Ehi @dsitu I don't think this is the right solution. I believe that the right fix is to change how Options are created. Those options that have a choice must have at least 2 values otherwise there is no use for those option

**Comment by andrea-ale-sbarra** [comment]
I'll report this on the bug and will address this issue in a proper way

**Pull request closed without merging**
