### PR TITLE
Automated Test - COMMERCE-6068 | master

### PR DESCRIPTION
**Pull request by Jamersonze**

### CODE REVIEW

**Comment by Jamersonze** [comment]
https://issues.liferay.com/browse/COMMERCE-6068, cc: @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@Jamersonze 

This pull request has a conflicting file CPCommerceProductProductGroups.testcase. Please fix and resend.

**Comment by Jamersonze** [comment]
Fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
