### PR TITLE
COMMERCE-10008 Remove search and pagination from the data-sets in the Account's Channel Defaults

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10008

Resent from https://github.com/liferay-commerce/liferay-portal/pull/3566

@22LucaGiannotta22

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Review by riccardo-alberti — COMMENTED** [review]
@CrescenzoRegaLF why are we taking the list of channels from the generic channel service?

**Comment by CrescenzoRegaLF** [comment]
> @CrescenzoRegaLF why are we taking the list of channels from the generic channel service?

As with SHIPPING OPTIONS, the PAYMENT METHODS count depends on the number of channels.
In Channel Defaults the PAYMENT METHODS table shows one row for each channel as for the SHIPPING OPTIONS table.
Before my modification the PAYMENT METHODS count was not shown correctly

@riccardo-alberti

**Review by riccardo-alberti — APPROVED** [review]

**Pull request closed without merging**
