### PR TITLE
LPS-127421 Commerce Info Panels should extend to bottom of window

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-127421

Let me know if I missed anything in Commerce.

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
@andrea-ale-sbarra is this PR still needed? If not please close

**Comment by andrea-ale-sbarra** [comment]
@riccardo-alberti I don't know, I think we should do some test on this

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
Already sent here https://github.com/liferay-frontend/liferay-portal/pull/779

**Pull request closed without merging**
