### PR TITLE
Automated Test - COMMERCE-5808 | master

### PR DESCRIPTION
**Pull request by juliaduartelira**

### CODE REVIEW

**Comment by juliaduartelira** [comment]
https://issues.liferay.com/browse/COMMERCE-5808, cc: @pietro.bocale

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @juliaduartelira can you remove the @ignore = true on your test and also rename your PR to Automated Test in the title? Thank you! :D

**Comment by juliaduartelira** [comment]
Hi @brittneyq, I've just done the adjustments. Thank you! :)

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
Sent in [887](https://github.com/liferay-commerce/liferay-portal/pull/887). Please close, thank you!

**Pull request closed without merging**
