### PR TITLE
LPD-27598 - Fixed broken poshi test AppManagement#AppShouldNotBeNestedWithinItself

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-27598

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:stop

**Comment by brbalazs** [comment]
ci:test:sf:stop

**Comment by smottal** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
