### PR TITLE
COMMERCE-11747 Add support for UoM to dataset DTOs

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-11747

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:forward:force

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by smottal** [comment]
Sent directly here: https://github.com/brianchandotcom/liferay-portal/pull/140465

**Pull request closed without merging**
