### PR TITLE
COMMERCE-11511 - Create date is not visible inside Product Relations

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11511](https://issues.liferay.com/browse/COMMERCE-11511)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:Sf

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automated test and resent on https://github.com/liferay-commerce/liferay-portal/pull/3797

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
