### PR TITLE
LPD-39812 Create separated test modules for commerce playwright tests

### PR DESCRIPTION
**Pull request by michelevigilante**
https://liferay.atlassian.net/browse/LPD-39812

cc @smottal

### CODE REVIEW

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:relevant

**Comment by michelevigilante** [comment]
ci:test:commerce

**Comment by michelevigilante** [comment]
ci:test:playwright:nocompile

**Comment by michelevigilante** [comment]
ci:report:48717332

**Comment by michelevigilante** [comment]
ci:report:48717329

**Comment by michelevigilante** [comment]
ci:test:relevant

**Comment by michelevigilante** [comment]
ci:test:playwright:nocompile

**Comment by michelevigilante** [comment]
ci:test:commerce

**Review by smottal — CHANGES_REQUESTED** [review]

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:playwright:nocompile

**Comment by michelevigilante** [comment]
ci:test:commerce

**Comment by michelevigilante** [comment]
ci:test:playwright:nocompile

**Comment by michelevigilante** [comment]
ci:test:playwright:nocompile

**Comment by michelevigilante** [comment]
ci:stop

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:report:50298288

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
