### PR TITLE
COMMERCE-8070

### PR DESCRIPTION
**Pull request by brianikim**
@riccardo-alberti ,

https://issues.liferay.com/browse/COMMERCE-8070

This one needs to be merged asap because all our upgrades to 7.3.x and Master fail from 7.1.x and 7.2.x COMMERCE currently.

We introduced schema changes through COMMERCE-4608 which were never introduced in 7.3.x or Master.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
