### PR TITLE
COMMERCE-5243 Use the currentURL as the searchResult's PortletURL

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by ivicac** [comment]
@marco-leo can you please check this one?

**Review by marco-leo — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
