### PR TITLE
LPD-26359 Product Description contains HTML elements

### PR DESCRIPTION
**Pull request by AlmirFe**
https://liferay.atlassian.net/browse/LPD-26359
https://liferay.atlassian.net/browse/LPP-54010

### CODE REVIEW

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra , tied to LPP. https://liferay.atlassian.net/browse/LPD-26359

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
Code looks good, thank you!

Can you please add an integration test [here](https://github.com/liferay/liferay-portal/blob/e9c93faeaa8c3ad54b80f37da4c5d816bb0c9d4f/modules/apps/commerce/commerce-product-test/src/testIntegration/java/com/liferay/commerce/product/search/test/CPDefinitionIndexerTest.java#L60)? 
The test should create a product with an HTML description and assert that the summary it's equal to the extracted text. The commit containing the test must be the first one in the commit history.
Thank you!

**Comment by AlmirFe** [comment]
Hi @andrea-ale-sbarra, Could you take a look at the changes I made?

**Comment by AlmirFe** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
