### PR TITLE
Automated Test - COMMERCE-5997 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-5997 ; cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Conflict resolved.

**Comment by pedro-michel** [comment]
ci:test:sf

**Pull request closed without merging**
