### PR TITLE
Automated Test - COMMERCE-6237 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6237 , cc: @iovaneale

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//div[@id='main-content']//div[contains(@class,'portlet')]//section[contains(@id,'Checkout')]"

**Comment by JoMaAlves** [comment]
> Element is not present at "//div[@id='main-content']//div[contains(@Class,'portlet')]//section[contains(@id,'Checkout')]"

Fixed!

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//span[@class='user-avatar-link']"

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
