### PR TITLE
COMMERCE-12658 Channel Restriction on Account Addresses

### PR DESCRIPTION
**Pull request by pietrobocale**
https://liferay.atlassian.net/browse/COMMERCE-12658

Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4433

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
New PR: https://github.com/liferay-commerce/liferay-portal/pull/4477

**Pull request closed without merging**
