### PR TITLE
COMMERCE-6831 Add to quarantine AssertPriceListHaveRequiredNameAndCurrency and AssertPriceEntriesAreProductsInTheSameCatalogAsPriceList

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-6831

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:stop

**Pull request closed without merging**
