### PR TITLE
COMMERCE-8322 Button style on the Open Carts widget

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-8322

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
Follow Andrea Censi request.

Thank you!

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
