### PR TITLE
LPS-197755 Throw the exception cause of ModelListenerException so that it is treated properly

### PR DESCRIPTION
**Pull request by devpedrotavares**
Bug: [LPS-197755](https://liferay.atlassian.net/browse/LPS-197755)

## Context
When a custom object validation fails for Account and Postal Address system objects, no error message is displayed on the UI

## Motivation
Properly handle the exception thrown when a custom object validation fails in Account and Postal Address system objects. This will replicate the current behavior when using User system object. You can see that  `EditUserMVCActionCommand` has a similar catch clause [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/users-admin/users-admin-web/src/main/java/com/liferay/users/admin/web/internal/portlet/action/EditUserMVCActionCommand.java#L309).

### CODE REVIEW

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
lgtm @devpedrotavares

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:test:relevant

**Comment by devpedrotavares** [comment]
ci:forward

**Pull request closed without merging**
