### PR TITLE
LPD-32243 Placed Orders - Returns Tab

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-32243
cc: @gianmarcobrunialti

### CODE REVIEW

**Review by gianmarcobrunialti — CHANGES_REQUESTED** [review]
Wonderful job, man! 🚀  Please remove bulk actions as there are none at the moment.

buildLang, functional test and you're ready to go.

Did you also verify what could happen if this table requests Returns for an order that's still open?

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
@gianmarcobrunialti removed bulk actions. I did not check for open order returns. I dont think we can create a return for a open order right?

**Review by gianmarcobrunialti — APPROVED** [review]

**Comment by dsitu** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
> @gianmarcobrunialti removed bulk actions. I did not check for open order returns. I dont think we can create a return for a open order right?

Correct, we can't, but since this data set will appear in a single DPT which handles both open and placed orders, we have to predict how it's gonna behave in case it appears in the context of an open order.

By design, the data set appears within a tab navigation fragment, which cannot be conditioned, and product already clarified that it's not gonna be a problem to have a "Returns" tab with an "empty results" data set inside. But of course, even for this to be achieved, the data sets should handle the "empty results" case, also for an open order. :)

**Comment by dsitu** [comment]
> > @gianmarcobrunialti removed bulk actions. I did not check for open order returns. I dont think we can create a return for a open order right?
> 
> Correct, we can't, but since this data set will appear in a single DPT which handles both open and placed orders, we have to predict how it's gonna behave in case it appears in the context of an open order.
> 
> By design, the data set appears within a tab navigation fragment, which cannot be conditioned, and product already clarified that it's not gonna be a problem to have a "Returns" tab with an "empty results" data set inside. But of course, even for this to be achieved, the data sets should handle the "empty results" case, also for an open order. :)

ahh kk, that makes since. Yeah I can verify that for the open orders detail page, it just shows a empty results table.

**Comment by dsitu** [comment]
ci:forward:force

**Pull request closed without merging**
