### PR TITLE
LPD-33439 Display template page implementation for orders

### PR DESCRIPTION
**Pull request by alessiorendina**
Based on https://github.com/brianchandotcom/liferay-portal/pull/153553

We now use the functionality provided by https://liferay.atlassian.net/browse/LPD-11147 to configure the friendly URL.

https://liferay.atlassian.net/browse/LPD-33439

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:playwright

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
