### PR TITLE
Automated Test - COMMERCE-6032 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-6032 ; CC: @Pietro69

**Comment by pedro-michel** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
Please add the property `test.name.skip.portal.instance = "CPCommerceProductMedia#AddAnAttachmentToAnOption"`

**Comment by leticiachiu** [comment]
@Pietro69 Fixed.

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:commerce-functional

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
