### PR TITLE
[Request Review] LPS-178725

### PR DESCRIPTION
**Pull request by JanisZhang**
Forwarded from:https://github.com/liferay-core-infra/liferay-portal/pull/3904 [**CI Passed**]

Hey Team !!!

We are working on the task, which is removing all `java.util.stream.Stream<>` & `java.util.Optional` usages. 

Since the last commit has something to do with the commerce business logic, please help to review it and leave your feedback !!!

Thank you!

https://issues.liferay.com/browse/LPS-178725

Regards,
Janis

### CODE REVIEW

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM, thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerc

**Comment by JanisZhang** [comment]
> LGTM, thank you!

Thanks, @andrea-ale-sbarra !!!
You can forward this to bc.  cc @dantewang

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
