### PR TITLE
COMMERCE-9698 No messages appear when items with different Shipping Methods are added to the Shipment

### PR DESCRIPTION
**Pull request by luca-pellizzon**
@markocikos rebased here, thanks.

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
@luca-pellizzon I've re-sent this here: #2989. Can you close this PR? Thanks!

**Pull request closed without merging**
