### PR TITLE
[IGNORE] COMMERCE-12514

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-12384

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
included here https://github.com/liferay-commerce/liferay-portal/pull/4435

**Pull request closed without merging**
