### PR TITLE
LPD-22038 Site settings default permissions

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-22038

Resent from https://github.com/liferay-commerce/liferay-portal/pull/4902 with the required changes and rebased on https://github.com/brianchandotcom/liferay-portal/pull/149929

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:um

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
