### PR TITLE
Commerce 8840 - support XML response type

### PR DESCRIPTION
**Pull request by fabio-d-m**
FE updates on top of https://github.com/liferay-commerce/liferay-portal/pull/2440

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
forwarded here https://github.com/liferay-commerce/liferay-portal/pull/2493

**Pull request closed without merging**
