### PR TITLE
COMMERCE-9194 corrected language key order -> display-order

### PR DESCRIPTION
**Pull request by sammonsjl**
Community contribution from Olaf: https://github.com/liferay/liferay-portal/pull/4627.  Can someone please review?

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
@luca-pellizzon is this PR still needed? If not please close it

**Comment by luca-pellizzon** [comment]
@riccardo-alberti I think it is still needed

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
