### PR TITLE
LPD-38820 - Removal of Poshi test CPCommerceProducts#ProductPublishing

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-38820

cc @smottal

### CODE REVIEW

**Comment by matyaswollner** [comment]
ci:test:sf

**Comment by matyaswollner** [comment]
cc @smottal

**Comment by matyaswollner** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
