### PR TITLE
COMMERCE-11736 - Special Character Validation for Product Relation Type

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11736](https://issues.liferay.com/browse/COMMERCE-11736)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
Hi @andrea-ale-sbarra, can you review this one? It's tied to an LPP. Thank you!

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3913

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
