### PR TITLE
LPD-31560 Remove FF

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-31560

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:report:38487643

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:39661858

**Review by riccardo-alberti — APPROVED** [review]

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
