### PR TITLE
COMMERCE-11848 - "search x in category" text in commerce search dropdown is not translated

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11848
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3945

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @victoroscuro, review passed for the automated test. And after analysis, the relevant/commerce-functional errors are not related to this pull, it can be force-forwarded, thank you!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
