### PR TITLE
LPD-15995 Fix virtual instance access to another account's address

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-15995

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
@luca-pellizzon Failed test for ci:test:relevant are unrelated, this can be forward once review is passed.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
