### PR TITLE
COMMERCE-6402 salesforce connector update

### PR DESCRIPTION
**Pull request by igorbeslic**
No need for CI

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/100612

**Pull request closed without merging**
