### PR TITLE
LPS 135602

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ivicac, could send to Brian manually?

**Comment by Tim-Cao** [comment]
The semantic verisoning issue is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/104375

**Comment by Tim-Cao** [comment]
ci:close

**Comment by ivicac** [comment]
thx @Tim-Cao

**Pull request closed without merging**
