### PR TITLE
Order item amos fong 2

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by amosfong** [comment]
ci:test:sf

**Comment by amosfong** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
Ehi @amosfong please see my comment here https://github.com/liferay-commerce/liferay-portal/pull/2582#discussion_r862727823 and here https://github.com/liferay-commerce/liferay-portal/pull/2582#discussion_r862725266

**Comment by amosfong** [comment]
@andrea-ale-sbarra , ah thanks, I thought it was strange. I had missed some commits when cherry-picking.

**Comment by amosfong** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/2582#issuecomment-1115073790

**Pull request closed without merging**
