### PR TITLE
LPD-32516 Return Reason and Payment Method are displaying the key instead of the label

### PR DESCRIPTION
**Pull request by michelevigilante**
https://liferay.atlassian.net/browse/LPD-32516

### CODE REVIEW

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTm
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
