### PR TITLE
COMMERCE-10891 OOTB Account Role of Supplier to Manage Catalogue

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-10891

### CODE REVIEW

**Comment by dsitu** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reevaluate:1377401_12559

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:commerce

**Comment by dsitu** [comment]
ci:reevaluate:1277401_8794

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Pull request closed without merging**
