### PR TITLE
LPS-203809 - Investigate failure in LocalFile.RolesAdmin#CanSearchRoleWithDifferentTitleAndKey

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/LPS-203809

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
cc/ @victoroscuro

**Comment by lorenzolapescara** [comment]
ci:test:um

**Comment by jaydawu** [comment]
ci:forward

**Pull request closed without merging**
