### PR TITLE
Automated Test - COMMERCE-5937 | master

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-5937 ; cc:  @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//ul[contains(@class,'list-group')]//*[@class='list-group-card-item-text' and normalize-space(./text())='Site Configuration']"

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
