### PR TITLE
COMMERCE-10711

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10711

@andrea-ale-sbarra ,

Idea of the implementation is similar to one you introduced in [COMMERCE-9935](https://issues.liferay.com/browse/COMMERCE-9935).

Implementations enables product options to be added to images using headles API

We only allow adding if it meets following:
1. CPOption exists.
2. CPOptionRel exists for the CPDefinition.
3. CPOptionValueRel exists.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@andrea-ale-sbarra , QA should double check, but the integration test failure is not reproducible locally.

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM

**Comment by victoroscuro** [comment]
ci:test:commerce

**Pull request closed without merging**
