### PR TITLE
COMMERCE-11893 - Search is not working while adding account groups

### PR DESCRIPTION
**Pull request by victorcdp**
Relevant Issue: [COMMERCE-11893](https://liferay.atlassian.net/browse/COMMERCE-11893)

@andrea-ale-sbarra Can you review this one? Tied to an LPP. Thank you.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:Sf

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM, but I'm not sure we're still supporting this API.

@luca-pellizzon can you have a look at this too?

**Comment by luca-pellizzon** [comment]
we are no longer actively supporting Commerce Account related APIs, but this is one of those included in
https://liferay.atlassian.net/browse/COMMERCE-11517
https://github.com/brianchandotcom/liferay-portal/pull/137460
So untile we have that in master, this must be fixed.
We need to remember to synch the same fix also to the AccountEntry modules

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
See: https://github.com/liferay-commerce/liferay-portal/pull/4021

@andrea-ale-sbarra , @luca-pellizzon

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
