### PR TITLE
COMMERCE-9979 check if it is an empty list

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Since the fix already [exists](https://github.com/liferay/liferay-portal/commit/1765fdd7fcc59c45702d975781575f2959f407c7) on master, we just send a functional test to cover this scene, see https://github.com/liferay-commerce/liferay-portal/pull/3787, thanks.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
