### PR TITLE
Lpd 43692

### PR DESCRIPTION
**Pull request by brianikim**
PR removes reference to

```
		"com.liferay.portlet.header-portlet-css=/css/main.css",
```

Removed as part of: https://github.com/liferay/liferay-portal/commit/b598fdffa6440cddf2153ae5071aba5449a1d93c

https://liferay.atlassian.net/browse/LPD-43692

### CODE REVIEW

**Comment by brianikim** [comment]
@andrea-ale-sbarra ,

I don't think we need a test for this, but let me know.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Agree the test should be verify the log doesn't appear anymore.

Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
