### PR TITLE
COMMERCE-12574

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/COMMERCE-12574

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
Re-sent at https://github.com/liferay-commerce/liferay-portal/pull/4341

**Comment by CrescenzoRegaLF** [comment]
ci:reopen

**Pull request closed without merging**
