### PR TITLE
[CLDR] LPD-18594 Fix CPCommerceWarehouseAndInventoryPermissions functional tests with CLDR

### PR DESCRIPTION
**Pull request by julschong**
Hi Team, @brianikim @luca-pellizzon 
This PR fixes all CPCommerceWarehouseAndInventoryPermissions test failures with CLDR enabled.
Issues:
https://liferay.atlassian.net/browse/LPD-18607
https://liferay.atlassian.net/browse/LPD-18608
https://liferay.atlassian.net/browse/LPD-18609
https://liferay.atlassian.net/browse/LPD-18610
https://liferay.atlassian.net/browse/LPD-18611
https://liferay.atlassian.net/browse/LPD-18612

CLDR Test is running here: https://github.com/julschong/liferay-portal/pull/1195#issuecomment-2025881224
This PR's commerce-functional test will be our result with JRE locale provider.

We just need to make sure that both test results don't contains CPCommerceWarehouseAndInventoryPermissions test failures and we should be good to go.

Thanks!

### CODE REVIEW

**Comment by julschong** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by julschong** [comment]
@brianikim CPCommerceWarehouseAndInventoryPermissions results all passed both on CLDR and JRE locale providers.
This is good to go

**Comment by brianikim** [comment]
ci:forward:force

**Pull request closed without merging**
