### PR TITLE
COMMERCE-10265 Properly use ClayTabs.Item

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10265

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@iovaneale merged to master and the temp branch.

**Comment by brianikim** [comment]
https://github.com/liferay/liferay-portal/commit/f51c6c9a7799b3f92af5f1877254a0cf7f96bf99

**Pull request closed without merging**
