### PR TITLE
COMMERCE-6975 Order type field 1/3 (2 of 2)

### PR DESCRIPTION
**Pull request by alessiorendina**
Based on #1554

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1277401_812

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci.forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
