### PR TITLE
COMMERCE-9449 truncate long product name in minicart

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9449

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
@alessiorendina can you have a look at this plese?

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra I merged this manually.

**Pull request closed without merging**
