### PR TITLE
COMMERCE-8929, COMMERCE-8930, COMMERCE-8931, COMMERCE-8932, COMMERCE-8933 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-8929
https://issues.liferay.com/browse/COMMERCE-8930
https://issues.liferay.com/browse/COMMERCE-8931
https://issues.liferay.com/browse/COMMERCE-8932
https://issues.liferay.com/browse/COMMERCE-8933

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional:nocompile

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Review by baharturk — APPROVED** [review]

**Review by baharturk — APPROVED** [review]

**Review by baharturk — APPROVED** [review]

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:forward

**Pull request closed without merging**
