### PR TITLE
COMMERCE-4844 headless-commerce-admin-pricing-impl added translation …

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
…to discount target field

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@riccardo-alberti fyi

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
