### PR TITLE
LPD-22886

### PR DESCRIPTION
**Pull request by brianikim**
https://github.com/liferay-commerce/liferay-portal/pull/4853/
https://github.com/brianikim/liferay-portal/pull/162

@andrea-ale-sbarra , resent from above

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-funcitonal

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
LGTM.
Thank you!

**Comment by brianikim** [comment]
Hello @andrea-ale-sbarra , I was able to test it. The publish happens on all 9 tabs.

The automation is not possible as per my previous comment on it: https://github.com/liferay-commerce/liferay-portal/pull/4853#issue-2236409052

**Comment by brianikim** [comment]
Here is my branch with the test included that I used to confirm the playwright test is not possible:

https://github.com/liferay-commerce/liferay-portal/pull/4853#issuecomment-2048441803

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
