### PR TITLE
COMMERCE-11252 Price a Product as Price on Application

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11252

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3809

@lorenzolapescara

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Failures in the relevant are not related.

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
