### PR TITLE
LPS-145823 Migrate FDS displays in the remaining `commerce` modules

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-147887 Delete Clay Data Set tags and API objects](https://issues.liferay.com/browse/LPS-147887)
- Related to #2706
- Followup on https://github.com/liferay-commerce/liferay-portal/pull/2741

### What is the goal of this PR?

Since there are suspicious repeating errors in relative CI tests in #2741 , I decided to split off the last migration from the tag and API deletion. This PR contains only the last migration, with a lot smaller affected area. We can do the deletion separately, on FI fork.

There are no changes in migration code from #2741

/cc @victoroscuro @luca-pellizzon

### What does it look like?

The last migration:
screen

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Pull request closed without merging**
