### PR TITLE
Commerce 4670

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
Changes required: https://github.com/brianchandotcom/liferay-portal/pull/93810#issuecomment-687207806.
Decided to pick a slightly less intrusive approach.

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
Changes required: https://github.com/brianchandotcom/liferay-portal/pull/93810#issuecomment-687207806.
Decided to pick a slightly less intrusive approach.

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
