### PR TITLE
LPD-18809 - testfix

### PR DESCRIPTION
**Pull request by wanderlast**
@andrea-ale-sbarra 

Test fix for CI issue reported

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:playwright

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
forwarded here: https://github.com/liferay-commerce/liferay-portal/pull/4859

**Pull request closed without merging**
