### PR TITLE
COMMERCE-11084 Migrate legacy selection modal to openSelectionModal

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-11084

@andrea-ale-sbarra , tied to LPP and also a current sprint ticket.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
The right pattern with the modal is to cover the whole page not just the side panel

**Comment by brianikim** [comment]
hi @andrea-ale-sbarra , addressed the issue with the modal not covering whole page.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3898.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
