### PR TITLE
[TS] LPS-152391 headless-commerce-admin-account: defaultBilling & defaultshipping cannot save with true value

### PR DESCRIPTION
**Pull request by jaydawu**
Resend from https://github.com/liferay-commerce/liferay-portal/pull/3276
https://issues.liferay.com/browse/COMMERCE-11105

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by lorenzolapescara — APPROVED** [review]

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
