### PR TITLE
COMMERCE-7198

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

https://issues.liferay.com/browse/COMMERCE-7198

I checked the front-end code to make sure our current implementation is correct in utilizing user input in search.

We just needed to update our API for `getChannelCartsPage` (`channels/{channelId}/account/{accountId}/carts`) to account for search.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
LGTM, can you just add "(yaml file)" in the first commit message, this is what we usually do when we change a yaml file.

Thank you!

**Comment by Brunno0liveira** [comment]
ci:bundle

**Comment by Brunno0liveira** [comment]
ci:help

**Comment by Brunno0liveira** [comment]
ci:test:bundle

**Comment by Brunno0liveira** [comment]
Hi @brianikim can you please close this PR

I open a new one at https://github.com/liferay-commerce/liferay-portal/pull/3464

Thanks!

**Pull request closed without merging**
