### PR TITLE
COMMERCE-6553 & COMMERCE-6555 Default display pages

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
Looks like info framework was merged, I'll have to fix this later.

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
hi @alecsloan can you please fix conflicts?

thx

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
resent at https://github.com/liferay-commerce/liferay-portal/pull/1601

**Pull request closed without merging**
