### PR TITLE
COMMERCE-5453 Add upgrade process to remove portlet 90 references from resourceAction

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@marco-leo didn't have a chance to test it because there is a problem with upgrading from 7.3 to 7.4. Is this the right fix? Thx

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@dsitu could you please check this PR? thx

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Pull request closed without merging**
