### PR TITLE
Automated Test - COMMERCE-5997 | master

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/COMMERCE-5997

@zmmarina

cc: @iovaneale
This is ready for review!

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
Review started

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Rebased after reindex was removed.

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
Element is not present at "//ul[contains(@class,'list-group')]//a[contains(@href,'site-configuration-details')]"

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1291. Please close @kristinonias

**Pull request closed without merging**
