### PR TITLE
COMMERCE-8850 | Automation Test to search within the Product filters

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://issues.liferay.com/browse/COMMERCE-8850

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Review by lorenzolapescara — CHANGES_REQUESTED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Review by lorenzolapescara — APPROVED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
