### PR TITLE
LPD-20516 Fix automation for 18646

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-20516

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:um

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:um

**Comment by gianmarcobrunialti** [comment]
ci:test:um

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:um

**Comment by gianmarcobrunialti** [comment]
ci:test:um

**Comment by gianmarcobrunialti** [comment]
@smottal I think we can forward this.

**Comment by gianmarcobrunialti** [comment]
ci:forward:force

**Comment by gianmarcobrunialti** [comment]
ci:forward:force

**Pull request closed without merging**
