### PR TITLE
Automated Test - COMMERCE-6221 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6221 , cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//div[contains(@role,'tabpanel') and contains(@class,'active')]//div[contains(@class,'applications-menu-nav-columns')]//li[contains(.,'Configuration')]/following-sibling::li//span[normalize-space(text())='System Settings']"

**Comment by JoMaAlves** [comment]
> Element is not present at "//div[contains(@ROLE,'tabpanel') and contains(@Class,'active')]//div[contains(@Class,'applications-menu-nav-columns')]//li[contains(.,'Configuration')]/following-sibling::li//span[normalize-space(text())='System Settings']"

Done! Could you check if its working well? @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
