### PR TITLE
LPD-23748 Added category title to commerce APIs

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/LPD-23748

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
The issue in the relevant suite is not related to this PR.

**Comment by alessiorendina** [comment]
ci:forward:force

**Pull request closed without merging**
