### PR TITLE
COMMERCE-12431 OrgChart View/Edit Panel - Account + Automation

### PR DESCRIPTION
**Pull request by baharturk**
Story: https://liferay.atlassian.net/browse/COMMERCE-12431

Test Plan: https://liferay.atlassian.net/browse/COMMERCE-12822

sent from: #4441 - #4402 - #4451

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:um

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:stable

**Comment by baharturk** [comment]
The failures in the relevant are not related to the PR, it can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
