### PR TITLE
Automated Test - COMMERCE-5839 | master

### PR DESCRIPTION
**Pull request by ocesar9**

### CODE REVIEW

**Comment by c3saroliveira** [comment]
https://issues.liferay.com/browse/COMMERCE-5839, cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by p-albuquerque** [comment]
New PR sent in #1318 
Please Close

**Pull request closed without merging**
