### PR TITLE
COMMERCE-11927 - Unable to search account group inside products

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://liferay.atlassian.net/browse/COMMERCE-11927

re-sent from #3993

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Review by baharturk — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
Failures are not caused by the PR.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
