### PR TITLE
COMMERCE-9886 Patching Addresses for Accounts Deletes and Creates New Addresses

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9886

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — COMMENTED** [review]
@dsitu fine to me, but it's not clear to me why we are deleting the address when not sent along with the request. I mean could be ok for a PUT method, but when using a PATCH I expect to change just what I send and nothing else.
What do you think?

cc @andrea-ale-sbarra

**Comment by dsitu** [comment]
@luca-pellizzon ahh true, yeah I agree the delete would make more sense for a PUT call. I'll remove the delete. Thanks!!

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
