### PR TITLE
COMMERCE-11793 The same Supplier Account can be linked to different channels (UI-API)

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/COMMERCE-11793

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by luca-pellizzon — APPROVED** [review]

**Comment by victoroscuro** [comment]
Relevant failure seem unrelated to the changes made for this PR. I'll force forward it.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
