### PR TITLE
Commerce 9235

### PR DESCRIPTION
**Pull request by MahmoudAzzam**

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
@dsitu Hi Danny, 
Can you please review my changes in light of ticket https://issues.liferay.com/browse/COMMERCE-9235 and let me know if I need to change anything?
Thanks

**Comment by andrea-ale-sbarra** [comment]
@alessiorendina can you have a look to this?

**Comment by alessiorendina** [comment]
@MahmoudAzzam it looks good, except you have to use Roboto as Andrea said, in order to maintain the same look and feel that we have now.
Thanks

**Pull request closed without merging**
