### PR TITLE
Commerce 9006 As a developer I want to unify all renderers for Product Details page - 2/2 (Frontend Story)

### PR DESCRIPTION
**Pull request by christian-chiappa**

### CODE REVIEW

**Comment by christian-chiappa** [comment]
ci:test:sf

**Comment by christian-chiappa** [comment]
brian's comments:

https://github.com/brianchandotcom/liferay-portal/pull/120930#issuecomment-1198152514

1) we can't use JSONUtil.put because the object is changing based on some conditions (if statements), so we can't just create a single object and returned. Because it is dinamically created
2) Fixed
3) -colon pattern is used for example search-colon=Search:
4) FIxed

@andrea-ale-sbarra

**Comment by christian-chiappa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@christian-chiappa 1.) this is not true

```
we can't use JSONUtil.put because the object is changing based on some conditions (if statements), so we can't just create a single object and returned. Because it is dinamically created
```

JSONUtil.puts have logic in them if you pass in a function. That's what I"m trying to get you to do.

2.) Sort

		_id = fileEntry.getFileEntryId();
		_url = defaultURL;
		_thumbnailURL = defaultURL;
		_mimeType = fileEntry.getMimeType();
		_title = fileEntry.getTitle();
		_size = 0;

and

sort

		_id = 0;
		_mimeType = null;
		_thumbnailURL = defaultURL;
		_title = null;
		_url = defaultURL;
		_size = 0;

Thx

**Pull request closed without merging**
