### PR TITLE
COMMERCE-9047 commerce-product-service use PrincipalThreadLocal inste…

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
…ad of ServiceContext to get userId

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by MahmoudAzzam** [comment]
Previous PR : https://github.com/liferay-commerce/liferay-portal/pull/3002

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by MahmoudAzzam** [comment]
New PR : https://github.com/liferay-commerce/liferay-portal/pull/3015

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Pull request closed without merging**
