### PR TITLE
LPD-34377 - WebURL api

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-34377

Resent from: https://github.com/brianchandotcom/liferay-portal/pull/154650

cc @smottal

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:27254894

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
