### PR TITLE
COMMERCE-8627 Unlock CIFA blocker BUG

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay-support.zendesk.com/agent/tickets/61706

https://issues.liferay.com/browse/COMMERCE-8388

https://issues.liferay.com/browse/COMMERCE-8617

https://issues.liferay.com/browse/COMMERCE-8627

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra merged

**Pull request closed without merging**
