### PR TITLE
LPD-26243 Refactor CPCommerceDiscounts#CanUserReciveAnErrorForEmptyOrDecimalCommaNumberForMinimumAmountField to playwright test

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-26243

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
