### PR TITLE
COMMERCE-12048 Show details for product relations workflow

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12048

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:stop

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
Resent at https://github.com/liferay-commerce/liferay-portal/pull/4118

Thanks!

**Comment by Brunno0liveira** [comment]
ci:close

**Pull request closed without merging**
