### PR TITLE
COMMERCE-9040 | COMMERCE-9041 Test fixes

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-9040
https://issues.liferay.com/browse/COMMERCE-9041

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:forward

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
Re-sent at #2530

**Pull request closed without merging**
