### PR TITLE
LPS-205284 - clarify language in key tooltip when adding a new role to address accessibility concerns

### PR DESCRIPTION
**Pull request by wanderlast**
Hi team!

Concerns were raised in [LPP-52202](https://liferay.atlassian.net/browse/LPP-52202) about the two tooltips that are found when generating a new Role (Control Panel > Roles > New Role) for the "Title" and "Key" input boxes respectively. I've already clarified that the "Title" tooltip is fine with the client which leaves only clarification needed in the "Key" tooltip. I've done so by explicitly naming that this is what's being added/edited to the tooltip.

The tooltip itself is exclusively used when adding a new role or account role, so it shouldn't affect anyone else's work.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
