### PR TITLE
COMMERCE-5943 Set order uuid in httpsession for logged in user and consolidate code for setting guest cookie

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
Merged by https://github.com/brianchandotcom/liferay-portal/pull/100191

**Pull request closed without merging**
