### PR TITLE
Automated Test - COMMERCE-6062 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6062 , cc: @pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
AddAProductRelations passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
