### PR TITLE
COMMERCE-10176

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10176

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@dsitu ,

Could you double check for me whether my upgradeProcess implementation was correct? Thank you.

**Review by andrea-ale-sbarra — COMMENTED** [review]
@brianikim isn't this the buildService?

**Comment by brianikim** [comment]
Hello @andrea-ale-sbarra ,

I addressed the wrong commit name.

**Review by dsitu — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
@brianikim rebase conflicts

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
also brian wants the autocode commits to be placed as last commit in the PR, so this should be shifted with the previous one

**Comment by brianikim** [comment]
@andrea-ale-sbarra , I took care of the bnd issues and the commit orders ( I was not aware of BChan's request on this. Thank you for letting me know!)

**Comment by andrea-ale-sbarra** [comment]
This was tested with this PR https://github.com/liferay-commerce/liferay-portal/pull/3165 that made the integration tests run on CI

**Comment by andrea-ale-sbarra** [comment]
approved by @igorbeslic here https://liferay.slack.com/archives/C034JL018TV/p1667902506228209?thread_ts=1667899190.385239&cid=C034JL018TV

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
resent here https://github.com/liferay-commerce/liferay-portal/pull/3182

**Pull request closed without merging**
