### PR TITLE
LPD-35542 Default Permissions changes: Unlock the values checked

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-35542

cc @smottal

resend this https://github.com/brianchandotcom/liferay-portal/pull/155671

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by smottal** [comment]
ci:report:62839707

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
