### PR TITLE
COMMERCE-12540 Create an Accordion for Options in the Minicart

### PR DESCRIPTION
**Pull request by pietrobocale**
https://liferay.atlassian.net/browse/COMMERCE-12540

Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4395

New PR that contains some test fixes and improvments

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
I did the qa review and just marked some typos in the functional tests part, since the pr is too long, I fetch it on my pull, please see details on https://github.com/jaydawu/liferay-portal/pull/184.

**Comment by jaydawu** [comment]
Fix tests and resent on https://github.com/liferay-commerce/liferay-portal/pull/4407

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
