### PR TITLE
COMMERCE-9478 Add search by skuExternalReferenceCode

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9478

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
@andrea-ale-sbarra Ive made it so the api can search by skuExternalRefenceCode. For some reason the filter is returning back 0 results, but search is working correctly.

**Review by luca-pellizzon — APPROVED** [review]
As said not really a fix for the ticket, but this code is still relevant and we should merge it.

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
This was resent here https://github.com/liferay-commerce/liferay-portal/pull/2796

**Pull request closed without merging**
