### PR TITLE
COMMERCE-11251 Order Splitting Object RuleCommerce

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-11192

Fixed conflicts from: #3753

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
@CrescenzoRegaLF

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:stop

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
sent here
https://github.com/liferay-commerce/liferay-portal/pull/3786

**Pull request closed without merging**
