### PR TITLE
LPD-35093, LPD-35520, LPD-37376 - fix failing upgrade tests

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @smottal,

https://liferay.atlassian.net/browse/LPD-37376, tied to LPP.

Resend of this with fix for failing upgrades. Logic behind fix is that if we both have the old ResourceAction (which is our first check) and we also have the correct new ResourceAction (second check), we can just remove the old ResourceAction rather than updating it to the new one. I had to rebase to account for the revert, but please let me know if you want me to rebase/resend again so it's easier to read.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:upgrade

**Comment by smottal** [comment]
hey @wanderlast , I don't know if it's the right solution because (trying to analyze)
```
private void _updatePermission(String newName, String oldName)
		throws Exception {

		if (!_hasPermission(oldName)) {
			return;
		}

		if (_hasPermission(newName)) {
			try (PreparedStatement preparedStatement =
					connection.prepareStatement(
						"delete from ResourceAction where actionId = ?")) {

				preparedStatement.setString(1, oldName);

				preparedStatement.executeUpdate();
			}

			return;
		}

		try (PreparedStatement preparedStatement = connection.prepareStatement(
				"update ResourceAction set actionId = ? where actionId = ?")) {

			preparedStatement.setString(1, newName);
			preparedStatement.setString(2, oldName);

			preparedStatement.executeUpdate();
		}
	}
```

* if we don't have the oldPermission is fine
* if we don't have the new one is fine (we are updating the old one to the new one)
* if we already have the new one (the new piece of code in the middle) we are removing the old one - but this old one can be already associated to roles and removing it we are losing this configuration. Probably, but please help me thinking about this and you have to do some try, it's better to delete the new one (because it's new it should not be "used") and continue now with the rename of the old one. What do you think?

**Comment by wanderlast** [comment]
> if we already have the new one (the new piece of code in the middle) we are removing the old one - but this old one can already be associated to roles and removing it we are losing this configuration. Probably, but please help me thinking about this and you have to do some try, it's better to delete the new one (because it's new it should not be "used" yet) and continue now with the rename of the old one. What do you think?

I think this should work too? My primary concern is how the 'old' and 'new' version came to coexist at the same time, but I'll try it out and test to make sure this covers all use cases.

**Comment by smottal** [comment]
@wanderlast I think both are there because
* the old are already there
* the new are created from the "service layer" (because it finds them in the portal-impl/src/resource-actions/portal.xml file)

**Comment by wanderlast** [comment]
Force push was due to necessary rebase. I've made the change per your suggestion and tested it and it appears to be working properly and is passing all relevant tests locally. I'll re-run SF and upgrade test suites.

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:upgrade

**Comment by smottal** [comment]
ci:report:57480659

**Comment by smottal** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
My apologies, I think when I rebased the semver accidentally became misaligned again. I've fixed it and I'm re-running the test suite since I didn't see any other relevant failures in the results.

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
