### PR TITLE
COMMERCE-4695 Fixed toggle switch in Panel

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
This is a fix which affects all of the toggle switches in PanelTag usages, which were broken and specifically blocking the form submission in certain sections of AdminUI.

This could be due to a deprecation (ever since 7.2) of parts of the `ParamAndPropertyAncestorTagImpl` (from which our `IncludeTag` extends) which are inhibiting the SSR and related *dynamic* attributes pass-through between FE and BE.

Needs further investigation.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
@marco-leo Temporarily not running relevant tests as i know they would fail.

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
