### PR TITLE
COMMERCE-5538 headless-commerce-admin-catalog-impl Include channels w…

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
…hen exporting for machine learning

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
