### PR TITLE
LPD-31645 - Search by Organizations when setting a user's organization roles is not working

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-31645

### CODE REVIEW

**Comment by matyaswollner** [comment]
ci:test:sf

**Comment by matyaswollner** [comment]
ci:test:relevant

**Comment by matyaswollner** [comment]
ci:test:playwright

**Comment by matyaswollner** [comment]
ci:test:stable

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
