### PR TITLE
Automated Test - COMMERCE-5980 | master

### PR DESCRIPTION
**Pull request by ewertonluna**

### CODE REVIEW

**Comment by ewertonluna** [comment]
https://issues.liferay.com/browse/COMMERCE-5980 cc: @AlessandroIovane

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@ewertonluna

This pull requests has conflicts with the CommerceChannel.Macro file. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@ewertonluna , 

This pull request has a formatting issue. Please fix and resend.

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
Element is not present at "//ul[contains(@class,'list-group')]//a[contains(@href,'site-configuration-details')]"

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//ul[contains(@class,'list-group')]//a[contains(@href,'site-configuration-details')]"

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//ul[contains(@class,'list-group')]//*[@class='list-group-card-item-text' and normalize-space(./text())='Site Configuration']"

**Pull request closed without merging**
