### PR TITLE
COMMERCE-12757

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/COMMERCE-12757

Let's forward this after https://liferay.atlassian.net/browse/COMMERCE-12755 is merged into master

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/145761

**Pull request closed without merging**
