### PR TITLE
Automated Test - COMMERCE-6369 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6369 ; cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
[Passing here](https://testray.liferay.com/home/-/testray/cases/1534566722)

**Pull request closed without merging**
