### PR TITLE
COMMERCE-6918 Permissions on the Attachments are not being respected

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #3101 

https://issues.liferay.com/browse/COMMERCE-6918

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
Please close this

**Pull request closed without merging**
