### PR TITLE
Automated Test - COMMERCE-6231 | master

### PR DESCRIPTION
**Pull request by IsaVV**

### CODE REVIEW

**Comment by IsaVV** [comment]
https://issues.liferay.com/browse/COMMERCE-6231, cc: @iovaneale

**Comment by IsaVV** [comment]
fixing https://github.com/liferay-commerce/liferay-portal/pull/1365

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Pull request closed without merging**
