### PR TITLE
COMMERCE-4741 Source format commerce upgrades

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-4741

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by marco-leo — COMMENTED** [review]
In the case of CPDefinitionVirtualSettingUpgradeProcess we are always add column and rename, so if we deploy this code to an existing commerce it will fail, as will try to upgrade form 1.0 to 2.0 right?

**Comment by dsitu** [comment]
I think theres checks for adding/renaming the table columns if they exist already. Although it looks like its still possible that it makes changes to some field. So I dont think we want to risk that. I'll look into a way to avoid the version increase, maybe suppress it.
```
if (hasColumn(
				CPDefinitionVirtualSettingImpl.TABLE_NAME, "classNameId")) {

			String template = StringUtil.read(
				CPDefinitionVirtualSettingUpgradeProcess.class.
					getResourceAsStream(
						"dependencies/CPDefinitionVirtualSetting.sql"));

			long classNameId = ClassNameLocalServiceUtil.getClassNameId(
				CPDefinition.class.getName());

			template = StringUtil.replace(
				template, "(?)", "\'" + classNameId + "\'");

			runSQLTemplateString(template, false, false);
		}
```

**Comment by dsitu** [comment]
gonna send a new pr

**Pull request closed without merging**
