### PR TITLE
COMMERCE-9454 remove noAccountErrorMessage declaration from the JSP file and move it to the JS file

### PR DESCRIPTION
**Pull request by manuelecastro**
[COMMERCE-9454](https://issues.liferay.com/browse/COMMERCE-9454)

[Previous PR](https://github.com/liferay-commerce/liferay-portal/pull/3338)

### CODE REVIEW

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:sf

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by manuelecastro** [comment]
ci:test:commerce

**Comment by manuelecastro** [comment]
ci:test:relevant

**Review by riccardo-ferrari — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
ci:forward

**Pull request closed without merging**
