### PR TITLE
LPD-15184 InputPermissions showAllRoles parameter

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-15184

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by smottal** [comment]
ci:report:2540494668

**Comment by smottal** [comment]
ci:report:2540925079

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Pull request closed without merging**
