### PR TITLE
Automated Test - COMMERCE-6195 | master

### PR DESCRIPTION
**Pull request by ewertonluna**

### CODE REVIEW

**Comment by ewertonluna** [comment]
https://issues.liferay.com/browse/COMMERCE-6195, cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//iframe[contains(@id,'selectCategory_iframe_')]"

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1339 @kristinonias

**Pull request closed without merging**
