### PR TITLE
Automated Test - COMMERCE-5997 | master

### PR DESCRIPTION
**Pull request by zmmarina**

### CODE REVIEW

**Comment by zmmarina** [comment]
https://issues.liferay.com/browse/COMMERCE-5997 
cc: @alessandroiovane

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@zmmarina The source formatting for this pull request has failed. Please fix and resend.

**Comment by zmmarina** [comment]
@kristinonias fixed! ;)

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Reviewing/Fixing

**Comment by brittneyq** [comment]
Fixed and sent in [#980](https://github.com/liferay-commerce/liferay-portal/pull/980). Please close.

**Pull request closed without merging**
