### PR TITLE
COMMERCE-11913 - Pagination is not correct on order details page

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11913
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3984

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
