### PR TITLE
COMMERCE-9470 Added missing language key

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
@alessiorendina rebase error, can you please fix?
Thank you!

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@alessiorendina now SF error

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
