### PR TITLE
Automated Test - COMMERCE-6235 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6235 , cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//div[@class='table-list-title']/../../../*[contains(.,'U-Joint')]//*[name()='svg'][contains(@class,'icon-ellipsis')]"

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by JoMaAlves** [comment]
Rebased

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
