### PR TITLE
COMMERCE-8473 Fixed multi side panel navigation

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

[Testray Comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=1843463197&testrayRunIdA=1851793759&statusB=2)
- ContentPageTemplates#ChangeEditableImage and ContentPageTemplates#CanViewPaginationContentViaAP look like unrelated flukes.
- The remaining failing tests look like recently started failing in upstream or failed prior to test running. So they are also unrelated to this PR.

**Comment by alessiorendina** [comment]
Manually forward here: https://github.com/brianchandotcom/liferay-portal/pull/117689

Thanks!

**Pull request closed without merging**
