### PR TITLE
COMMERCE-5754

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1257401_1689

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1257401_1689

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1257401_1689

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1257401_1689

**Comment by andrea-ale-sbarra** [comment]
ci:stop

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
