### PR TITLE
COMMERCE-12191 Make sure sub-facets have the proper facet configurations

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://liferay.atlassian.net/browse/COMMERCE-12191

Resent from #4162

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
Relevant failures are not related to this PR. It can be force forwarded

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
