### PR TITLE
Automated Test - COMMERCE-6238 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-6238; cc:@iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
Running CI on [kristinonias #9](https://github.com/kristinonias/liferay-portal/pull/9)

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//div[@id='main-content']//div[contains(@class,'portlet')]//section[contains(@id,'Checkout')]"

**Pull request closed without merging**
