### PR TITLE
COMMERCE-10685 Do not provide bean attribute. We have models that do not use groupId.

### PR DESCRIPTION
**Pull request by iovaneale**

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
