### PR TITLE
COMMERCE-8975 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-8975

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]

**Comment by pietrobocale** [comment]
ci:forward

**Comment by Kvale1733** [comment]
ci:reopen

**Pull request closed without merging**
