### PR TITLE
Commerce 7339

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-7339

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/1822

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
Hey @brianikim I've made some addition here: https://github.com/liferay-commerce/liferay-portal/pull/2498

**Pull request closed without merging**
