### PR TITLE
LPS-161068 Including a blankspace to avoid errors by a markup validation service

### PR DESCRIPTION
**Pull request by rijema**
Click here to see the LPS: https://issues.liferay.com/browse/LPS-161068

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:relevant

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
Hi @liferay-commerce , any news? Thanks!

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
