### PR TITLE
COMMERCE-4814 DDMFormHandler Util to correctly parse and send product options in FS

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
Please see https://github.com/liferay-commerce/liferay-portal/pull/226

**Pull request closed without merging**
