### PR TITLE
COMMERCE-9564 New headless APIs for warehouses

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-9564

resending this:
https://github.com/brianchandotcom/liferay-portal/pull/122941

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
refer to this
https://github.com/liferay-commerce/liferay-portal/pull/3034

**Pull request closed without merging**
