### PR TITLE
COMMERCE-6965 Clean up overload add and update methods for CommercePriceListService

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-6965

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
@igorbeslic if the PR is too big, Let me know and I can break up the commits to separate PR's.

**Comment by igorbeslic** [comment]
@dsitu I'll forward. Lets see if Brian would like us to remove completely deprecated methods.

**Comment by igorbeslic** [comment]
ci:forward

**Pull request closed without merging**
