### PR TITLE
COMMERCE-6998 Use filter() to delete rules.

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-6998

@dsitu , I think this is shopping experience. Could you confirm?

### CODE REVIEW

**Comment by brianikim** [comment]
ci;test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by dsitu** [comment]
@brianikim yeah it seems like it.

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
