### PR TITLE
COMMERCE-12346 Change the Label of "Commerce Products" to "Products" + Test Fix

### PR DESCRIPTION
**Pull request by baharturk**
Story: https://liferay.atlassian.net/browse/COMMERCE-11881

sent from: #4234

@dsitu

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
