### PR TITLE
COMMERCE-5286 MiniCart full coverage + extra refinements

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
```
PASS test/components/MiniCart/util/index.js
  MiniCart Utils
    hasErrors
      ✓ returns true if at least one cart item contains error messages (6ms)
      ✓ returns false if no cart item contains error messages (1ms)
    parseOptions
      ✓ parses and formats a JSON string input to an options list string (3ms)
      ✓ returns an empty string when input is neither valid JSON nor a JSON-parsed array (1ms)
    regenerateOrderDetailURL
      ✓ returns a new valid Order Detail URL string (4ms)
      ✓ throws if the "orderUUID" string argument is empty or null (2ms)
      ✓ throws if the "siteDefaultURL" string argument is empty or null
      ✓ throws if the "siteDefaultURL" string argument is a malformed URL (1ms)
    summaryDataMapper
      ✓ converts a DeliveryCart API summary payload to a label/value map list for the Summary used in the MiniCart (2ms)

PASS test/components/MiniCart/CartItemViews/ItemInfoView.js
  MiniCart Item Info View
    Base
      ✓ renders the name and the SKU of an item (61ms)
      + Bundle
        ✓ renders the name and the SKU of a bundle item, plus its child items with their related quantities (30ms)
      + Options
        ✓ renders the name and the SKU of an item, plus its options (11ms)
      + Bundle + Options
        ✓ renders the name and the SKU of an item, plus its child items with their related quantities, plus its options (16ms)

PASS test/components/MiniCart/CartItemsList.js
  MiniCart Items List
    by default
      ✓ renders the ItemsList component w/ the ItemsListActions and a div including a shopping cart icon and the label "Add a product to the cart" (138ms)
    by data flow
      if there are cart items
        ✓ renders the ItemsList component displaying the ItemsListActions, a div including the list of cart items and the order Summary (10ms)
        ✓ if the cart is updating, the Summary will be informed (4ms)

PASS test/components/MiniCart/Header.js
  MiniCart Header
    by default
      ✓ renders the MiniCart header which includes a dynamic title and a button to close the cart (84ms)
    by data flow
      ✓ if there are no cart items, the header title shows the label "Your order is empty" (28ms)
      ✓ if there are cart items, the header title shows the label "Your order" (7ms)
      ✓ if MiniCart is not toggleable, will not render the close button (16ms)

PASS test/components/MiniCart/Opener.js
  MiniCart Opener
    by default
      ✓ renders a clickable button with a shopping cart icon to open the MiniCart (104ms)
      ✓ renders a button showing no number of items as the cart is empty (9ms)
    by data flow
      if there are cart items
        ✓ renders a badge with their total count by item type (26ms)
        ✓ if "displayTotalItemsQuantity" is set to true, renders a badge with the total items count from the cart summary (12ms)
        ✓ if "displayTotalItemsQuantity" is set to true, but there is no summary, renders a badge with the total items count by item type (13ms)

PASS test/components/MiniCart/OrderButton.js
  MiniCart Order Button
    by default
      ✓ renders a block-styled button element (51ms)
      ✓ the button element is disabled as the cart is empty (16ms)
    by data flow
      if order workflow status is
        ✓ not set or 0, renders a button w/ label as "submit" to checkout the order (5ms)
        ✓ different from 0, renders a button w/ label as "review-order" to review the order (3ms)
      if there are cart items
        ✓ renders a clickable button element to checkout the order (8ms)
        if some cart item has errors
          ✓ renders a clickable button element to review the order (6ms)
        if order workflow status is
          ✓ not set or 0, renders a clickable button w/ label as "submit" to checkout the order (5ms)
          ✓ different from 0, renders a clickable button w/ label as "review-order" to review the order (5ms)

PASS test/components/MiniCart/CartItem.js
  MiniCart Item
    by default
      ✓ renders the cart item with its information (ItemInfoView), quantity (QuantitySelector), price (Price), and a button to remove it from the cart, plus a hidden div to handle the item removal cancellation (91ms)
      ✓ ...also with the item's thumbnail (22ms)
      ✓ always parses the cart item options (14ms)
    by data flow
      if the parsed options string is non-empty
        ✓ adds the "options" class name to the ItemInfoView wrapper div (15ms)
      if the cart item has errors
        ✓ renders a div with icon and error text (15ms)
    by interaction
      if the cart item delete button is clicked
        ✓ unhides the div to handle the item removal cancellation (54ms)
        ✓ if no action is performed, calls to API to remove the item from the order (81ms)
        ✓ if the "undo" button is clicked, cancels the removal of the item (26ms)
      if the cart item quantity is edited, calls the API and
        ✓ updates the item quantity (67ms)
        if the request fails
          ✓ renders a div with icon and error text (68ms)
          ✓ ...which automatically disappears in 4000ms (12ms)

PASS test/components/MiniCart/CartItemsListActions.js
  MiniCart Items List Actions
    by default
      ✓ renders the MiniCart items list action buttons View details and Remove all items as disabled, plus the action confirmation prompt as hidden (48ms)
    by data flow
      if there are cart items
        ✓ the MiniCart items list action buttons are clickable (9ms)
        ✓ renders the items count in singular noun form (7ms)
        ✓ renders the items count in plural noun form (6ms)
        by interaction
          ✓ if the "View details" button is clicked, navigates to the order detail page URL (13ms)
          ✓ if the "Remove all items" button is clicked, unhides the confirmation prompt with yes/no buttons (18ms)
          ✓ if the "Remove all items" button is clicked, and then the "No" button is clicked, hides the confirmation prompt with yes/no buttons (12ms)
          ✓ if the "Remove all items" button is clicked, and then the "Yes" button is clicked, calls the API to empty the cart and returns to the initial state on success (12ms)

PASS test/components/MiniCart/Wrapper.js
  MiniCart Wrapper
    by default
      ✓ renders the MiniCart Wrapper component w/ only Header, an empty div and the OrderButton (59ms)
    by data flow
      ✓ if the cart is open, renders the MiniCart Wrapper component w/ Header, a DataSetDisplay component wrapping the ItemsList, and the OrderButton (34ms)

PASS test/components/MiniCart/util/views.js
  MiniCart Utils -> Views
    resolveCartViews
      ✓ resolves the default MiniCart views (5ms)
      selectively replaces default views with
        ✓ resolved custom local component implementations (25ms)
        ✓ resolved custom Liferay module component implementations (4ms)
        ✓ fallback default MiniCart views if Liferay modules fail to resolve (2ms)

PASS test/components/MiniCart/MiniCart.js
  MiniCart
    by default
      ✓ renders the MiniCart in closed state with the default view components and an overlay div (50ms)
      ✓ wraps the MiniCart with a Context provider for all of the children component (5ms)
    by interaction
      if cart is toggleable
        ✓ click on the Opener button opens and the MiniCart (25ms)
        ✓ if the MiniCart is open, click on the overlay closes the MiniCart (8ms)
        ✓ the MiniCart is open from the start, and neither the Opener nor the overlay are rendered (12ms)
    by data flow
      if the order ID is defined and > 0
        ✓ calls the API to fetch the cart by orderId and (28ms)
        ✓ if the request fails, displays an error via Liferay Notification (8ms)
        if the request succeeds
          ✓ updates the cart action URL's (5ms)
          ✓ calls the "onAddToCart" custom function (7ms)
          ✓ renders the MiniCart displaying the cart content correctly (9ms)
    by event
      ✓ on "current-order-updated" event, calls the API with the ID of the order and updates the MiniCart (9ms)
      ✓ on "current-account-updated" event, resets the cart state (7ms)

Running coverage on untested files...Test Suites: 11 passed, 11 total
Tests:       70 passed, 70 total
Snapshots:   34 passed, 34 total
Time:        4.59s
yarn run v1.22.10
$ liferay-npm-scripts test MiniCart --coverage --collectCoverageOnlyFrom ./src/main/resources/META-INF/resources/components/mini_cart/CartItem.js ./src/main/resources/META-INF/resources/components/mini_cart/CartItemViews/ItemInfoView.js ./src/main/resources/META-INF/resources/components/mini_cart/CartItemsList.js ./src/main/resources/META-INF/resources/components/mini_cart/CartItemsListActions.js ./src/main/resources/META-INF/resources/components/mini_cart/Header.js ./src/main/resources/META-INF/resources/components/mini_cart/MiniCart.js ./src/main/resources/META-INF/resources/components/mini_cart/MiniCartContext.js ./src/main/resources/META-INF/resources/components/mini_cart/Opener.js ./src/main/resources/META-INF/resources/components/mini_cart/OrderButton.js ./src/main/resources/META-INF/resources/components/mini_cart/Wrapper.js ./src/main/resources/META-INF/resources/components/mini_cart/entry.js ./src/main/resources/META-INF/resources/components/mini_cart/util/constants.js ./src/main/resources/META-INF/resources/components/mini_cart/util/index.js ./src/main/resources/META-INF/resources/components/mini_cart/util/labels.js ./src/main/resources/META-INF/resources/components/mini_cart/util/views.js --silent --no-color
Using NODE_ENV: "test"
--------------------------|---------|----------|---------|---------|-------------------
File                      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
--------------------------|---------|----------|---------|---------|-------------------
All files                 |   99.45 |      100 |   90.67 |     100 |                   
 mini_cart                |   99.15 |      100 |   87.27 |     100 |                   
  CartItem.js             |     100 |      100 |     100 |     100 |                   
  CartItemsList.js        |     100 |      100 |     100 |     100 |                   
  CartItemsListActions.js |     100 |      100 |     100 |     100 |                   
  Header.js               |     100 |      100 |     100 |     100 |                   
  MiniCart.js             |   97.62 |      100 |   89.47 |     100 |                   
  MiniCartContext.js      |     100 |      100 |       0 |     100 |                   
  Opener.js               |     100 |      100 |     100 |     100 |                   
  OrderButton.js          |     100 |      100 |     100 |     100 |                   
  Wrapper.js              |     100 |      100 |     100 |     100 |                   
 mini_cart/CartItemViews  |     100 |      100 |     100 |     100 |                   
  ItemInfoView.js         |     100 |      100 |     100 |     100 |                   
 mini_cart/util           |     100 |      100 |     100 |     100 |                   
  constants.js            |     100 |      100 |     100 |     100 |                   
  index.js                |     100 |      100 |     100 |     100 |                   
  labels.js               |     100 |      100 |     100 |     100 |                   
  views.js                |     100 |      100 |     100 |     100 |                   
--------------------------|---------|----------|---------|---------|-------------------
Received 0
Done in 6.56s.
```

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
