### PR TITLE
COMMERCE-4793 Refactored checkout portlet JSP for Saved Addresses use case

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
DynamicSelect components don't allow access to their private properties or methods anymore (and if they were private, perhaps we shouldn't have relied on them in the first place 👀 ). This broke our commerce-checkout-web Portlet implementation when users select a previously saved address. The JS in the related JSP has been refactored to fix this issue.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
