### PR TITLE
LPD-29697 - Updating a product via a PATCH API call when a UOM is set is unexpectedly setting the list price to $0

### PR DESCRIPTION
**Pull request by victorcdp**
Resend of https://github.com/liferay-commerce/liferay-portal/pull/5092

@andrea-ale-sbarra Tied to FIRE LPP. I did the changes you requested, can you take another look? Thank you!

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by riccardo-alberti — APPROVED** [review]

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
Added another commit to fix an edge case

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
