### PR TITLE
LPD-34662 If there's only one Return Item, the Return status moved to Rejected if the user changes the Authorized Quantity of the Return Item once the Return is already in Authorized state

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-34662

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:report:74452340

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Pull request closed without merging**
