### PR TITLE
COMMERCE-11792 Fix unstable test

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11792

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test

**Comment by jaydawu** [comment]
ci:stop

**Comment by jaydawu** [comment]
ci:stop

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
