### PR TITLE
COMMERCE-7822 | Update UI for warehouses admin

### PR DESCRIPTION
**Pull request by iovaneale**
https://issues.liferay.com/browse/COMMERCE-7822

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:forward

**Comment by iovaneale** [comment]
ci:forward

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
