### PR TITLE
COMMERCE-10173 - It's possible to save a product configuration with wrong values

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-10173
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3637

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by lorenzolapescara — APPROVED** [review]
@jaydawu test looks good to me. buildService is also part of the autogenerated commits

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
Hi @lorenzolapescara, updated already, does it need to rerun ci:test:relevant?

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:forward

**Pull request closed without merging**
