### PR TITLE
COMMERCE-10421 Currencies Search bar is not given the expected result

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-10421

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
Re-sent at https://github.com/liferay-commerce/liferay-portal/pull/4366

**Comment by Brunno0liveira** [comment]
ci:close

**Pull request closed without merging**
