### PR TITLE
LPD-29992 Fix test failure for incorrect locators

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-29992

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:33806767

**Comment by CrescenzoRegaLF** [comment]
ci:report:33806767

**Review by alessiorendina — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:36463348

**Review by alessiorendina — APPROVED** [review]

**Pull request closed without merging**
