### PR TITLE
COMMERCE-9087 Update response for patch SKU endpoints

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-9087

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
Not sure about the order still, but let's try however.

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
QA Passed

**Comment by smottal** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
