### PR TITLE
Automated Test - COMMERCE-6222 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6222 , cc: @iovaneale

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by JoMaAlves** [comment]
Corrected a Typo and renamed the 2 paths that I created

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[@class='data-set-display-wrapper' or @class='searchcontainer-content']//a[text()='MIN55861']"

**Comment by JoMaAlves** [comment]
Fixed conflicts and possible error.

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
