### PR TITLE
COMMERCE-9820 discountId must not be required

### PR DESCRIPTION
**Pull request by pietrobocale**
Base PR #2983 

cc @andrea-ale-sbarra @alessiorendina

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
