### PR TITLE
COMMERCE-12014 Change the default sort order in discount admin page to be based on datemodified desc

### PR DESCRIPTION
**Pull request by lorenzolapescara**
Re-sent from #4099.

https://liferay.atlassian.net/browse/COMMERCE-12014

@CrescenzoRegaLF @luca-pellizzon

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]
QA Review Passed

Thanks!

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR.
@luca-pellizzon can you please force-forward the PR? Thanks in advance!

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
