### PR TITLE
Commerce 9441 - 🚓 secure bug

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9441

resolved conflicts by relaunching **ant build-lib-versions** from **portal-impl** folder

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
