### PR TITLE
Automated Test - COMMERCE-6287 | master

### PR DESCRIPTION
**Pull request by LucasAcacio**

### CODE REVIEW

**Comment by LucasAcacio** [comment]
https://issues.liferay.com/browse/COMMERCE-6287, cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "xpath=(//div | //li)[(contains(@class,'open') or contains(@class,'show')) and (contains(@class,'dropdown') or contains(.//*/@class,'dropdown'))]//*[self::a or self::span or self::button][normalize-space(text())='Master']"

**Comment by kristinonias** [comment]
https://issues.liferay.com/browse/LRQA-67149

**Pull request closed without merging**
