### PR TITLE
COMMERCE-9617 Replace DDM Form with a React structure

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://issues.liferay.com/browse/COMMERCE-9617

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Review by alessiorendina — CHANGES_REQUESTED** [review]
Hey @kresimir-coko
Thanks for your work. We need to discuss the solution and understand the flow behind this refactor. Maybe we can schedule a call to talk about it.

**Comment by kresimir-coko** [comment]
Closing this PR as it is a different approach than the one the Commerce team wants.

**Pull request closed without merging**
