### PR TITLE
COMMERCE-11152 SKU Virtual Settings

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11152

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3688
Resent from: https://github.com/brianchandotcom/liferay-portal/pull/134124

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by smottal** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
