### PR TITLE
LPD-36953 Integrate Multi Shipping Table with Tab fragment in Order detail page

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-36953

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
Sent here: https://github.com/liferay-commerce/liferay-portal/pull/5552

**Pull request closed without merging**
