### PR TITLE
LPD-3222 No email notification sent for order placed after checkout process completed for guest user

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-3222

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1267401_13094

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:report:2561457948

**Comment by CrescenzoRegaLF** [comment]
> ### ❌ ci:test:commerce-functional - 203 out of 214 jobs passed in 2 hours 14 minutes
> Click here for more details.

I checked the report and there are no failures due to this story

**Comment by CrescenzoRegaLF** [comment]
ci:report:2561460989

**Comment by CrescenzoRegaLF** [comment]
ci:test:stable

**Comment by CrescenzoRegaLF** [comment]
> ### ❌ ci:test:stable - 32 out of 33 jobs passed
> ### ❌ ci:test:relevant - 138 out of 169 jobs passed in 2 hours 53 minutes
> Click here for more details.

No Unique Failures

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
