### PR TITLE
COMMERCE-8003 Add contentType to attachment api

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-8003

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
hey @dsitu it seems there is a conflict?

**Review by ivicac — APPROVED** [review]

**Comment by dsitu** [comment]
@ivicac I rebased and rebuilt rest again, conflict is gone now.

**Comment by ivicac** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
