### PR TITLE
COMMERCE-12025 - Orders list page contains Add/Edit option for the users having only view permission

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-12025](https://liferay.atlassian.net/browse/COMMERCE-12025)

@luca-pellizzon Can you review this one? Tied to an LPP. Thank you.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by luca-pellizzon — CHANGES_REQUESTED** [review]
Since you are adding a new permission key (`MANAGE_COMMERCE_ORDER_PAYMENT_STATUSES`), you must also:
- add default permission to commerce roles who already has orders related permissions, like the operation manager (all the permissions that you are now checking need to be added)
- add an UpgradeProcess to update permissions on already existing systems (there are plenty of examples in commerce codebase)

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
@luca-pellizzon Can you see if it's alright now? The only role in Minium which had the MANAGE_COMMERCE_ORDERS permision was the Operations Manager, so i only added it to that role.

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@victorcdp please update the PR for conflicts

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
@luca-pellizzon Can you take another look now? Thank you.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by brianikim** [comment]
@luca-pellizzon ,

PR has conflicts so @victorcdp will update it on Monday. 
Also, he is going to introduce another front-end validation as well for the "save" button on the custom fields for orderItem and order.

**Comment by victorcdp** [comment]
@luca-pellizzon Updated it to include the additional checks

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by jaydawu** [comment]
ci:stop

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @victorcdp, manual testing is passed, but the batch [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2406722564?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2406720995%26testrayRunId%3D2406721524%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) failed, it should be related to your changes. Could you please update it well under this pr? Thanks!

**Comment by victorcdp** [comment]
@jaydawu updated it (it's the last commit). Thank you.

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed, resent on https://github.com/liferay-commerce/liferay-portal/pull/4136.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
