### PR TITLE
COMMERCE-9802

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

https://issues.liferay.com/browse/COMMERCE-9802

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
Screenshot 2022-09-05 at 15 50 56
Screenshot 2022-09-05 at 15 51 02
Screenshot 2022-09-05 at 15 51 09

**Comment by andrea-ale-sbarra** [comment]
Ehi @brianikim I think that to solve the issue we just need to use the same key in these three pages. The key is the one the produce: **Promotion Price**

**Comment by brianikim** [comment]
Hello @andrea-ale-sbarra ,



I don't think you deployed the changes. See attached pictures. ``

**Review by andrea-ale-sbarra — APPROVED** [review]
Thank you @brianikim !

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
Hello @brianikim, I tested the PR, it works as expected. I launched ci:test:commerce to see if there were failures in our test suits. We have 2 tests failing because of a change that this PR brings. Could you do the fix for the tests, please?

**This is where we need to change a `key_text` value that we pass:**
liferay-portal/modules/apps/commerce/commerce-product-test/src/testFunctional/macros/CommerceSKUs.macro

here go to macro editSkuPricing and change the key_text value in line 63 from `key_text = "Promo Price"` to `key_text = "Promotion Price"`.

Thank you!

After you push the code, we can relaunch ci:test:commerce to make sure it works also in ci. The tests passed in my local with this fix.

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@baharturk , I am re-running the test with the recommended change. Thanks!

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
