### PR TITLE
COMMERCE-9851 - Promotion's plus button title is not correct

### PR DESCRIPTION
**Pull request by alessiorendina**
@elocamp I forwarded it here, thanks!

Original PR: https://github.com/alessiorendina/liferay-portal/pull/24

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
forwarded here https://github.com/liferay-commerce/liferay-portal/pull/3337

**Pull request closed without merging**
