### PR TITLE
LPS-201007 Share document with users of user group with site membership + Automation

### PR DESCRIPTION
**Pull request by baharturk**
Bug ticket: https://liferay.atlassian.net/browse/LPS-201007

sent from: #4416

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Review by pietrobocale — APPROVED** [review]
Review Passed

Thanks!

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:um

**Comment by baharturk** [comment]
The failures in the relevant are not related, this PR can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
