### PR TITLE
Automated Test - COMMERCE-6665 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-6665; cc:@lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//span[@class='order-id']"

**Comment by pedroalmd** [comment]
Tried to work around it and sent in https://github.com/liferay-commerce/liferay-portal/pull/1448. Please check if this works on CI @kristinonias

**Pull request closed without merging**
