### PR TITLE
Automated Test - COMMERCE-6666 | master

### PR DESCRIPTION
**Pull request by juliomoraes-dev**

### CODE REVIEW

**Comment by julioribeiiro** [comment]
https://issues.liferay.com/browse/COMMERCE-6666; cc:@lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//span[@class='order-id']"

**Comment by julioribeiiro** [comment]
@kristinonias please re-open this pr, trying another way

**Comment by julioribeiiro** [comment]
Changes: 5s pause after adding a product to the cart, the delay for generating the order ID was causing the error

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
