### PR TITLE
Automated Test - COMMERCE-6023 | master

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/COMMERCE-6023

cc: @Pietro69

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Sent. https://github.com/liferay-commerce/liferay-portal/pull/857
Please close.

**Comment by brittneyq** [comment]
ci:close

**Pull request closed without merging**
