### PR TITLE
COMMERCE-6413 Commerce Channel API unable to define "Type"

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-6413

resend this: https://github.com/brianchandotcom/liferay-portal/pull/124871#issuecomment-1285796004

@victoroscuro

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
Thank you @CrescenzoRegaLF

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
