### PR TITLE
COMMERCE-10797 Add needed js to facets

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10797

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
@andrea-ale-sbarra asking for review

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
Re-sent at #3455. Closing this PR. Thanks!

**Comment by lorenzolapescara** [comment]
ci:close

**Pull request closed without merging**
