### PR TITLE
COMMERCE-9850 

### PR DESCRIPTION
**Pull request by pietrobocale**
These changes will fix the following bugs:

https://issues.liferay.com/browse/COMMERCE-9507
https://issues.liferay.com/browse/COMMERCE-9765
https://issues.liferay.com/browse/COMMERCE-9766
https://issues.liferay.com/browse/COMMERCE-9850

It will be possible to delete product versions and products when versioning is enabled.

Resent of from #2997

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
@pietrobocale can we forward it?

**Comment by andrea-ale-sbarra** [comment]
@alessiorendina we need to wait core-infra to send their work first and then we need to rebase this on top of that

**Comment by alessiorendina** [comment]
Sent here: https://github.com/liferay-commerce/liferay-portal/pull/3010

**Pull request closed without merging**
