### PR TITLE
COMMERCE-10066 Filter product's available quantities in product page …

### PR DESCRIPTION
**Pull request by brianikim**
…according to the product's configurations

From @victorcdp ,

> Related Issue: [COMMERCE-10066](https://issues.liferay.com/browse/COMMERCE-10066)
> 
> The problem was that there was no filtering being done before showing the quantity options on the product's page. Proposed fix is to filter the existing quantity options according to the specified configurations (min, max and multiple).

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:close

**Pull request closed without merging**
