### PR TITLE
COMMERCE-5326 Adjusted PriceTag to use CPCatalogEntry and render correctly via JSP template

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
From here: https://github.com/liferay-commerce/liferay-portal/pull/639

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by ivicac** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
