### PR TITLE
Commerce 5172

### PR DESCRIPTION
**Pull request by garofalog**

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
Hi @garofalog please remove commit 32b2936 and change commit message of edcd975

**Comment by andrea-ale-sbarra** [comment]
Hey @garofalog I believe it would be better to **fixup** the commits b5c408b 045382b and edcd975 in one commit

**Pull request closed without merging**
