### PR TITLE
COMMERCE-12167 remove wrong parameter

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12167

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR, thanks!

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Pull request closed without merging**
