### PR TITLE
COMMERCE-7915

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — CHANGES_REQUESTED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
QA Passed. Forwarding

**Comment by lorenzolapescara** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
ci:stop

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:commerce

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
Integration tests are now passing. Forwarding the PR.
cc @victoroscuro @riccardo-alberti

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
