### PR TITLE
LPD-33046 Enable filter by Custom Field for Users

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-33046

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:78371575

**Comment by smottal** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
