### PR TITLE
COMMERCE-10412 | Fix failing functional tests caused by changed success alert text message

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:stop

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
