### PR TITLE
LPD-15148 Remove the duplicate admin menu item of Countries from the Commerce Menu

### PR DESCRIPTION
**Pull request by riccardo-alberti**
https://liferay.atlassian.net/browse/LPD-15148

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
the breaking change comments were lost, to retain them use --verbatim option on commit command

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Pull request closed without merging**
