### PR TITLE
COMMERCE-9580 Removing order quantity validation in the order admin section

### PR DESCRIPTION
**Pull request by alessiorendina**
cc @MahmoudAzzam @luca-pellizzon

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
