### PR TITLE
LPD-43840 Fixed failing test testPostCartByExternalReferenceCodeItem

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-43840

cc @smottal

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
