### PR TITLE
LPD-20228 Languages are not working on personal sites

### PR DESCRIPTION
**Pull request by smottal**
Resent from https://github.com/liferay-commerce/liferay-portal/pull/4857

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:forward

**Comment by pei-jung** [comment]
ci:report:2560845583

**Comment by pei-jung** [comment]
Fixed compile error and resent as https://github.com/liferay-commerce/liferay-portal/pull/4873

**Comment by pei-jung** [comment]
ci:close

**Pull request closed without merging**
