### PR TITLE
Pr 2333

### PR DESCRIPTION
**Pull request by marco-leo**

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:forward

**Comment by liferay-commerce** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@alessiorendina can we sort

```
		// Shipment items

		ShipmentItem[] shipmentItems = shipment.getShipmentItems();

		if (shipmentItems != null) {
			_commerceShipmentItemService.deleteCommerceShipmentItems(
				commerceShipment.getCommerceShipmentId(), false);

			for (ShipmentItem shipmentItem : shipmentItems) {
				ShipmentItemUtil.addOrUpdateShipmentItem(
					shipmentItem.getExternalReferenceCode(), commerceShipment,
					_commerceShipmentItemService, shipmentItem,
					_serviceContextHelper);
			}
		}

		// Shipping address

		ShippingAddress shippingAddress = shipment.getShippingAddress();

		if (shippingAddress != null) {
			ShippingAddressUtil.updateShippingAddress(
				_commerceAddressService, _commerceShipmentService,
				commerceShipment, _countryService, _regionService,
				shippingAddress, _serviceContextHelper);
		}

		return commerceShipment;
```

and do address first, then items?

Please also fix and readd test cb7f0c75

@marco-leo merged, making build now.

**Pull request closed without merging**
