### PR TITLE
COMMERCE-10151 New API to get a list of Available Low Stock Actions

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-10151

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — CHANGES_REQUESTED** [review]
Since we are in admin APIs I think we should send a map of
<locale, value> for the label

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
looking good!
just need a rebase

**Comment by pietrobocale** [comment]
QA Passed, and the PM review is completed. After the conflicts are fixed, we can forward it

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
