### PR TITLE
Commerce 5979

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-5979

@riccardo-alberti 

We should merge this just like we merged https://issues.liferay.com/browse/COMMERCE-5372

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@luca-pellizzon , PR looks fine. The unique CI failure seems unrelated.

**Comment by luca-pellizzon** [comment]
@brianikim this is fine to me, but needs to be tested by QA, also relevant tests must pass to forward it.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
Hi @brianikim, I added a missing property to the test, now all tests are passing, forwarding [here](https://github.com/liferay-commerce/liferay-portal/pull/2911) the PR. Could you close this PR, please? Thnx

**Pull request closed without merging**
