### PR TITLE
COMMERCE-6396 | COMMERCE-6564

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
@lorenzolapescara Could you check this last commit, please? https://github.com/liferay-commerce/liferay-portal/pull/1081/commits/16ec92982c1171120d7d2e71578409b720c8a91b

Thank ya! :)

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
Resent at https://github.com/liferay-commerce/liferay-portal/pull/1120

**Pull request closed without merging**
