### PR TITLE
COMMERCE-12054

### PR DESCRIPTION
**Pull request by brianikim**
@CrescenzoRegaLF ,

https://liferay.atlassian.net/browse/COMMERCE-12054

Solution discussed with the headless team.

Fixes https://liferay.atlassian.net/browse/LPS-190692

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Pull request closed without merging**
