### PR TITLE
LPD-33466 - Add new pricing quantity column

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/LPD-33466

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
LGTM, thanks!

**Comment by andrea-ale-sbarra** [comment]
ci:report:58991341

**Comment by andrea-ale-sbarra** [comment]
sent here https://github.com/liferay-commerce/liferay-portal/pull/5253

**Pull request closed without merging**
