### PR TITLE
COMMERCE-7646 Update guest order accountId on login

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-7646

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
