### PR TITLE
LPS-130361 Migrate selection modals in commerce-product-definitions-web

### PR DESCRIPTION
**Pull request by markocikos**
Hey @liferay-commerce @riccardo-alberti ,

This is a part of [an ongoing epic](https://issues.liferay.com/browse/LPS-129246) to replace legacy AUI-based modals with Clay/React-based `openSelectionModal`. In this PR, we are replacing modals in `commerce-product-definitions-web` and related modules.

Forwarded from https://github.com/liferay-frontend/liferay-portal/pull/1015

Notes:
- After this PR, there is no 'Add' button on image selection. This is standard for single selection modals in DXP, to close on selection click. As a consequence, we don't even render the footer. There is a way around this, please let me know if you want me to reverse this. See the gifs with the change on bottom.
- We didn't cleanup event listeners on Visibility, resulting in weird buggy behavior. This is fixed in PR. 
- See comments on woes with optional chaining jsps, and workaround for opener window, in the original PR.

Testing:
- Have a site created using Minium template. This is a prerequisite for all commerce tasks.
    1. Contol Panel > Sites > (+) Minium
    1. Contol Panel > Search > Index Actions > Reindex all search indexes.
- Create a few channels, Commerce > Channels > (+)
- Commerce > Products > open a product

After this, there are 4 test cases:
1. Visibility > Channels > (+) > Select channels
1. Visibility > Account Groups > Filter toggle > (+) > Select account groups
1. Product Relations > (+) any selection
1. Media > Attachments > (+) > Select a file, Delete

/cc @kresimir-coko @jonmak08

Single selection before PR:
before2

Single selection after PR: 
after2

Events cleanup bug:
before
 bug, fixed in this PR:

### CODE REVIEW

**Comment by markocikos** [comment]
Force-pushed to get rid of conflict, no changes.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
Hi @markocikos, It looks perfect to me :) Thanks a lot for your support

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Pull request closed without merging**
