### PR TITLE
COMMERCE-9502 Fix UndeployedExternalRepositoryException in PortalInstanceLifecycleListener

### PR DESCRIPTION
**Pull request by adolfopa**
Add an explicit dependency to the liferay repository factory. This should ensure that the repository is fully initialized before usage.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@liferay-commerce any objections to forwarding this one?

**Comment by victoroscuro** [comment]
ci:test:commerce

**Pull request closed without merging**
