### PR TITLE
COMMERCE-11386 We should first check whether a CIBookedQuantity exist…

### PR DESCRIPTION
**Pull request by brianikim**
…s before restocking

https://issues.liferay.com/browse/COMMERCE-11386

@luca-pellizzon , tied to a LPP

Straight-forward PR. We are going to get NPE on this message listener if we cancel on any order that does not have existing commerceInventoryBookedQuantities.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
