### PR TITLE
LPD-39233 Review PR "Allow using directive script-src-attr 'none' by removing inline handlers"

### PR DESCRIPTION
**Pull request by izaera**
This is a rework of https://github.com/liferay-commerce/liferay-portal/pull/5518 using a newer approach that has already been merged to master.

In theory the code is equivalent to the original one, but it would probably be wise checking everything at CI again just in case...

### CODE REVIEW

**Comment by izaera** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
Hey @izaera! Just a question: will the `CSP` tag have to be used for client extensions as well? (Say in HTML|FTL, ...)

**Review by gianmarcobrunialti — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by izaera** [comment]
@gianmarcobrunialti 

> Hey @izaera! Just a question: will the CSP tag have to be used for client extensions as well? (Say in HTML|FTL, ...)

It's an internal tag but I guess it could be used. However the correct way to handle inline events is using React or properly written `<script>` nodes containing the CSP nonce that attach event handlers to the DOM node using `getElementById`, `querySelector`, `jQuery`, etc.

Inline event handlers in the HTML code are discouraged.

**Comment by izaera** [comment]
Also, CXs are technically customer code so it's up to them to decide the strategy to implement content security policy. For that they may need the CSP nonce so we provide [ContentSecurityPolicyNonceProviderUtil](https://github.com/liferay/liferay-portal/blob/ee19de3cb4e69cbd4a67057345dfaf61a1b98a75/portal-kernel/src/com/liferay/portal/kernel/content/security/policy/ContentSecurityPolicyNonceProviderUtil.java) for that, which would be the reference API.

**Comment by izaera** [comment]
Hi there :wave: 

Any news on this PR @gianmarcobrunialti? Do you need any help from me for it to being forwarded? :thinking: 

(Note: it's important but not urgent, as there are more PRs pending for the story to be completed)

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
Hey @izaera, to me there's no issue forwarding this, I had already given my approval and asked the informational question on the correct "usage" of the tag. Running the relevant to have it ready to be forwarded 👍🏼

**Comment by izaera** [comment]
@gianmarcobrunialti What happens if any of the test suites fails? Do I use forward force or wait for you to give another approval? :thinking:

**Comment by izaera** [comment]
Just in case you missed it because this was a rework of a previous PR, the intention of this PR is that your team checks the correctness of the code as explained in this confluence doc -> https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/3245277533/LPD-36188+-+Allow+using+directive+script-src-attr+none+by+removing+inline+handlers

So it's not like the typical PR, maybe...

**Comment by izaera** [comment]
Agreed to forward force this with @gianmarcobrunialti on Slack because tests (both CI and manual) are green.

**Comment by izaera** [comment]
ci:forward:force

**Comment by izaera** [comment]
ci:forward

**Pull request closed without merging**
