### PR TITLE
Remove soy (1/2)

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/4068

**Pull request closed without merging**
