### PR TITLE
LPD-38261 Fixed NPE on all commerce widgets

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/LPD-38261

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@alessiorendina ,

We need the null check in `getCPCatalogEntries` [here](https://github.com/liferay-commerce/liferay-portal/blob/963e34faeda3eb65ce23dcca53d998262a44ccd1/modules/apps/commerce/commerce-product-content-web/src/main/java/com/liferay/commerce/product/content/web/internal/display/context/BaseCPPublisherDisplayContext.java#L67) as well.

**Comment by brianikim** [comment]
@andrea-ale-sbarra ,

I took over the ticket at the request of @alessiorendina . The PR will be updated with additional changes as soon as customer confirms the fix works as expected.

**Comment by brianikim** [comment]
ci:close

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/5521

**Pull request closed without merging**
