### PR TITLE
Lpd 21835 - ERC on user api - contacts

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-21835

### CODE REVIEW

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by matyaswollner** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:2560859524

**Comment by smottal** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
