### PR TITLE
COMMERCE-11513 Show CartQuickAdd in MiniCart even if an order doesn't exist

### PR DESCRIPTION
**Pull request by rosdb**
Bug: [COMMERCE-10472](https://issues.liferay.com/browse/COMMERCE-10472)
Sub-Task: [COMMERCE-11513](https://issues.liferay.com/browse/COMMERCE-11513)

### CODE REVIEW

**Comment by rosdb** [comment]
ci:test:sf

**Comment by rosdb** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
