### PR TITLE
COMMERCE-12915 Specify DTO version

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12915

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:stable

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Pull request closed without merging**
