### PR TITLE
COMMERCE-13080

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-13080,

@andrea-ale-sbarra , tied to LPP.

Solution was discussed with you in Slack.

Made it read-only in the yaml for `fileEntryId`

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
See attached API example for how SRC is returned when attachment is for a video shortcut.

cc/ @andrea-ale-sbarra 

Shortcut

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM. Thank you!

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/4598

**Pull request closed without merging**
