### PR TITLE
COMMERCE-5699 | Remove OM functional tests from quarantine

### PR DESCRIPTION
**Pull request by iovaneale**

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by iovaneale** [comment]
ci:trest:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
