### PR TITLE
Commerce 3013 catalog api ml changes

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-3013

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:est:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@riccardo-ferrari this is for you

**Comment by riccardo-ferrari** [comment]
Thank you @andrea-ale-sbarra !

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
