### PR TITLE
LPS-168594 Commerce compatibility with Solr

### PR DESCRIPTION
**Pull request by BryanEngler**
Just wanted to run these changes to the commerce modules by you guys before I forward to bchan.

Let me know if you have any questions or concerns. Thanks!

Test results already available and passing - https://github.com/BryanEngler/liferay-portal/pull/714#issuecomment-1331996750

https://issues.liferay.com/browse/LPS-168594

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
Hello @BryanEngler, there's something that is not clear to me here.
We are saying that Commerce is not compatible with Solr right?
Then we are hiding the Commerce's sections and settings from the UI.
As you are removing index management from ML classes.
What is not clear to me is: 
we have site initializers for Commerce: Minium (with Minium Demo) and Speedwell,
are you managing also those?
Otherwise as soon as a site initializer is started it will break

cc @andrea-ale-sbarra @victoroscuro @riccardo-alberti @riccardo-ferrari

**Comment by BryanEngler** [comment]
@luca-pellizzon correct. the solr connector does not implement some of the search engine behavior that is used by commerce. 

im am not familiar with the site initializers, so it is possible that we need to make some changes there... i can try to look into it, i think ill ping you to see if you have any advice and also to make sure i understand the details of your concern more. thanks!

**Comment by BryanEngler** [comment]
@luca-pellizzon i just pushed a few commits to site-admin to hide the commerce site initializers...

**Comment by BryanEngler** [comment]
re-running tests on https://github.com/BryanEngler/liferay-portal/pull/714

**Comment by luca-pellizzon** [comment]
Hello @BryanEngler,
I was wondering if we could have issues.
I'll try to better explain:
- we are saying Commerce is not compatible with Solr
- we create a Commerce site using the initializer (this part does work)
- now we access the newly created site, since it is not 100% compatible, something will probably break
Is this right? That's why I was asking about the initilizers.

**Comment by BryanEngler** [comment]
yes, you are correct in your thinking. this commit should hide the commerce initializers from the UI: 91cf21d5d01b4dd15e27f92be209872b9223b21b

do you think thats an acceptable solution? i know the changes are in the `site` modules, so ill have to see who maintains those and probably send a pr there as well

**Comment by luca-pellizzon** [comment]
I guess this is fine then. Many thanks.
My only other concern is: if we are hiding those sections, is there any way a user can still access them causing issues? (direct link or similar) 
If they open a ticket on that, we can still say "you are not supposed to access it", but still, better to avoid this kind of situations.

**Comment by BryanEngler** [comment]
Ya im not too sure about the different ways it might be possible to access site initializers, but in our Solr setup documentation there are many features that are not compatible (not just commerce), so its pretty well documented that Solr provides limited functionality compared to Elasticsearch. 

https://learn.liferay.com/dxp/latest/en/using-search/installing-and-upgrading-a-search-engine/solr/solr-limitations.html

Thanks for your input as well, ill go ahead and close this pr but let me know if you have any other questions

**Pull request closed without merging**
