### PR TITLE
 [TS] LPS-200153

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/LPS-200153
Resent from https://github.com/liferay-commerce/liferay-portal/pull/4392

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Review by baharturk — APPROVED** [review]

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:um

**Comment by jaydawu** [comment]
Just need to wait for the CI results to come out before forwarding it, thanks.

cc. [@victoroscuro](https://github.com/victoroscuro)

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
There are no related errors to this pull. it can be force-forwarded, thanks!

cc/ @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
