### PR TITLE
COMMERCE-11737 - Printed Note Not Appearing on Order After Cart Checkout

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11737](https://issues.liferay.com/browse/COMMERCE-11737)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:stop

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
