### PR TITLE
Added Manage/View of Addresses permissions to Account's roles

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-8939

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra @luca-pellizzon see 8f182623a52cd59205b79edf7862e3a9ef22ab17

not sure why we need that call

**Pull request closed without merging**
