### PR TITLE
LPS-195105 Migrate SearchResults.soy to react

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://liferay.atlassian.net/browse/LPS-195105

Re-sent from #4254

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
