### PR TITLE
Automated Test - COMMERCE-6248 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/COMMERCE-6248, cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@91nilo 

This pull request has conflicting files. Please fix and resend.

**Comment by 91nilo** [comment]
Hi Kristin, its fixed now. Thank you!

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by 91nilo** [comment]
Fixed, thank you!

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Conflicts fixed, thank you!

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
