### PR TITLE
LPD-35066 - site roles search does not reset upon selecting a site

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @smottal,

https://liferay.atlassian.net/browse/LPD-35066, tied to LPP.

The fix was written by @brianikim before he went on PTO, although I've tested it and it does work in my testing. I wrote the playwright test which I've placed in roles-admin-web (since the fix itself is located there). Please let me know if you'd prefer it to be in users-admin-web due to it mostly using users-admin-web infrastructure. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:playwright

**Comment by wanderlast** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
@wanderlast can you please have a look? The test is failing on CI

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:playwright

**Comment by wanderlast** [comment]
I've added additional wait calls to hopefully improve consistency and reduce flakiness.

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
