### PR TITLE
Automated Test - COMMERCE-6229 | master

### PR DESCRIPTION
**Pull request by juliomoraes-dev**

### CODE REVIEW

**Comment by julioribeiiro** [comment]
https://issues.liferay.com/browse/COMMERCE-6229, CC: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class,'alert') and (contains(@class,'alert-error') or contains(@class,'alert-danger'))]"

**Comment by julioribeiiro** [comment]
@kristinonias, please re-open this PR

**Comment by julioribeiiro** [comment]
Fixed at https://github.com/liferay-commerce/liferay-portal/pull/1439

**Pull request closed without merging**
