### PR TITLE
Automated Test - COMMERCE-6653 | master

### PR DESCRIPTION
**Pull request by RitaSilveira**

### CODE REVIEW

**Comment by RitaSilveira** [comment]
https://issues.liferay.com/browse/COMMERCE-6653, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
@RitaSilveira 

This pull request has failed on source formatting. Please fix and resend.

**Comment by nikki-pru** [comment]
@RitaSilveira @kristinonias
See Files changed. The test is duplicated in the same file.

Thanks

**Comment by p-albuquerque** [comment]
New PR sent #1294 
Please close

**Pull request closed without merging**
