### PR TITLE
LPD-33658 Refactor poshi test

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-33658

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Review by andrea-ale-sbarra — APPROVED** [review]
I don't particularly like this solution, but it's fine enough to test the dates are right.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
Tests are anyway failing on CI:
https://testray.liferay.com/#/project/35392/routines/45357/build/56913762/case-result/56916423
https://testray.liferay.com/#/project/35392/routines/45357/build/56913762/case-result/56916435

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright:nocompile

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Tests are passing.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
