### PR TITLE
COMMERCE-5846 Fixed permission check

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@andrea-ale-sbarra please review and forward thia fix as soon as possible. It's a blocker for the GA1 release.

**Comment by andrea-ale-sbarra** [comment]
@jpince I'm building the local env to test this fix

**Comment by andrea-ale-sbarra** [comment]
ci:stop

**Comment by andrea-ale-sbarra** [comment]
sent directly to Brian https://github.com/brianchandotcom/liferay-portal/pull/100561

**Pull request closed without merging**
