### PR TITLE
Automated Test - COMMERCE-6249 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/COMMERCE-6249, cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@91nilo ,

This Pull Request has conflicting files. Please fix and resend.

**Comment by leticiachiu** [comment]
Sent in: https://github.com/liferay-commerce/liferay-portal/pull/1167

**Pull request closed without merging**
