### PR TITLE
COMMERCE-10086

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10086

@luca-pellizzon ,

@baharturk, this needs to be rebased: https://github.com/brianchandotcom/liferay-portal/pull/131502/commits/57d87f7c6af0703f022f3af5e8037e5e51526988 

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:reopen

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@luca-pellizzon , QA should confirm again, but I did confirm locally the upgradeProcess works as expected.

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:commerce

**Pull request closed without merging**
