### PR TITLE
COMMERCE-9421 if no permission getDefaultImage

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
QA Rejected. The duplicated bug: COMMERCE-9238 is still reproducible.

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
