### PR TITLE
COMMERCE-4539 Fixed modals width as standard changed

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@gianmarcobrunialti we haev Modal in commerce now and Modal in frontend ifra code, please send same fix to them

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
