### PR TITLE
COMMERCE-13221 Update UM functional tests

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-13221

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:um

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
