### PR TITLE
Automated Test - COMMERCE-5929| master

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-5929; cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by julioribeiiro** [comment]
fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
