### PR TITLE
COMMERCE-4828 Fix guest checkout

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Review by dsitu — CHANGES_REQUESTED** [review]
opps just noticed it did not pass sf haha.

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by jpince** [comment]
ignore semver failure, please check failing commerce int tests...

**Comment by marco-leo** [comment]
@jpince Results looks like not related to commerce but looks real random.  I will retry a retest before analyze more

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
