### PR TITLE
Commerce 8969

### PR DESCRIPTION
**Pull request by brianikim**
@riccardo-alberti ,

https://issues.liferay.com/browse/COMMERCE-8969

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
Hey @brianikim thanks for letting me know about this, but I think this is under OM so I would ask @luca-pellizzon to do the review of this.
Thanks!

**Review by luca-pellizzon — APPROVED** [review]
Fine to me.
I know there's a ticket to remove all JS from JSP and put in separate files.
You don't need to do that for this one, but I think it should be a good thing to do it for future PRs, where we need to work on JS.
Thanks.

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
