### PR TITLE
COMMERCE-8809 Search Component better handled in minium

### PR DESCRIPTION
**Pull request by fabio-d-m**
I also removed the intersection observer polyfill since we don't support IE11 anymore and it's widely supported by all the major browsers: https://caniuse.com/intersectionobserver

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Review by andrea-ale-sbarra — APPROVED** [review]
To me the changes are fine, now testers should forward this.

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
