### PR TITLE
Automated Test - COMMERCE-6027 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-6027, CC: @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @evanilson-santana, please remove the **@ignore = true** in your test. Thanks!

**Comment by evanilson-santana** [comment]
Ok

**Comment by evanilson-santana** [comment]
Done

**Comment by brittneyq** [comment]
ci:test:sf

**Pull request closed without merging**
