### PR TITLE
LPD-42940 - Refactor LocalFile.UsersAdmin#CanBulkActivateUsers into Playwright

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-42940

### CODE REVIEW

**Comment by matyaswollner** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:playwright

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by matyaswollner** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
