### PR TITLE
LPD-26244 Refactor CommerceOrderItemsSplitting test to playwright

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-26244

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
ci:test:playwright

**Comment by andrea-ale-sbarra** [comment]
ci:report 19783169

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
