### PR TITLE
LPD-33800 Autogenerated Code (baseline)

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-33800

# breaking

## What modules/apps/client-extension/client-extension-type-api/src/main/java/com/liferay/client/extension/type/CommerceCheckoutStepCET.java

New method for PaymentMethodKey

## Why

We need the new method + property to check whether checkoutStep is a payment checkout step

----

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@luca-pellizzon

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
