### PR TITLE
COMMERCE-5571 build utility class as it was in v1_1_0 schema version

### PR DESCRIPTION
**Pull request by luca-pellizzon**
Need backport to 7.3, 7.2 and 7.1

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
