### PR TITLE
COMMERCE-11657 Fix shipment page permission

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-11657

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
The issues are not related to the changes, PR can be forward

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
