### PR TITLE
COMMERCE-11836 Follow up

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
Beside from stable, everything is okay. As soon as the stable passes this can be force forwarded

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
