### PR TITLE
LPD-3113 Trying to create a new user via API with a longer than allowed firstName produces a nonfriendly error message in the logs

### PR DESCRIPTION
**Pull request by michelevigilante**
https://liferay.atlassian.net/browse/LPD-3113

### CODE REVIEW

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:report:63793407

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
