### PR TITLE
COMMERCE-12157 UI to Create Units of Measure at SKU level + Automation

### PR DESCRIPTION
**Pull request by baharturk**
sent from #4197 

Story: https://liferay.atlassian.net/browse/COMMERCE-11656

Test Plan: https://liferay.atlassian.net/browse/COMMERCE-12282

@CrescenzoRegaLF

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures on the relevant are not related to the PR. It can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
