### PR TITLE
Automated Test - COMMERCE-5913 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-5913 , cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
Review started.

**Review by lorenzolapescara — CHANGES_REQUESTED** [review]

**Comment by pedro-michel** [comment]
@evanilson-santana , please rebase and send again :)

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
