### PR TITLE
COMMERCE-10086 - OM - Order status is not being updated automatically on deletion of order items

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

https://issues.liferay.com/browse/COMMERCE-10086

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by luca-pellizzon — CHANGES_REQUESTED** [review]
This is not the right solution.
What happens if you remove the item using headless APIs? We are not going through the ActionCommand so the issue is still there.
You have to use something like commerce-product-type-virtual-order-service/src/main/java/com/liferay/commerce/product/type/virtual/order/internal/model/listener/CommerceOrderItemModelListener.java
Also you do that only if the order is closed, otherwise it will be executed every time someone deletes an item from the cart. It will do nothing but it still is lost execution time.

**Comment by brianikim** [comment]
Hi @luca-pellizzon , the new commits should address your request. The new changes fulfill the following conditions.

Check shipment status only if:
1. The order is not being deleted.
2. The order is in status of partially shipped.

Please let me know if you are satisfied with the new implementations.

Sincerely,
Brian I. Kim

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce

**Pull request closed without merging**
