### PR TITLE
COMMERCE-10173

### PR DESCRIPTION
**Pull request by brianikim**
@jaydawu,

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3633

https://issues.liferay.com/browse/COMMERCE-10173

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
@brianikim Thank you so much!

**Comment by jaydawu** [comment]
ci:test:relevant

**Review by lorenzolapescara — CHANGES_REQUESTED** [review]
@jaydawu please check my comments and re-send. Also, please move your commits before the autogenerated commits. Thanks!

**Comment by jaydawu** [comment]
Resent in https://github.com/liferay-commerce/liferay-portal/pull/3644

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
