### PR TITLE
COMMERCE-4707 Remove constants from pricing upgrade process

### PR DESCRIPTION
**Pull request by riccardo-alberti**
Changes requested in brianchandotcom#93817

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/93817

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
