### PR TITLE
Avalara - COMMERCE-4276 (Full Story) and COMMERCE-4348

### PR DESCRIPTION
**Pull request by katienesterovich**
Previously https://github.com/liferay-commerce/liferay-portal/pull/482. Rebased and retested: works as of 1/1/2021

### [COMMERCE-4276](https://issues.liferay.com/browse/COMMERCE-4276) Parent ticket
---

### [COMMERCE-5371](https://issues.liferay.com/browse/COMMERCE-5371) - Move Avalara credentials configuration to a global scope

- Application Menu (Under Settings > Avalara)
image

- Currently one tab - credentials
image

- Failed Verify Connection 
image

- Successful verification
image

---
#### Updated channel Avalara settings 
- If Global credentials invalid: 
image

- If Global credentials valid: 
image

---
### [COMMERCE-5297](https://issues.liferay.com/browse/COMMERCE-5297) - Make Company Code input a dropdown with avalara values
- Company codes are now displayed in a dropdown (Company name is displayed, but company Code is registered)
- If not specified or get call failed, will be set to DEFAULT 
image

---
### [COMMERCE-5281](https://issues.liferay.com/browse/COMMERCE-5281) - Create avalara dispatch trigger
- Modeled after existing dispatch modules - only TaskExecuter needed to be implemented for dispatch
- Our helper will create/update ~42k entries every time the job is run

---
### [COMMERCE-5282](https://issues.liferay.com/browse/COMMERCE-5282) - Automate trigger creation and deletion
- Trigger created and marked 'active' on avalara-tax-engine activation PER CHANNEL
   - Name convention `Avalara-[ChannelID]` (screenshot below is a trigger that's in progress)
   image

- Trigger de-activated/re-activated when when CHANNEL Avalara tax engine disabled/enabled. 
- Trigger deleted on before channel deletion, along with the tax rate rels
- Currently, the cron-expression is set to run every month on the first at 0:00am
- The job will fail if global credentials are invalidated after channel activation (no model listener there)

---

### [COMMERCE-5296](https://issues.liferay.com/browse/COMMERCE-5296) - Add a 'Run Now' button in Avalara settings
- Added logic and error messages to facilitate activation workflow
   - If valid credentials configured
       - Settings panel is shown
       - Prompted to run the job for the first time
image

   - While job is running
image

   - After successful run
image

   - After a failed run
image

---
### [COMMERCE-5298](https://issues.liferay.com/browse/COMMERCE-5298)- Display AvalaraTaxRate entries in a new tab
- Reusing most of existing logic from by-adress, copied over and cleaned up for avalara. This is done to prevent exposing connector logic to core/dxp apps.
- User can edit/delete entries (I was not able to remove that menu)
- Search bar present but does not work (I am experiencing same issue with other tax engine search bars)
- If user has not previously run health checks but has run the sync job, taxCategoryId will be 0 and this view will error out. To fix, user will need to run health checks and manually rerun the job from the dispatch menu.
- There will be ~ 42k entries 
image

---
### [COMMERCE-4348](https://issues.liferay.com/browse/COMMERCE-4348) - Add a health check to map Tax Categories to Avalara TaxCodes

- Health check
image

- Tax Categories created (Expired categories are filtered out in the Avalara call)
image

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by katienesterovich** [comment]
ci:reevaluate:1037401_9623

**Pull request closed without merging**
