### PR TITLE
LPD-1288 User selector

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
https://liferay.atlassian.net/browse/LPD-1288 

This solution fixes the selector problem for the OAuth 2 Application management UI.  But it is a more generic change to your module so I am forwarding it to you for review.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by ChrisKian** [comment]
Hi @andrea-ale-sbarra, is there an update for this issue?

**Comment by andrea-ale-sbarra** [comment]
@ChrisKian stable is not running, can you please check the failures? they could be related to your code change.
Thank you!

**Comment by stian-sigvartsen** [comment]
ci:test:stable

**Comment by stian-sigvartsen** [comment]
@andrea-ale-sbarra I re-trigger the stable testing and it is passing now so that is unrelated.

**Comment by stian-sigvartsen** [comment]
@andrea-ale-sbarra thanks for your review.
Because this is a change to your team's component we'll leave you to forward it at your discretion.

**Comment by victoroscuro** [comment]
@stian-sigvartsen @ChrisKian has this change been tested? Should a functional/integration test(s) cover this change?
FYI @riccardo-alberti @andrea-ale-sbarra

**Comment by victoroscuro** [comment]
ci:test:um

**Comment by stian-sigvartsen** [comment]
It was tested based on the reproduction steps of the ticket (focussed on the OAuth 2 UI usage)

**Pull request closed without merging**
