### PR TITLE
COMMERCE-10454 Product Source view not updating when changing from Dynamic to Manual

### PR DESCRIPTION
**Pull request by JLucasM**
COMMERCE-10454: [Jira Issue](https://issues.liferay.com/browse/COMMERCE-10454)

### CODE REVIEW

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by JLucasM** [comment]
ci:test:relevant

**Comment by JLucasM** [comment]
ci:test:sf

**Comment by interaminense** [comment]
LGTM! @andrea-ale-sbarra could you review it as well?

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by Brunno0liveira** [comment]
Hi @JLucasM can you please close this PR

I open a new one for this fix

https://github.com/liferay-commerce/liferay-portal/pull/3426

Thanks!

**Comment by JLucasM** [comment]
Resent to: https://github.com/liferay-commerce/liferay-portal/pull/3426

**Pull request closed without merging**
