### PR TITLE
Automated Test - COMMERCE-6326 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
GlobalSearchSearchEntryInAllContent passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
