### PR TITLE
COMMERCE-9435 fix UP of Image Company

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9435

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
I'm closing this because I'm not sure this is the right fix

**Pull request closed without merging**
