### PR TITLE
COMMERCE-12142 UOM in catalog

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12142

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
@andrea-ale-sbarra : please review last 3 commits

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
QA PASSED

**Comment by pietrobocale** [comment]
ci:forward

**Comment by pietrobocale** [comment]
Failures are no related to the PR

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
