### PR TITLE
Automated Test - COMMERCE-6319 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-6319 , cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//div[contains(@class,'commerce-item__content') and contains(.,'Shock Absorber')]"

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1344

**Pull request closed without merging**
