### PR TITLE
Commerce-9971 NPE thrown when creating a placed order with order items sending a POST request at headless-commerce-admin-order/v1.0/orders

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
QA passed manually

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:stop

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
merged here https://github.com/brianchandotcom/liferay-portal/pull/123240

**Pull request closed without merging**
