### PR TITLE
COMMERCE-10143 Set empty destination as a default for search bar minium

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by lipusz** [comment]
We are reverting the original fix under https://github.com/brianchandotcom/liferay-portal/pull/124476

**Comment by riccardo-alberti** [comment]
thanks @lipusz. i'm closing this one

**Pull request closed without merging**
