### PR TITLE
COMMERCE-13166 Update um integration tests

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-13166

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:um

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
double checked ci results along with @smottal. failures look unrelated to the PR

**Pull request closed without merging**
