### PR TITLE
COMMERCE-5717 Use different command name for categories and products

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Review by dsitu — CHANGES_REQUESTED** [review]
We should update the jsp names to match the MVCRenderCommand name also. 
`/commerce-product-asset-categories-web/.../edit_cp_display_layout.jsp -> edit_category_cp_display_layout.jsp`
`/commerce-product-definitions-web/.../edit_cp_display_layout.jsp -> edit_product_cp_display_layout.jsp`

**Comment by Commando18** [comment]
@dsitu Did it, Thanks!

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
