### PR TITLE
COMMERCE-11406 - Custom order statuses not shown correctly in placed order history

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11406](https://issues.liferay.com/browse/COMMERCE-11406)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
