### PR TITLE
COMMERCE-10974 Remove commerce-account-api/service

### PR DESCRIPTION
**Pull request by luca-pellizzon**
https://issues.liferay.com/browse/COMMERCE-10974

from https://github.com/liferay-commerce/liferay-portal/pull/3682

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:stop

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
relevant failed tests are not caused by this PR

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Comment by luca-pellizzon** [comment]
c:forward:force

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
