### PR TITLE
Commerce 11387

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
Jira : https://issues.liferay.com/browse/COMMERCE-11387
New PR : https://github.com/liferay-commerce/liferay-portal/pull/3804

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@MahmoudAzzam this doesn't look wrong, but looking at the related bug I see the exception is somehow related to the minicart, did you make sure you don't need to put the catch also for minicart (or any other widget)?

Thank you!

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
