### PR TITLE
COMMERCE-12227 Update Modal to add a Price Entry for a SKU with UOM+Automation

### PR DESCRIPTION
**Pull request by baharturk**
https://liferay.atlassian.net/browse/COMMERCE-12227

sent from: #4418

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
Review Passed!

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures in the relevant are not related to the PR. It can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
