### PR TITLE
COMMERCE-11276 Price on Application on Price Lists & Promotions

### PR DESCRIPTION
**Pull request by pietrobocale**
Base PR: #3841 and #3872

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Fix conflicts and resent on https://github.com/liferay-commerce/liferay-portal/pull/3888

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
