### PR TITLE
COMMERCE-9200 | Fix replacement SKU for diagram

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #3193 

https://issues.liferay.com/browse/COMMERCE-9200

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Review by lorenzolapescara — APPROVED** [review]

**Pull request closed without merging**
