### PR TITLE
COMMERCE-9413 As omni-admin user, new accounts are not shown on the Account Selector in Minium Demo

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-9413

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
QA Passed. Forwarding

**Comment by lorenzolapescara** [comment]
ci :forward

**Pull request closed without merging**
