### PR TITLE
COMMERCE-9851 - (commerce-pricing-web) - button to create new promoti…

### PR DESCRIPTION
**Pull request by brianikim**
…on now has correct hover text

@andrea-ale-sbarra ,

low priority pull request.

https://issues.liferay.com/browse/COMMERCE-9851

From @Victorcdp ,

> The button to create a new Promotion was with the wrong hover text. Proposed fix is to change the text to the correct one.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
Hey @brianikim , Fabio discovered that this solution breaks something else, the same button is being used for the Promotions and Price Lists, so the hover text is the same on both pages, if we change the hover text to show "Create New Promotion" like in this PR, then in the Price Lists page it will show the same thing.

**Comment by elocamp** [comment]
Hey, @brianikim 
I send another [PR](https://github.com/alessiorendina/liferay-portal/pull/24) with my solution

**Comment by andrea-ale-sbarra** [comment]
fix sent here: https://github.com/liferay-commerce/liferay-portal/pull/3337

**Pull request closed without merging**
