### PR TITLE
COMMERCE-9998 return all orders on the Global Search by email

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
https://issues.liferay.com/browse/COMMERCE-9998

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you @MahmoudAzzam

**Comment by baharturk** [comment]
ci:test:commerce

**Pull request closed without merging**
