### PR TITLE
LPD-29557 - Refactor AccountRoles#CanExportRolesViaAPI as a Playwright test

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-29557

### CODE REVIEW

**Comment by matyaswollner** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by matyaswollner** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
