### PR TITLE
LPD-17890 - Database Issue related to the utilization of a properties combination

### PR DESCRIPTION
**Pull request by victorcdp**
@smottal Can you review this one? Tied to an LPP. Thank you.

Relevant Issue: [LPD-17890](https://liferay.atlassian.net/browse/LPD-17890)

### CODE REVIEW

**Comment by victorcdp** [comment]
@smottal Updated it with the change required. Thank you.

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
@victorcdp do you think is it possible to create some kind of automation test for this?

**Comment by victorcdp** [comment]
Hi @smottal, for the test, do you mean testing the upgrade itself or testing the whole ticket reproduction?
Also, I'm running CI again because the column name was wrong in the update commit and most likely that was the cause of all the CI errors.

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by smottal** [comment]
@victorcdp a test that now creating the link it's "complete" and not truncated anymore (as I imagine it was before)

**Comment by victorcdp** [comment]
@smottal I added a new commit with a test, i put it into user-test because i didn't know where to put it. Can you please take a look? Thank you

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
