### PR TITLE
Automated Test - COMMERCE-6170 | master

### PR DESCRIPTION
**Pull request by IsaVV**

### CODE REVIEW

**Comment by IsaVV** [comment]
https://issues.liferay.com/browse/COMMERCE-6170, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class,'applications-menu-sites')]//span[normalize-space(text())='Minium']"

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by IsaVV** [comment]
fixed conflict

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Pull request closed without merging**
