### PR TITLE
COMMERCE-9483 Add new functional test

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://issues.liferay.com/browse/COMMERCE-9483

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Review by lorenzolapescara — CHANGES_REQUESTED** [review]

**Review by lorenzolapescara — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
@22LucaGiannotta22 please resolve the conflicts and relaunch the tests. Thanks!

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
