### PR TITLE
LPS-199518 XSS when rendering Role and Organization data under Account administration+functional test

### PR DESCRIPTION
**Pull request by saramart81**
sent from #4346 
https://liferay.atlassian.net/browse/LPS-199518

### CODE REVIEW

**Comment by saramart81** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
Review Passed

Thanks!

**Comment by saramart81** [comment]
ci:test:relevant

**Review by pietrobocale — APPROVED** [review]

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:um

**Comment by pietrobocale** [comment]
ci:stop

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:um

**Comment by saramart81** [comment]
ci:test:stable

**Comment by saramart81** [comment]
ci:test:um

**Comment by saramart81** [comment]
ci:test:um

**Comment by saramart81** [comment]
Hi @victoroscuro this PR is good please help force-forward it, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
