### PR TITLE
LPD-41036 - publishing to remote staging setup can fail due to missing organization ref with a blogs aggregator portlet

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @smottal,

https://liferay.atlassian.net/browse/LPD-41036, tied to LPP.

This is an extension of the work done on https://liferay.atlassian.net/browse/LPD-36031 which fixed an issue where staging could fail publishing due to issues with a missing Organization reference for the Blogs Aggregator portlet. The issue still occurs in remote staging setups due to an issue with the companyID being checked against. The fix addresses it by properly checking against the correct companyID. 

Since this is specifically only replicated through attempting to publish the Blogs Aggregator portlet the test is written in that test suite and I'll send it to the Content Management team for review once this has your approval. The fix itself however is contained within our own code.

As a note, the commit "LPD-41036 - this looks wrong?" (277d11e5c7216db85779920490ed403e81c89882 ) is an addition I made that is technically unrelated to the fix itself but fixes what appears to be an incorrect variable being passed. Please let me know if you would like this removed or otherwise spun off into a different ticket. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by smottal** [comment]
hey @wanderlast , could you please give me more context on this? In particular about what you are trying to test because the test you did is very "hard" to understand (in particular this part)

```
	PropsValuesTestUtil.swapWithSafeCloseable(
					"TUNNELING_SERVLET_SHARED_SECRET",
					"F0E1D2C3B4A5968778695A4B3C2D1E0F");
			SafeCloseable safeCloseable2 =
				PropsValuesTestUtil.swapWithSafeCloseable(
					"TUNNELING_SERVLET_SHARED_SECRET_HEX", true)) {
```

and I would like to find a simplest solution.
Thx

**Comment by wanderlast** [comment]
> hey @wanderlast , could you please give me more context on this? In particular about what you are trying to test because the test you did is very "hard" to understand (in particular this part)
> 
> ```
> 	PropsValuesTestUtil.swapWithSafeCloseable(
> 					"TUNNELING_SERVLET_SHARED_SECRET",
> 					"F0E1D2C3B4A5968778695A4B3C2D1E0F");
> 			SafeCloseable safeCloseable2 =
> 				PropsValuesTestUtil.swapWithSafeCloseable(
> 					"TUNNELING_SERVLET_SHARED_SECRET_HEX", true)) {
> ```
> 
> and I would like to find a simplest solution. Thx

Sure, so that is to setup an instance of remote staging within CI since the issue itself is only reproducible with remote staging. The values themselves are arbitrary and were chosen simply as the default values found throughout other instances of Liferay (e.g. https://help.liferay.com/hc/en-us/articles/360058563132-Configuring-instances-for-remote-live-staging or some of the other tests). The idea behind the test is setup remote staging > attempt to publish. Since we know if the publish is successful we did not encounter the error, we simply validate whether it was successfully done.

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Pull request closed without merging**
