### PR TITLE
Automated Test - COMMERCE-6158 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/COMMERCE-6158, cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
Review started.

**Review by lorenzolapescara — CHANGES_REQUESTED** [review]

**Comment by 91nilo** [comment]
Hi @lorenzolapescara, i did the changes, if you need anything else, just tell me. Thank you!

**Review by lorenzolapescara — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Review by lorenzolapescara — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
