### PR TITLE
COMMERCE-11017

### PR DESCRIPTION
**Pull request by brianikim**
@luca-pellizzon , included @dsitu 's commits from COMMERCE-11011 and COMMERCE-11012 for compatibility purposes.

https://issues.liferay.com/browse/COMMERCE-11017

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3619

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
looks like a unrelated failur, rerunning ci

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@brianikim please keep this in synch and resolve conflicts. Thanks

**Comment by brianikim** [comment]
@luca-pellizzon , waiting on [COMMERCE-11012](https://github.com/liferay-commerce/liferay-portal/pull/3608) to be updated before syncing. My PRs are dependent on COMMERCE-11012.

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
Identified the failure. Investigating. Expected PR update by tomorrow.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Blocked by ci:test:sf failure caused by https://issues.liferay.com/browse/POSHI-528. Need to wait until it is fixed.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by victoroscuro** [comment]
@brianikim I analysed the last two relevant runs and the failures seem not to be related to the changes made to this PR. I am going to force-forward it. FYI @luca-pellizzon

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
