### PR TITLE
COMMERCE-10944 set CommerceGroupThreadLocal

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
Failures on relevant are unrelated to this PR

**Pull request closed without merging**
