### PR TITLE
COMMERCE-6438 If product has options whatsoever, the user shall be forced to view its variants in the product detail (in FS)

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
From https://github.com/liferay-commerce/liferay-portal/pull/985 with couple of changes.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
