### PR TITLE
Add to cart button refactored to handle multiple skus + SbD table improved

### PR DESCRIPTION
**Pull request by fabio-d-m**

### CODE REVIEW

**Review by upalatucci — APPROVED** [review]

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by ivicac** [comment]
ci:test:commerce

**Pull request closed without merging**
