### PR TITLE
LPD-26733 Support for Objects entry permissions on Roles UI

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-26733

### CODE REVIEW

**Review by luca-pellizzon — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:repot:11884677

**Comment by smottal** [comment]
ci:report:12038410

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
