### PR TITLE
LPD-15876 Payments Listing Page - Header fields must be searchable

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-15876

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
