### PR TITLE
COMMERCE-11504 APIs to Link Catalogue to an Account + JSON macro fix

### PR DESCRIPTION
**Pull request by baharturk**
https://issues.liferay.com/browse/COMMERCE-11004

sent from #3771 with a macro fix

@dsitu

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures on the relevant are not related to the PR.

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
