### PR TITLE
COMMERCE-7277 Add functional tests

### PR DESCRIPTION
**Pull request by baharturk**
https://issues.liferay.com/browse/COMMERCE-7277

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:stop

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
