### PR TITLE
COMMERCE-6398 Custom OrderStatus label not displayed in header action labels

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@alecsloan please have a look at this to see if it's ok according to what we said. Thx

**Comment by alecsloan** [comment]
> @alecsloan please have a look at this to see if it's ok according to what we said. Thx

Looks good to me, Thanks!

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
