### PR TITLE
COMMERCE-12658 Channel Restriction on Account Addresses

### PR DESCRIPTION
**Pull request by pietrobocale**
Ticket: https://liferay.atlassian.net/browse/COMMERCE-12658

Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4484

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
The failures are not related to the PR

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
