### PR TITLE
LPS-196309 Filter Users that are not associated with Accounts or Organizations + Automation

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi @smottal,
Please help me to review this PR. Thanks.
This is the PR for story: https://liferay.atlassian.net/browse/LPS-196309
Due to Brian Chan's review, I updated the name of model Account to AccountEntry
old pr: https://github.com/brianchandotcom/liferay-portal/pull/144639
cc @tototrinh

### CODE REVIEW

**Review by smottal — APPROVED** [review]
LGTM! Thx

**Comment by smottal** [comment]
@baharturk could you please also the tests moving Account -> AccountEntry? Thx

**Comment by baharturk** [comment]
ci:test:um

**Comment by baharturk** [comment]
The failures are not related to this PR. It can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
