### PR TITLE
LPD-40177 | LPD-37597 | LPD-37596 | LPD-37595 | LPD-37593 | LPD-37592 | LPD-37591 Allow exporting and importing one Page referencing

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-40177
https://liferay.atlassian.net/browse/LPD-37597
https://liferay.atlassian.net/browse/LPD-37596
https://liferay.atlassian.net/browse/LPD-37595
https://liferay.atlassian.net/browse/LPD-37593
https://liferay.atlassian.net/browse/LPD-37592
https://liferay.atlassian.net/browse/LPD-37591

@alessiorendina

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:8860475

**Comment by CrescenzoRegaLF** [comment]
ci:report:88604750

**Comment by CrescenzoRegaLF** [comment]
@alessiorendina I checked the results of the ci
- ci:test:relevant is ok
- ci:test:commerce-functional is ok
- ci:test:upgrade is ok

**Comment by alessiorendina** [comment]
@CrescenzoRegaLF confirmed that failures are not related to the PR.

**Comment by alessiorendina** [comment]
ci:forward:force

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Comment by michaelhashimoto** [comment]
`88604750`

**Comment by michaelhashimoto** [comment]
88604750

**Pull request closed without merging**
