### PR TITLE
COMMERCE-11297

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3737

https://issues.liferay.com/browse/COMMERCE-11297

@luca-pellizzon ,

Need new review on ac85564^..73a464d

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
@brianikim if the user doesn't have the permission we should not show the button instead of just managing the permission after "the click"

**Comment by brianikim** [comment]
@luca-pellizzon , See: https://github.com/liferay-commerce/liferay-portal/pull/3762/commits/39cf2817098ef770dacaf2d4ba28f7a1754893d1 for requested change.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
@brianikim there are conflicts on the PR, can you please have a look at them? Thanks!

cc @luca-pellizzon

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@lorenzolapescara , the conflicts were because COMMERCE-11297 got merged. I resolved the conflicts. cc/ @luca-pellizzon

**Comment by lorenzolapescara** [comment]
Re-sent with automation at #3789.
Thanks!

**Pull request closed without merging**
