### PR TITLE
LPD-27339 - add support for cc and bcc in commerce notifications

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @andrea-ale-sbarra,

https://liferay.atlassian.net/browse/LPD-27339, tied to LPP.

I've added CC and BCC support for notifications due to the client's request per Bernard's statement in [PTR-4861](https://liferay.atlassian.net/browse/PTR-4861) and [this slack thread](https://liferay.slack.com/archives/G9CMBBA9H/p1716222504166119). It works in an identical manner to the To field. An integration test is also included.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
