### PR TITLE
COMMERCE-7229 Refactor CPMedia to package com.liferay.commerce.product.content.util

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
@alecsloan can you please fix SF?

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
@ivicac I ended up moving the interface into a package that corresponds with the implementations. If I move the interface to commerce-product-api like I had originally, that means I would have to move CPContentHelper and CPContentHelperImpl respectively.

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
@alecsloan can you please fix SF?

**Comment by ivicac** [comment]
@alecsloan it seems also baseline is required

**Comment by alecsloan** [comment]
cci:test:sf

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
