### PR TITLE
LPD-18470

### PR DESCRIPTION
**Pull request by brianikim**
@smottal ,

https://liferay.atlassian.net/browse/LPD-18470
With functional test. Sorry about the delay. Had to work out lot of kinks with the functional test.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:playwright

**Review by smottal — APPROVED** [review]
Good for me! Thx

**Comment by smottal** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:playwright

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@smottal , I updated the PR. Extremely minor change. Just changed a typo on the commit message.

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
