### PR TITLE
Commerce 12504 joao

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
resend of https://github.com/liferay-commerce/liferay-portal/pull/4406

---

Accommodating the changes requested by @andrea-ale-sbarra. Created new addEntity methods to be used exclusively by headless.
Used the [presence](https://github.com/liferay-commerce/liferay-portal/pull/4406/commits/b41eb74392b8d862f88c4d759d7dca5eac134231#diff-0df63818e5a102dad660cfee16d3c00c6aeeae966b0bb8057f76df31d3367294R78) of OptionValues sent to determine whether the ProductOption will import the default Option Values or not. If the user sends an array of OptionValues, then they will be created/updated; if the user sends an empty array of OptionValues, then the default ones will be imported.

[Pulled](https://github.com/liferay-commerce/liferay-portal/pull/4406/commits/5e70c5c8b25efde68b5d5cdc9a9eccb944c300d6#diff-29f705ffd258b4a5c752c2cb3c483fe05fbb49358512cf8602f966a6cbce7bd7L1102-L1108) a validation from _validateLinkedCPDefinitionOptionValueRel and put it into it's [own method](https://github.com/liferay-commerce/liferay-portal/pull/4406/commits/5e70c5c8b25efde68b5d5cdc9a9eccb944c300d6#diff-29f705ffd258b4a5c752c2cb3c483fe05fbb49358512cf8602f966a6cbce7bd7R1099-R1110) since the new add method needs this validation and the _validateLinkedCPDefinitionOptionValueRel [won't run](https://github.com/liferay-commerce/liferay-portal/pull/4406/commits/5e70c5c8b25efde68b5d5cdc9a9eccb944c300d6#diff-29f705ffd258b4a5c752c2cb3c483fe05fbb49358512cf8602f966a6cbce7bd7R1157-R1159) for new OptionValueRels.
The rest of the validations  on _validateLinkedCPDefinitionOptionValueRel don't need to be run as they're already enforced in the new addCPDefinitionOptionValueRel method.

Relevant Issue: [COMMERCE-12504](https://liferay.atlassian.net/browse/COMMERCE-12504)
Resent of #4387 and #4375.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
The failures in the relevant are not related to the changes

@victoroscuro

**Pull request closed without merging**
