### PR TITLE
LPD-29996 Fix LocalFile.CommerceAccountSupplierRole#CanSupplierEditOrderNotes

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-29996

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
the problem has already been solved

**Pull request closed without merging**
