### PR TITLE
COMMERCE-6529 Batch engine UI and test updates

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@matijapetanjek merged, see my origin for many changes

also

src/test/java/com/liferay/batch/engine/internal/reader/CSVBatchEngineImportTaskItemReaderTest.java
src/test/java/com/liferay/batch/engine/internal/reader/JSONBatchEngineImportTaskItemReaderTest.java
src/test/java/com/liferay/batch/engine/internal/reader/JSONLBatchEngineImportTaskItemReaderTest.java
src/test/java/com/liferay/batch/engine/internal/reader/XLSBatchEngineImportTaskItemReaderTest.java
src/test/java/com/liferay/batch/engine/internal/task/progress/JSONBatchEngineTaskProgressTest.java
src/test/java/com/liferay/batch/engine/internal/task/progress/JSONLBatchEngineTaskProgressTest.java
src/test/java/com/liferay/batch/engine/internal/writer/CSVBatchEngineExportTaskItemWriterTest.java
src/test/java/com/liferay/batch/engine/internal/writer/JSONBatchEngineExportTaskItemWriterTest.java
src/test/java/com/liferay/batch/engine/internal/writer/JSONLBatchEngineExportTaskItemWriterTest.java
src/test/java/com/liferay/batch/engine/internal/writer/XLSBatchEngineExportTaskItemWriterTest.java


Those should all be named after the IMPL because it is in the impl package.


JSONLBatchEngineImportTaskItemReaderTest

should be

JSONLBatchEngineImportTaskItemReaderImplTest

Please rename all and send me a follow up pull (just bypass CI)

Thx!

@igorbeslic fyi

**Comment by matijapetanjek** [comment]
ci:close

**Pull request closed without merging**
