### PR TITLE
LPD-22282 UPS client extension

### PR DESCRIPTION
**Pull request by alessiorendina**
Added test requested here: https://github.com/brianchandotcom/liferay-portal/pull/151768

https://liferay.atlassian.net/browse/LPD-22282

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:playwright

**Comment by alessiorendina** [comment]
ci:report:27602419

**Review by luca-pellizzon — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:playwright

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
