### PR TITLE
COMMERCE-7597 Remove delete action for base pricelist and promotions

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-7597

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — COMMENTED** [review]
This way we are not removing the action, but the content of the action, right?

**Comment by luca-pellizzon** [comment]
> > This way we are not removing the action, but the content of the action, right?
> > Hey @luca-pellizzon, I suppose its removing it from the response in api calls related to that pricelist. So the delete action wont show up as a available api call to who ever calls on a pricelist api. Although I believe they can still try to call the delete api call but will be hit by the cannot delete baseCatalogPriceListException. This is how dataset headless checks what actions are available for a specify pricelist.

I was asking because I see that the "delete" item is still added to the list of action, we are with this just setting the value to null. I was wondering if in the response I will see something like
{
"delete":
"get": getURL
}
instead of having something like
{
"get": getURL
}
regarding the entry that cannot be deleted.

**Comment by dsitu** [comment]
> > > This way we are not removing the action, but the content of the action, right?
> > > Hey @luca-pellizzon, I suppose its removing it from the response in api calls related to that pricelist. So the delete action wont show up as a available api call to who ever calls on a pricelist api. Although I believe they can still try to call the delete api call but will be hit by the cannot delete baseCatalogPriceListException. This is how dataset headless checks what actions are available for a specify pricelist.
> 
> @dsitu
> 
> I was asking because I see that the "delete" item is still added to the list of action, we are with this just setting the value to null. I was wondering if in the response I will see something like { "delete": "get": getURL } instead of having something like { "get": getURL } regarding the entry that cannot be deleted.

oh ic, yeah so it will remove the delete action correctly from the response. We will see something like this for a pricelist that can not be deleted.

"actions": {
        "permissions": {
          "method": "PATCH",
          "href": "http://localhost:8080/o/headless-commerce-admin-pricing/v2.0/price-lists/556011"
        },
        "get": {
          "method": "GET",
          "href": "http://localhost:8080/o/headless-commerce-admin-pricing/v2.0/price-lists/556011"
        },
        "update": {
          "method": "PATCH",
          "href": "http://localhost:8080/o/headless-commerce-admin-pricing/v2.0/price-lists/556011"
        }
      }

**Review by luca-pellizzon — APPROVED** [review]

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
