### PR TITLE
LPS-205475 Avoid test error on HSQL

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPS-205475

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:playwright:nocompile

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
