### PR TITLE
COMMERCE-11518 Prevent Users from checking out a Quote + Functional tests

### PR DESCRIPTION
**Pull request by baharturk**
https://issues.liferay.com/browse/COMMERCE-11296

sent from: #3855 

@luca-pellizzon

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Review by lorenzolapescara — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures on the relevant are not related to the PR. This is good to go!

@luca-pellizzon

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
