### PR TITLE
COMMERCE-5923 Fix test CPCommerceProducts#CreateProductBundleWithPriceTypeDynamic

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5923

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
