### PR TITLE
COMMERCE-10834 Virtual Product Activation Status Complete and Processing is not respected 

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10834

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you @CrescenzoRegaLF

**Comment by jaydawu** [comment]
QA passed. Remove ignore tags from the passed test cases and resent to https://github.com/liferay-commerce/liferay-portal/pull/3572

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
