### PR TITLE
LPD-34383 - Account group api

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-34383

cc @smottal

### CODE REVIEW

**Comment by matyaswollner** [comment]
ci:test:sf

**Comment by matyaswollner** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:stop

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:28317755

**Comment by smottal** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
