### PR TITLE
COMMERCE-10775

### PR DESCRIPTION
**Pull request by lorenzolapescara**
Re-send of #3463.

Ticket: [COMMERCE-10775](https://issues.liferay.com/browse/COMMERCE-10775)

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
