### PR TITLE
COMMERCE-6585 Fix cp display layout edits

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-6585

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
@dsitu can you please fix the conflict?

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
@dsitu can you please fix the conflict, again?

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
Resent at https://github.com/liferay-commerce/liferay-portal/pull/1511

**Pull request closed without merging**
