### PR TITLE
LPD-37780 

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
From: https://github.com/liferay-commerce/liferay-portal/pull/5602

Just for SF. \cc @alessiorendina

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:foward:force

**Pull request closed without merging**
