### PR TITLE
COMMERCE-7178 portrait pictures ratio fixed on product thumbnails and cards

### PR DESCRIPTION
**Pull request by fabio-d-m**
I've used clay stickers when possibile.
In cards I created a custom class which applies `object-fit`

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:stop

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
