### PR TITLE
[TS] LPS-194611

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Rebased.

**Comment by marianoalvarosaiz** [comment]
Rebased.

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
@andrea-ale-sbarra the failures are not related to the changes in the PR. Manual upgrade test is ok.

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
The failures in the relevant and commerce-functional are not related to the PR. It can be forwarded.
@victoroscuro

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
