### PR TITLE
COMMERCE-4277 Adding External Reference Code to CPTaxCategory

### PR DESCRIPTION
**Pull request by CalvinKeum**

### CODE REVIEW

**Comment by CalvinKeum** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@CalvinKeum please rebase

**Comment by kevinccruz** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/158

New PR with rebase sent here.

**Comment by dsitu** [comment]
Closing was resent here https://github.com/liferay-commerce/liferay-portal/pull/158.

**Pull request closed without merging**
