### PR TITLE
LPD-3230, LPD-16623

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

https://liferay.atlassian.net/browse/LPD-3230,
https://liferay.atlassian.net/browse/LPD-16623

Tied to LPP

I am not sure if we need functional tests for these. Please let me know.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
failures don't look related to the changes of this PR.

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
