### PR TITLE
LPD-34682 - part 1

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-34682

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
Hey @dsitu  if the pr passes your review could you forward it. thanks in advance

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:forward

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Pull request closed without merging**
