### PR TITLE
Commerce 11255

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-11255

--- 

Fix of conflicts from here https://github.com/liferay-commerce/liferay-portal/pull/3666

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
@andrea-ale-sbarra it seems there's an error while compiling the portal. 
`[exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/upgrade/registry/CommerceServiceUpgradeStepRegistrator.java:110: error: constructor CommerceAccountUpgradeProcess in class com.liferay.commerce.internal.upgrade.v2_2_0.CommerceAccountUpgradeProcess cannot be applied to given types;
     [exec] 			new com.liferay.commerce.internal.upgrade.v2_2_0.
     [exec] 			^
     [exec]   required: com.liferay.account.service.AccountEntryLocalService,com.liferay.account.service.AccountEntryOrganizationRelLocalService,com.liferay.account.service.AccountEntryUserRelLocalService,com.liferay.portal.kernel.service.EmailAddressLocalService,com.liferay.portal.kernel.service.OrganizationLocalService,com.liferay.portal.kernel.service.RoleLocalService
     [exec]   found: com.liferay.commerce.account.service.CommerceAccountLocalService,com.liferay.commerce.account.service.CommerceAccountOrganizationRelLocalService,com.liferay.portal.kernel.service.EmailAddressLocalService,com.liferay.portal.kernel.service.OrganizationLocalService
     [exec]   reason: actual and formal argument lists differ in length
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/upgrade/registry/CommerceServiceUpgradeStepRegistrator.java:115: error: constructor CommerceOrderUpgradeProcess in class com.liferay.commerce.internal.upgrade.v2_2_0.CommerceOrderUpgradeProcess cannot be applied to given types;
     [exec] 			new com.liferay.commerce.internal.upgrade.v2_2_0.
     [exec] 			^
     [exec]   required: com.liferay.account.service.AccountEntryLocalService,com.liferay.account.service.AccountEntryUserRelLocalService,com.liferay.portal.kernel.service.UserLocalService
     [exec]   found: com.liferay.commerce.account.service.CommerceAccountLocalService,com.liferay.portal.kernel.service.UserLocalService
     [exec]   reason: actual and formal argument lists differ in length
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 2 errors
     [exec] 
     [exec] > Task :apps:commerce:commerce-service:compileJava FAILED`
Check out the log file here: https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11246/jenkins-console.txt.gz?authuser=0

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
