### PR TITLE
COMMERCE-10778 Mini cart fragment

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10778

Previous PR: https://github.com/liferay-commerce/liferay-portal/pull/3478

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
@andrea-ale-sbarra for review

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by baharturk** [comment]
Stable is green. All the failing tests on the relevant are not related to the PR itself. This is good to go.

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
