### PR TITLE
COMMERCE-7047 Wrap it in aui form so it can be published properly.

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-7047

We only accept forms with following namespace:

`var form = document.getElementById('<portlet:namespace />fm');`

https://github.com/liferay-commerce/liferay-portal/blob/a4e6ca098566e12cd033072c7e5326a3bbe5ae8b/modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/edit_cp_definition.jsp#L79

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:stop

**Pull request closed without merging**
