### PR TITLE
COMMERCE-9930 Remove unused dependency

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:staging

**Comment by iovaneale** [comment]
@JessieZhao0714 this PR should fix the issue you found. I triggered "ci:test:staging", let's see if it works.

Thanks for reporting.

/cc @gaborlovasdotcom

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:reevaluate:1347401_2724

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Pull request closed without merging**
