### PR TITLE
Automated Test - COMMERCE-6121| master

### PR DESCRIPTION
**Pull request by wesleyroberts**

### CODE REVIEW

**Comment by wesleyroberts** [comment]
https://issues.liferay.com/browse/COMMERCE-6121; cc: @Pietro69

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@wesleyroberts 

There are a lot of commits and files changed on this pull request. Please rebase, fix, and resend.

**Comment by wesleyroberts** [comment]
> @wesleyroberts
> 
> Existem muitos commits e arquivos alterados nesta solicitação pull. Faça o rebase, corrija e reenvie.

ok, i will go.

**Comment by wesleyroberts** [comment]
> @wesleyroberts
> 
> There are a lot of commits and files changed on this pull request. Please rebase, fix, and resend.

Changes made.

**Comment by wesleyroberts** [comment]
> @wesleyroberts
> 
> There are a lot of commits and files changed on this pull request. Please rebase, fix, and resend.

@kristinonias 
changes made

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:stop

**Comment by wesleyroberts** [comment]
rebase done

**Comment by wesleyroberts** [comment]
conflicts resolved

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
New PR sent in: #1340 
Please Close

**Pull request closed without merging**
