### PR TITLE
Automated Test - COMMERCE-6333 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6333 , cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
EditCartItemQuantityFromMiniCart passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
