### PR TITLE
COMMERCE-9713 Fixed new product images issue

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-9713

use the right group id and permission on newly added CPFileEntries

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
Thank you @alessiorendina

**Comment by alessiorendina** [comment]
Hey @andrea-ale-sbarra do I have to rebase it and re-run CI or we can forward it?

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
