### PR TITLE
COMMERCE-5499 SF Rename constants with *_SERVICE_NAME

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-5499

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by marco-leo — APPROVED** [review]

**Comment by marco-leo** [comment]
@riccardo-alberti up to you forwarding this

**Comment by riccardo-alberti** [comment]
@dsitu could you please rebase this so i can forward it? thx

**Comment by dsitu** [comment]
> @dsitu could you please rebase this so i can forward it? thx

@riccardo-alberti kk rebased

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
