### PR TITLE
Automated Test - COMMERCE-6111 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6111 ; cc: @pietro69

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
Review started

**Comment by Pietro69** [comment]
Hey, I made a mistake in the description the step 6 says: Click on the Edit button for Variable Rate but it's wrong is not Variable Rate but Flat Rate, can you please change this into the test?

Sorry again for this lack

**Comment by Pietro69** [comment]
I fixed the description, please check again the steps 6 and 13

**Comment by pedroalmd** [comment]
@Pietro69 fixed it

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
