### PR TITLE
COMMERCE-8318

### PR DESCRIPTION
**Pull request by brianikim**
@riccardo-alberti 

https://issues.liferay.com/browse/COMMERCE-8318

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@brianikim https://issues.liferay.com/browse/COMMERCE-7855 you may want to check this.
Not sure why these changes got lost

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
