### PR TITLE
COMMERCE-11447 use right serviceContext

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11447
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3866

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]
QA Review Passed

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Just waiting for the commerce-functional results to come out and analyze if all tests are not related. Because a few tests didn't run successfully last time. Then it can be forwarded, thanks.

cc/ @victoroscuro

**Comment by victoroscuro** [comment]
Tests are ok now, I'll force forward it. Thanks

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
