### PR TITLE
COMMERCE-9488 New order details page default configuration

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9488

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@dsitu lots of failures in functional tests with this code. Could you please have a look at all the failures?

**Comment by dsitu** [comment]
> @dsitu lots of failures in functional tests with this code. Could you please have a look at all the failures?

Hey @luca-pellizzon after analysis I believe the unique failures are expected because we now default to the new order page.
Errors found:
1. `com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class,'portlet') and contains(@class,'container')]//a[span/*[name()='svg'][contains(@class,'icon-ellipsis')]] | //*[contains(@class,'sheet-title')]//*[contains(@class,'dropdown-toggle')][.//*[name()='svg'][contains(@class,'icon-ellipsis')]]"`

2. `//div[@id='main-content']//div[contains(@class,'portlet')]//section[contains(@id,'Checkout')]`

Let me know if I should update the functional test.

**Comment by luca-pellizzon** [comment]
Thank you @dsitu
QA will take care of fixing the tests.

**Comment by iovaneale** [comment]
Sent to #3112 

@dsitu please close this one.

/cc @luca-pellizzon

**Comment by dsitu** [comment]
Closing, thanks @iovaneale!

**Pull request closed without merging**
