### PR TITLE
COMMERCE-12951 Update delivery APis to support extra information

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12951

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:test:stable

**Comment by pietrobocale** [comment]
The failures are not related to the PR

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
Close this directly since the pr has been forwarded manually to BChan's repo, and already merged into master.
See https://github.com/brianchandotcom/liferay-portal/pull/144322

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
