### PR TITLE
COMMERCE-9025 Fixed product info item permission checking

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
I've worked in peer with @alessiorendina so I've seen this code already working

**Comment by andrea-ale-sbarra** [comment]
ci:test.relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
QA Passed

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
