### PR TITLE
COMMERCE-6432 ArrayIndexOutOfBoundsException in MercanetServlet coming back from a payment (sandbox)

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@luca-pellizzon could you please have a look at this? thx

**Review by luca-pellizzon — APPROVED** [review]

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
