### PR TITLE
COMMERCE-12452 - Console errors appear after upgrading from 7.2 then manually reindexing assets

### PR DESCRIPTION
**Pull request by victorcdp**
@andrea-ale-sbarra Can you review this one? Tied to an LPP. Thank you.
Related Issue: [COMMERCE-12452](https://liferay.atlassian.net/browse/COMMERCE-12452)

When upgrading from 7.2.10.1 to Master and indexing for the first time, NPEs were being thrown in the places changed because the AccountEntry and CommerceContext were null. These parameters were null because the methods are called while the fragments are being validated, so there's no commerceContext or accountEntry defined in this situation.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
No related errors to this pull, it can be force-forwarded, thanks!
cc/ [victoroscuro](https://github.com/victoroscuro)

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
