### PR TITLE
Automated Test - COMMERCE-5864 | master

### PR DESCRIPTION
**Pull request by juliaduartelira**

### CODE REVIEW

**Comment by juliaduartelira** [comment]
https://issues.liferay.com/browse/COMMERCE-5864, cc: @lorenzo.lapescara

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
@juliaduartelira  The pull request failed due to source formatting. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Pull request closed without merging**
