### PR TITLE
COMMERCE-4917 Ensure that assetCategory is passed to template and id is rendered on config page

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevance

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevance

**Comment by ivicac** [comment]
ci:test:relevance

**Review by dsitu — APPROVED** [review]

**Review by marco-leo — APPROVED** [review]

**Comment by ivicac** [comment]
ci:test:relevance

**Comment by ivicac** [comment]
@alecsloan can you please check why ci:test:relevance is failing?

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
