### PR TITLE
LPD-3491 Country not localized in the shipment shipping address

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-3491

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Review by luca-pellizzon — CHANGES_REQUESTED** [review]
That not a solution, you are just replacing name with title you are not getting the localized value. To get the localized value you must use the
`Country country.getName(Locale locale)`

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
