### PR TITLE
LPD-34386 - User group API

### PR DESCRIPTION
**Pull request by matyaswollner**
https://liferay.atlassian.net/browse/LPD-34386

cc @smottal

### CODE REVIEW

**Comment by matyaswollner** [comment]
ci:test:sf

**Comment by matyaswollner** [comment]
cc @smottal

**Comment by matyaswollner** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:59073457

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
