### PR TITLE
COMMERCE-8685 upgradeProcess to prevent duplicate ERC for taxCategories

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-8685

Sending initial PR, let me know if there are additional changes I missed.

@luca-pellizzon

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]
Looks fine to me, we must test the compatibility of "having count" with all kind of databases, but the relevant should take care of that.

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@brianikim rebase pls

**Comment by brianikim** [comment]
@luca-pellizzon , PR is rebased

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
@luca-pellizzon relevant runs only on mysql57, if we need to run this on other dbs we'll have to set it up FYI @brianikim

**Comment by luca-pellizzon** [comment]
@victoroscuro mysql should be ok. These queries are pretty standard.
Do we still have daily tests on all DBs when merged in master? If so I think we can send it forward, when relevant is green.

**Comment by victoroscuro** [comment]
@luca-pellizzon nope, we'll have to check this on the release if we're safe doing so

**Comment by jaydawu** [comment]
After checking, the relevant and commerce-functional suites' failures are not unique to this pull. This PR should be good.

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Hi @brianikim, this pull has conflicts. Please rebase that, thanks!

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:stop:commerce

**Comment by jaydawu** [comment]
ci:stop

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
