### PR TITLE
COMMERCE-7349 Fixed diagram product type

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by Commando18** [comment]
ci:test:sf

**Comment by Commando18** [comment]
ci:forward

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
Manually sent to brian: https://github.com/brianchandotcom/liferay-portal/pull/107888

**Pull request closed without merging**
