### PR TITLE
COMMERCE-11961

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-11961,

tied to critical LPP. @andrea-ale-sbarra , need to be prioritized if possible.

Sincerely,
Brian

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — COMMENTED** [review]
LGTM.

Thank you!

**Comment by jaydawu** [comment]
QA passed. Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/4032.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
