### PR TITLE
COMMERCE-12631 Update Modal to add a Price Entry for a SKU with UOM+Automation

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12227

sent from: https://github.com/liferay-commerce/liferay-portal/pull/4349

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:stable

**Comment by baharturk** [comment]
sent here: #4427

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
