### PR TITLE
COMMERCE-11923 added POA column to PL table

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11923
Test plan: https://liferay.atlassian.net/browse/COMMERCE-12209
Resent from https://github.com/liferay-commerce/liferay-portal/pull/4152

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @andrea-ale-sbarra, could you please help force-forward this pr? Since the relevant failures are not related to this pr, thanks!

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
