### PR TITLE
LPS-195105 Migrate SearchResults.soy to react

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi guys! 😄 I would appreciate if you can take a look at this PR. I'm leaving some description and steps, thanks!

## Ticket 📄
- https://liferay.atlassian.net/browse/LPS-195105

## Context 📖
This PR migrates `SearchResults.soy` to a new react component. This way, we don't have anything else in `soy` in this module, so I could also remove `soy` dependencies.

## How to test 🧪
- Deploy `commerce-frontend-taglib`, `commerce-theme-minium` and `commerce-theme-speedwell`
- Create a Minium site and also a Speedwell site
- In both home pages, use the search bar and see the results

### Note ⚠️
When moving from a Minium site to a Speedwell one, sometimes refreshing cache is needed, as they share some CSS classes and the browser can mix them.

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
@sandrodw3 I had to send a new PR to fix failing functional tests in the commerce-functional suite. See #4287.

cc @victoroscuro @andrea-ale-sbarra

**Comment by lorenzolapescara** [comment]
ci:close

**Pull request closed without merging**
