### PR TITLE
LPS-205284 - clarify language in key tooltip when adding a new role to address accessibility concerns

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @smottal, 

https://issues.liferay.com/browse/LPS-205284, tied to LPP

Concerns were raised about the two tooltips that are found when generating a new Role (Control Panel > Roles > New Role) for the "Title" and "Key" input boxes respectively. I've already clarified that the "Title" tooltip is fine with the client which leaves only clarification needed in the "Key" tooltip. I've done so by explicitly naming that this is what's being added/edited to the tooltip.

The tooltip itself is exclusively used when adding a new role or account role, so it shouldn't affect anyone else's work.

CC: @brianikim

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
