### PR TITLE
LPD-21744 CheckoutPortletURL does not need to be fetched unless a cha…

### PR DESCRIPTION
**Pull request by brianikim**
…nnel exists.

https://liferay.atlassian.net/browse/LPD-21744

### CODE REVIEW

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
It looks good to me, thank you!

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:stable

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
I've just relaunched the suite because on testray stable seems to be not failing while here is results are different. Could be something flaky

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
