### PR TITLE
COMMERCE-9450 Redundant check. localService call already validates

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-9450

@CrescenzoRegaLF

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
@brianikim in the description it says to replicate the logic in the VisibilityCommerceOrderValidator but I don't see the change in the code

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/4223.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
