### PR TITLE
Revert "LPS-169263 Page displays not proper after clicking the cancel…

### PR DESCRIPTION
**Pull request by riccardo-alberti**
… button"

This reverts commit 1e267f567a635bac34115b0e199a265ef8d8e86e.

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
QA checks passed.

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
