### PR TITLE
LPS-195988 Increase the database AccountEntry.name column character limit to 250

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPS-195988

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
Minor CSS change so extra long names display correctly and stay within the search container text box https://github.com/liferay-commerce/liferay-portal/pull/4333/commits/6615965faaa1a032c4520c3c82af8e81b45758dd.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:um

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
Applied same CSS to Commerce related modules https://github.com/liferay-commerce/liferay-portal/pull/4333/commits/078485d85c5464225603a198485d1e58c1ebf23b.

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Comment by luca-pellizzon** [comment]
rebased here https://github.com/liferay-commerce/liferay-portal/pull/4361

**Pull request closed without merging**
