### PR TITLE
Automated Test - COMMERCE-6663 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6663 , cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
Renamed a path, after perceving that it could be used in other parts of the portal.

**Comment by kristinonias** [comment]
Running CI on [kristinonias #9](https://github.com/kristinonias/liferay-portal/pull/9)

**Pull request closed without merging**
