### PR TITLE
COMMERCE-4657 Mark order as paid if order total is 0

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@alecsloan please provide an integration test to cover this case

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
@marco-leo added an integration

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
