### PR TITLE
COMMERCE-11977 fix upgrade process

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:search

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
The upgrade test failing before is not failing anymore. Relevant is ok. commerce test suite is ok too.

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
