### PR TITLE
LPD-40613 Deprecate Commerce Notifications

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse//LPD-40613

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:78808896

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:79178425

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
> ### ❌ ci:test:commerce-functional - 162 out of 201 jobs passed in 2 hours 28 minutes
> Click here for more details.

@luca-pellizzon I checked the failures and they are not due to the changes made

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:report:80017438

**Comment by CrescenzoRegaLF** [comment]
> ### ✔️ ci:test:stable - 24 out of 24 jobs passed
> ### ❌ ci:test:relevant - 38 out of 44 jobs passed in 1 hour 31 minutes
> Click here for more details.

@luca-pellizzon I checked the failures and they are not due to the changes made

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
