### PR TITLE
LPD-37502 Update fetchByERC

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-37502

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:report:23360053

**Comment by smottal** [comment]
ci:report:24303014

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@smottal conflicts on my latest origin.

**Comment by brianchandotcom** [comment]
@smottal I fixed the conflict and manually merged this. This PR is good.

**Pull request closed without merging**
