### PR TITLE
LPD-29982 text truncation inside an `<a>`, not viceversa

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-29982

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:workflow

**Review by riccardo-alberti — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
Sent here: https://github.com/liferay-frontend/liferay-portal/pull/4290

**Pull request closed without merging**
