### PR TITLE
COMMERCE-10680 Fix "Two separate minicart items are created instead of a single one using quick add to cart along with the normal add to cart"

### PR DESCRIPTION
**Pull request by kresimir-coko**
https://issues.liferay.com/browse/COMMERCE-10680

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by kresimir-coko** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. After checking, no relevant errors to this pull.

**Comment by jaydawu** [comment]
Add automation and resend on https://github.com/liferay-commerce/liferay-portal/pull/3541

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
