### PR TITLE
Automated Test - COMMERCE-5957 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-5957 cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
SearchForAnOrderAndSelectItAsActive passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
