### PR TITLE
COMMERCE-12716 update payment status only if it is passed

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12716

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed, add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/4412

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
