### PR TITLE
COMMERCE-8433 shopping-experience  - added sku text in storefront too…

### PR DESCRIPTION
**Pull request by garofalog**
COMMERCE-8433 shopping-experience  - added sku text in storefront tooltip

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@garofalog there is a problem on your module... could you please take care? thanks

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
