### PR TITLE
LPD-15995 Fix virtual instance access to another account's address

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-15995

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:um

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward:force

**Pull request closed without merging**
