### PR TITLE
Automated Test - COMMERCE-6218  | master

### PR DESCRIPTION
**Pull request by IsaVV**

### CODE REVIEW

**Comment by IsaVV** [comment]
https://issues.liferay.com/browse/COMMERCE-6218 , @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by IsaVV** [comment]
Rebase Master Fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
