### PR TITLE
LPS-173628 Add permission check on account roles

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://liferay.atlassian.net/browse/LPS-173628

Resent from #4308

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:um

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Comment by 22LucaGiannotta22** [comment]
ci:test:stable

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to the PR. It can be force-forwarded

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
