### PR TITLE
LPD-3492 Channel and Tax (Tax Rate removed) configuration items categorized

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
Linking LPD-3489 (Site settings), LPD-3490 (System settings), LPD-3492 (Instance settings)

image

image

image

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — COMMENTED** [review]
LGTM.
I've made a question here: https://liferay.slack.com/archives/C05QY9CH336/p1707211291852879. Let's wait for an answer before moving forward

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
@andrea-ale-sbarra dropping the baseline commit and rebasing should do the job. I'll do it asap. 

Ref: https://liferay.slack.com/archives/C05QY9CH336/p1707289825215689?thread_ts=1707211291.852879&cid=C05QY9CH336

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by gianmarcobrunialti** [comment]
ci:forward:force

**Pull request closed without merging**
