### PR TITLE
COMMERCE-7335 overriding getPortletURL in CPOptionCategoryDisplayContext

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
Jira : https://issues.liferay.com/browse/COMMERCE-7335

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA Passed. The relevant errors [PortalLogAssertorTest-modules-integration-mysql57-jdk8](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2289031860&testrayRunId=2289038173&statuses=3) are not unique to this pull. Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3725.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
