### PR TITLE
COMMERCE-4776 use new catalog instead of system

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
@riccardo-alberti FYI

**Comment by marco-leo** [comment]
ci:forward

**Comment by marco-leo** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
Included in #299

**Pull request closed without merging**
