### PR TITLE
[DO NOT MERGE] LPD-18594

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-18605
https://liferay.atlassian.net/browse/LPD-18606
https://liferay.atlassian.net/browse/LPD-20673
https://liferay.atlassian.net/browse/LPD-20674
https://liferay.atlassian.net/browse/LPD-20675
https://liferay.atlassian.net/browse/LPD-20677

@luca-pellizzon . Just will be running CI to make sure it passes. This PR should only be used to confirm it passes on CLDR.

cc/ @julschong

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by julschong** [comment]
ci:report:2555514811

**Comment by julschong** [comment]
running report on `ci:test:commerce-functional`

**Comment by regiCesar21** [comment]
Hi @brianikim, @julschong. I see that there some failures related with date issues, but it's not related with the test cases that are being modified. I think we can forward with that, and later see if those tests that failed appear on another round using CLDR.

**Comment by julschong** [comment]
@brianikim @luca-pellizzon good to go. Test change related to this PR all passed both in this PR and in the CLDR PR

**Pull request closed without merging**
