### PR TITLE
Automated Test - COMMERCE-6243 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6243 ; cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedroalmd** [comment]
@kristinonias please reopen

**Comment by pedroalmd** [comment]
@kristinonias fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
