### PR TITLE
COMMERCE-11977 Properly way to generate a dependency to execute upgrades in order

### PR DESCRIPTION
**Pull request by achaparro**
cc/ @luca-pellizzon

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:commerce

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Any update with the review?

**Review by luca-pellizzon — APPROVED** [review]

**Pull request closed without merging**
