### PR TITLE
COMMERCE-6976 followup

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
https://github.com/brianchandotcom/liferay-portal/commit/5cd0b039902e27954a57a66f779cbcfcdb45386a and https://github.com/brianchandotcom/liferay-portal/commit/1de380766d598cc89b128b4cfb53b307e4208de1 to be done wherever we use predicates in commerce

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
