### PR TITLE
COMMERCE-10474 | Fix comma and enter in quickAddToCart

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #3400

https://issues.liferay.com/browse/COMMERCE-10474

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
