### PR TITLE
Commerce 5461 gg

### PR DESCRIPTION
**Pull request by garofalog**

### CODE REVIEW

**Comment by garofalog** [comment]
ci:test:sf

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by garofalog** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
@andrea-ale-sbarra Is this still on / to be merged? LGTM, just asking what I should do about it :)

**Review by gianmarcobrunialti — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
Rebased and sent here: https://github.com/liferay-commerce/liferay-portal/pull/577

**Pull request closed without merging**
