### PR TITLE
Automated Test-COMMERCE-5803| Master

### PR DESCRIPTION
**Pull request by CalumR23**
[COMMERCE-5803](https://issues.liferay.com/browse/COMMERCE-5803) @pietro69

### CODE REVIEW

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
@CalumR23, please see Search#ViewSortedSearchResults for examples of asserting Sort tests.

**Comment by CalumR23** [comment]
ci:test:commerce-functional

**Comment by CalumR23** [comment]
ci:test:sf

**Comment by CalumR23** [comment]
Above failures are not related to testcase

**Comment by brittneyq** [comment]
Sent in [887](https://github.com/liferay-commerce/liferay-portal/pull/887). Please close, thank you!

**Pull request closed without merging**
