### PR TITLE
COMMERCE-9596 Extension point to define a Collection Provider that supplies SKU's as options

### PR DESCRIPTION
**Pull request by pietrobocale**
Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4139

https://liferay.atlassian.net/browse/COMMERCE-9596

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR.
@luca-pellizzon can you please force-forward this PR? Thanks!

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
