### PR TITLE
Automated Test - COMMERCE-6145 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-6145 , cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
SearchResultsWidgetChangeNumberOfItemsToDisplayFromPaginationBar passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
