### PR TITLE
COMMERCE-12944 Fix supplier role usages in commerce

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12944

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
closing this. resent here https://github.com/liferay-commerce/liferay-portal/pull/4493

**Pull request closed without merging**
