### PR TITLE
COMMERCE-9853 - LanguageUtil.get() added to label in dropdownItem

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9853

@andrea-ale-sbarra 

Low priority pull request.

from @elocamp ,

> Add Option button was being displayed as "add-option-template".
> Purposed fix was to add a LanguageUtil.get() in the label where the button was being set and to remove "template" from title.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
Thank you! @brianikim @elocamp

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
