### PR TITLE
COMMERCE-6060 commerce-warehouse-web js moved out of jsp files

### PR DESCRIPTION
**Pull request by fabio-d-m**
Pages affected by these changes:

1) Product detail page in admin panel) -> skus (select a sku from dataset display) -> Inventory (side panel)
2) Warehouse detail page (admin panel)

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
