### PR TITLE
LPS-161253 Add rich text description to the Asset Category 

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
Adapting the code from Commerce module to accept the changes made in https://github.com/liferay-echo/liferay-portal/pull/9396.

cc: @lfbesada

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ehi @BarbaraCabrera we will schedule QA activities for this PR in the next sprint. Thank you for your work!

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by BarbaraCabrera** [comment]
ci:reevaluate:1307401_4382

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:forward

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_4398

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1317401_4850

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
