### PR TITLE
COMMERCE-4277 Adding External Reference Code to CPTaxCategory

### PR DESCRIPTION
**Pull request by kevinccruz**
Replaces github.com/liferay-commerce/liferay-portal/pull/111 , to rebase on top of it as requested by @marco-leo

### CODE REVIEW

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by kevinccruz** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
@kevinccruz the pull looks ok, please rebase  and run test, so we can merge

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
Not sure what's happening here @marco-leo , I've rebased commerce/master onto the work here, ran:
gradle baseline -Dbaseline.ignoreFailures=true

and pushed, but Jenkins doesn't seem to be liking the changes. Any idea about a fix here? 

@dsitu ?

**Comment by dsitu** [comment]
> Not sure what's happening here @marco-leo , I've rebased commerce/master onto the work here, ran:
> gradle baseline -Dbaseline.ignoreFailures=true
> 
> and pushed, but Jenkins doesn't seem to be liking the changes. Any idea about a fix here?
> 
> @dsitu ?

@kevinccruz usually when it has issues with merging, rebasing with liferay/master should fix the issue. CI pulls its master branch from liferay not liferay-commerce.

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by kevinccruz** [comment]
ci:test:sf

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
This seems to be an unrelated failure, that was also seen in https://github.com/brianchandotcom/liferay-portal/pull/94154

Is this one good to go @marco-leo @dsitu ?

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
ci:test:relevant

**Comment by kevinccruz** [comment]
3 successes! QUICK SOMEONE PUSH IT THROUGH @marco-leo @dsitu

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
