### PR TITLE
COMMERCE-6877 Remove Reindex from testcase setUp blocks

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-6877

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
cc/ @victoroscuro

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
