### PR TITLE
COMMERCE-12533 Show uom column in checkout summary

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #4293 

https://liferay.atlassian.net/browse/COMMERCE-12533

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by brianchandotcom** [comment]
@smottal @22LucaGiannotta22 I merged this manually.

**Pull request closed without merging**
