### PR TITLE
LPD-22516 Paginate results in Make a Return Modal in Service

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-22516

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:report:2560024638

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
