### PR TITLE
COMMERCE-10984 Update priceEntries after adding or updating cpInstance

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10984

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM, thank you @brianikim

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@andrea-ale-sbarra , ci:test:commerce had no unique failures. This should be QA ready now if you are okay with the changes.

**Comment by victoroscuro** [comment]
@brianikim @andrea-ale-sbarra closing this one and opening sending the code through #3568 since I had to change a macro

**Comment by victoroscuro** [comment]
ci:close

**Pull request closed without merging**
