### PR TITLE
COMMERCE-8290 Fix commerce when context is different from root

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-8290

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:commerce

**Comment by dsitu** [comment]
ci:test:commerce

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:revlevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
@dsitu what I see is ok, but I'm not sure we cover everything.
Could you please check where we call our headless endpoints, like:

modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/commerce_channel/general.jsp line 244

modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rels.jsp line 34

modules/apps/commerce/commerce-order-web/src/main/resources/META-INF/resources/commerce_order/general.jsp line 433

Just to understand if all of these places are using the utilities that you've already fixed.

Many thanks.

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
> @dsitu what I see is ok, but I'm not sure we cover everything. Could you please check where we call our headless endpoints, like:
> 
> modules/apps/commerce/commerce-channel-web/src/main/resources/META-INF/resources/commerce_channel/general.jsp line 244
> 
> modules/apps/commerce/commerce-product-definitions-web/src/main/resources/META-INF/resources/definition_option_rels.jsp line 34
> 
> modules/apps/commerce/commerce-order-web/src/main/resources/META-INF/resources/commerce_order/general.jsp line 433
> 
> Just to understand if all of these places are using the utilities that you've already fixed.
> 
> Many thanks.

@luca-pellizzon I checked over the code again. I found a few apis that were calling commerce-ui and constructing the full URL that I missed.
In general my changes make it so our commerce-frontend-js modules that were passing in full URL will now pass in a relative URL. I had to do this because the defaultFetch function in frontend-js has some logic that will add the pathContext for us if the URL being passed to the fetch is not a full URL but a relative path. From what I can see our api calls eventually end up calling defaultFetch. So rule of thumb would be, if we pass a full URL, we will also need to include the pathContext. If we are just passing a relative path, `frontend-js defaultFetch` will append it on for us.

commerce-frontend-js api calls that eventually call `defaultFetch` (Our api calls are either using these for api calls or `Liferay.Util.fetch/frontend-js defaultFetch`, I believe `Liferay.Util.fetch` is the same as `frontend-js defaultFetch`):
```
modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/utilities/index.js
modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/utilities/AJAX/index.js
```

My changes to those 2 files will ensure that `defaultFetch` will handle adding `pathContext` for us and that should handle any commerce-frontend-js module calls. Let me know what you think. Thanks!!

**Comment by victoroscuro** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:forward

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
