### PR TITLE
Automated Test - COMMERCE-6150 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6150, cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@JoMaAlves ,

This pull request has formatting issues. Please fix and resend.

**Comment by JoMaAlves** [comment]
Fixed!

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
SearchBarWidgetSearchProductByNameSingleQuotes Passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
