### PR TITLE
COMMERCE-10013 InfoItemCollectionProvider implementation for Product Attachments

### PR DESCRIPTION
**Pull request by alessiorendina**
Story https://issues.liferay.com/browse/COMMERCE-9434
Tech Task: https://issues.liferay.com/browse/COMMERCE-10013

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Sent here: https://github.com/liferay-commerce/liferay-portal/pull/3062

**Review by andrea-ale-sbarra — COMMENTED** [review]
These changes look good to me

**Pull request closed without merging**
