### PR TITLE
COMMERCE-4934 Dispatch Log Integration tests - repeat

### PR DESCRIPTION
**Pull request by igorbeslic**
Please review

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
this is EXPERIMENTAL PR please do not forward.

**Comment by igorbeslic** [comment]
DO NOT FORWARD I'LL DO IT

**Comment by igorbeslic** [comment]
DO NOT FORWARD: it depends on https://github.com/brianchandotcom/liferay-portal/pull/94930

**Pull request closed without merging**
