### PR TITLE
COMMERCE-9432 - PIM - Use default pagination settings like other Commerce dat…

### PR DESCRIPTION
**Pull request by brianikim**
…a sets

https://issues.liferay.com/browse/COMMERCE-9432

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
Thanks @brianikim

**Comment by andrea-ale-sbarra** [comment]
@brianikim can you try rebase this PR because the relevant log says CI failed on rebasing this branch.
Thanks!

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
@brianikim I resent this at #3105 with functional test coverage. Can you please close this PR?
Thanks, Lorenzo.

**Pull request closed without merging**
