### PR TITLE
Automated Test - COMMERCE-6230 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-6230, cc:@iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//li[contains(@class,'commerce-subtotal')]//div[contains(@class,'commerce-value') and contains (.,'21.60')]"

**Comment by pedroalmd** [comment]
Please reopen @kristinonias

**Comment by pedroalmd** [comment]
Fixed @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//li[contains(@class,'commerce-subtotal')]//div[contains(@class,'commerce-value') and contains (.,'21.60')]"

**Comment by pedroalmd** [comment]
@kristinonias please reopen

**Comment by pedroalmd** [comment]
Fixed @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
