### PR TITLE
COMMERCE-9135

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by amosfong** [comment]
@riccardo-alberti , made a small adjustment which fixes the emptyQuery test. Also updated the module versions.
https://github.com/liferay-commerce/liferay-portal/pull/2580

**Pull request closed without merging**
