### PR TITLE
COMMERCE-10685 Do not provide bean attribute. We have models that do …

### PR DESCRIPTION
**Pull request by brianikim**
…not use groupId.

https://issues.liferay.com/browse/COMMERCE-10685

@luca-pellizzon , straightfoward fix. 

The solution was simpler than expected. 

It was purely a front-end issue due to including `bean` attribute in the taglib for workflow-status. 

This will trigger `long groupId = BeanPropertiesUtil.getLong(bean, "groupId");` ([link](https://github.com/liferay/liferay-portal/blob/e4eb4d487ab671822e68374898057634928b616d/portal-web/docroot/html/taglib/aui/workflow_status/init-ext.jspf#L27)) which will always throw NPEs because we have models that do not have groupId implementation. 

The solution is okay because the only thing that matters when using the taglib is providing the status correctly i.e.:

`status="<%= workflowedModel.getStatus() %>"`

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
Sent to #3394 3394

**Comment by iovaneale** [comment]
ci:close

**Pull request closed without merging**
