### PR TITLE
COMMERCE-11195 | Fix fragment diagram product card

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://issues.liferay.com/browse/COMMERCE-11195

Re-sent from #3614

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Sent here: https://github.com/liferay-commerce/liferay-portal/pull/3647

**Pull request closed without merging**
