### PR TITLE
LPS-180050 Layout errors on forms bundle Speedwell

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys!

From the Echo team we have this issue https://liferay.atlassian.net/browse/LPS-180050 related to forms in the Page Editor with the Speedwell theme. I've added css for buttons inside form groups to fix it. Could you take a look at the commit c25ad1493c09e2d0c2eb681cb5a4e9e2654fcbce? 

Thank you in advance! 😄 

cc @DiegoHu97

## Steps 
1. Go to Control Panel > Objects 
2. Create a object “object1”
3. Create a object “object2”
4. Edit “object1” and go to fields tab
5. Create a text field
6. Go to Relationships tab > Create a Relationship of One (object1) to Many (object2) > Publish the object
7. Edit “object2” > Publish the object
8. Create a Site with Speedwell template
9. Go to Site Builder > Pages > Create a Content Page
10. Add a Form Container fragment
11. Map the Form to “object2”
13. See the selector next to the input
Screen Shot 2023-09-28 at 1 08 18 PM

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by veroglez** [comment]
ci:forward:force

**Pull request closed without merging**
