### PR TITLE
COMMERCE-9744

### PR DESCRIPTION
**Pull request by brianikim**
From @elocamp,

> The language keys for time periods in SubscriptionTypeImpl files were not being passed in their plural form, and some didn't exist Proposed fix is to modify the language keys for time periods to their adapted plural form and add the language keys that doesn't exist
> 
> Related Ticket: [COMMERCE-9744](https://issues.liferay.com/browse/COMMERCE-9744)

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed. Add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/4058.

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
