### PR TITLE
[TS] LPS-202027 Fix user transaction rollback

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-202027](https://liferay.atlassian.net/browse/LPS-202027)

Hi Commerce Team,

I hope you can review my change that tends to make user transaction rollback work. The change is simple, the key is to throw the exception further so that BaseTransactionExecutor will know that a rollback is required.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
@liferay-commerce , this belongs to a customer case. Please prioritize if possibile.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]
LGTM! Thx.

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:close

**Pull request closed without merging**
