### PR TITLE
COMMERCE-12658 Channel Restriction on Account Addresses

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12658

### CODE REVIEW

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
test failed seem unrelated, going to try to forward one more time to make sure test are unrelated

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:reevaluate:1297401_8802

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
