### PR TITLE
COMMERCE-12183 Rename of bookedQuantityId

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-12183

Follow up PR for https://github.com/brianchandotcom/liferay-portal/pull/139534#issuecomment-1688233225

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1277401_9758

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
@smottal could you rebase, thanks

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Comment by CrescenzoRegaLF** [comment]
ci:forward:force

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR.

**Comment by lorenzolapescara** [comment]
@andrea-ale-sbarra can you please force-forward this PR? Thanks!

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
