### PR TITLE
LPS-195448 Fix bypass related to redirect

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #4469 

https://liferay.atlassian.net/browse/LPS-195448

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:um

**Comment by 22LucaGiannotta22** [comment]
This can be force forwarded, relevant failures are not related to the PR

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
