### PR TITLE
Automated Test - COMMERCE-6067 | master

### PR DESCRIPTION
**Pull request by Jamersonze**

### CODE REVIEW

**Comment by Jamersonze** [comment]
https://issues.liferay.com/browse/COMMERCE-6067, cc; @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by Jamersonze** [comment]
Fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
@Jamersonze Can you please clean up and resend this PR? Because at this moment it is difficult to read and review

**Comment by Jamersonze** [comment]
Fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
