### PR TITLE
COMMERCE-11356 Automate tests for user story COMMERCE-10449 Reject Cookies to be handled with Compare Products

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-11356

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by baharturk — CHANGES_REQUESTED** [review]
Please take a look at the changes I asked. Thanks!

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
