### PR TITLE
COMMERCE-11847 - Catalog default language is used in commerce search suggestions product descriptions

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11847](https://liferay.atlassian.net/browse/COMMERCE-11847)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
@andrea-ale-sbarra Can you review this one? It's tied to an LPP. Thank you!

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Review by alessiorendina — APPROVED** [review]
LGTM! Thanks @victorcdp

**Comment by Brunno0liveira** [comment]
Resent at https://github.com/liferay-commerce/liferay-portal/pull/4046

**Comment by Brunno0liveira** [comment]
ci:close

**Pull request closed without merging**
