### PR TITLE
Automated Test - COMMERCE-5725 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-5725, cc:@lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//div[@id='main-content']//div[contains(@class,'portlet')]//section[contains(@id,'Checkout')]"

**Pull request closed without merging**
