### PR TITLE
Automated Test - COMMERCE-5805 | master 

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/COMMERCE-5805

cc: @pietro69

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
ci:stop

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:stop

**Comment by brittneyq** [comment]
ci:stop

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Comment by brittneyq** [comment]
ci:close

**Pull request closed without merging**
