### PR TITLE
LPS-171830 | master

### PR DESCRIPTION
**Pull request by ces-sontruong**
Hi team,

This is the fix for the [LPS-171830](https://issues.liferay.com/browse/LPS-171830), the original has passed my review at sontruongces#71. Please help me to review and give feedback.

Thanks!
cc: @locpham97

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
Ehi @sontruongces the PR was reviewed by Commerce Team and it was approved.
Thank you!

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by locpham97** [comment]
Hi @andrea-ale-sbarra ,
Do you have any update about this PR ?
I am looking forward to hearing your response.
Thanks,
Loc

**Pull request closed without merging**
