### PR TITLE
LPD-24497 birthDate property of UserAccount has incorrect format

### PR DESCRIPTION
**Pull request by monaco-fabio**
https://liferay.atlassian.net/browse/LPD-24497

cc @smottal

### CODE REVIEW

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
