### PR TITLE
Automated Test - COMMERCE-6320 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
https://issues.liferay.com/browse/COMMERCE-6320, cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by julioribeiiro** [comment]
Fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
