### PR TITLE
Automated Test - COMMERCE-5806 | master

### PR DESCRIPTION
**Pull request by lucasperj**

### CODE REVIEW

**Comment by lucasperj** [comment]
https://issues.liferay.com/browse/COMMERCE-5806 ; cc: @pietrobocale

**Comment by Pietro69** [comment]
Start review

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
