### PR TITLE
COMMERCE-12191 Make sure sub-facets have the proper facet configurations

### PR DESCRIPTION
**Pull request by brianikim**
@andrea-ale-sbarra ,

https://liferay.atlassian.net/browse/COMMERCE-12191, tied to a critical LPP.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
sent here https://github.com/liferay-commerce/liferay-portal/pull/4176

**Pull request closed without merging**
