### PR TITLE
Automated Test - COMMERCE-6303 | master

### PR DESCRIPTION
**Pull request by lima-rafa**

### CODE REVIEW

**Comment by lima-rafa** [comment]
https://issues.liferay.com/browse/COMMERCE-6303; cc: @pietro69

**Comment by lima-rafa** [comment]
https://issues.liferay.com/browse/COMMERCE-6303; cc: @pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
UseSchedule passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
