### PR TITLE
COMMERCE-2909 new mini compare react component bootstrap compliant

### PR DESCRIPTION
**Pull request by luca-pellizzon**
Please @marco-leo @FabioDiegoMastrorilli review this PR
Lots of conflicts while migrating it to master, so help me finding anything inconsistent.

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@ivicac took this and rebased already

**Pull request closed without merging**
