### PR TITLE
COMMERCE-11139 Remove default currencies at the startup

### PR DESCRIPTION
**Pull request by alessiorendina**
https://issues.liferay.com/browse/COMMERCE-11139

---

Re-sent from liferay-commerce#3581

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Hi @alessiorendina, could you please take a look at those errors? Are they related to the commits?

`testCommerceOrderCurrency: com.liferay.commerce.currency.exception.NoSuchCurrencyException: No CommerceCurrency exists with the key` failed in [com.liferay.commerce.internal.order.test.CommerceOrderTest](https://testray.liferay.com/home/-/testray/case_results/2263954789?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2263937961%26testrayRunId%3D2263938018%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc%26resetCur%3Dfalse) and some other batches. 

Also there are hundreds of failures `Failed prior to running test` when running the relevant/commerce CI suites. 

cc/ @andrea-ale-sbarra, @victoroscuro

**Comment by alessiorendina** [comment]
Hi @jaydawu We removed the creation of the currencies at the startup, so all the functional and integration tests that were relying on that will fail. Can we identify all the integration tests that are failing so we can fix them?

cc @andrea-ale-sbarra

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
Thank you @alessiorendina

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:stop

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
New PR opened here https://github.com/liferay-commerce/liferay-portal/pull/3657

**Pull request closed without merging**
