### PR TITLE
LPD-40881 Adds shippable field to headless-commerce-admin-order

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-40881

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF errors in the rest builder test

**Comment by CrescenzoRegaLF** [comment]
ci:report:59397010

**Comment by CrescenzoRegaLF** [comment]
@luca-pellizzon failures do not depend on the pr

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
