### PR TITLE
COMMERCE-10132 - PIM - dlfileentry records are not deleted after deleting a product

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10132

@andrea-ale-sbarra ,

cc/ @riccardo-alberti

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra , @riccardo-alberti , let me know if you guys are okay with providing a hot-fix for this if you guys are okay with the PR and/or do not see any further significant changes required.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
@andrea-ale-sbarra , if the ci:test (I pray) decides to be successful, we need this to go through QA asap.

**Comment by brianikim** [comment]
I am going to run ci:test for the last time before reaching out to someone for while this PR is the only PR failing. The compile errors being thrown are not seen locally.

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
