### PR TITLE
COMMERCE-12658 Channel Restriction on Account Addresses

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12658

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — CHANGES_REQUESTED** [review]
headless-commerce-admin-account APIs are deprecated, we should not be adding things there.

**Comment by dsitu** [comment]
> headless-commerce-admin-account APIs are deprecated, we should not be adding things there.

kk, ill look for a more appropriate place to put the new api.

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
@luca-pellizzon I moved the API to the Channel API, it seems like that is the most relevant place.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4470

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
