### PR TITLE
LPD-28328 Fix poshi locator

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-28328

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:um

**Comment by riccardo-alberti** [comment]
ci:test:playwright

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
