### PR TITLE
COMMERCE-7039 commerce-product-service rerun of buildUpgradeTable script

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-7039

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forwarx

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci.forward

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by vicnate5** [comment]
ci:test:liferay-online

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
