### PR TITLE
COMMERCE-12043 fixed NPE

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12043

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
The failures on the relevant are not related to this PR, it can be forwarded.

@victoroscuro

**Pull request closed without merging**
