### PR TITLE
Automated Test - COMMERCE-5858 | master

### PR DESCRIPTION
**Pull request by ThalitaCeli**

### CODE REVIEW

**Comment by ThalitaCeli** [comment]
https://issues.liferay.com/browse/COMMERCE-5858; CC: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
Sent in https://github.com/liferay-commerce/liferay-portal/pull/881
Please close.

**Pull request closed without merging**
