### PR TITLE
COMMERCE-10066 - On the quantity selector, allowed quantities list is not filtered based on the product configurations(min,max,multiple)

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-10066](https://issues.liferay.com/browse/COMMERCE-10066)

The problem was that there was no filtering being done before showing the quantity options on the product's page. Proposed fix is to filter the existing quantity options according to the specified configurations (min, max and multiple).

Resend of #3349

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:close

**Pull request closed without merging**
