### PR TITLE
COMMERCE-5497 Fix and remove quarantine CPCommerceProducts#ProductPublishing

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5497

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@Pietro69 add the wait command for the issue we have on this PR

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by brianchandotcom** [comment]
@Pietro69 I merged this.

ci:close

**Pull request closed without merging**
