### PR TITLE
Automated Test - COMMERCE-6275 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-6275 , cc: @Pietro69

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by evanilson-santana** [comment]
Fixed.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Combined: https://github.com/liferay-commerce/liferay-portal/pull/1255
Forwarded: https://github.com/brianchandotcom/liferay-portal/pull/102208

**Pull request closed without merging**
