### PR TITLE
Automated Test - COMMERCE-5956 | master

### PR DESCRIPTION
**Pull request by leilanyaragao**

### CODE REVIEW

**Comment by leilanyaragao** [comment]
https://issues.liferay.com/browse/COMMERCE-5956, cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Closed. Merged here: [#102033](https://github.com/brianchandotcom/liferay-portal/pull/102033)

**Pull request closed without merging**
