### PR TITLE
Commerce 10961

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-10961

@andrea-ale-sbarra

resent from: https://github.com/liferay-commerce/liferay-portal/pull/3519 to address rebase error

---

Added some fields to this initial PR https://github.com/liferay-commerce/liferay-portal/pull/3517

@22lucagiannotta22

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
