### PR TITLE
COMMERCE-7277 Info Framework CPDefinition fields

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
Merge #1736 first.

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@andrea-ale-sbarra is this PR still needed? if not please close it

**Pull request closed without merging**
