### PR TITLE
LPD-41005 Order return fixes

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-41005
cc: @gianmarcobrunialti

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Review by gianmarcobrunialti — APPROVED** [review]

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward:force

**Pull request closed without merging**
