### PR TITLE
Automated Test - COMMERCE-6172 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6172 , cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
Fixed line sent incorrectly

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
