### PR TITLE
COMMERCE-4684 | master | Changes for MiniumSiteFullFlow test

### PR DESCRIPTION
**Pull request by nikki-pru**
partial fix for https://issues.liferay.com/browse/COMMERCE-4684

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:relevant:nocompile

**Comment by nikki-pru** [comment]
ci:test:commerce

**Comment by nikki-pru** [comment]
CC @iovaneale

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
