### PR TITLE
COMMERCE-9193 Correct DDMForm for jsonFormSettings 

### PR DESCRIPTION
**Pull request by sammonsjl**
Community Contribution from: https://github.com/liferay/liferay-portal/pull/4523.  Can someone please review?

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
@andrea-ale-sbarra is this PR still needed? if not please close

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
Looks fine to me, let's test this to see if it keeps working

**Comment by baharturk** [comment]
ci:test:commerce

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
