### PR TITLE
LPD-39122 Step tracker listens to event

### PR DESCRIPTION
**Pull request by alessiorendina**
Forwarded from:https://github.com/liferay-commerce/liferay-portal/pull/5493

https://liferay.atlassian.net/browse/LPD-39122

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by alessiorendina** [comment]
ci:forward:force

**Comment by alessiorendina** [comment]
ci:stop

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by alessiorendina** [comment]
ci:forward:force

**Pull request closed without merging**
