### PR TITLE
Automated Test - COMMERCE-6198 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-6198 cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by julioribeiiro** [comment]
Fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//iframe[contains(@id,'selectCategory_iframe_')]"

**Comment by julioribeiiro** [comment]
Fixed in: https://github.com/liferay-commerce/liferay-portal/pull/1379

**Pull request closed without merging**
