### PR TITLE
LPS-204579

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Fix some inconsistencies in management toolbar for some applications

Proposed solution
----
It is the actual Result that we have in portal at this moment:

Screenshot from 2023-12-21 09-39-39
Screenshot from 2023-12-21 09-39-58
Screenshot from 2023-12-21 09-40-28
Screenshot from 2023-12-21 09-40-49
Screenshot from 2023-12-21 09-41-02

So, following Lexicon patterns those are the changes that we did:

- Picture 1, 2 and 3: Removes **All** since we have only one filter element
- Picture 4: Removes all filter since it has only one option
- Picture 5: Adds filter navigation label like the filter by account membership

Please let me know if you have any question.

### CODE REVIEW

**Comment by smottal** [comment]
Hey @ealonso, is it possible to have a screenshot on how will be the Picture 5 after the change? All the other points look good to me. Thx

**Comment by ealonso** [comment]
Hey @smottal,

I've added it in the LPS but I forgot to add it here, 😅 , see:

Account_Users_-_Liferay

**Review by smottal — APPROVED** [review]
Hi @ealonso , sorry for the delay. Everything looks good to me. Running the test suites to verify if we have some tests that need to be updated

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:um

**Comment by ealonso** [comment]
Hey @smottal,

Can we forward this one? Or are we waiting for something else?

**Comment by smottal** [comment]
Hi @ealonso , I had a look to the tests and I think we need to update these
```
LocalFile.Account#CanDeleteAccount
LocalFile.Account#CanDeactivateAccount
LocalFile.Account#CanSearchForAccountInTheInactiveFilter
LocalFile.Account#CanEditInactiveAccount
LocalFile.Account#CanDeleteAnInactiveAccount
LocalFile.Account#CanDeleteAccount
LocalFile.Account#CanDeactivateAccount
LocalFile.Account#CanActivateAnInactiveAccount
LocalFile.AccountGroups#CanRemoveAccountFromGroup
LocalFile.AccountGroups#CanRemoveAccountFromGroup
LocalFile.AccountGroups#CanFilterAccountsBelongToAccountGroupByStatus
LocalFile.AccountPermissions#FilterByStatus
LocalFile.AccountPermissions#AccountAdminCanDeactivateAccount
```
because they are not working anymore. I think they are "all the same" because the locator of some filter in the dropdown menu it's changed due to the changes of this PR. Could you please take care of that? Thx

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:um

**Comment by ealonso** [comment]
ci:test:commerce

**Comment by ealonso** [comment]
Hey @smottal,

I've already fixed the problems.

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:um

**Comment by ealonso** [comment]
ci:test:commerce

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:um

**Comment by ealonso** [comment]
ci:test:commerce-functional

**Comment by ealonso** [comment]
Hey @smottal,

relevant and stable, are in green, Could be possible to forward it? or Do we need to fix something else in commerce or um tests?

**Comment by smottal** [comment]
Hey @ealonso , sorry for the delay. There is only one test I'm in doubt with - LocalFile.OnDemandAdmin#OnDemandAdminUnavailableInNonDefaultInstance - it should not be related but if you can have a look on it it will be better. Thx

**Comment by ealonso** [comment]
Hey @smottal,

It is not related.

**Comment by smottal** [comment]
I think this can be forwarded

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
