### PR TITLE
Automated Test - COMMERCE-5907 | master

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by fmarcio** [comment]
New PR made to fix https://github.com/liferay-commerce/liferay-portal/pull/973; it's about the following ticket https://issues.liferay.com/browse/COMMERCE-5907; cc: @Pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
AssertMultipleSKUProductCannotBeDirectlyAddedToCart passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
