### PR TITLE
LPS-145823 Migrate FDS displays in the remaining `commerce` modules

### PR DESCRIPTION
**Pull request by markocikos**
@liferay-commerce @FabioDiegoMastrorilli @victoroscuro

### References

- [LPS-145823 Migrate FDS displays in the remaining `commerce` modules](https://issues.liferay.com/browse/LPS-145823)
- [Strategy to rebuild Data Set Display as a DXP app](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/1912931035/LPS-140691+-+Create+a+strategy+to+rebuild+Data+Set+Display+as+a+DXP+app)

### What is the goal?

This is the last part of the FDS migration:
- [x]  `search-experiences`
- [x] `objects`
- [x] `remote-app`
- [x] `commerce-pricing-web`
- [ ] remaining `commerce` modules

There were a total of 94 DSD usages in commerce. Since the amount of changes is high, I split in into two PRs. In the first one, we migrated `commerce-pricing-web` (30% of usages). In this one, we are migrating the remaining 70%. I split modules in individual commits, in the case we need to revert one of them. This can easily happen if there is a change going in parallel through the review process. 

In this PR, we are:
- migrating `<clay:headless-data-set-display>` to `<frontend-data-set:headless-display>`
- migrating `<clay:data-set-display>` to `<frontend-data-set:classic-display>`
- changing backend API from `frontend-taglib-clay` to API from `frontend-data-set` app. There is **no change in logic**, just a switch of tag and API classes, along with rename of variables to match the new API.
- standardizing pattern of handling FDS objects, based on https://github.com/brianchandotcom/liferay-portal/pull/111833#issuecomment-1009551559. This includes:
  - files containing FDS IDs/names are now named `*FDSNames.java`
  - files containing FDS are now in `constants` package
  - FDS name constants now don't have any prefixes, like `COMMERCE_` or `COMMERCE_DATA_SET_KEY_`
  - FDS API objects are in `frontend.data.set` package

### What does it look like?

There are no changes in UI. Every FDS display should look and behave the same as DSD.

### How to replicate

Visit pages containing FDS displays. These are almost all pages in commerce, not including the ones pricing-related. I did check every page easily accessible from UI, but there are certainly a lot that I missed, behind more complex user workflows.

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
CI failures were related. I added https://github.com/liferay-commerce/liferay-portal/pull/2265/commits/447fe2559807d5386c14bc05f7c96c5b3fa2ecc6 with the fix.

The issue were lambdas that we added in migration. They do not preserve inheritance, only implements `FDSKeywords` interface. But, in commerce modules we have `OrderFDSKeywordsImpl` implementation. [This cast](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-order-content-web/src/main/java/com/liferay/commerce/order/content/web/internal/frontend/taglib/clay/data/set/provider/PendingCommerceOrderItemDataSetDataProvider.java#L109) failed, causing the failures. /cc @LuismiBarcos

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@victoroscuro I was not able to locally replicate CI error in https://github.com/liferay-commerce/liferay-portal/pull/2265#issuecomment-1048037374 :

screen

Screenshot it broken in [the CI test](https://testray.liferay.com/reports/production/logs/2022-02/test-1-37/test-portal-acceptance-pullrequest(master)/418/functional-tomcat90-mysql57-jdk8/1/10/LocalFile.CommerceAccelerators_MiniumSiteFullFlowCheckingOutViaOrderDetails/summary.html.gz), maybe it crashed during execution? I'll try running relevant tests again.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
@markocikos it's probably a flaky test. To proceed with a more complete test on our end, when we plan it, can you please also run "ci:test:commerce"? Thanks a lot!

**Comment by markocikos** [comment]
Force-pushed, to fix conflicts in `commerce-order-content-web`. @victoroscuro I hope you can schedule working on this soon.   PR touches a lot of code, so there will likely be a lot of conflicts with time.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Another day, another conflict fix.

I'll keep on trying `relevant` tests, until we get them green. At this point, it's very likely that it should be green, but I'd like to be 100% sure. I don't see much point in running `ci:test:commerce` until just before commerce QA starts working on this.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Force-pushed. Fixed a minor conflict, but also added missing migration in `commerce-shop-by-diagram-web`. I missed it as it was hiding under `dxp` dir.

**Comment by markocikos** [comment]
Fixed minor semver conflict, force-pushed.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Force-pushed, fixed conflicts.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
Force-pushed, fixing a bunch of conflicts.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
Fixed conflicts, it was some minor SF on common code. Auto SF added https://github.com/liferay-commerce/liferay-portal/pull/2265/commits/b1fdde24137b1c8699055ee109de6968891cbf3f, it looks like unrelated missing SF from directly merged code.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
Force-pushed, fixed couple of conflicts.

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
Force-pushed, fixing conflicts and a [bug in migration code.](https://liferay.slack.com/archives/C0239L4PJR2/p1649144795093019?thread_ts=1645777684.970849&cid=C0239L4PJR2)

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
Force-pushed, with minor conflicts fixed.

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
Force-pushed. The only change from the previous iteration is the way we are setting FDS names. They need to be unique in the DXP scope, see more in https://github.com/liferay-frontend/liferay-portal/pull/2140 and followups. The naming convention that we are setting is: portlet key + `-` + descriptive camel-casel string.

We are applying this convention to `commerce-pricing-web`, that we previously migrated.

The fact that we had a few identical IDs cause the regressions in  https://issues.liferay.com/browse/COMMERCE-8596

After PR:
comm1
comm2

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
Force-pushed! Changes:
- fixed conflicts
- removed unnecessary tag attributes
- applied new scheme builder

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:commerce

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
CI failure in https://github.com/liferay-commerce/liferay-portal/pull/2265#issuecomment-1135796741 looks unrelated, retrying!

**Comment by markocikos** [comment]
ci:forward

**Pull request closed without merging**
