### PR TITLE
COMMERCE-10866  implement RelatedInfoItemCollectionProvider for Related Diagrams

### PR DESCRIPTION
**Pull request by baharturk**
Jira:
https://issues.liferay.com/browse/COMMERCE-9392

sent from: #3465

@MahmoudAzzam

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:relevant

**Pull request closed without merging**
