### PR TITLE
COMMERCE-7481 commerce-product-definitions-web price entry are never unpublished

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-7481

I've put workflow action as Published, because the price entries cannot be unpublished in the UI unless for expiration date, which cannot be changed in the SKU UI.

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
@Commando18 can you have a look at this?

**Comment by Commando18** [comment]
@andrea-ale-sbarra It looks good to me

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:reevaluate:132null_1088

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
