### PR TITLE
LPS-203360

### PR DESCRIPTION
**Pull request by brianikim**
@smottal ,

https://liferay.atlassian.net/browse/LPS-203360

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:test:um

**Comment by saramart81** [comment]
CI results are ok, the PR can be force-forwarded. Thanks @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
