### PR TITLE
COMMERCE-5713 When an Account is deactivated, it disappears from Accounts widget in Account Management

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@drewbrokke it looks like when active was null before we were not adding the attribute to the searchContext. Like here in the previous commerceAccountLocalService
if (active != null) {
	searchContext.setAttribute(
		CommerceAccountIndexer.FIELD_ACTIVE, active);
}

do you see any issue with the change in this PR? active = null -> status = STATUS_ANY
Thx

**Review by dsitu — APPROVED** [review]

**Comment by drewbrokke** [comment]
@riccardo-alberti I think that should be fine. This is just for the search, correct? As long as we're not writing that status to the DB at any point then it's ok.

**Comment by riccardo-alberti** [comment]
@drewbrokke great! thanks a lot

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
