### PR TITLE
COMMERCE-9691 Fix quantity popover inside minicart clipping

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9691

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
