### PR TITLE
COMMERCE-7892 We use underline as part of our logic. Replace all unde…

### PR DESCRIPTION
**Pull request by brianikim**
…rline with dash.

@andrea-ale-sbarra 

https://issues.liferay.com/browse/COMMERCE-7892

See our logic here: https://github.com/liferay/liferay-portal/blob/3c55480d05c99665f55bc56d6e6ef312bdb1c584/modules/apps/commerce/commerce-product-content-search-web/src/main/java/com/liferay/commerce/product/content/search/web/internal/util/CPSpecificationOptionFacetsUtil.java#L34

Implementation in this PR is to make sure all underline usages are replaced.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
resent here https://github.com/liferay-commerce/liferay-portal/pull/2446

**Pull request closed without merging**
