### PR TITLE
Commerce 11353

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-11353

resend of https://github.com/liferay-commerce/liferay-portal/pull/3691/

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Re-sent at #3712

**Comment by lorenzolapescara** [comment]
ci:close

**Pull request closed without merging**
