### PR TITLE
LPS-201389 Fix functional test

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPS-201389

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
Failures look unrelated to the fix of this PR.

**Pull request closed without merging**
