### PR TITLE
COMMERCE-5035 keyword "new" removed from Liferay.PortletURL.createURL…

### PR DESCRIPTION
**Pull request by fabio-d-m**
… usages in commerce due to api changes

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by wincent** [comment]
Hey @FabioDiegoMastrorilli, can you please hold off on shipping this?

The real fix should be applied elsewhere; this one is a subtle side effect of dropping support for IE in our build process. I'll link the PR when I have it (should only take a few minutes to produce).

**Comment by wincent** [comment]
Please see: https://github.com/liferay-frontend/liferay-portal/pull/460

**Comment by marco-leo** [comment]
@FabioDiegoMastrorilli @wincent is this PR good to go?

**Comment by wincent** [comment]
This one shouldn't be needed any more @marco-leo ([the replacement](https://github.com/brianchandotcom/liferay-portal/pull/95472) was merged by Brian), but I don't think I have privileges to close PRs in this fork.

**Comment by wincent** [comment]
ci:close

**Pull request closed without merging**
