### PR TITLE
COMMERCE-11044 API to Create a Virtual Product

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11044

Resent from https://github.com/liferay-commerce/liferay-portal/pull/3642

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
Re-sent from:https://github.com/brianchandotcom/liferay-portal/pull/133197

**Comment by smottal** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:forward

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:stop

**Comment by smottal** [comment]
ci:test:relevant

**Pull request closed without merging**
