### PR TITLE
COMMERCE-12979

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-12979
Add automation and resend from https://github.com/liferay-commerce/liferay-portal/pull/4552

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by jaydawu** [comment]
There are no related errors to this pull, it can be force-forwarded, thanks!
cc/ @victoroscuro

**Pull request closed without merging**
