### PR TITLE
COMMERCE-2475 Add app.bnd

### PR DESCRIPTION
**Pull request by dsitu**

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@dsitu I recommend running `ci:test:stable` until the startup errors are resolved. You'll get results faster since fewer tests run, and this will save CI resources.

**Comment by dsitu** [comment]
> @dsitu I recommend running `ci:test:stable` until the startup errors are resolved. You'll get results faster since fewer tests run, and this will save CI resources.

ahh got it thanks for the tip @jpince!

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:stable

**Comment by dsitu** [comment]
ci:test:stable

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
