### PR TITLE
COMMERCE-9383 | As a Developer I want to implement InfoItemRenderer for OptionSelector

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #3431 

https://issues.liferay.com/browse/COMMERCE-9383

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:stop

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:stop

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
Forwarded [here](https://github.com/liferay-commerce/liferay-portal/pull/3506)

**Pull request closed without merging**
