### PR TITLE
COMMERCE-9456 Use smaller width for the container for mobile

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9456

@andrea-ale-sbarra , I used Google Chrome's Dev Tool for checking mobile devices. I did not find our Liferay's in-built mobile tool to be reliable. Correct me if I am wrong here. We are supporting the behavior down to 375px as that is one of the smallest mobile available (IPhone SE)

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
thanks @brianikim

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
