### PR TITLE
Automated Test - COMMERCE-6380 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-6380, cc:@lorenzolapescara

**Comment by kristinonias** [comment]
@p-albuquerque 

There are conflicting files in this pull request. Please fix and resend.

**Comment by p-albuquerque** [comment]
Fixed.

**Comment by kristinonias** [comment]
ci:test:sf

**Pull request closed without merging**
