### PR TITLE
Automated Test - COMMERCE-5927 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-5927 , cc: @lorenzolapescara

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by p-albuquerque** [comment]
New PR sent in: #1332 
Please Close

**Pull request closed without merging**
