### PR TITLE
COMMERCE-4827 headless-commerce-delivery-catalog-impl added filter lo…

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
…gic for products

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
