### PR TITLE
Automated Test - COMMERCE-5707 | master

### PR DESCRIPTION
**Pull request by juliomoraes-dev**

### CODE REVIEW

**Comment by julioribeiiro** [comment]
https://issues.liferay.com/browse/COMMERCE-5707, CC:@riccardoalberti

**Comment by julioribeiiro** [comment]
https://issues.liferay.com/browse/COMMERCE-5707, cc: @riccardo-alberti

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
