### PR TITLE
COMMERCE-5441 btn-default is remplaced by btn-secondary

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
This pull ports the commit from this one https://github.com/liferay-commerce/liferay-portal/pull/453

**Comment by andrea-ale-sbarra** [comment]
@marco-leo @marcoscv-work SF passing

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
