### PR TITLE
LPD-20774 Fix account name truncation - done right

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-20774

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
@gianmarcobrunialti please check the results of functional.

**Comment by gianmarcobrunialti** [comment]
@riccardo-alberti Waiting for an answer here: https://liferay.slack.com/archives/CNBG06JS3/p1718616362669729

The PR fixes the offending `accounts-admin-web` tests, but breaks others in Commerce which rely on the presence of `table-title` as defined in `LexiconTable.path` locators. The issue comes from some apparently wrong CSS in Clay for the `.table-title a[href]` rule.

**Comment by gianmarcobrunialti** [comment]
ci:test:um

**Comment by gianmarcobrunialti** [comment]
Sent here: https://github.com/liferay-commerce/liferay-portal/pull/5101

**Pull request closed without merging**
