### PR TITLE
(Resent) Organization Chart 4 - Permissions handling and refinements (fixed)

### PR DESCRIPTION
**Pull request by fabio-d-m**
New PR after the [old one](https://github.com/liferay-commerce/liferay-portal/pull/1675) was rejected

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
@brianchandotcom we made the changes to the Language.properties in portal-language but we cannot run the buildLang with this error "Translation is disabled because credentials are not specified". What should we do in this case?

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
