### PR TITLE
LPD-37906 Permissions to manage Multi Shipping

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-37906

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1297401_10515

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:report:43521088

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by luca-pellizzon** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:report:47713282

**Comment by CrescenzoRegaLF** [comment]
ci:report:4768503

**Comment by CrescenzoRegaLF** [comment]
ci:report:47685039

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
