### PR TITLE
COMMERCE-9698 | No messages appear when items with different Shipping Methods are added to the Shipment

### PR DESCRIPTION
**Pull request by lorenzolapescara**
re-send of #2975 
cc @luca-pellizzon

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Pull request closed without merging**
