### PR TITLE
COMMERCE-10628 Always save as draft for initial creation if workflow …

### PR DESCRIPTION
**Pull request by brianikim**
…is enabled.

https://issues.liferay.com/browse/COMMERCE-10628

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
LGTM

**Review by luca-pellizzon — APPROVED** [review]

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
Hey @brianikim 

I created a new for this issue, can you please close this one, thanks.

New PR: https://github.com/liferay-commerce/liferay-portal/pull/3346

**Pull request closed without merging**
