### PR TITLE
LPD-3272

### PR DESCRIPTION
**Pull request by brianikim**
Resent from:

https://github.com/liferay-commerce/liferay-portal/pull/4796

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:playwright

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:playwright

**Comment by brianikim** [comment]
SF failure due to this: https://github.com/liferay-commerce/liferay-portal/pull/4851

**Comment by brianikim** [comment]
@andrea-ale-sbarra , test passed. See: https://testray.liferay.com/reports/production/logs/2024-04/test-1-39/test-portal-acceptance-pullrequest(master)/9868/playwright-js-tomcat90-mysql57-jdk8/2/0/playwright-report/index.html#?testId=e0670bac7ff8d9714ad3-1e77a73fcaa020f62bf8

**Comment by andrea-ale-sbarra** [comment]
forwarded here https://github.com/liferay-commerce/liferay-portal/pull/4859

**Pull request closed without merging**
