### PR TITLE
COMMERCE-4399 commerce-api account open order limit default value cha…

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
…nged to 0

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
@andrea-ale-sbarra The tests results says that is needed a baseline

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
