### PR TITLE
LPD-33347 Fix lifecycle ranking

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-33347

Test is not needed because we have already tests that are failing for this problem:
* LocalFile.AccountRoles#AccountManagerCannotViewOrAssignSpecificAccountRolesWithoutPermissions
* LocalFile.AccountRoles#AccountManagersCanViewUsersbyDefault
* LocalFile.AccountRoles#CanOnlyViewOrganizationsByDefault
* LocalFile.Account#NoWarningDisplaysWhenAddingAUserWithValidDomain

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
