### PR TITLE
COMMERCE-9738 - SE - Internal Server Error when trying to post products to a cart

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9738

@andrea-ale-sbarra ,

Resent from https://github.com/liferay-commerce/liferay-portal/pull/2904

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
new PR from @22LucaGiannotta22 here: https://github.com/liferay-commerce/liferay-portal/pull/3102

**Pull request closed without merging**
