### PR TITLE
LPD-37649 show commerce channel panel entry if there is permission for it

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-37649

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:29073194

**Comment by CrescenzoRegaLF** [comment]
ci:report:29126166

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:30606589

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:33828727

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
