### PR TITLE
LPD-23535 Fix playwright tests

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-23535

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:playwright

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
