### PR TITLE
LPD-16328 Assign user from another instance to an organization

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-16328

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:um

**Comment by dsitu** [comment]
ci:test:um

**Comment by dsitu** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
