### PR TITLE
COMMERCE-9973 fix NPE and nested fields name

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9973

I'm sending this in place of this https://github.com/liferay-commerce/liferay-portal/pull/3386

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
