### PR TITLE
LPD-31999 Pending orders table columns ordering

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-31999

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:report:44719426

**Comment by alessiorendina** [comment]
ci:report:44692601

**Comment by alessiorendina** [comment]
ci:report:45702967

**Comment by alessiorendina** [comment]
ci:report:45705455

**Comment by gianmarcobrunialti** [comment]
Sent here: https://github.com/liferay-commerce/liferay-portal/pull/5186

**Pull request closed without merging**
