### PR TITLE
LPD-36169 Fix cart items errors when product is removed from catalog

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-36169

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Review by smottal — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:forward:force

**Pull request closed without merging**
