### PR TITLE
LPS-171321 Migrate FDS Autocomplete filters to Selection filters in commerce

### PR DESCRIPTION
**Pull request by markocikos**
### References

- [LPS-171321 Migrate FDS Autocomplete filters to Selection filters in commerce](https://issues.liferay.com/browse/LPS-171321)

### What is the goal of this PR?

This is the last part of FDS filters merge, where we merged several filters with similar features and a lot of shared code (Radio, Chechbox and Autocomplete). Autocomplete is now a feature in the `SelectionFDSFilter`.

### What does it look like?

No changes in UI. 

### Steps to reproduce

PR affects filters on few pages, that I checked manually:
- Orders
- Price Lists
- Products
- Warehouses <-- this filter is **not** working, but is not working in `master` either. It seems to have no effect on items shown.

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
lgtm
@alessiorendina @riccardo-alberti @andrea-ale-sbarra 

@victoroscurodo you thing we need to test this with our QA?

**Comment by victoroscuro** [comment]
I'd run ci:test:commerce and I'll have this quickly manually double-checked. Thanks

**Comment by markocikos** [comment]
Forwarding, after green light in [Slack discussion](https://liferay.slack.com/archives/C03LXJA82J1/p1673522438568279?thread_ts=1673430304.042369&cid=C03LXJA82J1).

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
Last try, before manual forward :crossed_fingers:

**Comment by markocikos** [comment]
ci:forward

**Comment by markocikos** [comment]
ci:stop

**Comment by markocikos** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/129386

**Pull request closed without merging**
