### PR TITLE
COMMERCE-4712 Porting COMMERCE-4711 to master

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — CHANGES_REQUESTED** [review]
@riccardo-alberti lets remove the logs from here also, so we dont risk getting this pr sent back. From bchans commit https://github.com/brianchandotcom/liferay-portal/commit/c8b2e9e1c0530db1a4bf09c1ee28b1d9bafa544e. I will make the changes to other files.

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
@dsitu done!

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
