### PR TITLE
Automated Test - COMMERCE-6272 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/COMMERCE-6272 cc: @pietrobocale

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
Fixed and sent in https://github.com/liferay-commerce/liferay-portal/pull/1323. Please close @kristinonias

**Pull request closed without merging**
