### PR TITLE
COMMERCE-10705 added auth verifier filter

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-10705

~~According to what is written here https://liferay.slack.com/archives/C0A1Z5FJL/p1678378958925429?thread_ts=1677744742.824529&cid=C0A1Z5FJL this is what we need to add support to OAUTH2 authentication~~

In the end a new AuthFilter was added.

kudos to @riccardo-alberti

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
