### PR TITLE
COMMERCE-5853 Admin UI fixes on order management domain

### PR DESCRIPTION
**Pull request by fabio-d-m**
Spacing, margins, alignments and other minor UI improvements on admin UI (order management team domain)

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:stable

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
