### PR TITLE
COMMERCE-8659

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-8659

This is the fix for Lpp 45403 and it is a resend of https://github.com/andrea-ale-sbarra/liferay-portal/pull/18, I just changed the commit messages

@pei-jung  @drewbrokke FYI

### CODE REVIEW

**Review by luca-pellizzon — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@pei-jung @andrea-ale-sbarra 
Looks like this has already been merged in master.
If so, can we close the PR? Thanks

**Comment by pei-jung** [comment]
Posting my response here for reference:

The `as count` alias is required for the subquery. The whole sql looks like this
```
select count(*) from
(select frist... union select second...) as count
```

**Comment by pei-jung** [comment]
ci:close

**Pull request closed without merging**
