### PR TITLE
COMMERCE-9210-DI UI refinements on batch planner

### PR DESCRIPTION
**Pull request by fabio-d-m**
@igorbeslic

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Pull request closed without merging**
