### PR TITLE
Commerce 12164

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/COMMERCE-12164

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by Brunno0liveira** [comment]
Errors are not related to the changes, PR can be forward

cc: @andrea-ale-sbarra

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
