### PR TITLE
COMMERCE-5061 Fix order transfering from guest to new user

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
@alecsloan can you please fix SF?

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:stop

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by ivicac** [comment]
@alecsloan can you please rebase PR as Brian has ported some commits from 7.3.x PR, but not everything

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Review by ivicac — APPROVED** [review]

**Pull request closed without merging**
