### PR TITLE
Commerce 11353

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3712

https://issues.liferay.com/browse/COMMERCE-11353

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
@lorenzolapescara FYI

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
