### PR TITLE
COMMERCE-4719 Make Commerce functional tests work on master

### PR DESCRIPTION
**Pull request by lorenzolapescara**

### CODE REVIEW

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:sf

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:stable

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by Lorenzo280800** [comment]
ci:test:stable

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:commerce

**Comment by Lorenzo280800** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:commerce

**Comment by iovaneale** [comment]
ci:test:stable

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by Lorenzo280800** [comment]
Forwarded to #293.

**Pull request closed without merging**
