### PR TITLE
Automated Test - COMMERCE-5708 | master

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/COMMERCE-5708
@zmmarina 
cc: @riccardo-alberti
This should be ready for review.

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
This PR has conflicts, please fix.

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Fixed @iovaneale

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
@iovaneale @riccardo-alberti this is ready for review!

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
