### PR TITLE
Automated Test - COMMERCE-6105 | master

### PR DESCRIPTION
**Pull request by evanilson-santana**

### CODE REVIEW

**Comment by evanilson-santana** [comment]
https://issues.liferay.com/browse/COMMERCE-6105 , cc: @PietroBocale

**Comment by Pietro69** [comment]
Review started

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
