### PR TITLE
LPD-35439 Fix modal url

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-35439

Tests already available (fixed by this change):

- LocalFile.SiteTeams#AddSiteTeamAssignUser
- LocalFile.SiteTeams#AddSiteTeamSearchUsers
- LocalFile.RecieveUserNotification#CanGetCurrentUserNotifications
- LocalFile.RecieveUserNotification#CanGetOwnedUserNotifications
- LocalFile.RecieveUserNotification#CanPutUserNotificationRead
- LocalFile.RecieveUserNotification#CanPutUserNotificationUnread

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:um

**Review by alessiorendina — APPROVED** [review]
LGTM, thank you!

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
