### PR TITLE
COMMERCE-5187 Liferay Portal 7.2 + Commerce 2.0.7 → Liferay Portal 7.3 + Commerce 3.0 After upgrade process mini-cart is empty and a NPE is thrown

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by marco-leo — APPROVED** [review]

**Comment by marco-leo** [comment]
@dsitu please forwrd if all test passes or manually if fais for unrelated issues

**Comment by dsitu** [comment]
hmmm seems to have failed with this LocalFile.CPCommercePriceLists#AssertPriceListIsAppliedToAllAssociatedAccounts
Found a ticket related to it, might be a flaky test
https://issues.liferay.com/browse/COMMERCE-5183
Gonna try to run ci:forward, just to test again once more

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
