### PR TITLE
Automated Test - COMMERCE-5707 | master

### PR DESCRIPTION
**Pull request by 91nilo**

### CODE REVIEW

**Comment by 91nilo** [comment]
https://issues.liferay.com/browse/COMMERCE-5707, cc@riccardo-ferrari

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
We changed the code using a for loop to remove the repetition of "types"

**Comment by riccardo-ferrari** [comment]
I think this is for @riccardo-alberti

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by julioribeiiro** [comment]
Fixed

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by julioribeiiro** [comment]
Fixed in: https://github.com/liferay-commerce/liferay-portal/pull/1292, please close this PR

**Pull request closed without merging**
