### PR TITLE
COMMERCE-11150 Fix preload subscription fields

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-11294

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.

Thank you!

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed, will resent it after adding the automation test.

**Comment by jaydawu** [comment]
Resent on https://github.com/liferay-commerce/liferay-portal/pull/3766

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
