### PR TITLE
LPD-32908 - When patching Product, expiration date is reset if not present in the call's body

### PR DESCRIPTION
**Pull request by victorcdp**
https://liferay.atlassian.net/browse/LPD-32908

@andrea-ale-sbarra Can you review this? Tied to LPP. Thank you!

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — CHANGES_REQUESTED** [review]
LGTM.
Code looks good, can you please add an assert that verifies the expirationDate gets changed with the patch? same for dispaly date.
Thank you!

**Comment by victorcdp** [comment]
@andrea-ale-sbarra I don't understand, are you talking about the default behavior when patching a product? because that should be covered by [this](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-test/src/testIntegration/java/com/liferay/headless/commerce/admin/catalog/resource/v1_0/test/ProductResourceTest.java#L219).

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
