### PR TITLE
COMMERCE-5040 commerce-theme-minium-full-site-initializer Fix missing…

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
… fieldReference in DDMForm

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:format

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
