### PR TITLE
COMMERCE-9575 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-9575

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
It looks like I need to add a wait after the compare button is clicked. 4 tests are failing because the compare page doesn't load in time.

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
Hmm I don't see why those tests should be failing. The compare page isn't being open when the compare button is clicked. This isn't an issue locally though. I see that the tests never even checked for this page before so they never had an issue passing in CI. I'm going to put the tests that edit the max comparison items in a separate instance with the skip property and see if that works.

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
Well that didn't fix it. It doesn't even look like the compare button is there on the screen shot but the steps to click it pass. The compare page just doesn't appear on CI for some reason.

**Comment by Kvale1733** [comment]
On second though, it looks like the compare button is present even when no items are being compared. I will check if I can alter the path to make sure only to click it when it's visible.

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
The tests are finally passing.

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
