### PR TITLE
Automated Test - COMMERCE-6225 | master

### PR DESCRIPTION
**Pull request by p-albuquerque**

### CODE REVIEW

**Comment by p-albuquerque** [comment]
https://issues.liferay.com/browse/COMMERCE-6225, cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
AddEditAndDeletePriceModifier passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
