### PR TITLE
LPD-45186 Wrong quantity added to cart of an existing order when UOM is set with decimal base unit quantity and decimal multiple order quantity

### PR DESCRIPTION
**Pull request by michelevigilante**
https://liferay.atlassian.net/browse/LPD-45186

fix for failing test: SFCommerceUnitsOfMeasure#CanAssertDecimalIncrementInMiniCartWithMinimumOrderQuantitySet

### CODE REVIEW

**Comment by michelevigilante** [comment]
ci:test:sf

**Comment by michelevigilante** [comment]
ci:test:relevant

**Comment by michelevigilante** [comment]
ci:test:commerce-functional

**Comment by michelevigilante** [comment]
ci:report:101708658

**Comment by michelevigilante** [comment]
ci:report:101716316

**Comment by michelevigilante** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
