### PR TITLE
COMMERCE-5904 dataset display style consistent with front store themes

### PR DESCRIPTION
**Pull request by fabio-d-m**
Dataset Display in minium before the fix: 

image

Dataset Display in minium after the fix:

image (1)

/cc @gianmarcobrunialti , @ivicac

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:stable

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
