### PR TITLE
COMMERCE-10896 Refactor CommercePayments#CancelPayment test

### PR DESCRIPTION
**Pull request by kristinonias**
https://issues.liferay.com/browse/COMMERCE-10896

### CODE REVIEW

**Review by lorenzolapescara — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
New failures are not related [Testray Compare](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2214614333&testrayRunIdA=2213715167&testrayTeamId=1314987312&statusB=3)

**Comment by kristinonias** [comment]
ci:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
