### PR TITLE
COMMERCE-4949 I get an error when I open the mini-cart with a product bundle

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
@igorbeslic please check those changes

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
