### PR TITLE
Automated Test - COMMERCE-5915 | master

### PR DESCRIPTION
**Pull request by ewertonluna**

### CODE REVIEW

**Comment by ewertonluna** [comment]
https://issues.liferay.com/browse/COMMERCE-5915, cc: @lorenzolapescara

**Comment by lorenzolapescara** [comment]
@ewertonluna Please resolve conflicts and push again.

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by JoMaAlves** [comment]
New PR sent: https://github.com/liferay-commerce/liferay-portal/pull/1328
@brittneyq, please close

**Pull request closed without merging**
