### PR TITLE
COMMERCE-10279 See if promotion price is lower than base price before…

### PR DESCRIPTION
**Pull request by brianikim**
… showing it in checkout

From @victorcdp:

> Related Issue: [COMMERCE-10279](https://issues.liferay.com/browse/COMMERCE-10279)
> 
> Problem was that the discount price was being showed even if it was higher than the base price. Proposed fix is to only show the discount price if it is lower than the base price

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by Brunno0liveira** [comment]
Hi @brianikim can you please close this PR 

I sent a new one at https://github.com/liferay-commerce/liferay-portal/pull/3648

Thanks!

**Comment by brianikim** [comment]
ci:close

**Comment by victoroscuro** [comment]
@Brunno0liveira @brianikim was this PR reviewed and approved by someone? FYI @andrea-ale-sbarra

**Comment by andrea-ale-sbarra** [comment]
@victoroscuro we saw this in the grooming session yesterday, we agreed to accept this change and eventually open some new story to better shape the functionality

**Pull request closed without merging**
