### PR TITLE
LPD-28036 - fixed unit of measure key is mandatory error when posting order via api

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-28036

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:relevant

**Review by smottal — CHANGES_REQUESTED** [review]

**Comment by brbalazs** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
