### PR TITLE
COMMERCE 2580 3

### PR DESCRIPTION
**Pull request by ivicac**
master

follow up of https://github.com/brianchandotcom/liferay-portal/pull/98746

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
@andrea-ale-sbarra is this PR still needed? if not please close it

**Comment by andrea-ale-sbarra** [comment]
This can be closed as @ivicac said

**Pull request closed without merging**
