### PR TITLE
LPS-196309 As an Instance Administrator I want to filter Users that are not associated with Accounts or Organizations

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi @smottal 
Please help review this ticket and give your feedback. Thanks
cc: @ces-quanhuynh @locpham97
### Motivation
[LPS-196309 ](https://liferay.atlassian.net/browse/LPS-196309) As an Instance Administrator I want to filter Users that are not associated with Accounts or Organizations

### Solution
LPS-196309
Create a new filter with a custom query to return a list of users who are not associated with any accounts or organizations.

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by smottal** [comment]
It's using the "old way" to do custom query but I cannot find a simple way to do it with the "new format" only for the single filter we are adding so I think we can keep as  it is.
@tototrinh could you please only re-arrange the commits to have the buildLang at the end? Thx

**Review by smottal — CHANGES_REQUESTED** [review]
Just move this commit at the end of the PR. Thx

**Comment by tototrinh** [comment]
Hi @smottal, thanks for your feedback, I updated the PR.

**Review by smottal — APPROVED** [review]
LGTM! Thx

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:um

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:stable

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
