### PR TITLE
Lpd 21633 andrea

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Rebase of https://github.com/liferay-commerce/liferay-portal/pull/5116

----

https://liferay.atlassian.net/browse/LPD-21633

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by monaco-fabio** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
