### PR TITLE
COMMERCE-11003 We need to filter for allowedCPDefinitionOptionValueRe…

### PR DESCRIPTION
**Pull request by brianikim**
…ls always

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/3540

@andrea-ale-sbarra ,

https://issues.liferay.com/browse/COMMERCE-11003

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by jaydawu** [comment]
QA passed. The two testcases failed in the commerce suite passed on locally. Will resend it after finishing the automation.

**Comment by jaydawu** [comment]
Automation finished and resent on https://github.com/liferay-commerce/liferay-portal/pull/3621

**Pull request closed without merging**
