### PR TITLE
COMMERCE-11767 Switch on Price on Application Feature Flag

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/COMMERCE-11767

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
The failing test [LocalFile.CPCommerceProducts#ProductPublishing](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/233689//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CPCommerceProducts_ProductPublishing_) is due to a "now wrong" path (because with this PR the price on application field is always visibile): it needs to be updated

**Comment by andrea-ale-sbarra** [comment]
We should change this FF to be a release one not remove it completely.

**Pull request closed without merging**
