### PR TITLE
LPD-42560 Fix booked quantities

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Solution looks good to me.

Note for myself for administration purposes:

1. Test fix locally
2. Handle backports and hot-fixes.

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
