### PR TITLE
COMMERCE-12225 Enhanced Tier Pricing Admin page with UOM

### PR DESCRIPTION
**Pull request by pietrobocale**
https://liferay.atlassian.net/browse/COMMERCE-12225

Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4259

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:stable

**Comment by pietrobocale** [comment]
ci:test:stable

**Comment by pietrobocale** [comment]
The failures are no related to the PR

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
