### PR TITLE
COMMERCE-6918 Permissions on the Attachments are not being respected

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-6918

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — COMMENTED** [review]
@alessiorendina can you have a look at this? I'm not sure about the thread local.

Thanks!

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by lorenzolapescara** [comment]
ci:test:commerce

**Pull request closed without merging**
