### PR TITLE
COMMERCE-11343 clean fields if not override

### PR DESCRIPTION
**Pull request by jaydawu**
https://issues.liferay.com/browse/COMMERCE-11343
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3757

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by pietrobocale — CHANGES_REQUESTED** [review]
Hi @jaydawu, good job on the test so far. However, we need to include some additional checks apart from the image. Could you please fill in the other fields and options? It would be best to change everything and then when the toggle is disabled and enabled again, ensure that everything is reset to the default value. Thank you.

The same check should also be done on the API.

Thanks!

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Review by pietrobocale — APPROVED** [review]
Everything is ok for me, nice work!

Review Passed.

Thanks!

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
cc/ @victoroscuro Review passed. If the suits are good, then it could be forwarded, thank you.

**Comment by victoroscuro** [comment]
Relevant failures aren't related to the changes made for this PR. I'll force-forward it.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
