### PR TITLE
LPD-41250 Add GTIN to CPInstance document

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-41250

cc @smottal

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
