### PR TITLE
COMMERCE-9488 New Order Details Page default configuration

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-9488
https://issues.liferay.com/browse/COMMERCE-10179
https://issues.liferay.com/browse/COMMERCE-10193

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:reevaluate:1377401_5799

**Comment by dsitu** [comment]
ci:test: relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
@dsitu it seems you hid the whole Open Carts and Placed Order menu items. The aim of the fix was to remove the "Enable Updated Order Details Page" checkboxes from them (they had other configurations to be kept), since they double the toggle we introduced in the widget's configuration. Could you fix it? Thanks.

@victoroscuro @luca-pellizzon

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
> @dsitu it seems you hid the whole Open Carts and Placed Order menu items. The aim of the fix was to remove the "Enable Updated Order Details Page" checkboxes from them (they had other configurations to be kept), since they double the toggle we introduced in the widget's configuration. Could you fix it? Thanks.
> 
> @victoroscuro @luca-pellizzon

@iovaneale I've updated the PR and only "Enable Updated Order Details Page" is removed now.

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Pull request closed without merging**
