### PR TITLE
COMMERCE-11026 | COMMERCE-11192 | COMMERCE-11259

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-11026
https://issues.liferay.com/browse/COMMERCE-11192
https://issues.liferay.com/browse/COMMERCE-11259

Fixed conflicts from: https://github.com/brianchandotcom/liferay-portal/pull/135142

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
