### PR TITLE
COMMERCE-7910 Fix minicart error on speedwell

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-7910

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:commerce

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@dsitu I merged this manually. Lots of poshi issues though?

**Comment by dsitu** [comment]
> @dsitu I merged this manually. Lots of poshi issues though?

@brianchandotcom thanks, yeah I think it cleared up the ones that were added from last nights regression.

**Comment by dsitu** [comment]
Closing this since its been merged.

**Pull request closed without merging**
