### PR TITLE
LPD-20696 Returns edit commerce return item page

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-20282
https://liferay.atlassian.net/browse/LPD-20696

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:forward

**Comment by dsitu** [comment]
ci:reevaluate:1287401_10153

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
