### PR TITLE
COMMERCE-12341 | Warehouse-level Permission to regular roles doesn't work + Automation

### PR DESCRIPTION
**Pull request by lorenzolapescara**
https://liferay.atlassian.net/browse/COMMERCE-12341

Re-sent with automation from #4286 

@victoroscuro @CrescenzoRegaLF

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Since there are many tests that didn't run successfully in the commerce-functional suite, I opened another PR to keep all other tests passing via CI, please see https://github.com/liferay-commerce/liferay-portal/pull/4394, thanks!

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
