### PR TITLE
LPD-15994 Company violation checker

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-15994

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by tinatian** [comment]
Just some additional info. This was sent to core-infra for review.
This is targeting at the security issue reported in the ticket, but we may suffer same issue for other membership policy like UserGroupMembershipPolicy. I suggested that we should fix this kind of stuff in a consistent way by treating all membership policy in the same way in the same pull though there is no issue reported yet.

Tina.

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:report:2539649178

**Comment by gianmarcobrunialti** [comment]
Closing this, as the issue is being handled differently.
https://liferay.atlassian.net/browse/LPD-15994?focusedCommentId=2584825

**Pull request closed without merging**
