### PR TITLE
COMMERCE-11748 Adapt action models for price entries and tier price entries

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/COMMERCE-12017

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF please check with the help of a QA the functional results, then I guess we can forward it

**Comment by victoroscuro** [comment]
The results for the relevant weren’t produced but it passed and from the details there are no evident issues.
Our commerce-functional is in line with the latest runs (no specific to the PR issues)
If it doesn’t have to be moved to QA Check and properly tested then this can be forwarded.

**Comment by luca-pellizzon** [comment]
ci:forward

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
