### PR TITLE
COMMERCE-10366 Integration tests for Wishlist API

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10366

From PR: https://github.com/liferay-commerce/liferay-portal/pull/3234

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:stop

**Comment by smottal** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
