### PR TITLE
COMMERCE-12569 Fix DB2 error

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-12569

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
@andrea-ale-sbarra ,

Test results look good to me. The PR is straight-forward.

If @victoroscuro confirms test failures are not related, we can forward this.

Sincerely,
Brian I. Kim

**Comment by brianikim** [comment]
Actually, I need to make another change. Reassigning back to myself.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@andrea-ale-sbarra , sorry about that. I updated with the correct changes.

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by victoroscuro** [comment]
ci:test:commerce-database

**Comment by brianikim** [comment]
ci:test:commerce-database

**Comment by brianikim** [comment]
ci:test:sf

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
@brianikim I'll have to ask you the favor to send this manually, results are ok. Thanks a lot!

**Comment by brianikim** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/143209

**Pull request closed without merging**
