### PR TITLE
COMMERCE-12055 CommerceTierPriceEntry, CommercePriceList and CommercePriceEntry db tables mismatch on upgraded database

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/COMMERCE-12055

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1397401_6409

**Review by luca-pellizzon — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by lucasperj** [comment]
Test that caught this error not merged on master yet, testing on CI at : https://github.com/lucasperj/liferay-portal/pull/359

cc/ @victoroscuro

**Comment by lucasperj** [comment]
Hey @victoroscuro , I don't know why the expected test didn't run on the PR I mentioned, but I built it locally and ran it, failures no longer present. 
- Other failures in ci:test:upgrade are unrelated.

Thanks.

**Comment by baharturk** [comment]
The failures in the relevant are unrelated to the PR, it can be forwarded. Thanks!

@victoroscuro

**Comment by victoroscuro** [comment]
Thanks @lucasperj and @baharturk . I'll forward this

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
