### PR TITLE
COMMERCE-11504 APIs to Link Catalogue to an Account

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-11004
https://issues.liferay.com/browse/COMMERCE-11504

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
Based on: #3811

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
new PR opened here https://github.com/liferay-commerce/liferay-portal/pull/3816

**Pull request closed without merging**
