### PR TITLE
COMMERCE-10831 Provide an endpoint to allow clients to configure subscription overrides via API

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10831

resent from
https://github.com/brianchandotcom/liferay-portal/pull/132770

@riccardo-alberti

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by brianchandotcom** [comment]
@CrescenzoRegaLF please resend on top of https://github.com/CrescenzoRegaLF/liferay-portal/pull/23

1.) The usage of

```
		HashMapBuilder.HashMapWrapper<String, String>
			newSubscriptionTypeSettingsUnicodeProperties = HashMapBuilder.put(
				yearlyModeKey, String.valueOf(yearlyMode));

		if (yearlyMode == CPSubscriptionTypeConstants.MODE_EXACT_DAY_OF_YEAR) {
			String monthValue = subscriptionTypeSettingsUnicodeProperties.get(
				monthKey);

			if (Validator.isBlank(monthValue)) {
				throw new CPSubscriptionTypeSettingsException(
					"The " + monthKey + " field is mandatory");
			}

			int month = GetterUtil.getInteger(monthValue, -1);

			if ((month < 0) || (month > 11)) {
				throw new CPSubscriptionTypeSettingsException(
					StringBundler.concat(
						"Invalid ", monthKey, " ", monthValue));
			}

			newSubscriptionTypeSettingsUnicodeProperties.put(
				monthKey, String.valueOf(month));

			String monthDayValue =
				subscriptionTypeSettingsUnicodeProperties.get(monthDayKey);

			if (Validator.isBlank(monthDayValue)) {
				throw new CPSubscriptionTypeSettingsException(
					"The " + monthDayKey + " field is mandatory");
			}

			int monthDay = GetterUtil.getInteger(monthDayValue, -1);

			if ((monthDay < 1) || (monthDay > 31)) {
				throw new CPSubscriptionTypeSettingsException(
					StringBundler.concat(
						"Invalid ", monthDayKey, " ", monthDayValue));
			}

			newSubscriptionTypeSettingsUnicodeProperties.put(
				monthDayKey, String.valueOf(monthDay));
		}

		return UnicodePropertiesBuilder.create(
			newSubscriptionTypeSettingsUnicodeProperties.build(), true
		).build();
```

is not right. Use UnicodePropertiesBuilder properly and use functions.

2.) The name of the exception mappers are not meant to follow after the naming from the Service Builder models, but from the DTOs.

For example, contrast

CPDefinitionDeliverySubscriptionLengthExceptionMapper

with

DefinitionDisplayDateExceptionMapper

Please rename all the exception mappers.

**Comment by andrea-ale-sbarra** [comment]
sent here https://github.com/brianchandotcom/liferay-portal/pull/132887

**Pull request closed without merging**
