### PR TITLE
LPD-1603 IDOR vulnerable in Contacts Center

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-1603

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
> @dsitu did we test that if the widget is put in a public page it is visible by a guest?

@riccardo-alberti yep, the widget will still be visible to the guest if it is put on a public page. This fix will prevent the guest or users that do not have the proper permissions to view a certain contact from viewing it. So if they some how get access to a contact id that they dont have permission to view, they can no longer get access to it by replacing the id field of a view/edit url.

**Comment by dsitu** [comment]
ci:reevaluate:1357401_5278

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
ci:test:relevant

**Review by riccardo-alberti — APPROVED** [review]

**Comment by dsitu** [comment]
ci:forward

**Pull request closed without merging**
