### PR TITLE
Commerce 9235

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
resend of this https://github.com/liferay-commerce/liferay-portal/pull/2717/

https://issues.liferay.com/browse/COMMERCE-9235

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@MahmoudAzzam why did you make a new PR instead of updating the old one ? Anyway for reference you should link the two so that it's easy to access all the informations and also you should update the JIRA ticket with the new PR link.

Finally looking at the code this looks like the old one, the only difference I noticed is the order of the commits. Can you explain what you did differently to make the Fonts work?

Thanks!

**Comment by andrea-ale-sbarra** [comment]
@MahmoudAzzam you don't need to apolgise :)! Thank you for your collaborative spirit and for your explanation, I'll approve this PR and move to QA check.

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by pietrobocale** [comment]
ci:forward

**Pull request closed without merging**
