### PR TITLE
COMMERCE-9951

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@riccardo-alberti merged, but please send a follow up PR and remove the other method. Thx.

**Comment by iovaneale** [comment]
ci:close

**Pull request closed without merging**
