### PR TITLE
Automated Test - COMMERCE-6355 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-6355 , cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by kristinonias** [comment]
Element is not present at "//td[contains(@class,'table-cell-expand') and contains(.,'U-Joint')]"

**Comment by JoMaAlves** [comment]
Rebased and everything is working well.
@kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by JoMaAlves** [comment]
Rebased and adapted to the new way commits are being made

**Pull request closed without merging**
