### PR TITLE
COMMERCE-10054

### PR DESCRIPTION
**Pull request by brianikim**
From https://github.com/brianikim/liferay-portal/pull/57

https://issues.liferay.com/browse/COMMERCE-10054

### CODE REVIEW

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by brianikim** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
@brianikim the semantic versioning keeps failing in the relevant. Please have a look at it. Thanks

**Comment by brianikim** [comment]
hey @lorenzolapescara , there's no baseline changes triggered locally. I am not sure why that error is being observed.

**Comment by brianikim** [comment]
Same failure seen in different PR: https://github.com/liferay-commerce/liferay-portal/pull/3353

**Pull request closed without merging**
