### PR TITLE
COMMERCE-12534 Shipment quantity doesn't respect UOM's incremental order quantity

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12534

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to this PR. It can be force forwarded

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to the PR, this can be force forwarded.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
