### PR TITLE
Commerce 9006

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9006

resend of https://github.com/liferay-commerce/liferay-portal/pull/2926

---

Applied following change requests:

> @christian-chiappa 1.) this is not true
> 
> ```
> we can't use JSONUtil.put because the object is changing based on some conditions (if statements), so we can't just create a single object and returned. Because it is dinamically created
> ```
> 
> JSONUtil.puts have logic in them if you pass in a function. That's what I"m trying to get you to do.
> 
> 2.) Sort
> 
> ```
> 	_id = fileEntry.getFileEntryId();
> 	_url = defaultURL;
> 	_thumbnailURL = defaultURL;
> 	_mimeType = fileEntry.getMimeType();
> 	_title = fileEntry.getTitle();
> 	_size = 0;
> ```
> 
> and
> 
> sort
> 
> ```
> 	_id = 0;
> 	_mimeType = null;
> 	_thumbnailURL = defaultURL;
> 	_title = null;
> 	_url = defaultURL;
> 	_size = 0;
> ```
> 
> Thx

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerc

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Review by alessiorendina — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
