### PR TITLE
COMMERCE-5062 Fix path MENU_TAB

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5062

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:stop

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
