### PR TITLE
COMMERCE-11026 | COMMERCE-11192 | COMMERCE-11259

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-11026
https://issues.liferay.com/browse/COMMERCE-11192
https://issues.liferay.com/browse/COMMERCE-11259

Fixed conflicts from: https://github.com/brianchandotcom/liferay-portal/pull/135000#issuecomment-1553710621

@pietrobocale

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1277401_8256

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by pietrobocale** [comment]
Relevant checked, everything should be fine

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
