### PR TITLE
COMMERCE-12537 Handle exceptions for tier price quantity

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/COMMERCE-12537

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:forward

**Pull request closed without merging**
