### PR TITLE
Automated Test - COMMERCE-6112 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
https://issues.liferay.com/browse/COMMERCE-6112, cc: @Pietro69

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
fixed it

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
