### PR TITLE
COMMERCE-11909 Health Check Fix should not be turning on the Order Splitting Rule + Test fix

### PR DESCRIPTION
**Pull request by baharturk**
https://liferay.atlassian.net/browse/COMMERCE-11909

sent from: #3968 

@luca-pellizzon

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
The failures are not related to the PR. This is good to go!

cc/ @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
