### PR TITLE
COMMERCE-4747 BOM deps clean up, minor refactor, dismissed redux

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
- After the migration to master, the BOM modules were not respecting the deps configuration standards, and now have been fixed.
- Accommodated also the use of the `render` exposed by `frontend-js-react-web` within the modules.
- Removed an unnecessary dependency on the `redux` library which was currently solely used for its `combineReducers` util, and replaced with a local implementation that does the same job. The state management of the two React apps was already almost fully relying on the React Context API. And for this reason...
- Bumped the versions of both the BOM modules.

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
@marco-leo @FabioDiegoMastrorilli We'll need to refactor this, as there is a bunch of duplicated code that can be exposed from some common module (e.g. our `commerce-frontend-js`?) via `.npmbridgerc` and shared-imported by both of the BOM modules implementations.

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
@wincent There you go

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
