### PR TITLE
[TS] LPD-1790

### PR DESCRIPTION
**Pull request by dacousalr**
Ticket: [liferay.atlassian.net/browse/LPS-205417](https://liferay.atlassian.net/browse/LPS-205417)

It comes from https://github.com/liferay-commerce/liferay-portal/pull/4600

## Motivation

The language of the generated email is not matching that of the password reset link, causing confusion.

## Proposed Solution

It is suggested to add &languageId=user.getLanguageId() to the URL of the password reset link. This ensures that the language selected by the administrator for a new user is now consistently incorporated into both the email content and the password reset link.

## Steps to Verify

1.Go to Instance Settings -> Email and ability Account Created Notification.

2.Set a different language for the email than the Instance.

3.As an administrator go to Control Panel -> Users and Organizations

4.Click to Plus button to create a new User

5.Fill in the form

6.Set the same language selected in point 2 for the user

7.Save new user

8.Login with new user

9.Check the email and click in the link to set up your password

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:2549308963

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
