### PR TITLE
LPD-32846 - NoSuchCatalog exception isn't mapped

### PR DESCRIPTION
**Pull request by victorcdp**
@andrea-ale-sbarra Can you review this? It's the changes required from Riccardo for LPD-27293, along with the integration test. Thank you!

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
