### PR TITLE
Automated Test - COMMERCE-5916 | master

### PR DESCRIPTION
**Pull request by pedroalmd**

### CODE REVIEW

**Comment by pedroalmd** [comment]
https://issues.liferay.com/browse/COMMERCE-5916 cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by pedroalmd** [comment]
This ticket is blocked now @kristinonias

**Pull request closed without merging**
