### PR TITLE
COMMERCE-9335 commerce-product-service Removing the lines responsible…

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
… for returning no channels for discounts in virtual instances

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Review by luca-pellizzon — CHANGES_REQUESTED** [review]
This cannot be the solution to the ticket. Even if it works it is just because you are removing any permission check from the call.
Also wrong because that code is based on inlineSQLHelper being "true", so you can avoid running the code simply by sending false as parameter value, not by deleting it.

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by MahmoudAzzam** [comment]
@luca-pellizzon Please review the latest changes

**Comment by luca-pellizzon** [comment]
See https://github.com/liferay-commerce/liferay-portal/pull/2840

**Pull request closed without merging**
