### PR TITLE
LPD-21803 Get static resource URL in order to minify file

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://liferay.atlassian.net/browse/LPD-21803

/o/commerce-frontend-js/styles/main.css file is not being minified since it does not have minifierType="css".

To resolve this we call _portal.getStaticResourceURL on the URL so that minifierType="css" is added and the AggregateFilter is able to minify the file.

Please let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Errors don't seem related to this pull request.

Could anyone confirm we can forward this pull request, please?

**Comment by gianmarcobrunialti** [comment]
@fortunatomaldonado @antonio-ortega This doesn't seem to be affecting `master` per se, as there's minification in place, based on my test.

Firefox:
image

Chrome:
image


On the contrary, by testing your fix, and having `minifierType=css` added, the CSS size increased by some bytes, also resulting in breaking dependencies for some reasons. 

image

Can we take this offline for a quick discussion?

**Review by gianmarcobrunialti — COMMENTED** [review]
Please check the general comment.

**Comment by gianmarcobrunialti** [comment]
@fortunatomaldonado As the LPD-21803 ticket was closed as not reproducible on `master`, can this PR be closed as well? Thanks!

**Comment by fortunatomaldonado** [comment]
Closing PR, Thank you for all the help!

**Comment by gianmarcobrunialti** [comment]
Thank you!

**Pull request closed without merging**
