### PR TITLE
COMMERCE-11195 Fix fragment diagram product card

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by luca-pellizzon** [comment]
@alessiorendina please rebase, code is fine 👍

**Review by luca-pellizzon — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by lorenzolapescara** [comment]
Re-sent at #3614

**Comment by lorenzolapescara** [comment]
ci:close

**Pull request closed without merging**
