### PR TITLE
COMMERCE-12540 Create an Accordion for Options in the Minicart

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-12540

Original PRs: https://github.com/liferay-commerce/liferay-portal/pull/4326, https://github.com/liferay-commerce/liferay-portal/pull/4393

Open a new pr to run the test suites.

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4397

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
