### PR TITLE
COMMERCE-7912 commerce-warehouse-web feature flag

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-7912

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@andrea-ale-sbarra I merged this, but please send a follow up PR and remove

<aui:input name="mvccVersion" type="hidden" value="<%= (commerceInventoryWarehouse == null) ? 0 : commerceInventoryWarehouse.getMvccVersion() %>" />

git grep "aui:input name=\"mvccVersion" **.jsp

You should never pass in the mvccVersion like this

**Comment by andrea-ale-sbarra** [comment]
already merged

**Pull request closed without merging**
