### PR TITLE
Order item amos fong

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
ci:test:sf

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by amosfong** [comment]
ci:test:commerce

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@amosfong there is another pull from @andrea-ale-sbarra here: https://github.com/liferay-commerce/liferay-portal/pull/2582. Is this pull/CI test still needed?

**Comment by amosfong** [comment]
New PR with upsert changes too https://github.com/liferay-commerce/liferay-portal/pull/2585

**Pull request closed without merging**
