### PR TITLE
Commerce 8750

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by amosfong** [comment]
ci:test:sf

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
@amosfong need to be rebased due to conflicts. I asked @andrea-ale-sbarra for a review, looks fine to me.

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
@amosfong looks fine to me too.

Thanks!

**Comment by amosfong** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by amosfong** [comment]
@luca-pellizzon rebased and repushed, thanks!

**Comment by luca-pellizzon** [comment]
@jpince if you agree on following commerce's standard flow, this needs to go through our QA tests before sending it to Brian.
@andrea-ale-sbarra already asked if there's enough capacity to test this inside the current sprint, but I guess not.
see https://issues.liferay.com/browse/COMMERCE-8750?focusedCommentId=2675082&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2675082

**Comment by jpince** [comment]
@luca-pellizzon @andrea-ale-sbarra thanks for the explanation, I didn't know the team had this process for assigning QA work. We'll wait for the QA review, please let us know if you need anything in the meantime.

**Comment by lorenzolapescara** [comment]
QA Passed. Forwarding

**Pull request closed without merging**
