### PR TITLE
COMMERCE-7695 Add ClickOnCartItemRedirectToProductDetails test

### PR DESCRIPTION
**Pull request by nkkwon**
https://issues.liferay.com/browse/COMMERCE-7695

### CODE REVIEW

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nkkwon** [comment]
ci:test:stop

**Comment by nkkwon** [comment]
ci:stop

**Comment by nkkwon** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
@nkkwon, please close this PR. We will review on https://github.com/nikki-pru/liferay-portal/pull/123

**Pull request closed without merging**
