### PR TITLE
Automated Test - COMMERCE-6336 | master

### PR DESCRIPTION
**Pull request by leticiachiu**

### CODE REVIEW

**Comment by leticiachiu** [comment]
https://issues.liferay.com/browse/COMMERCE-6336 cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ViewMiniCartItemWithPromotion passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
