### PR TITLE
Automated Test - COMMERCE-6113 | master

### PR DESCRIPTION
**Pull request by PauloVAS**

### CODE REVIEW

**Comment by PauloVAS** [comment]
https://issues.liferay.com/browse/COMMERCE-6113, CC: @pietro69

**Comment by brittneyq** [comment]
ci:test:sf

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:test:commerce-functional

**Comment by PauloVAS** [comment]
Rebase Done, @kristinonias

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Combined: https://github.com/liferay-commerce/liferay-portal/pull/1255
Forwarded: https://github.com/brianchandotcom/liferay-portal/pull/102208

**Pull request closed without merging**
