### PR TITLE
COMMERCE-12768 - Case sensitive coupon codes are not applied

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-12768

Resent from https://github.com/liferay-commerce/liferay-portal/pull/4420

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Review by baharturk — APPROVED** [review]

**Comment by jaydawu** [comment]
There are no related failures to this pull, it can be force-forwarded, thanks!
cc. @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
