### PR TITLE
LPS-146539

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
Hello,
I'm sending this PR that modify the _updateOrder method in the OrderResource because we need to update the CommerceOrderItems before to update the CommerceOrder, since we need to get the right prices values (like subtotal, total and so on...), so i want to know if it's  if this would be a huge impact in the code.

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
@andrea-ale-sbarra can you review this PR, please?

**Comment by joseabelenda** [comment]
ci:close

**Pull request closed without merging**
