### PR TITLE
LPD-0 Add playwright to commerce suite

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce-functional

**Comment by riccardo-alberti** [comment]
ci:stefano

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by smottal** [comment]
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/4703

**Pull request closed without merging**
