### PR TITLE
COMMERCE-11497 We need to pass in userId instead

### PR DESCRIPTION
**Pull request by brianikim**
Resent from: 

https://github.com/liferay-commerce/liferay-portal/pull/3772

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed, no related errors to this pull. I will forward this. Thank you!

cc @victoroscuro

**Comment by jaydawu** [comment]
ci:forward

**Pull request closed without merging**
