### PR TITLE
Automated Test - COMMERCE-5530 | master

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/COMMERCE-5530 

cc: @Pietro69

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
Sent in #857.
Please close.

**Comment by brittneyq** [comment]
ci:close

**Pull request closed without merging**
