### PR TITLE
LPD-38261

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-38261

Resent from: https://github.com/liferay-commerce/liferay-portal/pull/5466

@alessiorendina , @andrea-ale-sbarra

### CODE REVIEW

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM
Thank you!

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:playwright

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
