### PR TITLE
LPS-198665 AccountEntry permission validation on v1.0/postal-addresses/{postalAddressId} endpoint

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:um

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:um

**Comment by jaydawu** [comment]
Just need to analyze the results again when they come out.
cc/ @victoroscuro

**Comment by baharturk** [comment]
ci:test:stable

**Comment by baharturk** [comment]
ci:test:stable

**Comment by baharturk** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
There are no related errors to this pull, it can be force-forwarded, thanks!
cc/ @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
