### PR TITLE
LPS-192298 Permissions to handling the "Channel Default" tab

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPS-192298
Test plan: https://liferay.atlassian.net/browse/COMMERCE-12689

Resent from https://github.com/liferay-commerce/liferay-portal/pull/4399 for semantic versioning

@jaydawu

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi [@victoroscuro](https://github.com/victoroscuro), please help monitor the results when they come in your working time and see if it's good to be forwarded, thank you!

**Comment by jaydawu** [comment]
ci:test:um

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi [@victoroscuro](https://github.com/victoroscuro), this pr is good please help force-forward it, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
