### PR TITLE
COMMERCE-9463 Add breadcrumb on Minium Demo Pack product details page

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-9463

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by Brunno0liveira** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
