### PR TITLE
LPD-37101 - Remove Release FF for LPD-19843

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-37101

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:relevant

**Review by smottal — APPROVED** [review]

**Comment by brbalazs** [comment]
ci:stop

**Comment by brbalazs** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:20027495

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
