### PR TITLE
COMMERCE-10847 Select order type before add product to a cart

### PR DESCRIPTION
**Pull request by ilzamcmed**

### CODE REVIEW

**Comment by ilzamcmed** [comment]
ci:test:sf

**Comment by ilzamcmed** [comment]
ci:test:relevant

**Comment by ilzamcmed** [comment]
The test that is failing are related to the old behavior of order type.
Can you confirm, @victoroscuro ?
Thanks! :smiley:

**Comment by baharturk** [comment]
Hi @ilzamcmed, I checked the failing test, as you mentioned above, this is related to the change in the behavior and the test needs to be fixed according to the story. Thanks!
cc/ @victoroscuro

**Comment by baharturk** [comment]
ci:test:commerce-funtional

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by ilzamcmed** [comment]
Hey @alessiorendina 
Could you review this PR?
Please, see [this thread](https://liferay.slack.com/archives/C03LXJA82J1/p1684412728414609?thread_ts=1679403955.189219&cid=C03LXJA82J1) on slack
Thanks!

**Review by alessiorendina — APPROVED** [review]

**Comment by jaydawu** [comment]
QA passed, add automated tests and resent on https://github.com/liferay-commerce/liferay-portal/pull/3818

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
