### PR TITLE
COMMERCE-8143 - Add to Cart new Style

### PR DESCRIPTION
**Pull request by fabio-d-m**
@victoroscuro all tests with quantity selectors need to be updated :)

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:stop

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
@victoroscuro I've updated the PR

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:commerce

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
ci:stop

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Pull request closed without merging**
