### PR TITLE
Commerce 8388 1/3 account changes

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-8388

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
@andrea-ale-sbarra this is missing the ugrade process, same for the PR 2, I can't see where you put the upgrade process

**Comment by andrea-ale-sbarra** [comment]
@luca-pellizzon I missed that, now I've made it and added here

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:stop

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Pull request closed without merging**
