### PR TITLE
COMMERCE-11835 | COMMERCE-12921 

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/COMMERCE-12921
https://liferay.atlassian.net/browse/COMMERCE-11835

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
ci:test:stable

**Comment by jaydawu** [comment]
There are no related errors to this pull, please help force-forwarded, thanks!
cc/ @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
