### PR TITLE
COMMERCE-8462 Translate commerce report

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-8462

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:forward

**Pull request closed without merging**
