### PR TITLE
COMMERCE-8752 Performance issue with update shipment status

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
@riccardo-alberti  need for a rebase here, thanks

**Comment by andrea-ale-sbarra** [comment]
sent [here](https://github.com/liferay-commerce/liferay-portal/pull/6374)

**Pull request closed without merging**
