### PR TITLE
COMMERCE-5745 Remove from quarantine all tests into CPCommerceSettings

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5745

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by brianchandotcom** [comment]
@Pietro69 I merged this manually.

**Comment by brianchandotcom** [comment]
ci:close

**Pull request closed without merging**
