### PR TITLE
COMMERCE-9811

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-9811

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@luca-pellizzon ,

COMMERCE-9811 was already partially committed. These three commits are the ones that got reverted. The only change is the commit: https://github.com/liferay-commerce/liferay-portal/pull/2990/commits/240ce7aaae4b5f28d36f5185064af7ff2cc4bae9 . I modified the single SQL query to work as expected. I tested the query in MySQL prior to sending this PR.

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
