### PR TITLE
[TS] LPS-201603

### PR DESCRIPTION
**Pull request by ChrisKian**
https://liferay.atlassian.net/browse/LPS-201603

Resent from https://github.com/liferay-commerce/liferay-portal/pull/4498

Previous PR was failing due to upgrade process issues.  The problem was [a lower-cased table name](https://github.com/liferay-commerce/liferay-portal/pull/4498/commits/0a70af9e5c514d837f4cfc176034dbe8ec52ce96#diff-e719bf0af6a4242196f20d6d1a53970aa7953b639be0f3e95e543ca619caf9fbR35), which is now [fixed](https://github.com/liferay-commerce/liferay-portal/commit/ac2576ecc5b60358d8be5f74b88cb294cf6e3d0d#diff-e719bf0af6a4242196f20d6d1a53970aa7953b639be0f3e95e543ca619caf9fbR35).

Please let me know if you have any questions, thanks!

CC @smottal

### CODE REVIEW

**Review by smottal — APPROVED** [review]
LGTM! Thx

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:um

**Comment by lorenzolapescara** [comment]
Failures are not related to the PR.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
