### PR TITLE
COMMERCE-5596 Isolate order refresh to call the API by itself on update

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:test:relavant

**Review by ivicac — APPROVED** [review]

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
