### PR TITLE
COMMERCE-8534, COMMERCE-8535, COMMERCE-8536, COMMERCE-8537, COMMERCE-8538, COMMERCE-8539, COMMERCE-8542 | master

### PR DESCRIPTION
**Pull request by Kvale1733**
https://issues.liferay.com/browse/COMMERCE-8534
https://issues.liferay.com/browse/COMMERCE-8535
https://issues.liferay.com/browse/COMMERCE-8536
https://issues.liferay.com/browse/COMMERCE-8537
https://issues.liferay.com/browse/COMMERCE-8538
https://issues.liferay.com/browse/COMMERCE-8539
https://issues.liferay.com/browse/COMMERCE-8542

### CODE REVIEW

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce:functional

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
@Kvale1733 can you please remove the test stubs for these tests that were wrongly placed in `CPCommerceChannels.testcase`? Thanks a lot!

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:s

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:sf

**Comment by Kvale1733** [comment]
ci:test:commerce-functional

**Review by lorenzolapescara — APPROVED** [review]

**Comment by lorenzolapescara** [comment]
ci:forward

**Pull request closed without merging**
