### PR TITLE
COMMERCE-9434 Product Attachments available for use with Collection Display Fragments

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Story https://issues.liferay.com/browse/COMMERCE-9434
Tech Task: https://issues.liferay.com/browse/COMMERCE-10013

This PR contains Commits from https://github.com/liferay-commerce/liferay-portal/pull/3056

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
@andrea-ale-sbarra @22LucaGiannotta22 can we forward it?

**Comment by 22LucaGiannotta22** [comment]
@alessiorendina Just analyzed ci:test:commerce, I think we can forward

**Comment by andrea-ale-sbarra** [comment]
@alessiorendina @22LucaGiannotta22 These changes look good to me

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:forward

**Pull request closed without merging**
