### PR TITLE
LPD-19793 Move feature flag to release

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-19793
and
https://liferay.atlassian.net/browse/LPD-19788

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:forward

**Comment by smottal** [comment]
ci:report:2547306433

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
