### PR TITLE
COMMERCE-10497 commerce-product-service Make CommerceChannelIndexer p…

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
…ermission filtering configurable

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:test:commerce

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
Test suites checked, everything looks fine.

**Comment by victoroscuro** [comment]
ci:forward

**Pull request closed without merging**
