### PR TITLE
LPD-22897 - Administrator can't change accounts in Account Management Widget

### PR DESCRIPTION
**Pull request by victorcdp**
https://liferay.atlassian.net/browse/LPD-22897

After the changes made by COMMERCE-12663/LPD-13529, admin users can't change to an account they didn't create because the fetch method only returns accounts they created.
I added a check to return all accounts if the current user is an admin

@smottal Can you review this one? Tied to an LPP. Thank you!

### CODE REVIEW

**Review by smottal — COMMENTED** [review]
Hi @victorcdp , the code itself is fine but I don't get why this should fix the problem. I mean... if I understood correctly both admins view the full list of accounts but then, when selected one, they lose the selection. But with this change I think we are only "not filtering" the list

**Comment by victorcdp** [comment]
@smottal the problem is actually when you refresh the page and the getCurrentAccountEntry method is run. When it reaches [this](https://github.com/liferay/liferay-portal/blob/7a3e7ec6f386e1fe6f4c2d8bf4d71177f881fe66/modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/util/CommerceAccountHelperImpl.java#L359-L383) part, it will switch back to the previous account because the commerceChannelAccountEntries will not include accounts not created by the current user.

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:report:2560432061

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
