### PR TITLE
COMMERCE-4722 Only show decimals if user inputs decimals

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
@alecsloan  is this PR still relevant?

**Comment by alecsloan** [comment]
Yes, can be rebased when @marco-leo is ready to review/merge

**Comment by ivicac** [comment]
@alecsloan, can you please re-base it first and run tests again?

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
