### PR TITLE
COMMERCE-11715 - Issue with Custom Fields not being returned in OptionValue API

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #3877 

https://liferay.atlassian.net/browse/COMMERCE-11715

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Review by baharturk — APPROVED** [review]

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not caused by the PR. This can be force forwarded

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
