### PR TITLE
LPS-152750 ant build-lib-versions

### PR DESCRIPTION
**Pull request by MarinhoFeliphe**

### CODE REVIEW

**Comment by victoroscuro** [comment]
ci:test:commerce

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
@pietrobocale

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
PR was already forwarded and merged by brian

**Comment by ChrisKian** [comment]
Hi @riccardo-alberti,
I believe the changes in LPS-152750 only account for half of the iText usages.  This PR is also required (or [at least this change](https://github.com/liferay-commerce/liferay-portal/pull/3021/files?show-viewed-files=true&file-filters%5B%5D=#diff-64ad78ee70a991c55de491892bcb5c195bde682064a846bf67cebee85242c9a3R7)) since there is another dependency on iText which lives exclusively on the commerce side.

Please let me know if you need me to make a follow-up PR, or if my analysis is incorrect.  Thanks!

CC @MarinhoFeliphe

**Comment by ChrisKian** [comment]
Sure thing @riccardo-alberti, follow-up sent here: https://github.com/liferay-commerce/liferay-portal/pull/3078

**Pull request closed without merging**
