### PR TITLE
COMMERCE-12228 New item finder for sku with UOM

### PR DESCRIPTION
**Pull request by pietrobocale**
Ticket: https://liferay.atlassian.net/browse/COMMERCE-12228

Base PR: https://github.com/liferay-commerce/liferay-portal/pull/4203

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by smottal** [comment]
@smottal

**Review by 22LucaGiannotta22 — APPROVED** [review]

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/4225

**Pull request closed without merging**
