### PR TITLE
COMMERCE-12540 Create an Accordion for Options in the Minicart

### PR DESCRIPTION
**Pull request by pietrobocale**
Original PR: https://github.com/liferay-commerce/liferay-portal/pull/4326

https://liferay.atlassian.net/browse/COMMERCE-12540

### CODE REVIEW

**Comment by pietrobocale** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:stop

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Fix the conflict and resent on https://github.com/liferay-commerce/liferay-portal/pull/4395

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
