### PR TITLE
COMMERCE-7858 Use callbackURL as next step if not null

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
@alessiorendina
check this out. That's what I was talking about.

**Comment by alessiorendina** [comment]
@joseabelenda @luca-pellizzon This makes sense for me. I remember that the request was to move the logic as it was, so I just moved it, but this is the way I wanted to do it from the beginning. I'll run the CI and then forward it to Brian.

Thanks,
Alessio

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:sf

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
Hi @alessiorendina @luca-pellizzon 
I ran sf, relevant and stable tests on my own branch and it's ok.
https://github.com/joseabelenda/liferay-portal/pull/122
Can I forward to BChan?

**Comment by luca-pellizzon** [comment]
@joseabelenda try to rebase on BChan master and update this PR with that code. We prefer to have tests running before merging.
Thank you.

**Comment by joseabelenda** [comment]
ci:test:relevant

**Comment by kevenleone** [comment]
ci:test:relevant

**Comment by joseabelenda** [comment]
@alessiorendina all tests are ok.
Can we forward to BChan?

**Comment by alessiorendina** [comment]
ci:forward

**Comment by alessiorendina** [comment]
@joseabelenda Forwarded, thanks!

**Pull request closed without merging**
