### PR TITLE
LPD-20542 - When updating the image of an org the size limit of the file is not showing the correct value

### PR DESCRIPTION
**Pull request by victorcdp**
https://liferay.atlassian.net/browse/LPD-20542

@smottal Can you take a look at this one? Tied to an LPP. Thank you

### CODE REVIEW

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:stop

**Comment by victorcdp** [comment]
ci:test:um

**Comment by victorcdp** [comment]
ci:stop

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:um

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:um

**Comment by victorcdp** [comment]
@smottal the failures don't seem to be related to the changes

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:forward

**Pull request closed without merging**
