### PR TITLE
Automated Test - COMMERCE-6149 | master

### PR DESCRIPTION
**Pull request by fmarcio**

### CODE REVIEW

**Comment by fmarcio** [comment]
https://issues.liferay.com/browse/COMMERCE-6149; cc: @lorenzolapescara

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
SearchBarWidgetSearchProductByNameDoubleQuotes passed. Forwarding.

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
