### PR TITLE
COMMERCE-4774 actions definitions fixed on order items data set display

### PR DESCRIPTION
**Pull request by fabio-d-m**

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
@marco-leo the error is totally unrelated

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
Closing sent directly here https://github.com/brianchandotcom/liferay-portal/pull/94156.

**Pull request closed without merging**
