### PR TITLE
LPD-37608 - Failing poshi test CPCommerceProducts#DuplicateAProductAndVerifyIfSkuPriceIsUnique

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-37608

Test already covered by:
* LocalFile.CPCommerceProducts#DuplicateAProductAndVerifyIfSkuPriceIsUnique
* LocalFile.CPCommerceProducts#CanDuplicateProductAndVerifyFriendlyUrlMatchesProductName

cc @smottal

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by brbalazs** [comment]
restarted bc of CI failure

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
