### PR TITLE
COMMERCE-11736 - Special Character Validation for Product Relation Type

### PR DESCRIPTION
**Pull request by jaydawu**
https://liferay.atlassian.net/browse/COMMERCE-11736
Resent from https://github.com/liferay-commerce/liferay-portal/pull/3892

### CODE REVIEW

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
SF team is working on this SF issue, we are having new issue with https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-issueidorkey-get

@jaydawu You can do the manual forward to BChan if other tests are green.

/cc @qz1010 @Tim-Cao
https://liferay.slack.com/archives/C1SJ64S9X/p1687151985725329

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by ling-alan-huang** [comment]
The fix for SF issue is here: https://github.com/ling-alan-huang/liferay-portal/pull/1943

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Review by baharturk — APPROVED** [review]

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
The failures are not related to the PR. This can be forwarded.

@victoroscuro

**Comment by victoroscuro** [comment]
ci:forwad:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by jaydawu** [comment]
Hi @victoroscuro, the CI command is not retriggered, could you please rerun it again? Thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
