### PR TITLE
Automated Test - COMMERCE-6266 | master

### PR DESCRIPTION
**Pull request by IsaVV**

### CODE REVIEW

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@IsaVV This is failing at Source Formatting. Please fix and resend.

**Comment by nikki-pru** [comment]
Testing here: https://github.com/nikki-pru/liferay-portal/pull/97

**Comment by nikki-pru** [comment]
Testing here: https://github.com/nikki-pru/liferay-portal/pull/97

**Comment by nikki-pru** [comment]
Testing here: https://github.com/nikki-pru/liferay-portal/pull/97

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not present at "//div[contains(@class,'dnd-tr with-bg')]//div[contains(text(), 'Test')][1]"

**Pull request closed without merging**
