### PR TITLE
COMMERCE-11699 Supplier to Manage Warehouses & Inventory linked to their channel 

### PR DESCRIPTION
**Pull request by luca-pellizzon**

### CODE REVIEW

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
The failures are not related to the PR

**Comment by CrescenzoRegaLF** [comment]
resent here: https://github.com/liferay-commerce/liferay-portal/pull/3942

**Pull request closed without merging**
