### PR TITLE
COMMERCE-10834 Virtual Product Activation Status Complete and Processing is not respected

### PR DESCRIPTION
**Pull request by ghost**
https://issues.liferay.com/browse/COMMERCE-10834

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@CrescenzoRegaLF I don't think this is the right fix. By debugging the download widget I found that this https://github.com/liferay-commerce/liferay-portal/blob/6bf731fe26dbabf1d85588b9a43eb9888980e8c5/modules/apps/commerce/commerce-product-type-virtual-order-content-web/src/main/java/com/liferay/commerce/product/type/virtual/order/content/web/internal/display/context/CommerceVirtualOrderItemContentDisplayContext.java#L324

is not finding the Virtual Order Item because the query that runs that is <sql id="com.liferay.commerce.product.type.virtual.order.service.persistence.CommerceVirtualOrderItemFinder.findByG_C_A"> is looking for an VirtualOrderItem that is active while this remains inactive:

Screenshot 2023-03-21 at 12 58 06

I think you should find the reason why this is not getting activated

**Pull request closed without merging**
