### PR TITLE
LPD-35329 functional test for Checkout with Multi Shipping (order summary)

### PR DESCRIPTION
**Pull request by monaco-fabio**

### CODE REVIEW

**Comment by monaco-fabio** [comment]
@luca-pellizzon

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:sf

**Comment by monaco-fabio** [comment]
ci:test:playwright

**Comment by luca-pellizzon** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/5578

**Pull request closed without merging**
