### PR TITLE
LPD-18547 - let the reminder query answer input box appear in plaintext if appropriate setting is enabled

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @smottal,
https://liferay.atlassian.net/browse/LPD-18547, tied to LPP.

Changes to hide user security answers due to security concerns were made in [LPS-107063](https://liferay.atlassian.net/browse/LPS-107063). However, at the same time, this LPS added a property (users.reminder.queries.display.answer.in.plain.text) which allows the portal admin to revert back to the previous behavior if they wish. We can see the property was applied to a number of places in commit https://github.com/liferay/liferay-portal-ee/commit/e287417318943d691313bbe80d370212b28b73c8, but notably was not applied to the forgot_password.jsp where the [text box was strictly changed to a password box](https://github.com/liferay/liferay-portal-ee/commit/e287417318943d691313bbe80d370212b28b73c8#diff-cbfdde23acb54464ca00b6ff3e3ae2ab73b5b2477a2211360423538b3cfc772cL102-R102). This change uses the property to determine whether the input box's type is password or text.

AppSec's opinion on the issue can be found here: https://liferay.slack.com/archives/C0A1Z5FJL/p1708569888112929

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:um

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Pull request closed without merging**
