### PR TITLE
COMMERCE-12504 Missing Data in headless-commerce-admin-catalog Endpoints

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #4434 

https://liferay.atlassian.net/browse/COMMERCE-12504

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
