### PR TITLE
Automated Test - COMMERCE-6063 | master

### PR DESCRIPTION
**Pull request by ocesar9**

### CODE REVIEW

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
Remove the @ignore = "true"

**Comment by c3saroliveira** [comment]
https://issues.liferay.com/browse/COMMERCE-6063, cc: @PietroBocale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:forward

**Pull request closed without merging**
