### PR TITLE
COMMERCE 2580 2

### PR DESCRIPTION
**Pull request by ivicac**

### CODE REVIEW

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
@andrea-ale-sbarra is this PR still needed? if not please close it

**Comment by andrea-ale-sbarra** [comment]
This can be closed as @ivicac said

**Pull request closed without merging**
