### PR TITLE
COMMERCE-9568 - No underline for Unit tab for Measurement Units

### PR DESCRIPTION
**Pull request by alessiorendina**
@victorcdp I forwarded it here, thanks!

Original PR: https://github.com/alessiorendina/liferay-portal/pull/25

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victorcdp** [comment]
ci:close

**Comment by victorcdp** [comment]
Closed as it needed additional fix. New PR is [here](https://github.com/liferay-commerce/liferay-portal/pull/3383)

**Pull request closed without merging**
