### PR TITLE
Commerce 10759 refactor

### PR DESCRIPTION
**Pull request by brianikim**
only open for ci testing

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@dsitu , requesting a review just in case I missed anything in my refactor.

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@dsitu , only need review on 4cf735c

**Comment by brianikim** [comment]
ci:test:sf

**Comment by dsitu** [comment]
@brianikim looks good!

**Pull request closed without merging**
