### PR TITLE
COMMERCE-12621 Accessibility alt for images

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/COMMERCE-12621

@alessiorendina ,

This needs a quick review. tied to LPP.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
I'm not sure of adding the alt attribute to the adaptive media, let's check the console of the browser to see if it warns of something.

Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by brianikim** [comment]
@andrea-ale-sbarra , the addition of `alt` to the tag was directly recommended by the adaptive media team (lima)

**Comment by brianikim** [comment]
The `alt` addition to adaptive media taglib directly is handled here: https://github.com/liferay-commerce/liferay-portal/blob/f84d3aba700b3b305d3a7aee9a8fcb8c03fb41ba/modules/apps/adaptive-media/adaptive-media-image-taglib/src/main/java/com/liferay/adaptive/media/image/taglib/servlet/taglib/AMImageImgTag.java#L57

**Comment by Brunno0liveira** [comment]
Re-sent at https://github.com/liferay-commerce/liferay-portal/pull/4358

**Comment by Brunno0liveira** [comment]
ci:close

**Pull request closed without merging**
