### PR TITLE
Commerce 9580

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9580

resend of this https://github.com/brianchandotcom/liferay-portal/pull/122094

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]
I don't like parameters to be "hidden" in the serviceContext, I prefer them to be exposed, but we don't have much time so it is approved

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@luca-pellizzon I agree with you, but that was a request from Brian https://github.com/brianchandotcom/liferay-portal/pull/122094

**Comment by luca-pellizzon** [comment]
@andrea-ale-sbarra yes I know but he was asking for sorting "serviceContext is almost always the last param"

**Comment by andrea-ale-sbarra** [comment]
> @andrea-ale-sbarra yes I know but he was asking for sorting "serviceContext is almost always the last param"

> This almost seems like something you would put in serviceContext.setAttribute(

> since it's not really a column.

**Comment by andrea-ale-sbarra** [comment]
ci:stop

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
