### PR TITLE
LPD-18316 Commerce Order Notes functional test is now sound

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:commerce-functional

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by gianmarcobrunialti** [comment]
ci:test:nocompile

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Pull request closed without merging**
