### PR TITLE
LPD-35323 Hide elements with readonly

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-36953

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by gianmarcobrunialti — APPROVED** [review]
[NB] Evaluate rems, even though I understand the need for `px` for the time being.

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
