### PR TITLE
LRQA-61503 - Quarantine functional tests | master

### PR DESCRIPTION
**Pull request by nikki-pru**
https://issues.liferay.com/browse/LRQA-61503

@iovaneale, @marco-leo, the Commerce tests were previously set to ignore=true and were not running on any job on master. This makes analysis difficult because we don't know which are passing or failing. This PR puts the tests in quarantine, which will prevent the tests from running on PRs, Stable, and on the Acceptance job but still run on the Development job for monitoring.

Also sending in a test fix for selecting the modal to help Smoke along.

### CODE REVIEW

**Comment by marco-leo** [comment]
ci:test:relevant
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:relevant:nocompile

**Comment by nikki-pru** [comment]
ci:test:relevant:nocompile

**Comment by marco-leo** [comment]
ci:forward

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Comment by jpince** [comment]
@nikki-pru :clap:

**Pull request closed without merging**
