### PR TITLE
COMMERCE-6508 Remove product from compare page

### PR DESCRIPTION
**Pull request by lorenzolapescara**
Re-sent from #3704 

@smottal 

https://issues.liferay.com/browse/COMMERCE-6508

### CODE REVIEW

**Comment by lorenzolapescara** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
ci:test:commerce-functional

**Comment by lorenzolapescara** [comment]
ci:forward

**Comment by lorenzolapescara** [comment]
ci:forward

**Comment by andrea-ale-sbarra** [comment]
sent directly to Brian here https://github.com/brianchandotcom/liferay-portal/pull/134290

**Pull request closed without merging**
