### PR TITLE
COMMERCE-10604 PATCH a sku's ERC via API

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-10604

Resent from https://github.com/liferay-commerce/liferay-portal/pull/3587

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
QA passed, add automation and resent on https://github.com/liferay-commerce/liferay-portal/pull/3694

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
