### PR TITLE
LPD-20881 Commerce Product Object Actions Groovy Script Does Not Have Variables

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-20881

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
Code LGTM.
Thank you!

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
@CrescenzoRegaLF see here https://github.com/liferay-commerce/liferay-portal/pull/4818

**Pull request closed without merging**
