### PR TITLE
LPS-197006 As an Instance Administrator I want to be able to Export/Import the Roles with the default Permissions

### PR DESCRIPTION
**Pull request by ghost**
resend this
https://github.com/liferay-commerce/liferay-portal/pull/4535

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:um

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by pietrobocale** [comment]
ci:test:um

**Comment by pietrobocale** [comment]
ci:test:um

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:um

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
CI results are ok, this PR can be ff @victoroscuro

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
