### PR TITLE
LPS-196309 Filter Users that are not associated with Accounts or Organizations + Automation 

### PR DESCRIPTION
**Pull request by baharturk**
resent from: #4513 

Story:
https://liferay.atlassian.net/browse/LPS-196309

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:sf

**Comment by baharturk** [comment]
ci:test:relevant

**Comment by baharturk** [comment]
ci:test:um

**Comment by riccardo-alberti** [comment]
ci:forward:force

**Pull request closed without merging**
