### PR TITLE
COMMERCE-11648 - Product Images extension is not working properly

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issue: [COMMERCE-11648](https://issues.liferay.com/browse/COMMERCE-11648)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
@andrea-ale-sbarra Can you review this one? it's tied to an LPP. Thank you.

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures on the relevant are not related to this PR. It can be forwarded.

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
