### PR TITLE
COMMERCE-9313 fixed service for DB2 issue

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
Selecting the whole entity with the distinct clause was causing an issue on DB2 engine because of the CLOB column

https://liferay.atlassian.net/browse/COMMERCE-9313

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:help

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce

**Comment by saramart81** [comment]
ci:help

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
Relevant failures aren't related to the changes made for this PR.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
