### PR TITLE
COMMERCE-11504 APIs to Link Catalogue to an Account + JSON macro fix

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-11004
https://issues.liferay.com/browse/COMMERCE-11504

### CODE REVIEW

**Comment by dsitu** [comment]
ci:forward

**Comment by alessiorendina** [comment]
Hey @dsitu relevant is failing on the same tests, can you check if they are related to this PR?

**Comment by pietrobocale** [comment]
I checked the tests, and the problem with why the test is failing is that the fix for the JSON used for the tests is not working, I created this new PR here with the changes #3815 

@alessiorendina @dsitu

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
