### PR TITLE
LPD-34379 Add exception mappers

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-34379

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Review by alessiorendina — APPROVED** [review]

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:17122361

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
