### PR TITLE
Automated Test - COMMERCE-6164 | master

### PR DESCRIPTION
**Pull request by ocesar9**

### CODE REVIEW

**Comment by kristinonias** [comment]
@c3saroliveira ,

There are conflicting files in this Pull Request. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by lorenzolapescara** [comment]
@c3saroliveira this test has been committed on top of another test code. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by nikki-pru** [comment]
[Passing here](https://testray.liferay.com/home/-/testray/cases/1532400191)

**Comment by nikki-pru** [comment]
ci:forward

**Pull request closed without merging**
