### PR TITLE
LPS-132087 Migrate selection modals in commerce-bom-admin-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-commerce,

Attached is an update for http://issues.liferay.com/browse/LPS-132087.

I was not able to figure out how to test these changes since I only go the modal to appear, but could not add any data/items to the search container to test if the selection actually works.

**Test Plan:**
1. Login to Liferay
2. Click on the **Application Menu**
3. Go to **Commerce** -> **Shop by Diagram**
4. Click the `+` and **Add Folder**
5. Enter a folder name
6. Click on the **Models** tab
7. Click the `+` to open the modal

commerce

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:reevaluate:1167401_8313

**Comment by jonmak08** [comment]
ci:reevaluate:1167401_8313

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:reevaluate:1097401_4810

**Comment by markocikos** [comment]
@FabioDiegoMastrorilli please review this PR

**Comment by FabioDiegoMastrorilli** [comment]
Good job ;)

**Comment by FabioDiegoMastrorilli** [comment]
ci:relevant

**Comment by FabioDiegoMastrorilli** [comment]
ci:forward

**Pull request closed without merging**
