### PR TITLE
COMMERCE-10498 | Discontinued skus are not replaced using Quick Add to Cart

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://liferay.atlassian.net/browse/COMMERCE-11205
https://liferay.atlassian.net/browse/COMMERCE-10498

Resent from #3859

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
New PR:
https://github.com/liferay-commerce/liferay-portal/pull/4085

**Comment by pietrobocale** [comment]
ci:close

**Pull request closed without merging**
