### PR TITLE
COMMERCE-5453 Add upgrade process to remove portlet 90 references from resourceAction

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Review by marco-leo — CHANGES_REQUESTED** [review]
Is not just deleting, but in adding as well the resources mapped to the existing roles

**Comment by riccardo-alberti** [comment]
closing this PR and opening https://github.com/liferay-commerce/liferay-portal/pull/696

**Pull request closed without merging**
