### PR TITLE
COMMERCE-10520

### PR DESCRIPTION
**Pull request by brianikim**
From @victorcdp,

> Related Issue: [COMMERCE-10520](https://issues.liferay.com/browse/COMMERCE-10520)
> 
> There was no logic to add the Shipment Status to the return of the API call. Proposed fix is to add such logic.

@luca-pellizzon

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by Brunno0liveira** [comment]
ci:test:sf

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:forwward

**Comment by Brunno0liveira** [comment]
ci:forward

**Pull request closed without merging**
