### PR TITLE
Automated Test - COMMERCE-6062 | master

### PR DESCRIPTION
**Pull request by gmbc92**

### CODE REVIEW

**Comment by gmbc92** [comment]
https://issues.liferay.com/browse/COMMERCE-6202; cc: AlessandroIovane

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
Please add the property test.name.skip.portal.instance = "CPCommerceProductProductRelations#AddAProductRelations"

**Comment by gmbc92** [comment]
Property added and pushed @Pietro69

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
Hi @gmbc92, please fix your sf. Thanks!

**Comment by kristinonias** [comment]
@gmbc92 

This PR is closed. Please reopen this PR and force push your commit again.

**Comment by kristinonias** [comment]
ci:reopen

**Comment by JoMaAlves** [comment]
Moved to PR: https://github.com/liferay-commerce/liferay-portal/pull/1141

**Pull request closed without merging**
