### PR TITLE
COMMERCE-10079 Edit a product with options from Order Details page

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
Resent from #4377 

https://liferay.atlassian.net/browse/COMMERCE-10079

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
@smottal

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to the PR. It can be force-forwarded

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
