### PR TITLE
LPD-20228 - replace usage of PLID in update language formAction

### PR DESCRIPTION
**Pull request by wanderlast**
@smottal 

https://liferay.atlassian.net/browse/LPD-20228, tied to LPP

Currently user pages are explicitly prohibited from being accessed using a plid due to possible enumeration attacks. I've switched the PLID usage to using a layoutFriendlyURLId instead. These IDs from my testing appear to be non-sequential unlike the plids and therefore appear to me to be significantly more difficult to potentially brute force which hopefully fulfills our security brief. Since we no longer are adding the plid to our parameters, we retrieve it in servicePreAction using our layoutFriendlyURLId along with our layout. I've replaced the usages of plid in other areas that invoke the update language formAction as well for consistency.

CC: @pei-jung

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:stop

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by smottal** [comment]
Closing as replace by https://github.com/liferay-commerce/liferay-portal/pull/4857

**Pull request closed without merging**
