### PR TITLE
Automated Test - COMMERCE-6202 | master

### PR DESCRIPTION
**Pull request by lima-rafa**

### CODE REVIEW

**Comment by lima-rafa** [comment]
https://issues.liferay.com/browse/COMMERCE-6202; cc: @iovaneale

**Comment by kristinonias** [comment]
@lima-rafa ,

There are conflicting files in this Pull Request. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
Element is not present at "//label[contains(.,'Minium Portal')]/input[@type='checkbox' and @checked]"

**Comment by pedroalmd** [comment]
@lima-rafa Please close this PR. 
New PR: https://github.com/liferay-commerce/liferay-portal/pull/1231

**Pull request closed without merging**
