### PR TITLE
[TS] LPS-188035 | master

### PR DESCRIPTION
**Pull request by samanzanedo**
Hi team,

I send you this PR after a review done in https://github.com/liferay-core-infra/liferay-portal/pull/4810

Best regards

References:
https://liferay.atlassian.net/browse/LPS-188035

CC: @tinatian

### CODE REVIEW

**Comment by samanzanedo** [comment]
Hi team,

any updates on this?

Regards

**Review by andrea-ale-sbarra — COMMENTED** [review]
This looks fine, but I don't get why it should be reviewed by Commerce team, it's not changing Commerce code, can you please clarify this?

Thank you!

**Comment by samanzanedo** [comment]
Hi @andrea-ale-sbarra 

This PR was sent to core team  in https://github.com/liferay-core-infra/liferay-portal/pull/4810

They asked why the disptachTrigger could be  null, and based on this commit  [COMMERCE-9611](https://github.com/liferay-core-infra/liferay-portal/commit/99a44fcab92bffc07f912603b7aad852c9ac3e6c)  , they considered Commerce Team should review this PR instead.

Regards

**Comment by samanzanedo** [comment]
Hi @andrea-ale-sbarra 

Do you need additional info about this?

Regards

**Comment by samanzanedo** [comment]
Hi @andrea-ale-sbarra 

We need to move forward with this because customer is waiting for the fix.

Regads

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by crodriguezy** [comment]
Hi @andrea-ale-sbarra , do you think is this PR ready to be moved forward? As @samanzanedo pointed, the customer is waiting for the fix.
Thanks

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
@andrea-ale-sbarra @samanzanedo Thanks for catching the bug, please see https://github.com/liferay-headless/liferay-portal/pull/1342 for the fix. (each dispatch trigger log must have a related dispatch trigger, no need to check for null)

**Comment by andrea-ale-sbarra** [comment]
fix sent here https://github.com/liferay-headless/liferay-portal/pull/1342

**Pull request closed without merging**
