### PR TITLE
LPD-28466 - Products' ERC cannot be updated with PATCH by external reference code

### PR DESCRIPTION
**Pull request by victorcdp**
Resend of https://github.com/liferay-commerce/liferay-portal/pull/5048

https://liferay.atlassian.net/browse/LPD-28466

@andrea-ale-sbarra Can you review this? Tied to an LPP. Thank you!

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
