### PR TITLE
LPD-31978 - Refactor poshi test Organizations#RemoveMember

### PR DESCRIPTION
**Pull request by brbalazs**
https://liferay.atlassian.net/browse/LPD-31978

### CODE REVIEW

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:playwright:nocompile

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:playwright:nocompile

**Comment by andrea-ale-sbarra** [comment]
ci:test:playwright

**Comment by andrea-ale-sbarra** [comment]
ci:test:playwright

**Comment by brbalazs** [comment]
ci:test:sf

**Comment by brbalazs** [comment]
ci:test:playwright:nocompile

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
