### PR TITLE
COMMERCE-4692 Change separator between title and information

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/COMMERCE-4692

image

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:forward

**Pull request closed without merging**
