### PR TITLE
COMMERCE-8680 Fixed order resource implementation

### PR DESCRIPTION
**Pull request by alessiorendina**

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by luca-pellizzon — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@alessiorendina just 40712d03d382d44e8bd2ba22a719bf81d72e59c4 156ca52e7a1030b3be82e3b26e34a03af6301523 and bce0da880a727da52c70986686878fb50993a384

**Comment by alessiorendina** [comment]
ci:test:relevant

**Pull request closed without merging**
