### PR TITLE
Automated Test - COMMERCE-6114 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/COMMERCE-6114 cc: @pietrobocale

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Review by Pietro69 — APPROVED** [review]

**Comment by Pietro69** [comment]
ci:test:commerce-functional

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by iovaneale** [comment]
ci:test:commerce-functional

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
