### PR TITLE
LPD-29992 LocalFile.CPCommerceTermsAndConditions#CanCompleteCheckoutWithRichTextTermDescription

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-29992

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Review by alessiorendina — APPROVED** [review]

**Comment by CrescenzoRegaLF** [comment]
ci:forward

**Pull request closed without merging**
