### PR TITLE
COMMERCE-11884 Support update for paymentStatus in headless-api

### PR DESCRIPTION
**Pull request by brianikim**
@luca-pellizzon ,

Tied to LPP. https://liferay.atlassian.net/browse/COMMERCE-11884

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Review by luca-pellizzon — APPROVED** [review]

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:test:commerce-functional

**Comment by pietrobocale** [comment]
ci:forward

**Comment by pietrobocale** [comment]
The failures are not related to the PR

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
