### PR TITLE
COMMERCE-2912 Global Search React Component

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
from https://github.com/liferay-commerce/liferay-portal/pull/381

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by ivicac** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:close

**Pull request closed without merging**
