### PR TITLE
COMMERCE-12230 Checkout perfomance

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-integration

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-integration

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-integration

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1327401_2411

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1257401_3822

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-integration

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by riccardo-alberti — CHANGES_REQUESTED** [review]
@CrescenzoRegaLF @luca-pellizzon this is a breaking change. We need to write the commit message following the standard. See https://github.com/brianchandotcom/liferay-portal/pull/142322/commits/d5dde9bfd099fff1cf8f211ebd931ae1377e7fe4 as a reference

**Comment by luca-pellizzon** [comment]
@CrescenzoRegaLF https://liferay.atlassian.net/wiki/spaces/ENGR/pages/2489483265/Process+to+register+breaking+changes+in+commits

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
Hi @baharturk I ran the upgradeProcess test locally this is the log

`2023-10-20 17:52:46.165 INFO  [main][UpgradeProcess:118] Upgrading com.liferay.commerce.internal.upgrade.v11_3_0.CommerceOrderUpgradeProcess - Modifying table CommerceOrder to add the columns [shippable BOOLEAN]
2023-10-20 17:52:46.265 INFO  [main][UpgradeProcess:136] Completed upgrade process com.liferay.commerce.internal.upgrade.v11_3_0.CommerceOrderUpgradeProcess - Modifying table CommerceOrder to add the columns [shippable BOOLEAN] in 113 ms
2023-10-20 17:52:46.266 INFO  [main][UpgradeProcess:118] Upgrading com.liferay.commerce.internal.upgrade.v11_3_0.CommerceOrderUpgradeProcess
2023-10-20 17:52:46.270 INFO  [main][UpgradeProcess:136] Completed upgrade process com.liferay.commerce.internal.upgrade.v11_3_0.CommerceOrderUpgradeProcess in 4 ms
2023-10-20 17:52:46.284 INFO  [main][LoggingTimer:74] Starting com.liferay.portal.db.index.IndexUpdaterUtil#lambda$updateIndexes$2#Updating database indexes for com.liferay.commerce.service
2023-10-20 17:52:46.545 INFO  [main][BaseDB:1166] Dropping stale indexes
2023-10-20 17:52:46.559 INFO  [main][BaseDB:1478] Adding indexes
2023-10-20 17:52:46.560 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.db.index.IndexUpdaterUtil#lambda$updateIndexes$2#Updating database indexes for com.liferay.commerce.service in 276 ms`

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-integration

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:upgrade

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-integration

**Review by riccardo-alberti — APPROVED** [review]

**Comment by baharturk** [comment]
sent to: #142694

**Comment by baharturk** [comment]
ci:close

**Pull request closed without merging**
