### PR TITLE
LPD-37258 Remove erc checks

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-37258

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:20049936

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:report:21046524

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
