### PR TITLE
COMMERCE-9850

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
These changes will fix the following bugs:
- https://issues.liferay.com/browse/COMMERCE-9507
- https://issues.liferay.com/browse/COMMERCE-9765
- https://issues.liferay.com/browse/COMMERCE-9766
- https://issues.liferay.com/browse/COMMERCE-9850

It will be possible to delete product versions and product when versioning is enabled.

Fixes also conflicts from https://github.com/liferay-commerce/liferay-portal/pull/2982

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1287401_4219

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
Forwarded here: https://github.com/liferay-commerce/liferay-portal/pull/2997

**Pull request closed without merging**
