### PR TITLE
COMMERCE-10173 - It's possible to save a product configuration with wrong values

### PR DESCRIPTION
**Pull request by victorcdp**
Relevant Issue: [COMMERCE-10173](https://issues.liferay.com/browse/COMMERCE-10173)
Resent from [#3644](https://github.com/liferay-commerce/liferay-portal/pull/3644). Changing Exception names per BChan's request.

Problem was that there was no validation for these values.
Proposed fix is to add validation both in the frontend as well in the backend.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:relevant

**Comment by victorcdp** [comment]
ci:test:commerce

**Comment by victorcdp** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:sf

**Comment by jaydawu** [comment]
ci:forward

**Pull request closed without merging**
