### PR TITLE
COMMERCE-5800 (resend)

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
Resend for https://github.com/brianchandotcom/liferay-portal/pull/99089

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Review by ivicac — APPROVED** [review]

**Comment by gianmarcobrunialti** [comment]
ci:close

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:test:relevant

**Comment by ivicac** [comment]
ci:forward

**Pull request closed without merging**
