### PR TITLE
Commerce 8840 - support XML response type

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-8840

This changes will support the XML response type, indeed we will no longer generate xml tags that start with numbers

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by FabioDiegoMastrorilli** [comment]
@andrea-ale-sbarra please close this PR. [Here's the new one ](https://github.com/liferay-commerce/liferay-portal/pull/2504)

**Pull request closed without merging**
