### PR TITLE
COMMERCE-9433 Default display page template for a product

### PR DESCRIPTION
**Pull request by alessiorendina**
Changed after Brian Chan's review here: https://github.com/brianchandotcom/liferay-portal/pull/131357

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
Stable is green. Relevant failures are unrelated to the code of this PR. I'll force-forward this PR.

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by alessiorendina** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/131712

**Pull request closed without merging**
