### PR TITLE
COMMERCE-12603 - Dimensions facet url is truncated before the " character

### PR DESCRIPTION
**Pull request by victorcdp**
Relevant Issue [COMMERCE-12603](https://liferay.atlassian.net/browse/COMMERCE-12603)

@andrea-ale-sbarra can you review this one? Tied to an LPP. Thank you.

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM
Thank you!

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce-functional

**Comment by Brunno0liveira** [comment]
Re-sent at https://github.com/liferay-commerce/liferay-portal/pull/4356

**Comment by Brunno0liveira** [comment]
ci:close

**Pull request closed without merging**
