### PR TITLE
COMMERCE-10065 Add more functional tests to Commerce relevant test suite

### PR DESCRIPTION
**Pull request by iovaneale**

### CODE REVIEW

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:stop

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by victoroscuro** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:test:relevant

**Comment by iovaneale** [comment]
ci:forward

**Pull request closed without merging**
