### PR TITLE
LPS-163842 Add filter in ChannelEntityModel 

### PR DESCRIPTION
**Pull request by kellylisbino**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:commerce

**Comment by gleicelisbino** [comment]
ci:test:commerce

**Comment by gleicelisbino** [comment]
ci:test:commerce

**Pull request closed without merging**
