### PR TITLE
COMMERCE-6697 Fix CommerceSitemapURLProviderTest

### PR DESCRIPTION
**Pull request by alecsloan**

### CODE REVIEW

**Comment by alecsloan** [comment]
ci:test:sf

**Comment by alecsloan** [comment]
ci:test:relevant

**Comment by alecsloan** [comment]
ci:forward

**Comment by ivicac** [comment]
ci:forward

**Review by ivicac — APPROVED** [review]

**Comment by jpince** [comment]
@ivicac @alecsloan I see the error below in upstream, and the rest of the failures seem less severe than the issue this PR fixes. I recommend sending directly to Brian and fixing the other failing tests in a separate PR.
```
com.liferay.portal.kernel.exception.PortalException
com.liferay.portal.kernel.exception.PortalException
at com.liferay.commerce.product.service.impl.CommerceChannelLocalServiceImpl.getCommerceChannelGroup(CommerceChannelLocalServiceImpl.java:218)
at com.liferay.commerce.product.service.impl.CommerceChannelLocalServiceImpl.deleteCommerceChannel(CommerceChannelLocalServiceImpl.java:133)
```

**Comment by ivicac** [comment]
Sent directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/102313

**Comment by ivicac** [comment]
cc @jpince

**Pull request closed without merging**
