### PR TITLE
LPS-176720 Append originalCommerceOrder to message payload

### PR DESCRIPTION
**Pull request by p-albuquerque**
Related issue: https://issues.liferay.com/browse/LPS-176720

Hi, team

Due the new ExpressionBuilder function oldValues, we need to pass through Payload the values of a CommerceOrder, before its update also. By the prefix "original" the code of this new function is able to get the values properly.
Thanks

### CODE REVIEW

**Comment by p-albuquerque** [comment]
ci:test:sf

**Comment by p-albuquerque** [comment]
ci:test:relevant

**Comment by p-albuquerque** [comment]
ci:test:commerce

**Review by riccardo-alberti — APPROVED** [review]

**Comment by p-albuquerque** [comment]
Directly sent: https://github.com/brianchandotcom/liferay-portal/pull/130928

**Pull request closed without merging**
