### PR TITLE
COMMERCE-9978 Filter catalog by tags

### PR DESCRIPTION
**Pull request by smottal**
https://issues.liferay.com/browse/COMMERCE-9978

Now it's possible to add the tag values in the filter parameter
ex. ***/headless-commerce-delivery-catalog/v1.0/channels/${channelId}/products?filter=(tags/any(x:(x eq 'featured') or (x eq 'cccc')))
ex. ***/headless-commerce-admin-catalog/v1.0/products?filter=(tags/any(x:(x eq 'featured') or (x eq 'cccc')))

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you @smottal

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Review by andrea-ale-sbarra — APPROVED** [review]
thank you @smottal

**Comment by 22LucaGiannotta22** [comment]
ci:forward

**Pull request closed without merging**
