### PR TITLE
COMMERCE-11392 Use correct fieldNames to display dates

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-11392

@luca-pellizzon , tied to a LPP

Straight-forward PR. We are using wrong fieldNames to display dates for the affected two classes.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
Hi @brianikim could you please close this PR I have opened a new one at https://github.com/liferay-commerce/liferay-portal/pull/3733

Thanks!

**Comment by brianikim** [comment]
ci:close

**Pull request closed without merging**
