### PR TITLE
Lpd 15804 feature flag for Checkout Step CX

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://liferay.atlassian.net/browse/LPD-15804

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Review by riccardo-alberti — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:forward:force

**Comment by victoroscuro** [comment]
ci:forward:force

**Comment by andrea-ale-sbarra** [comment]
sent directly here https://github.com/brianchandotcom/liferay-portal/pull/146753

**Pull request closed without merging**
