### PR TITLE
COMMERCE-6926 Upgrade process fails

### PR DESCRIPTION
**Pull request by riccardo-alberti**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by dsitu — APPROVED** [review]

**Comment by jpince** [comment]
ci:test:upgrade

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:upgrade

**Comment by riccardo-alberti** [comment]
ci:test:upgrade

**Comment by riccardo-alberti** [comment]
sent directly to bchan

**Pull request closed without merging**
