### PR TITLE
[TS] LPS-199518

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Commerce Team,

I'm sending my changes for review based on [Brian's confirmation](https://github.com/brianikim/liferay-portal/pull/116). Please let me know if you have any questions.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
@luca-pellizzon , could you please take a look into my changes? Thank you!

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:sf

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
FYI @smottal

**Comment by smottal** [comment]
ci:test:stable

**Comment by smottal** [comment]
ci:test:stable

**Comment by victoroscuro** [comment]
ci:test:commerce-functional

**Comment by victoroscuro** [comment]
ci:test:um

**Comment by saramart81** [comment]
ci:close

**Pull request closed without merging**
