### PR TITLE
COMMERCE-9850

### PR DESCRIPTION
**Pull request by alessiorendina**
These changes will fix the following bugs:
- https://issues.liferay.com/browse/COMMERCE-9507
- https://issues.liferay.com/browse/COMMERCE-9765
- https://issues.liferay.com/browse/COMMERCE-9766
- https://issues.liferay.com/browse/COMMERCE-9850

It will be possible to delete product versions and product when versioning is enabled.

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by pietrobocale** [comment]
ci:test:commerce

**Pull request closed without merging**
