### PR TITLE
COMMERCE-11652 PriceOnApplication in product details page + functional tests

### PR DESCRIPTION
**Pull request by baharturk**
https://issues.liferay.com/browse/COMMERCE-11324

sent from #3858

@smottal

### CODE REVIEW

**Comment by baharturk** [comment]
ci:test:commerce-functional

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:commerce-functional

**Comment by baharturk** [comment]
The failures on the relevant are not related to the PR, it can be forwarded. Thanks!

@luca-pellizzon

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
