### PR TITLE
LPD-21146

### PR DESCRIPTION
**Pull request by brianikim**
https://liferay.atlassian.net/browse/LPD-21146

@luca-pellizzon , tied to LPP.

Maybe this should be sent in together with https://liferay.atlassian.net/browse/LPD-19944 since commit: https://github.com/liferay-commerce/liferay-portal/commit/d94d0a8a33979b16e1304758f47cfbb635ceac47 is a follow-up of LPD-19944. However, I decided to separate the PRs because I was not sure about the commit implementation. I await your feedback on this.

The root cause of the issue is here: https://github.com/liferay-commerce/liferay-portal/blob/9641251e1f89d456c2e0235377379fad47f66525/modules/apps/commerce/commerce-service/src/main/java/com/liferay/commerce/internal/scheduler/CheckGuestCommerceOrdersSchedulerJobConfiguration.java#L44

We are calling `deleteCommerceOrdersByAccountId` for all stale Guest Orders. Schedulers/Listeners are not dependent on `PrincipalThreadLocal.setName(xxxx)` so `getCurrentUser` will return null.

Sincerely,
Brian I. Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@luca-pellizzon , this one still needs your review. tied to LPP.

**Review by luca-pellizzon — APPROVED** [review]

**Comment by luca-pellizzon** [comment]
ci:test:relevant

**Comment by luca-pellizzon** [comment]
ci:forward:force

**Pull request closed without merging**
