### PR TITLE
Automated Test - COMMERCE-5915 | master

### PR DESCRIPTION
**Pull request by JoMaAlves**

### CODE REVIEW

**Comment by JoMaAlves** [comment]
https://issues.liferay.com/browse/COMMERCE-5915 , cc: @lorenzolapescara

**Comment by JoMaAlves** [comment]
New PR, correcting https://github.com/liferay-commerce/liferay-portal/pull/1078

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
java.lang.Exception: Element is not checked at "//p[@title='U-Joint']//../..//input[contains(@aria-label,'Compare')]"

**Pull request closed without merging**
