### PR TITLE
DO NOT MERGE COMMERCE-5840 Update macro CPCommerceCatalog.newOptionsEntry

### PR DESCRIPTION
**Pull request by pietrobocale**
https://issues.liferay.com/browse/COMMERCE-5840

### CODE REVIEW

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:sf

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:releveant

**Comment by Pietro69** [comment]
ci:test:relevant

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by Pietro69** [comment]
ci:test:commerce

**Comment by brianchandotcom** [comment]
@Pietro69 I merged this.

ci:close

**Pull request closed without merging**
