### PR TITLE
LPD-34676 Delivery Cart / Placed Order Headless API extension

### PR DESCRIPTION
**Pull request by gianmarcobrunialti**
https://liferay.atlassian.net/browse/LPD-34676

### CODE REVIEW

**Comment by gianmarcobrunialti** [comment]
ci:test:sf

**Comment by gianmarcobrunialti** [comment]
API commits from review here: https://github.com/liferay-commerce/liferay-portal/pull/5474

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by gianmarcobrunialti** [comment]
ci:forward

**Comment by gianmarcobrunialti** [comment]
ci:stop

**Comment by andrea-ale-sbarra** [comment]
sent here https://github.com/liferay-commerce/liferay-portal/pull/5487

**Pull request closed without merging**
