### PR TITLE
COMMERCE-12144 Min quantity can be anything greater than 0

### PR DESCRIPTION
**Pull request by 22LucaGiannotta22**
https://liferay.atlassian.net/browse/COMMERCE-12144

Resent from #4189

### CODE REVIEW

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Comment by 22LucaGiannotta22** [comment]
ci:test:sf

**Comment by 22LucaGiannotta22** [comment]
ci:test:relevant

**Review by pietrobocale — APPROVED** [review]
QA Review Passed

**Comment by 22LucaGiannotta22** [comment]
relevant failures are not related to this PR. This can be force forwarded.

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
