### PR TITLE
LPD-20228 Languages are not working on personal sites

### PR DESCRIPTION
**Pull request by pei-jung**
Hi team,

`UpdateLanguageAction.java#getRedirect` relies on `themeDisplay.getLayout()` to get the redirect, and the `plid` param was used to set the layout on the ThemeDisplay in `ServicePreAction.java` so we can't just strip out the `plid` param as pointed out by @wanderlast. Since we can't use `plid` to get the user personal page, we need to use the `groupId` and `layoutId` combo to get the layout, as defined in https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/events/ServicePreAction.java#L995-L1006. Please let me know if you see any issues with this fix. Thanks!

/cc @wanderlast

### CODE REVIEW

**Comment by pei-jung** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:um

**Review by smottal — APPROVED** [review]

**Comment by smottal** [comment]
Resent here: https://github.com/liferay-commerce/liferay-portal/pull/4869

**Pull request closed without merging**
