### PR TITLE
COMMERCE-11672 | Discount Handling of UOM

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/COMMERCE-11672

@jaydawu

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1277401_10105

**Comment by CrescenzoRegaLF** [comment]
ci:reevaluate:1257401_3420

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
Hi @CrescenzoRegaLF, after analyzing the results, the errors in [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2430228449?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2430227098%26testrayRunId%3D2430227148%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) should be related to your [change](https://github.com/liferay-commerce/liferay-portal/pull/4249/commits/fedaa734d0a8017d80a495199be781817bc93b93), could you please take a look and fix? Thanks!
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-test-util] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 24.2.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
```
   
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/commerce/commerce-discount-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.commerce.discount.service              MAJOR      9.0.0      9.0.0      10.0.0     VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.commerce.discount.service.CommerceDiscountLocalServiceUtil
```

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:stable

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:relevant

**Comment by jaydawu** [comment]
ci:test:commerce-functional

**Comment by jaydawu** [comment]
Hi @CrescenzoRegaLF, the stable issue is fixed now, please refer to this pr https://github.com/liferay-commerce/liferay-portal/pull/4248#issuecomment-1734835034. So the stable in this pr is a flaky issue on [modules-compile-jdk8/0/6](https://testray.liferay.com/home/-/testray/case_results/2431151089?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2431149645%26testrayRunId%3D2431149685%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc), I'm creating a new pr that includes the functional tests for it, so we can rerun the suites to see there if it's okay later, thanks.

**Comment by jaydawu** [comment]
Add functional test coverage and resent on https://github.com/liferay-commerce/liferay-portal/pull/4261.

**Pull request closed without merging**
