### PR TITLE
DataSetDisplay now works in commerce static fe env

### PR DESCRIPTION
**Pull request by fabio-d-m**

### CODE REVIEW

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:sf

**Comment by FabioDiegoMastrorilli** [comment]
ci:test:stable

**Review by marco-leo — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
