### PR TITLE
Automated Test - COMMERCE-6234 | master

### PR DESCRIPTION
**Pull request by Jamersonze**

### CODE REVIEW

**Comment by Jamersonze** [comment]
https://issues.liferay.com/browse/COMMERCE-6234, cc: @iovaneale

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by kristinonias** [comment]
@Jamersonze ,

This Pull Request has a formatting issue. Please fix and resend.

**Comment by kristinonias** [comment]
ci:test:sf

**Comment by Jamersonze** [comment]
Fixed

**Comment by pedro-michel** [comment]
ci:test:sf

**Comment by Jamersonze** [comment]
Fixed

**Comment by Jamersonze** [comment]
https://issues.liferay.com/browse/COMMERCE-6234, cc: @iovaneale

**Comment by Jamersonze** [comment]
New PR: https://github.com/liferay-commerce/liferay-portal/pull/1047

**Pull request closed without merging**
