### PR TITLE
COMMERCE-10605 Set portletId of generated repository

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [COMMERCE-10605](https://issues.liferay.com/browse/COMMERCE-10605)

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:commerce

**Comment by brianikim** [comment]
@andrea-ale-sbarra , fix is straightforward, but review needs to high priority because the issue described is affecting non-COMMERCE customers as well.

**Review by andrea-ale-sbarra — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:reevaluate:1377401_7950

**Comment by brianikim** [comment]
@mbowerman , could you resolve the merge conflicts?

**Comment by mbowerman** [comment]
Hi @brianikim I've resolved the merge conflicts and force-pushed the changes.

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Pull request closed without merging**
