### PR TITLE
COMMERCE 12756 Configurable Refund Reasons + functional tests

### PR DESCRIPTION
**Pull request by saramart81**
sent from #4439 
https://liferay.atlassian.net/browse/COMMERCE-12756

### CODE REVIEW

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
ci:test:sf

**Comment by saramart81** [comment]
ci:test:relevant

**Comment by saramart81** [comment]
ci:test:commerce-functional

**Comment by saramart81** [comment]
Hi @victoroscuro this PR is good please help force-forward it, thanks!

**Comment by victoroscuro** [comment]
ci:forward:force

**Pull request closed without merging**
