### PR TITLE
COMMERCE-8115 Reordering a product with options causes duplicate items to appear in the order summary

### PR DESCRIPTION
**Pull request by dsitu**
https://issues.liferay.com/browse/COMMERCE-8115

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
@dsitu @luca-pellizzon Is this PR still needed?

**Comment by luca-pellizzon** [comment]
@alessiorendina I see there's already a fix in master from Ivica a little bit different from this one, but I guess with the same results:
`if (commerceOrderItem.getParentCommerceOrderItemId() != 0) {
	continue;
}`
I think this (and the related jira ticket) can be closed.

**Pull request closed without merging**
