### PR TITLE
COMMERCE-5239 if unit price is lower than promo then do not show prom…

### PR DESCRIPTION
**Pull request by riccardo-alberti**
…o price

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
ci:test:sf

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Comment by riccardo-alberti** [comment]
ci:test:relevant

**Review by marco-leo — APPROVED** [review]

**Review by marco-leo — APPROVED** [review]

**Comment by riccardo-alberti** [comment]
ci:forward

**Pull request closed without merging**
