### PR TITLE
Commerce 9999

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-9999

https://issues.liferay.com/browse/COMMERCE-10064

resend of this https://github.com/liferay-commerce/liferay-portal/pull/3044

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by andrea-ale-sbarra** [comment]
ci:test:commerce

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Comment by iovaneale** [comment]
ci:test:relevant

**Pull request closed without merging**
