### PR TITLE
COMMERCE-11706 Provide full URL first before constructing alternateURLs

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/COMMERCE-11706

@andrea-ale-sbarra

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
ci:test:relevant

**Comment by Brunno0liveira** [comment]
Hi @brianikim could you please close this PR I have sent a new one at https://github.com/liferay-commerce/liferay-portal/pull/3893

Thanks!

**Comment by jaydawu** [comment]
ci:close

**Pull request closed without merging**
