### PR TITLE
LPD-37783 patchWishList API can add the same item more than once to the same wish list

### PR DESCRIPTION
**Pull request by ghost**
https://liferay.atlassian.net/browse/LPD-37783
https://liferay.atlassian.net/browse/LPD-37778

resend this https://github.com/brianchandotcom/liferay-portal/pull/156586

https://liferay.atlassian.net/browse/LPD-43404

### CODE REVIEW

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Review by alessiorendina — DISMISSED** [review]
@CrescenzoRegaLF LGTM overall, just few small changes, thank you!

Please squash autogenerated commits together.

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:sf

**Comment by CrescenzoRegaLF** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:87316889

**Comment by CrescenzoRegaLF** [comment]
@alessiorendina The relevant results do not present errors due to the changes contained in the pr

**Comment by CrescenzoRegaLF** [comment]
ci:report:87324660

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:report:87821184

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:stop

**Comment by CrescenzoRegaLF** [comment]
ci:stop:commerce-functional

**Comment by CrescenzoRegaLF** [comment]
ci:test:commerce-functional

**Pull request closed without merging**
