### PR TITLE
COMMERCE-5641 commerce-product-service use local service reference instead of direct method call

### PR DESCRIPTION
**Pull request by andrea-ale-sbarra**
https://issues.liferay.com/browse/COMMERCE-5641

There were some method call that used direct method instead of using local service reference, this possibly created an issue with the Indexer that was not working properly in the reindex phase. At least with this change the modal seems to work properly now. What do you think @Commando18

### CODE REVIEW

**Comment by andrea-ale-sbarra** [comment]
ci:test:sf

**Comment by andrea-ale-sbarra** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
@andrea-ale-sbarra Yes, we should always use the LocalService reference. Good job!

**Review by dsitu — APPROVED** [review]

**Comment by andrea-ale-sbarra** [comment]
ci:forward

**Pull request closed without merging**
