### PR TITLE
LPD-25542 Control panel visibility issue with user groups

### PR DESCRIPTION
**Pull request by smottal**
https://liferay.atlassian.net/browse/LPD-25542

Resent from: https://github.com/brianchandotcom/liferay-portal/pull/150376

### CODE REVIEW

**Comment by smottal** [comment]
ci:test:sf

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:test:relevant

**Comment by smottal** [comment]
ci:report:2569804894

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by smottal** [comment]
ci:forward:force

**Pull request closed without merging**
