### PR TITLE
LPD-22282 UPS client extension

### PR DESCRIPTION
**Pull request by alessiorendina**
https://liferay.atlassian.net/browse/LPD-22282

### CODE REVIEW

**Comment by alessiorendina** [comment]
ci:test:sf

**Comment by alessiorendina** [comment]
ci:test:relevant

**Comment by alessiorendina** [comment]
ci:test:commerce-functional

**Review by luca-pellizzon — APPROVED** [review]
Nice!

**Comment by luca-pellizzon** [comment]
ci:forward

**Pull request closed without merging**
