### PR TITLE
LPD-20282\LPD-20696 Returns Workflow - part 1

### PR DESCRIPTION
**Pull request by dsitu**
https://liferay.atlassian.net/browse/LPD-20282
https://liferay.atlassian.net/browse/LPD-20696

Ref: https://github.com/brianchandotcom/liferay-portal/pull/151749

### CODE REVIEW

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by dsitu** [comment]
@CrescenzoRegaLF can you verify if this breaks anything? https://github.com/liferay-commerce/liferay-portal/pull/5115/commits/80598c8d11868d242cd2192e6e50f06f062d74bd

**Comment by dsitu** [comment]
ci:stop

**Comment by dsitu** [comment]
ci:test:sf

**Comment by dsitu** [comment]
ci:test:relevant

**Comment by CrescenzoRegaLF** [comment]
resend this [here](https://github.com/brianchandotcom/liferay-portal/pull/152071)

**Pull request closed without merging**
